### ISSUE TITLE
Snake case strategy should consider numerics as capital letters

### ISSUE THREAD

**Issue by shuawest** [FasterXML/jackson-databind#1864] opened 2017-12-19 18:03 UTC
Context: jackson-databind v2.8.7

##  Problem: 
The snake case strategy doesn't consider numerics may be part of a field name. When a service/json is being consumed that has a number in the name, for example `volume_30day` [1], the field cannot be matched to the java object model [2] without overriding [3][4] the object mapper. 

## Expected Behavior
The snake case strategy should consider a numeric in the field name to be a capital letter in the context of the snake case strategy. 

## Workaround
Handle the specific property translation by extending the SnakeCaseStrategy [3] and initializing it in the object mapper [4]

## Appendix
[1] Sample json body
```
{
  "open": "19442.38000000",
  "high": "19787.99000000",
  "low": "18200.00000000",
  "volume": "28237.41544911",
  "last": "18575.00000000",
  "volume_30day": "952310.05768915"
}
```
[2] Swagger generated java model
```
@ApiModel(description="Product 24 hour stats")
public class ProductStats  {
...
  @ApiModelProperty(example = "null", value = "")
  private BigDecimal volume30day = null;
...
 public BigDecimal getVolume30day() {
    return volume30day;
  }
  public void setVolume30day(BigDecimal volume30day) {
    this.volume30day = volume30day;
  }
  public ProductStats volume30day(BigDecimal volume30day) {
    this.volume30day = volume30day;
    return this;
  }
```

[3] Extended snake case strategy
```
public class ExtSnakeCaseStrategy extends PropertyNamingStrategy.SnakeCaseStrategy {
    @Override
    public String translate(String input)
    {
        if(input == "volume30day") {
            return "volume_30day";
        }
        return super.translate(input);
    }
}
```

[4] Object mapper initialization
```
        ObjectMapper modelMapper = new ObjectMapper();
        modelMapper.setPropertyNamingStrategy(new ExtSnakeCaseStrategy());
```

**Comment by cowtowncoder** [comment] 2017-12-19 18:47
Ok, Would it be possible to express the problem in test case form? I think I understand the basic part, but just to make sure to show what JSON and property names would be expected to match.

One thing to note is that I am not 100% sure if the fix could be applied to a patch release -- although it could be considered a fix for flaw, it can also be seen as change in behavior, and could break existing code. It can certainly go in 3.0.0 (`master`) without problems; conversely I do not think it should go in 2.8 (and earlier branches are closed); but `2.9` is an open question.

**Comment by Mashinist555** [comment] 2017-12-22 11:05
Hi @shuawest. If snake case strategy consideres numerics as capital letter, then `volume30day` should be translated into `volume_3_0day `. Am I correct?

**Comment by cowtowncoder** [comment] 2017-12-22 18:15
Good point: rules would have to clearly defined.

**Comment by cowtowncoder** [comment] 2020-04-02 06:05
Since this is behavior change, likely needs to go in 2.12(.0) (unless a patch is made very quickly to make it into 2.11.0, due to release within 1-2 weeks!).
Seems like potentially good issue for new contributors, so labeling as such.

**Comment by cowtowncoder** [comment] 2020-05-12 01:47
I think better definition would be needed: if someone can point to a specification, or set of tests from other systems that do similar mapping, those would be great.

To me, logically there are couple of possibilities if starting from `volume_30day`:

* `[get]Volume30Day` (seems most readable)
* `[get]Volume30day` (original suggestion)

but maybe as importantly, Jackson actually starts with "standard" name, extracted from get/set methods. So we could start from `[get]Volume30day` and I suppose there could be different expected answers there too:

* `volume_30_day`
* `volume30day` (current result)
* `volume_30day` (suggested new result)

All of these are possible to produce I think by simple change in `PropertyNamingStrategy.SnakeCaseStrategy` (line 319), by replacing:

```java
if (Character.isUpperCase(c))
```

with

```java
if (Character.isUpperCase(c) || Character.isDigit(c))
```

but doing so will break existing tests, which assume no changes to cases like "a1" and "A1".

**Comment by cowtowncoder** [comment] 2020-08-19 18:56
Unfortunately not clear on how to proceed, closing: may be reopened with information requested.

**Closed by cowtowncoder** 2020-08-19 18:56 UTC
Labels: 2.12, need-test-case

**Comment by Hronom** [comment] 2020-11-19 23:50
Please reopen it, just create additional strategy, something like **SnakeCaseDigitStrategy**

**Comment by cowtowncoder** [comment] 2020-11-20 01:14
@Hronom I'd be open to adding a new strategy, but what is really needed even more than implementation would be test case(s) to show expected behavior. Adding implementation only is problematic because that does not really define how various things should work, just how particular piece of code happens to work.

So: may be reopened (or re-filed) with definition of expected behavior.

Then again, users are free to implement their own naming strategies as well, so it is not clear if a new one should be added as one of default choices.
