### ISSUE TITLE
Exception deserializing a collection @JsonIdentityInfo and a property based creator

### ISSUE THREAD

**Issue by myrosia** [FasterXML/jackson-databind#687] opened 2015-01-23 17:19 UTC
I am trying to serialize and de-serialize objects with cyclic dependencies, using JsonIdentityInfo, in Jackson 2.5. For objects that have no creator, serialization and deserialization works fine. If I add a creator, an exception `JsonMappingException: No _idValue when handleIdValue called` is thrown.

Here's a test case that I constructed. `testSerializeDeserializeNoCreator()` passes. `testSerializeDeserializeWithCreator()` throws an exception. Both produce identical JSON on serialization, it's de-serialization that is an issue. It appears to be similar to https://jira.codehaus.org/browse/JACKSON-847 , but the exception is different this time.

``` java

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;

import models.circuit.Circuit;
import models.circuit.Terminal;
import models.circuit.Wire;

import org.junit.*;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.databind.ObjectMapper;



public class MinimalTest {


    private static final ObjectMapper JSON_MAPPER = new ObjectMapper();

    @JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="label")
    private static class ReferredWithCreator {
        @JsonProperty("label")
        private String label;
        @JsonCreator
        private ReferredWithCreator(@JsonProperty("label")String label) {
            this.label = label;
        }
    }

    @JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="label")
    private static class ReferringToObjWithCreator {
        @JsonProperty("label")
        private String label = "test1";
        @JsonProperty("refs")
        private List<ReferredWithCreator> refs = new ArrayList<>();
        public void addRef(ReferredWithCreator r) {
            this.refs.add(r);
        }
    }

    @JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="label")
    private static class EnclosingForRefsWithCreator {
        @JsonProperty("label")
        String label = "enclosing1";
        @JsonProperty("baseRef")
        ReferredWithCreator baseRef;
        @JsonProperty("nextRef")
        ReferringToObjWithCreator nextRef;
    }

    @JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="label")
    private static class ReferredWithNoCreator {
        @JsonProperty("label")
        private String label = "label2";
    }

    @JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="label")
    private static class ReferringToObjWithNoCreator {
        @JsonProperty("label")
        private String label = "test2";
        @JsonProperty("refs")
        private List<ReferredWithNoCreator> refs = new ArrayList<>();
        public void addRef(ReferredWithNoCreator r) {
            this.refs.add(r);
        }
    }

    @JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="label")
    private static class EnclosingForRefWithNoCreator {
        @JsonProperty("label")
        String label = "enclosing2";
        @JsonProperty("baseRef")
        ReferredWithNoCreator baseRef;
        @JsonProperty("nextRef")
        ReferringToObjWithNoCreator nextRef;
    }





    @Test
    public void testSerializeDeserializeWithCreator() throws IOException {
        ReferredWithCreator base = new ReferredWithCreator("label1");
        ReferringToObjWithCreator r = new ReferringToObjWithCreator();
        r.addRef(base);
        EnclosingForRefsWithCreator e = new EnclosingForRefsWithCreator();
        e.baseRef = base;
        e.nextRef = r;

        String jsonStr = JSON_MAPPER.writeValueAsString(e);

        EnclosingForRefsWithCreator deserialized = JSON_MAPPER.readValue(jsonStr, EnclosingForRefsWithCreator.class);
    }

    @Test
    public void testSerializeDeserializeNoCreator() throws IOException {
        ReferredWithNoCreator base = new ReferredWithNoCreator();
        ReferringToObjWithNoCreator r = new ReferringToObjWithNoCreator();
        r.addRef(base);
        EnclosingForRefWithNoCreator e = new EnclosingForRefWithNoCreator();
        e.baseRef = base;
        e.nextRef = r;

        String jsonStr = JSON_MAPPER.writeValueAsString(e);

        EnclosingForRefWithNoCreator deserialized = JSON_MAPPER.readValue(jsonStr, EnclosingForRefWithNoCreator.class);
    }


}
```

The exception thrown is

```
com.fasterxml.jackson.databind.JsonMappingException: No _idValue when handleIdValue called, on instance of MinimalTest$ReferredWithCreator
[error]  at [Source: {"label":"enclosing1","baseRef":{"label":"label1"},"nextRef":{"label":"test1","refs":["label1"]}}; line: 1, column: 50] (through reference chain: EnclosingForRefsWithCreator["baseRef"]->ReferredWithCreator["label"]), took 0.018 sec
[error]     at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
[error]     at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:843)
[error]     at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer.handleIdValue(PropertyValueBuffer.java:124)
[error]     at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:169)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:386)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1036)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
[error]     at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
[error]     at com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty.deserializeSetAndReturn(ObjectIdReferenceProperty.java:70)
[error]     at com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty.deserializeAndSet(ObjectIdReferenceProperty.java:62)
[error]     at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap.findDeserializeAndSet(BeanPropertyMap.java:285)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:335)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1036)
[error]     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
[error]     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3560)
[error]     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2576)
```

**Comment by cowtowncoder** [comment] 2015-01-23 18:12
Thank you for reporting this, and especially for including the test case.

I will have to see if this is a bug in existing handling, or one of cases where implementation is incomplete; there are unit tests under `failing` that include remaining such cases. But I think this is not one of those (ones I see are for arrays, `EnumMap` and `ArrayBlockingQueue`)

**Comment by redben** [comment] 2015-05-25 20:38
I have the same issue. When @myrosia says, when I disable creator everything works fine.

**Comment by cowtowncoder** [comment] 2015-05-26 17:58
@redben Does the problem occur on both 2.5.3? (and if so, also 2.6.0-rc1)

**Comment by technotic** [comment] 2015-05-29 13:07
This is an issue for me but only when using YAMLFactory. The behaviour is the same in 2.6.0-rc1.

**Comment by cowtowncoder** [comment] 2015-05-29 16:56
@technotic Hmmh. YAML part is interesting; it may have to do with use of native Object Ids (anchors), or incompatibilites thereof. But you are saying JSON part does work? If so, may need to file a separate issue for YAML module to investigate things from that end.

**Comment by technotic** [comment] 2015-06-01 08:05
@cowtowncoder Yes that's correct. It works fine when using a JsonFactory.

**Comment by aldobrucale** [comment] 2015-06-04 09:35
Here is a shorter version of the failing test case. It fails on both 2.5.3 and 2.6.0-rc1

```java
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import org.junit.Test;

public class ImmutableTest {

    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
    private static class ImmutablePojo {
        private final int id;

        @JsonCreator
        public ImmutablePojo(@JsonProperty("id") final int id) {
            this.id = id;
        }

        public int getId() {
            return id;
        }
    }

    @Test
    public void serialize_single() throws IOException {
        final ObjectMapper om = new ObjectMapper();
        final ImmutablePojo pojo = new ImmutablePojo(0);
        final String json = om.writeValueAsString(pojo);

        final ImmutablePojo readValue = om.readValue(json, ImmutablePojo.class);
    }
}
```
and throws the same exception:

```
com.fasterxml.jackson.databind.JsonMappingException: No _idValue when handleIdValue called, on instance of ImmutableTest$ImmutablePojo
 at [Source: {"id":0}; line: 1, column: 8] (through reference chain: ImmutablePojo["id"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:840)
	at com.fasterxml.jackson.databind.deser.impl.PropertyValueBuffer.handleIdValue(PropertyValueBuffer.java:195)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:140)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:381)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1100)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1072)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:130)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3699)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2711)
	at ImmutableTest.serialize_single(ImmutableTest.java:34)
```

**Comment by bojanv55** [comment] 2015-06-18 09:59
In 2.6 rc2 I get this error for similar usecase:


    Exception in thread "main" org.springframework.data.redis.serializer.SerializationException: Could not read JSON: com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty; nested exception is java.lang.ArrayStoreException: com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty
	at     org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer.deserialize(Jackson2JsonRedisSerializer.java:73) Caused by: java.lang.ArrayStoreException: com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:485)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:426)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:164)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:665)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:946)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:426)

**Comment by nezda** [comment] 2015-07-24 18:00
I started getting https://github.com/FasterXML/jackson-databind/issues/687#issuecomment-113097184 in many of our tests when upgrading from 2.5.4 -> 2.6.0

```java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
```

**Comment by arora2atul** [comment] 2015-07-26 04:40
Do we have any fix for this issue or any workaround..

**Comment by reda-alaoui** [comment] 2015-10-15 00:13
Hi, I just stumbled on the same issue.
A fix or workaound would be nice indeed :)

**Comment by reda-alaoui** [comment] 2015-10-15 09:03
In fact, my issue seems to be a consequence of Jackson Hibernate module usage.

**Comment by hjohn** [comment] 2016-01-30 23:56
Also experienced this, seems it doesn't like constructors (in 2.7.0 btw).

**Comment by cowtowncoder** [comment] 2016-01-31 18:47
@hjohn Correct: we do have a reproduction where no-creator path works, with-creator one fails.
Test under

    src/test/java/com/fasterxml/jackson/failing/TestObjectId687.java

No clear idea if or how this could be fixed: there is definitely challenge wrt the fact that creators can only be called once, at construction, and IF value is not yet available there is no way to call creator again. Nor is it possible to defer call itself (or, if trying, you can have deadlock condition). Perhaps it would be possible to use creator OR setters, but require latter.

From user perspective the best solution is probably simply not to use combination of Creators with Object Ids for one of values passed: pass anything for which Object Id may be used via setter or field.

**Comment by gdabski** [comment] 2017-02-05 20:07
The problem seems to boil down to using `@JsonIdentityInfo` together with `@JsonCreator` when `PropertyGenerator` is used as `ObjectIdGenerator` and the ID property is also a creator property.

The code in `BeanDeserializer._deserializeUsingPropertyBased()` doesn't foresee that the object ID property may also be a creator property. This can't happen for any kind of ID generated only for the purpose of serialization, but is more likely than not when `PropertyGenerator` is used. `BeanSerializer` first checks if the encountered property is a creator property and if so `continue`s the loop not reaching the check against the configured object ID property name. The bean actually gets successfully instantiated with the right properties using the creator, but then the code believes the object ID had not been encountered and throws the exception.

If you exclude the object ID property from the creator method (e.g. tag a 0-arg constructor with `@JsonCreator` in aldobrucale's `ImmutablePojo` example), everything suddenly begins to work, the property ID being set by field access using reflection (cf. `CreatorProperty._fallbackSetter` called from `PropertyValueBuffer.handleIdValue()`). I'm not sure what business case does this additional mechanism of setting the object ID cater to, but it helps this time, although I guess in the basic case it would succeed in setting the ID property for the second time had it been recognized that the object ID is available.

**Comment by cowtowncoder** [comment] 2017-03-16 15:37
Looks like this issue has been resolved by some fix for another reported issue, either with same root cause (most likely) or some cleanup of creator handling/fallback-property checking.
Either way passes with code that will become `2.9.0.pr2` and contents seem ok (although with older test verification may be incomplete).

**Closed by cowtowncoder** 2017-03-16 15:37 UTC
