### ISSUE TITLE
Multiple `@JsonBackReference` on a single class not working (with Hibernate)

### ISSUE THREAD

**Issue by joydeep1982** [FasterXML/jackson-databind#1091] opened 2016-01-22 10:40 UTC
I have a class called

``` java
public class DoctorVO
{
    @JsonManagedReference(value="doctor")
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorHospitalVO> hospitals;
}

public class HospitalVO
{
    @JsonManagedReference(value="hospital")
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorHospitalVO> doctors;
}

public class DoctorHospitalVO
{
    @JsonBackReference(value="doctor")
    private DoctorVO doctor;

    @JsonBackReference(value="hospital")
    private HospitalVO hospital;

    @JsonManagedReference
    private Set<DoctorHospitalScheduleVO> schedules;
}
```

When I fetch a doctor information both hospital and doctor values are dropped in the DoctorHospitalVO by the jackson whereas it should ideally drop the doctor object in DoctorHospitalVO and keep the hospital object as it is.

Please let me know how to handle double back reference in jackson. I have tried out several ways but nothing seems to work.

**Comment by cowtowncoder** [comment] 2016-01-22 15:57
Managed/back reference must be resolvable with only JSON content and specific parent/child structure with just one parent: there is no way to indicate multiple parents in JSON. Or, put another way, a back-reference can only be resolved directly to match forward reference traversed.
In your case, then, one of `doctor` or `hospital` can ever be resolved, depending on which type of object was the parent object in JSON hierarchy (containing JSON Object).
This is a hard limitation and can not, unfortunately, be changed.

For more generic object graphs, use of `@JsonIdentityInfo` is the mechanism to use, without having to resort to custom serializers/deserializers.

**Comment by joydeep1982** [comment] 2016-01-23 09:53
Can you provide me some insight on how do I resolve the same using @JsonIdentityInfo, I have removed managed and back reference from my class and added JsonIndentityInfo but the problem still  persists, this is what I have done at the moment.

@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="@jacksonVersion")
public class DoctorVO
{
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorHospitalVO> hospitals;
}

@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="@jacksonVersion")
public class HospitalVO
{
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorHospitalVO> doctors;
}

@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="@jacksonVersion")
public class DoctorHospitalVO
{
    private DoctorVO doctor;

    private HospitalVO hospital;

    private Set<DoctorHospitalScheduleVO> schedules;
}

Am I missing something, can you please guide me to resolve my problem, thanks a lot in advance.

**Comment by cowtowncoder** [comment] 2016-01-23 23:57
Ok. So, you have added annotations. What is the remaining problem? Error, missing data?
How are you deserializing JSON, and what does that look like?
Are you serializing content with Jackson, reading back as well, or are other libraries used on one direction?

**Comment by joydeep1982** [comment] 2016-01-24 08:06
basically I am using jersey web services and I have configured jersey to use jackson internally to serialize and deserialize by objects. I am using this configuration to achieve the same.

<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>2.22.1</version>
</dependency>

My webservice call starts throwing this exception.

failed to lazily initialize a collection of role: org.project.hospital.vo.HospitalVO.inPatientServices, no session or session was closed (through reference chain: org.project.common.vo.LoginVO["doctor"]->org.project.doctor.vo.DoctorVO["hospitals"]->org.hibernate.collection.PersistentSet[0]->org.project.doctor.vo.DoctorHospitalVO["hospital"]->org.project.hospital.vo.HospitalVO["inPatientServices"])

Actually there are several other collections present in the Hospital and DoctorVO they stop working after I make this change. I am unable to understand the behavior. I checked several websites but couldn't find a proper solution to the problem, you are my last hope at the moment. Sending you my hospital and doctor class with other collections, so that it gets easier for you to understand the problem.


@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="@id")
public class HospitalVO extends VendorBaseVO implements ISearchableObject
{

    /**
     * 
     */
    private static final long serialVersionUID = 7246657251921956603L;

    private Boolean cashlessInsuranceBenefits;

    private String facilityType;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<HospitalFeedbackVO> feedbacks;
    
    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<HospitalPhoneVO> phones;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<HospitalServiceVO> inPatientServices;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<HospitalServiceVO> outPatientServices;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<HospitalServiceVO> paraMedicalServices;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<HospitalServiceVO> specialityServices;
    
    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<HospitalServiceVO> tieups;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<HospitalPackageVO> packages;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<HospitalImageVO> images;

    //@JsonManagedReference(value="hospital")
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorHospitalVO> doctors;
    
    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<HospitalScheduleVO> schedules;
}

@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="@id")
public class DoctorVO extends BaseVO implements ISearchableObject
{

    /**
     * 
     */
    private static final long serialVersionUID = -1029195003422638875L;

    private String firstname;

    private String lastname;

    private Integer gender;

    private String profile;

    private String image;

    private Date dob;

    private BloodGroupVO bloodGroup;

    private Boolean donateBlood;
    
    private String doctorType;

    @JsonIgnore
    private LoginVO login;

    private String about;

    private Integer status;

    private Timestamp createdTime;

    private Timestamp lastUpdatedTime;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorAchievementVO> achievements;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorEducationVO> educations;

    //@JsonManagedReference(value="doctor")
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorHospitalVO> hospitals;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorExpertiseVO> expertises;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorServiceVO> services;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorExperienceVO> experiences;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorMembershipVO> memberships;

    @JsonManagedReference
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<DoctorFeedbackVO> feedbacks;

    private String registrationNumber;

    private Integer registrationYear;

    private RegistrationCouncilVO registrationCouncil;

    private Boolean projectVerified;

    @JsonIgnore
    private LoginVO createdBy;
}

@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class, property="@id")
public class DoctorHospitalVO extends BaseVO
{

    /**
     * 
     */
    private static final long serialVersionUID = -5417295243194345972L;

    //@JsonBackReference(value="doctor")
    private DoctorVO doctor;

    //@JsonBackReference(value="hospital")
    private HospitalVO hospital;

    @JsonManagedReference
    private Set<DoctorHospitalScheduleVO> schedules;

    private DesignationVO designation;

    private Integer status;

    private Integer consultationFees;
}

As you can see in the above three classes that I have commented out the back references, please have a look and guide me to a resolution. Thanks a ton in advance.

**Comment by cowtowncoder** [comment] 2016-01-25 18:43
I do not use Hibernate myself, but the exception sounds like it was due to attempts to access properties outside of Hibernate session. This would not seem to be directly related to issues with identity mapping (`@JsonIdentityInfo`) or managed/back references.

Given the exception, I assume problem occurs during serialization, when trying write out JSON.

Usually the way to try to get things working is to reduce the case to simplest structure possible, and then add missing properties back, to isolate the specific problem. In your case, I would try to retain properties, through which problem occurs, to see if the problem is strictly related to just that smaller set of fields/properties. Alternatively you could try keeping simpler references, to avoid having to use `@JsonIdentityInfo`.

Another thing to make sure is that you are using a recent version of Jackson (all components).
Ideally you would be able to see if 2.7.0 (the last public release) still has same issues; but if not, at least 2.6.5. Both contain fixes to Hibernate handling that were not included in earlier versions.

**Comment by Grant-W** [comment] 2016-11-21 12:37
Hi, 

Im getting a similar error, with different code:

`public class CompanyUser{
    @ManyToOne
    @JsonManagedReference(value = "companyUser-user")
    private User user;

    @ManyToOne
    @JsonManagedReference(value = "companyUser-company")
    private Company company;

    @OneToMany(mappedBy = "companyUser")
    @JsonBackReference(value = "appointment-companyUser")
    private Set<Appointment> appointments;

    @OneToMany(mappedBy = "costCentreCustodian")
    @JsonBackReference(value = "salesAgencyCostCentres-companyUser")
    private Set<SalesAgencyCostCentre> salesAgencyCostCentres;
}

public class Company {
    @OneToMany(mappedBy = "company")
    @JsonBackReference(value = "companyUser-company")
    private Set<CompanyUser> companyUsers;
}  

public class User {
    @OneToMany(mappedBy = "user")
    @JsonBackReference(value = "companyUser-user")
    private Set<CompanyUser> companyUsers;
}

public class Appointment {
    @ManyToOne
    @JsonManagedReference(value = "appointment-companyUser")
    private CompanyUser companyUser;
}

public class SalesAgencyCostCentre {
    @ManyToOne
    @JsonManagedReference(value = "salesAgencyCostCentres-companyUser")
    private CompanyUser companyUser;
}`

My Controller thats deserializing:
`@RequestMapping(method=RequestMethod.PUT, consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseBody
    public CompanyUser update(@RequestBody CompanyUser companyUser) {
        LOG.debug("Company User Controller processing 'update' for id " + companyUser.getId());

        companyUserService.save(companyUser);

        return companyUser;
    }`

I get the following error when the PUT request is made:
WEB console: error 415
Server Console:
Failed to evaluate Jackson deserialization for type [[simple type, class com.app.domain.CompanyUser]]: com.fasterxml.jackson.databind.JsonMappingException: Multiple back-reference properties with name 'defaultReference'
Failed to evaluate Jackson deserialization for type [[simple type, class com.app.domain.CompanyUser]]: com.fasterxml.jackson.databind.JsonMappingException: Multiple back-reference properties with name 'defaultReference'
Resolved exception caused by Handler execution: org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/json;charset=UTF-8' not supported

Please Help if you can, Thanks in advance

**Comment by skuppa** [comment] 2018-01-31 08:22
Did any resolve this error?  I could resolve by using the `List` instead of `Set` which is very weird.  This might be helpful still someone looking answer for this error.

**Comment by Kezibri** [comment] 2018-07-25 13:54
Yes I'm still having this error. Can anyone please explain exactly how to resolve it?

**Comment by cowtowncoder** [comment] 2018-07-25 15:36
Not clear what exactly is the problem and how it relates to Hibernate (which has its own significant hurdles outside of standard Jackson handling).

Will close it: may be re-filed with up-to-date reproduction: either here (if reproducible without Hibernate), or for Hibernate module (if requires Hibernate).

**Closed by cowtowncoder** 2018-07-25 15:36 UTC
Labels: hibernate

**Comment by Kezibri** [comment] 2018-07-25 15:41
I can't do any PUT or POST requests on my entities, on Postman I get unsupported mediatype, and on java I get the jackson exception : Multiple back-reference properties with name 'defaultReference' ... I've been stuck for weeks :/ anyone any idea?

**Comment by nice2h8u** [comment] 2018-09-18 17:04
It's not good decision, but it just works for me. I just added temp class only with parameters:


My entity:
```
@Entity
@Table(name = "User")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id", nullable = false, updatable = false)
    private Integer user_id;

    @Length(min = 5,max = 20, message = "*Your login must have at least 5 or not more then 20 characters")
    @Column(nullable = false)
    private String login;

    @Column(nullable = false)
    private String hash;

    @Column(nullable = false)
    private String user_type;


    @Column(nullable = false)
    private String email;

    @OneToMany(targetEntity = Order.class, mappedBy = "user", fetch = FetchType.LAZY)
    @OrderBy
    @JsonManagedReference
    private Set<Order> orderList = new HashSet<Order>();



   public User() {

   }
//getters and setters

```

So that is temp entity:

```
`
public class TempUser
{

        private String login;
        private String hash;
        private  String email;

        TempUser(){

        }

        public TempUser(String login, String hash, String email) {
            this.login = login;
            this.hash = hash;
            this.email = email;

        }
//getters and setters
`
```

My rest  now:
```
`
@RestController
@RequestMapping("/aparts/")
public class ApartREST {
  
    @Autowired
    LoginService loginService;


    @RequestMapping(value = "a", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<Object> createNewUser(@RequestBody TempUser user) {
       //do something
        return ResponseEntity.ok("sa");
    }
`
```

**Comment by kingpeter1992** [comment] 2023-02-12 13:11
Bonjour, 
j'ai  eu  le même problème, après  plusieurs  heure de recherche, ne toujours  pas trouve une solution
ce qui as  marché  pour mois c'est juste  la classe tempo, qu'il faut créer
