### ISSUE TITLE
Jackson-Databind library is consuming a lot of memory

### ISSUE THREAD

**Issue by balram0694** [FasterXML/jackson-databind#4686] opened 2024-09-04 05:45 UTC
### Describe your Issue

It looks like the Jackson library is caching a lot of data. I am trying to parse a 1.5 GB file, and it seems to be caching the entire dataset. Is there any way Jackson could fix this in an upcoming version? I'm attaching a heap dump analyzer screenshot for your reference.
![Screenshot from 2024-08-26 18-25-01](https://github.com/user-attachments/assets/fbf2efc5-25aa-4a9d-a83f-12805432d4d1)

**Comment by JooHyukKim** [comment] 2024-09-04 06:00
> Is there any way Jackson could fix this in an upcoming version.

This is not a bug, you need to use Jackson Streaming API for your use case.

**Comment by cowtowncoder** [comment] 2024-09-04 16:18
What the.... ? You are not telling anything about usage but attaching a screenshot of heap dump?!! How does this mean caching in any sense of the word.

Yes, if you read the whole JSON document in memory, it will have in-memory representation. If you want incremental access, you need to use streaming API as @JooHyukKim suggested.

**Comment by cowtowncoder** [comment] 2024-09-13 23:39
Without anything useful to indicate unusual working, can't really help. Basically, if you read the whole content in, it will be in memory... how else would that work?

**Closed by cowtowncoder** 2024-09-13 23:39 UTC
