### ISSUE TITLE
/ in key breaks deserialization

### ISSUE THREAD

**Issue by three-old-coders** [FasterXML/jackson-databind#3019] opened 2021-01-19 21:21 UTC
**Version information**
2.12.1

My provider uses a "/" in a key, so the JSON basically looks like this

{ "a/b": "value" }

This causes an exception: 

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "a/b" (class ... not marked as ignorable (129 known properties: [truncated]])
 at [Source: (StringReader); line: 25, column: 45] (through reference chain: ...["a/b"])

_om.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);    // BUG IN JACKSON KEYS WITH "/"

helps at least to retrieve all other properties

**Comment by cowtowncoder** [comment] 2021-01-19 21:29
I don't actually see a flaw in here: if your object does not have a property indicated to have name "a/b", then this occurs.
Since no Java field can have name "a/b" (nor any setter/getter method exist that would imply such name), you would need to use `@JsonProperty` or similar to assign a name.

What specifically is the problem, then? A reproduction would be needed.

**Comment by three-old-coders** [comment] 2021-01-19 23:24
you are right. But this annotation exists, too

    @JsonProperty("a/b")
    @NotNull
    @Nonnull
    private double ab;

**Comment by three-old-coders** [comment] 2021-01-20 00:03
A little test:

Schema

```json schema
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/O",
  "definitions": {
    "O": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "a/b": { "type": "number" }
      },
      "required": [ "a/b" ],
      "title": "O"
    }
  }
}
```

JSON:

```json
{ "a/b": 173.0926 }
```

```java
package xyz;

import javax.annotation.Nonnull;
import javax.validation.constraints.NotNull;
import org.codehaus.jackson.annotate.JsonProperty;
import org.codehaus.jackson.annotate.JsonPropertyOrder;
import org.codehaus.jackson.annotate.JsonTypeInfo;
import org.codehaus.jackson.map.annotate.JsonSerialize;


@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
@JsonPropertyOrder({
    "a/b"
})
public class O {
    @JsonProperty("a/b")
    @NotNull
    @Nonnull
    private double aB;

    public O() {
    }

    @JsonProperty("a/b")
    public double getaB() {
        return aB;
    }

    @JsonProperty("a/b")
    public void setaB(double aB) {
        this.aB = aB;
    }

    public O withaB(double aB) {
        this.aB = aB;
        return this;
    }
}

```

UNIT TEST

```java
public class TestCase_JSON_Basic
    extends TestCase
{
    final ObjectMapper _om;

    public TestCase_JSON_Basic()
    {
        _om = new ObjectMapper();
        // _om.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);    // BUG IN JACKSON KEYS WITH "/"
    }

    @SneakyThrows public void testBasicAPPL()
    {
        final URL url = this.getClass().getClassLoader().getResource("json/jackson.json");
        final String json = IOUtils.toString(url.toURI(), StandardCharsets.UTF_8);
        final O o = _om.readValue(json, O.class);
        System.out.println(o);
    }
}
```

ERROR:

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "a/b" (class de_3oc_.pricing.finnhub.types.O), not marked as ignorable (one known property: "aB"])
 at [Source: (String)"{ "a/b": 173.0926 }"; line: 1, column: 18] (through reference chain: xyz.types.O["a/b"])

**Comment by three-old-coders** [comment] 2021-01-20 09:39
I tried this too:

https://stackoverflow.com/questions/59521550/unable-to-match-node-containing-forward-slash-using-jackson-library

but this does not affect readVaue()

**Comment by cowtowncoder** [comment] 2021-01-20 18:11
@three-old-coders There is something wrong with your example: you seem to be using Jackson 1.x annotations:

```
import org.codehaus.jackson.annotate.JsonProperty;
import org.codehaus.jackson.annotate.JsonPropertyOrder;
import org.codehaus.jackson.annotate.JsonTypeInfo;
import org.codehaus.jackson.map.annotate.JsonSerialize;
```

I suspect you accidentally imported wrong annotations (IDE auto-completion?) but are using Jackson 2.x: if so, annotations would not have any effect: Jackson 2.x annotations are under `com.fasterxml.jackson.annotation.` package
I think this is the case based on exception class type which is for Jackson 2.x

 So you'd need to fix import statements first and that should make annotations take effect as intended.

**Comment by three-old-coders** [comment] 2021-01-20 21:13
You are right. I am using a code generator, so after switching to Jackson2 code the generated class is:

```java

package xyz.types;

import javax.annotation.Nonnull;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "aDivB"
})
public class O {
    @JsonProperty("aDivB")
    @NotNull
    @Nonnull
    private double aDivB;

    @JsonProperty("aDivB")
    public double getaDivB() {
        return aDivB;
    }

    @JsonProperty("aDivB")
    public void setaDivB(double aDivB) {
        this.aDivB = aDivB;
    }

    public O withaDivB(double aDivB) {
        this.aDivB = aDivB;
        return this;
    }
}

```

when trying to serialize from json to java I now get:
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class xyz.types.O]: missing type id property '@class'
 at [Source: (String)"{ "aDivB": 173.0926 }"; line: 1, column: 21]

It looks like the mapper creates a wrong annotation. 

When replacing @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
with @JsonInclude(JsonInclude.Include.NON_NULL)
it is working.

**Comment by cowtowncoder** [comment] 2021-01-20 21:35
Ok. So why do you want to use `@JsonTypeInfo` here? Do you need polymorphic typing?
If you do, name of property to use must match; if not, it should not be added as it forces serialization (writing of type id in JSON) and deserialization (reading json into Java object).

**Comment by cowtowncoder** [comment] 2021-01-29 23:16
Not sure what would remain; sounds like POJO generator has a mismatch. Closing; may be refiled if problems remain (only re-open this one if naming itself was problematic; ideally one issue covers one specific problem).

**Closed by cowtowncoder** 2021-01-29 23:16 UTC
Labels: need-test-case
