### ISSUE TITLE
Unexpected behaviour when deserializing a type containing a map with a custom TypeIdResolver

### ISSUE THREAD

**Issue by patrick1024** [FasterXML/jackson-databind#1464] opened 2016-11-29 15:13 UTC
Hi,

I'm using jackson 2.8.4 and I have experienced some unexpected behaviour when deserializing a custom type containing a map into a map. I'm not really sure if it's a bug or a misunderstanding on my side.

I implemented a custom TypeIdResolver based on the ClassNameIdResolver. This works fine so far. I can serialize and deserialize custom types while adding a type property (@type). It is also possible to deserialize those types into Map.class **except** for types which contain maps or lists. This fails with either 

*JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property '@type' that is to contain type id  (for class java.lang.Object)*
(for types containing maps) 

or 

*JsonMappingException: Unexpected token (END_ARRAY), expected VALUE_STRING: need JSON String that contains type id (for subtype of java.lang.Object)*
(for types containing lists).

The following code snippet reproduces my problem - it failed in the last line of the main method.
```java
public class DeserializeToMapTest {
    public static class Bean1 {
        private String data;

        public void setData(final String aData) {
            data = aData;
        }

        public String getData() {
            return data;
        }
    }

    public static class Bean2 {
        private String data;
        private Map<String, String> map;

        public void setData(final String aData) {
            data = aData;
        }

        public String getData() {
            return data;
        }

        public void setMap(final Map<String, String> aMap) {
            map = aMap;
        }

        public Map<String, String> getMap() {
            return map;
        }
    }

    public static class MyTypeResolverBuilder extends StdTypeResolverBuilder
            implements TypeResolverBuilder<StdTypeResolverBuilder> {
        private final MyCustomTypeIdResolver typeIdResolver;

        public MyTypeResolverBuilder(final TypeFactory typeFactory) {
            super();
            typeIdResolver = new MyCustomTypeIdResolver(typeFactory);
            init(JsonTypeInfo.Id.CUSTOM, typeIdResolver);
            inclusion(JsonTypeInfo.As.PROPERTY);
            typeProperty("@type");
        }

        @Override
        public final TypeDeserializer buildTypeDeserializer(final DeserializationConfig config,
                final JavaType baseType, final Collection<NamedType> subtypes) {
            if (useForType(baseType)) {
                return super.buildTypeDeserializer(config, baseType, subtypes);
            } else {
                return null;
            }
        }

        @Override
        public final TypeSerializer buildTypeSerializer(final SerializationConfig config,
                final JavaType baseType, final Collection<NamedType> subtypes) {
            if (useForType(baseType)) {
                return super.buildTypeSerializer(config, baseType, subtypes);
            } else {
                return null;
            }
        }

        private boolean useForType(final JavaType t) {
            if (t.isArrayType()) {
                return false;
            }
            if (t.isEnumType()) {
                return false;
            }
            if (t.isContainerType()) {
                return false;
            }
            final boolean result = t.getRawClass() == Object.class || !t.isConcrete() || isOwnClass(t);
            return result;
        }

        private boolean isOwnClass(final JavaType t) {
            final Class<?> rawClass = t.getRawClass();
            if (rawClass == null) {
                return false;
            }
            return typeIdResolver.isKnown(rawClass);
        }
    }

    public static class MyCustomTypeIdResolver extends ClassNameIdResolver {
        private final Map<Class<?>, String> classToIdMap = new HashMap<>();
        private final Map<String, Class<?>> idToClassMap = new HashMap<>();
        private final TypeFactory typeFactory;

        public MyCustomTypeIdResolver(final TypeFactory aTypeFactory) {
            super(aTypeFactory.constructType(Object.class), aTypeFactory);
            typeFactory = aTypeFactory;
            final String bean1Id = "test:bean1";
            final String bean2Id = "test:bean2";
            classToIdMap.put(Bean1.class, bean1Id);
            classToIdMap.put(Bean2.class, bean2Id);
            idToClassMap.put(bean1Id, Bean1.class);
            idToClassMap.put(bean2Id, Bean2.class);
        }

        @Override
        public Id getMechanism() {
            return Id.CUSTOM;
        }

        @Override
        public final String idFromValue(final Object aValue) {
            return idFromValueAndType(aValue, aValue.getClass());
        }

        @Override
        public final String idFromValueAndType(final Object aValue, final Class<?> aSuggestedType) {
            assert aSuggestedType != null;
            final String classId = classToIdMap.get(aSuggestedType);
            if (classId == null) {
                return _idFrom(aValue, aSuggestedType, typeFactory);
            }
            return classId;
        }

        @Override
        public final JavaType typeFromId(final DatabindContext context, final String id) {
            final Class<?> cls = idToClassMap.get(id);
            if (cls != null) {
                return _typeFactory.constructSpecializedType(_baseType, cls);
            } else {
                try {
                    return _typeFromId(id, context);
                } catch (final IOException e) {
                    throw new RuntimeException(e);
                }
            }
        }

        public boolean isKnown(final Class<?> aClass) {
            return classToIdMap.get(aClass) != null;
        }
    }

    public static void main(final String[] args) throws Exception {
        final ObjectMapper objectMapper = new ObjectMapper();
        final TypeFactory typeFactory = objectMapper.getTypeFactory();
        objectMapper.setDefaultTyping(new MyTypeResolverBuilder(typeFactory));

        final Map<String, Object> testMap = new HashMap<>();
        testMap.put("myUuid", UUID.randomUUID());
        final String testMapJson =
                objectMapper.writeValueAsString(testMap);
        System.out.println(testMapJson);
        final Map deserTestMap = objectMapper.readValue(testMapJson, Map.class);

        final Bean1 bean1 = new Bean1();
        bean1.setData("Hello");

        final String bean1Json = objectMapper.writeValueAsString(bean1);
        System.out.println(bean1Json);
        final Bean1 deserBean1 = objectMapper.readValue(bean1Json, Bean1.class);
        final Map deserBean1Map = objectMapper.readValue(bean1Json, Map.class);

        final Bean2 bean2 = new Bean2();
        bean2.setData("World");
        bean2.setMap(new HashMap<String, String>());

        final String bean2Json = objectMapper.writeValueAsString(bean2);
        System.out.println(bean2Json);
        final Bean2 deserBean2 = objectMapper.readValue(bean2Json, Bean2.class);
        final Map deserBean2Map = objectMapper.readValue(bean2Json, Map.class);
    }
}
```

**Comment by cowtowncoder** [comment] 2016-11-29 20:42
Ok, hard to say just from description and code, since things can get complicated. But exception does suggest mismatch between expected and actual structures.

But I think that it should definitely be possible to use custom type ids; and that whatever serialization Jackson uses should be possible to read back.
However: one definite problem I do see are the last 2 lines -- with polymorphic types round-trip success requires that root value are same: it is not possible to write a POJO and read it as Map, because type id inclusion rules depend on types, structure, and this is not guarantees for such case.

Anyway I'll need to look into this with more time: this may take a while.

**Comment by patrick1024** [comment] 2016-11-30 06:02
> with polymorphic types round-trip success requires that root value are same: it is not possible to write a POJO and read it as Map

Ok, that is exactly what I would like to do and maybe that is my mentioned misunderstanding. I assumed it had to work because it works with `bean1` in the example.

**Comment by cowtowncoder** [comment] 2016-12-03 23:40
@patrick1024 Ah. The problem is that although you can read anything back as `Map`, polymorphic type information must be embedded as metadata. When reading POJOs (and in some cases with Map properties too if explicitly forced) this metadata is extracted and used; but rules for how it is used depend on expected (declared) base type.

Another way to say this is that base type (type declared in POJO) MUST be the same when serializing and deserializing, since information on how to handle type id are defined for that basetype and may vary between different types (different `@JsonTypeInfo`, or different inclusion rules for default typing).

On the other hand, serialize/deserialize with different types is perfectly fine when NOT using polymorphic typing: since there is no metadata, data only has to match structurally. This is how `ObjectMapper.convertValue()` works.

**Comment by patrick1024** [comment] 2016-12-05 08:43
Thanks for the information. I found a workaround by replacing the `objectMapper` in the last line with a virgin one (`new ObjectMapper()`).

**Comment by cowtowncoder** [comment] 2016-12-05 22:10
@patrick1024 Ok. Yes, this is tricky area, and documentation is sorely lacking.

I think I will close this one for now; this does not mean everything is definitely working as expected, but at this point I do not specific things to fix. So may be reopened with more targeted issue (although a new issue might make more sense if so).

**Closed by cowtowncoder** 2016-12-05 22:10 UTC
Labels: 2.8, ACTIVE
