### ISSUE TITLE
2.15.0 breaking behaviour change for records and Getter Visibility

### ISSUE THREAD

**Issue by matteobertozzi** [FasterXML/jackson-databind#3895] opened 2023-04-24 06:42 UTC
In 2.15 trying to encode records with PropertyAccessor.GETTER = Visibility.NONE will result in an empty object {}.
```java
record DataObject (int a, int b) {}

@Test
public void testRecord() throws Exception {
    final ObjectMapper jsonMapper = new JsonMapper();
    final String r = jsonMapper.writeValueAsString(new DataObject(2, 3));
    jsonMapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY);
    jsonMapper.setVisibility(PropertyAccessor.GETTER, Visibility.NONE);
    Assertions.assertEquals("{\"a\":2,\"b\":3}", r); // we get {}
}
```

to resolve that we can set PropertyAccessor.GETTER = Visibility.DEFAULT or others, but that will break every single class serialization that does not have annotations on getter methods.
```java
public class Foo {
    private final int x = 2;
    public int getComputedValue() { return 11; }
}

jsonMapper.writeValueAsString(new Foo()) // { x: 2, computedValue: 11 }
```

The behaviour in 2.14 with PropertyAccessor.GETTER = Visibility.NONE is the expected one, with records able to serialize all fields

Is this change something done on purpose? are there alternatives to set the visibility of getters and annotate every class method?

**Comment by yihtserns** [comment] 2023-04-26 14:49
@matteobertozzi can you share the reason for that config? Is the reason the same as #3628?

**Comment by matteobertozzi** [comment] 2023-04-26 15:20
@yihtserns the main reason is because we have "bad code". with classes that contains methods called "getXyz()" but they are not getters and they are doing computations and maybe some business logic.

so if we use something different from .GETTERS = Visbility.NONE, we end up with a value that is not supposed to be serialized and maybe some business logic triggered.
```java
public class Foo {
    private final int x = 2;
    public int getComputedValue() { return 11; }
}

jsonMapper.writeValueAsString(new Foo()) // { x: 2, computedValue: 11 }
```
going around all the methods in the codebase to add annotations may be fine for a major (e.g. the 3.x) but we didn't expect that for a minor.

**Comment by cowtowncoder** [comment] 2023-04-26 16:32
@matteobertozzi Sorry did not mean that you specifically should have tested, just that it is too bad no one with this use case had tried it and reported. There are gaps, hopefully over time fewer and fewer.

**Comment by agavrilov76** [comment] 2023-04-27 14:25
It is probably related that since version 2.15 `MapperFeature.SORT_PROPERTIES_ALPHABETICALLY` is not longer respected by record method based JSON properties.

The property 'a' in the example below comes at the last place:

```java
    final var mapper =
        Jackson.mapperBuilder()
            .enable(SerializationFeature.INDENT_OUTPUT)
            .enable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY)
            .build();

    record R(String c, String b, String e) {

      @JsonProperty
      String a() {
        return "4";
      }
    }

    System.out.println(mapper.writeValueAsString(new R("1", "2", "3")));
```
Output:

  {
    "b" : "2",
    "c" : "1",
    "e" : "3",
    "a" : "4"
  }

**Comment by yihtserns** [comment] 2023-04-27 14:43
@agavrilov76 can you create another issue for that?  It's not related to this, but rather is caused by #3724.

**Comment by agavrilov76** [comment] 2023-04-27 15:55
@yihtserns https://github.com/FasterXML/jackson-databind/issues/3900

**Comment by cowtowncoder** [comment] 2023-05-04 00:39
Would #3894 fix solve this as well? I just merged the fix.

**Comment by matteobertozzi** [comment] 2023-05-04 08:46
Hi, I did run my tests with the 2.15.1-20230504.033533-11 SNAPSHOT
#3894 seems to solve this issue!

Thanks!

```xml
<repositories>
    <repository>
      <id>oss.sonatype.snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

  <properties>
    <jackson.version>2.15.1-SNAPSHOT</jackson.version>
...
```

**Comment by cowtowncoder** [comment] 2023-05-04 17:32
Thank you @matteobertozzi !

**Closed** 2023-05-04 18:14 UTC

**Comment by haraldk** [comment] 2023-05-11 17:31
I just discovered that the default mapper configuration for the Azure SDK for Java is:

```java
        .visibility(PropertyAccessor.FIELD, Visibility.ANY)
        .visibility(PropertyAccessor.GETTER, Visibility.NONE)
```

Upgrading `jackson-databind` to 2.15.0 did break my message serialization in Azure Service Bus... Was about to file a new issue, when I found this. Indeed, 2.15.1-SNAPSHOT does seem to restore things to how it worked in 2.14.2 again. 👍🏻
