### ISSUE TITLE
Null Pointer Exception while Deserializing a bean with Jackson-databind 2.8.8.

### ISSUE THREAD

**Issue by Johny-Kandhari** [FasterXML/jackson-databind#1638] opened 2017-06-01 19:54 UTC
This scenario was working fine with Jackson Databind and other Jackson 2.5.2 Jars. Seems to be some issue with Jackson Databind and other Jackson 2.8.8. Please help if anyone can. This is urgent.

In our scenario we sent below bean in our rest request in form a Json: 

```
Json Used
{
  "sftpConnection": {
    "hostName": "localhost",
    "hostPort": 22,
    "userName": "root",
    "password": "kronites"
  },
  "dbConnection": null,
  "connectionType": {
    "id": 1,
    "name": "SFTP Connection",
    "typeName": "SFTP"
  },
  "name": "Connection 1"
}
```

Bean Used to save in POST Request
Bean1

```
@ApiModel(description = "@v1.0.ihubconnectiondefinitionbean.apimodel.description", value = "Integration Connection Definition")
@JsonRootName(value = "integration_connection_definition")
public class IhubConnectionDefinitionBean {
    @ApiModelProperty(required = true, value = "@v1.0.ihubconnectiondefinitionbean.apimodelproperty.id.description")
    private Long id;

    @ApiModelProperty(required = true, value = "@v1.0.ihubconnectiondefinitionbean.apimodelproperty.name.description")
    private String name;

    @ApiModelProperty(required = false, value = "@v1.0.ihubconnectiondefinitionbean.apimodelproperty.description.description")
    private String description;

    @ApiModelProperty(required = false, value = "@v1.0.ihubconnectiondefinitionbean.apimodelproperty.connectiontype.description")
    private IhubConnectionTypeBean connectionType;

    @ApiModelProperty(required = false, value = "@v1.0.ihubconnectiondefinitionbean.apimodelproperty.sftpconnection.description")
    private SFTPConnectionBean sftpConnection;

    @ApiModelProperty(required = false, value = "@v1.0.ihubconnectiondefinitionbean.apimodelproperty.dbconnection.description")
    private DBConnectionBean dbConnection;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description
	 *            the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}
	
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the connectionType
	 */
	public IhubConnectionTypeBean getConnectionType() {
		return connectionType;
	}

	/**
	 * @param connectionType
	 *            the connectionType to set
	 */
	public void setConnectionType(IhubConnectionTypeBean connectionType) {
		this.connectionType = connectionType;
	}

	/**
	 * @return the sftpConnection
	 */
	public SFTPConnectionBean getSftpConnection() {
		return sftpConnection;
	}

	/**
	 * @param sftpConnection
	 *            the sftpConnection to set
	 */
	public void setSftpConnection(SFTPConnectionBean sftpConnection) {
		this.sftpConnection = sftpConnection;
	}

	/**
	 * @return the dbConnection
	 */
	public DBConnectionBean getDbConnection() {
		return dbConnection;
	}

	/**
	 * @param dbConnection
	 *            the dbConnection to set
	 */
	public void setDbConnection(DBConnectionBean dbConnection) {
		this.dbConnection = dbConnection;
	}



Internal Bean 1: IhubConnectionTypeBean 

@ApiModel(description = "@v1.0.ihubconnectiontypebean.apimodel.description", value = "Integration Connection Type")
@JsonRootName(value = "integration_connection_type")
public class IhubConnectionTypeBean {
    @ApiModelProperty(required = false, value = "@v1.0.ihubconnectiontypebean.apimodelproperty.id.description")
    private Long id;

    @ApiModelProperty(required = false, value = "@v1.0.ihubconnectiontypebean.apimodelproperty.name.description")
    private String name;

    @ApiModelProperty(required = false, value = "@v1.0.ihubconnectiontypebean.apimodelproperty.typename.description")
    private String typeName;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name
	 *            the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the typeName
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * @param typeName the typeName to set
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}

Internal Bean 2:

@ApiModel(description = "@v1.0.sftpconnectionbean.apimodel.description", value = "SFTP Connnection")
public class SFTPConnectionBean {
    @ApiModelProperty(required = false, value = "@v1.0.sftpconnectionbean.apimodelproperty.hostname.description")
    private String hostName;

    @ApiModelProperty(required = false, value = "@v1.0.sftpconnectionbean.apimodelproperty.hostport.description")
    private Long hostPort;

    @ApiModelProperty(required = false, value = "@v1.0.sftpconnectionbean.apimodelproperty.username.description")
    private String userName;

    @ApiModelProperty(required = false, value = "@v1.0.sftpconnectionbean.apimodelproperty.password.description")
    private String password;

    @ApiModelProperty(required = false, value = "@v1.0.sftpconnectionbean.apimodelproperty.destinationdir.description")
	private String destinationDir;

	/**
	 * @return the hostName
	 */
	public String getHostName() {
		return hostName;
	}

	/**
	 * @param hostName
	 *            the hostName to set
	 */
	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	/**
	 * @return the hostPort
	 */
	public Long getHostPort() {
		return hostPort;
	}

	/**
	 * @param hostPort
	 *            the hostPort to set
	 */
	public void setHostPort(Long hostPort) {
		this.hostPort = hostPort;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName
	 *            the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password
	 *            the password to set
	 */
	public void setPassWord(String password) {
		this.password = password;
	}

	public String getDestinationDir() {
		return destinationDir;
	}

	public void setDestinationDir(String destinationDir) {
		this.destinationDir = destinationDir;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((hostName == null) ? 0 : hostName.hashCode());
		result = prime * result
				+ ((hostPort == null) ? 0 : hostPort.hashCode());
		result = prime * result
				+ ((userName == null) ? 0 : userName.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (obj == null || getClass() != obj.getClass())
			return false;
		if (hostName == null || hostPort == null || userName == null)
			return false;
		SFTPConnectionBean other = (SFTPConnectionBean) obj;
		return checkEquals(other);
	}

	/**
	 * @param other
	 */
	private boolean checkEquals(SFTPConnectionBean other) {
		return hostName.equalsIgnoreCase(other.hostName)
				&& hostPort.equals(other.hostPort)
				&& userName.equals(other.userName);
	}

}

Internal Bean 3: DBConnectionBean

@ApiModel(description = "@v1.0.dbconnectionbean.apimodel.description", value = "DB Connnection")
public class DBConnectionBean {
    @ApiModelProperty(required = false, value = "@v1.0.dbconnectionbean.apimodelproperty.hostname.description")
    private String hostName;

    @ApiModelProperty(required = false, value = "@v1.0.dbconnectionbean.apimodelproperty.hostport.description")
    private String hostPort;

    @ApiModelProperty(required = false, value = "@v1.0.dbconnectionbean.apimodelproperty.dbname.description")
    private String dbName;

    @ApiModelProperty(required = false, value = "@v1.0.dbconnectionbean.apimodelproperty.username.description")
    private String userName;

    @ApiModelProperty(required = false, value = "@v1.0.dbconnectionbean.apimodelproperty.password.description")
    private String password;

	/**
	 * @return the hostName
	 */
	public String getHostName() {
		return hostName;
	}

	/**
	 * @param hostName
	 *            the hostName to set
	 */
	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	/**
	 * @return the hostPort
	 */
	public String getHostPort() {
		return hostPort;
	}

	/**
	 * @param hostPort
	 *            the hostPort to set
	 */
	public void setHostPort(String hostPort) {
		this.hostPort = hostPort;
	}

	/**
	 * @return the dbName
	 */
	public String getDbName() {
		return dbName;
	}

	/**
	 * @param dbName
	 *            the dbName to set
	 */
	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName
	 *            the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password
	 *            the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}
```

Exception with Full Stack Trace

```
"ERR": { java.lang.NullPointerException
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase._resolvedObjectIdProperty(BeanDeserializerBase.java:798)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:497)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:466)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:479)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:476)
	at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1902)
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:676)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:803)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1348)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBody(JAXRSUtils.java:1299)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameter(JAXRSUtils.java:825)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameters(JAXRSUtils.java:789)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:212)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:77)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:262)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:299)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:218)
```

**Comment by cowtowncoder** [comment] 2017-06-01 21:01
Since this problem occurs when invoked via CXF, there are 2 main possibilities: either it is on Jackson side, or on CXF. I can't help with latter, but can with former. So what would be helpful would be a stand-alone test case that only uses `jackson-databind`, not via framework.

**Comment by Johny-Kandhari** [comment] 2017-06-02 14:41
HI

Thanks for the quick response. I am in process of converting this to a sample rest call program, But it would be very helpful if you can get some clues by looking at the stacktrace, this issue is working fine with jackson 2.5.2. The beans which I have added here are independent of my application, but I would try to upload a full fledged program replicating this exception in some time.

**Comment by cowtowncoder** [comment] 2017-06-02 19:44
@Johny-Kandhari All I can say is that this is the first time problem has been reported so it probably has to be quite unusual use case or setup.

One guess I do have from stack trace: if application or framework in use specifies custom deserializers, one of them may not be properly propagating calls to `resolve()` method, which could perhaps lead to some state being left incomplete. This would happen when for example custom deserializer was wrapping standard one, created via `BeanDeserializerModifier`: both `resolve()` (via `ResolvableDeserializer`) and `createContextual` (via `ContextualDeserializer`) should be propagated as they are the mechanism to resolve cyclic type dependencies (resolve) and access to contextual information (annotations).

Another possibility wrt custom deserializers could be if `BeanDeserializer` was sub-classes: while this is not encouraged (sub-classing here is fragile, but can not be prevented) it is sometimes done as work-around.

**Comment by Johny-Kandhari** [comment] 2017-06-02 19:58
[Jackson Issue Client and rest Service.zip](https://github.com/FasterXML/jackson-databind/files/1048810/Jackson.Issue.Client.and.rest.Service.zip)

@cowtowncoder 

I have uploaded the stand alone test replicating the exact error without any dependency on my application. I think this will help you to resolve. You just need to add dependencies manually. Please let me know as I am stuck. In this test also it is working fine with Json 2.5.2 but not with json 2.8.8. 

One more important point to note, you will see a CustomObjectmapper defined in this stand alone test, thats the same way mapper is defined in our application also. is there any issue with these mappers.

**Comment by Johny-Kandhari** [comment] 2017-06-05 18:34
@cowtowncoder 

Any updates on this issue. This is a acting like a blocker for our environment. Please let me know if there is any update regarding the same.

**Comment by Johny-Kandhari** [comment] 2017-06-05 19:36
@cowtowncoder 

Now I have the root cause for this issue. In Jackson 2.8.8 (MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES,true) is not working. When i kept this feature disabled by default then the scenario is working fine.

Actually in the above scenario one of the bean is having wrong setter method Name. In SFTPConnectionBean the setter for field password is named as setPassWord instead of setPassword.

This is a typo error in the bean, bull till jackson 2.5.2 this feature (MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES,true) was allowing this bean to deserialize 

But in jackson 2.8.8 this is not working. when i commented this feature then the functionality was working fine and the bean was deserialized.

Is is like that it is not reccomended to use this feature after 2.8.0? If it is recommended then why it is failing and if there is some another alternative to this in jackson 2.8.8.?

Please answer my queries so that i can get down to suitable conclusion. Because if i remove this mapperfeature then it can cause impact on my system. Please let me know the current and future roadmap for this feature MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES

**Comment by cowtowncoder** [comment] 2017-06-05 22:32
@Johny-Kandhari sounds like there could be a remaining problem with that feature then. It should not throw an NPE. There have been some issues with this feature, but as far as I know all known issues before this one have been fixed.

I have not had time to work on this issue, and probably will not for next couple of days. I hope to look into it relatively soon, still, as it sounds legitimate problem, even if as of yet not reported by anyone else.

Now.... I think you may have misunderstood how open source software works: there are many, MANY users with all kinds of problems -- our projects have literally hundreds of open, reported issues -- and volunteers like me try to help these get resolved. Quite often I work on things on first-come, first-served basis. Others may work the same way, helping in areas they are most familiar with, or on issues they have also experienced. Sometimes more widely relevant issues get worked on earlier, sometimes not.

But one sure-fire way to get people pissed is to demand immediate focus for problem that you happen to have; somehow assuming that your need should somehow trump needs of everyone else. I suggest you avoid making that mistake.

I will also not be giving hourly updates -- when I work on an issue, I add updates. Lack of updates is typically an indication of nothing of interest happening. It is fine to occasionally ask since things may fall through the cracks, but as I wrote, what seems like a demand is unlikely to result in additional helpful interaction.

Thank you for providing a test case; that should be helpful in isolating the problem.

**Comment by Johny-Kandhari** [comment] 2017-06-06 05:28
@cowtowncoder 

This is bad on my part. I will take care for this and assure that it does not happen again. We have drill down this problem to a single feature which is not working fine with these latest jars. Let me try if i can contribute something to this and will let you know. If you have any update regarding the same, then please let me know.

**Comment by cowtowncoder** [comment] 2017-06-09 02:21
@Johny-Kandhari ok no problem. I hope we can resolve the issue. I appreciate all your help here, and hope to work on this very soon now, before 2.9.0.pr4.

**Comment by cowtowncoder** [comment] 2017-06-09 03:10
Ok. Unfortunately the project is kind of big for reproducing the specific problem. However, given the stack trace I can see where the problem is triggered. Although I am bit suspicious of null problem being a symptom and not the cause, it is easy enough to add null check for specific case, and it really should not cause any problems -- and if root cause is problematic, it will probably exhibit other problems.

So, I checked in a patch in `2.8` branch, which will go in `2.8.9`.

If you can do a local build from that branch (or use snapshot from maven central), you can see if the fix allows system to run, or if it hits some other problem.

**Closed** 2017-06-09 03:10 UTC
