### ISSUE TITLE
Polymorphic Inheritance deserialization fails due to missing type id

### ISSUE THREAD

**Issue by isakovarseniy** [FasterXML/jackson-databind#3831] opened 2023-03-16 17:42 UTC
**Describe the bug**
During deserialization object with inheritance I. am getting following exception 

com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class objects.test.serialazable.jpa.Canvas]: missing type id property '@class' (for POJO property 'canvas')
 at [Source: (String)"{"@class":"Window","serializationid":"1344b4ba-89c4-436b-a0f3-122062efed60","attached":null,"cpaid":null,"uid":"49eeb110-ff9d-4f77-b09d-c9aae4414a58","name":null,"suidCanvas":null,"canvasName":null,"uiElement":["java.util.ArrayList",[{"@class":"InputText","serializationid":"91542b40-c602-475b-9f48-2558c4ea2e07","attached":null,"cpaid":null,"uid":"c599c204-f2c1-4dcd-a25b-16610916ae5b","suidUiElement":null,"transientrefParent":null,"uiElName":null,"canvas":"1344b4ba-89c4-436b-a0f3-122062efed60","s"[truncated 69 chars]; line: 1, column: 460] (through reference chain: objects.test.serialazable.jpa.Window["uiElement"]->java.util.ArrayList[0]->objects.test.serialazable.jpa.InputText["canvas"])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:1771)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1300)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:299)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:164)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:88)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:369)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1257)
	

**Version information**
2.10.3

**To Reproduce**
I have created an example maven project with test in ObjectSerialTest.java file 

[inheritance-serialization.zip](https://github.com/FasterXML/jackson-databind/files/10994007/inheritance-serialization.zip)

**Comment by cowtowncoder** [comment] 2023-03-16 23:44
First things first: 2.10 is a rather old version -- can this still be reproduced with 2.14(.2)?

**Comment by isakovarseniy** [comment] 2023-03-16 23:47
Yes same issue with 2.14.2

**Comment by cowtowncoder** [comment] 2023-03-18 17:31
Ok one problem is that `@JsonTypeInfo` is used on all types -- it should ONLY be used on specific base type used in declarations. Or, worse, since you are for some reason using BOTH `@JsonTypeInfo` AND Default Typing, things get even more confusing -- generally only one or the other ought to be used. I would start by disabling default typing.
And in fact this really cannot even work: `@JsonTypeInfo` indicates use of "type name" (logical name) as Type Id -- but Default Typing ALWAYS uses class name as Type Id. That cannot work.

And to top it off, `@JsonIdentityInfo` is used also for a good measure (is that really needed?)

I am guessing definitions were done by trying to out various things, possibly not quite understanding what each thing does? (understandable as polymorphic handling is not trivial).

So. Removing use of either Default Typing OR annotations would be the first step to try to figure out things.
If using `@JsonTypeInfo` (recommended over Default Typing for), also make sure NOT to add it on subtypes -- only on common base type, used on type declarations (type common to subtypes to support).

**Comment by isakovarseniy** [comment] 2023-03-19 00:37
You can do like this ( See archive)
[inheritance-serialization.zip](https://github.com/FasterXML/jackson-databind/files/11009931/inheritance-serialization.zip)

**Comment by cowtowncoder** [comment] 2023-03-20 01:16
@isakovarseniy so does that work now, with changes? If so, we can close the issue.

**Closed** 2023-03-20 01:18 UTC
Labels: to-evaluate
