### ISSUE TITLE
JsonTypeInfo is lost when serializing a Page

### ISSUE THREAD

**Issue by Ganondolf** [FasterXML/jackson-databind#2710] opened 2020-05-04 20:52 UTC
Possibly related to #2606 (due to type erasure), and already reported on [stackoverflow](https://stackoverflow.com/questions/56293048/jsontypeinfo-not-shown-in-response-whit-pageable).

I have a polymorphic type that needs to be serialized and deserialized:

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({ @Type(value = FooSubType.class, name = "fooSubType") })
public abstract class Foo {

    private Long id;
    private Long userId;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

}
```

When serializing an instance of `FooSubType` or a list of instances, everything works fine, but if I try to serialize a `org.springframework.data.domain.Page`, the `type` property disappears:

```java
    @GetMapping("/list")
    public List<Foo> list() {
        FooSubType sub = new FooSubType();
        sub.setId(1l);
        sub.setUserId(2l);
        sub.setBar(3l);
        return List.of(sub);
    }
```
```json
// correct
[
  {
    "type": "fooSubType",
    "id": 1,
    "userId": 2,
    "bar": 3
  }
]
```
```java
    @GetMapping("/page")
    public Page<Foo> page() {
        FooSubType sub = new FooSubType();
        sub.setId(1l);
        sub.setUserId(2l);
        sub.setBar(3l);
        return new PageImpl<>(List.of(sub));
    }
```
```json
// missing subtype
{
  "content": [
    {
      "id": 1,
      "userId": 2,
      "bar": 3
    }
  ],
  ...
}
```

As mentioned in the stackoverflow answer, using an anonymous inner class `new PageImpl<>(List.of(sub)) {};` is a functioning workaround, but it's not pretty.

Currently on Jackson 2.10.3 and Spring 5.2.1.RELEASE.

**Comment by cowtowncoder** [comment] 2020-05-04 22:05
I am not sure there is much Jackson can do here since invocation of Jackson (and specifically passing of types) is outside its control. Definition of `Page` is missing making it difficult to say for sure, but I am guessing this is due to Spring just passing instance without type parameters, meaning Jackson likely only sees type as `Page<?>` and hence has no way of knowing expected type parameter bounds.

If you can reproduce this with Jackson-only reproduction that would help; alternatively it should probably go to Spring (Boot? MVC?) issue tracker first.

**Comment by Ganondolf** [comment] 2020-05-06 19:04
invoking Jackson explicitly leads to almost the same results, except that now Lists also behave in the same weird way:

```java
FooSubType sub = new FooSubType();
sub.setId(1l);
sub.setUserId(2l);
sub.setBar(3l);
List<Foo> list = new ArrayList<>();
list.add(sub);
mapper.writeValueAsString(list);
```
```json
[ {
  "id" : 1,
  "userId" : 2,
  "bar" : 3
} ]
```
But with an anonymous class we fix the problem (spring still deserialize both  correctly):
```java
FooSubType sub = new FooSubType();
sub.setId(1l);
sub.setUserId(2l);
sub.setBar(3l);
List<Foo> list = new ArrayList<>() {};
list.add(sub);
mapper.writeValueAsString(list);
```
```json
[ {
  "type" : "fooSubType",
  "id" : 1,
  "userId" : 2,
  "bar" : 3
} ]
```

Same with page:
```java
FooSubType sub = new FooSubType();
sub.setId(1l);
sub.setUserId(2l);
sub.setBar(3l);
List<Foo> list = new ArrayList<>();
list.add(sub);
Page<Foo> page = new PageImpl<>(list);
mapper.writeValueAsString(page);
```
```json
{
  "content" : [ {
    "id" : 1,
    "userId" : 2,
    "bar" : 3
  } ],
  "pageable" : "INSTANCE",
  "last" : true,
  "totalPages" : 1,
  "totalElements" : 1,
  "size" : 1,
  "number" : 0,
  "sort" : {
    "sorted" : false,
    "unsorted" : true,
    "empty" : true
  },
  "first" : true,
  "numberOfElements" : 1,
  "empty" : false
}
```
with anonymous class:
```java
FooSubType sub = new FooSubType();
sub.setId(1l);
sub.setUserId(2l);
sub.setBar(3l);
List<Foo> list = new ArrayList<>();
list.add(sub);
Page<Foo> page = new PageImpl<>(list) {};
mapper.writeValueAsString(page);
```
```json
{
  "content" : [ {
    "type" : "fooSubType",
    "id" : 1,
    "userId" : 2,
    "bar" : 3
  } ],
  "pageable" : "INSTANCE",
  "last" : true,
  "totalPages" : 1,
  "totalElements" : 1,
  "size" : 1,
  "number" : 0,
  "sort" : {
    "sorted" : false,
    "unsorted" : true,
    "empty" : true
  },
  "first" : true,
  "numberOfElements" : 1,
  "empty" : false
}
```

**Comment by cowtowncoder** [comment] 2020-05-06 19:18
Ah. Yes, this is due to infamous Java Type Erasure, where runtime type of `List<MyType>` is effectively `List<?>`, which is about same as `List<Object>`. And since `Object` does not have `@JsonTypeInfo` polymorphic typing is not enabled.

Work-arounds include:

1. Never using generic types as root values: always have non-generic POJO as container. This is what I recommend in designs to reduce risks.
2. Create helper type (work-around you mentioned earlier) for `class MyList extends ArrayList<MyType> { }`
3. Tell Jackson actual intended type:

     mapper.writerFor(new TypeReference<List<MyType>>() { }).
        .writeValueAsString(list);

of which (3) is actual solution in which you indicate more refined type.

I think some frameworks may do (3), but JAX-RS specification (for example) unfortunately does not have good mechanism for doing this (I wrote this -- http://www.cowtowncoder.com/blog/archives/2010/12/entry_436.html -- 10 years ago to explain what the problem is).
Although I guess theoretically one can try to implement one of `java.lang.reflect.Type` subtypes to make it work.

**Comment by cowtowncoder** [comment] 2020-05-08 02:19
Unfortunately I am not sure there is much Jackson itself can do about this, so closing.

**Closed by cowtowncoder** 2020-05-08 02:19 UTC

**Comment by ThisIsIPat** [comment] 2024-07-12 12:09
I hope I'm not reopening the issue by responding, but the following could be useful for developers using Kotlin looking for a solution online:

```kotlin
import org.springframework.data.domain.Page
import org.springframework.data.domain.PageImpl

/**
 * Wraps a [Page] into a subclass of [PageImpl] to allow for Jackson serialization:
 * https://github.com/FasterXML/jackson-databind/issues/2710#issuecomment-624833047
 */
inline fun <reified T> Page<T>.wrap(): Page<T> {
    return object : PageImpl<T>(
        this.content,
        this.pageable,
        this.totalElements
    ) {}
}
```

Simply call `.wrap()` on a Page to have the contents be able to get serialized **including** consideration of the Jackson annotations of, for example, `T` being a parent class with a JsonSubTypes / JsonTypeInfo annotation.

**Comment by cowtowncoder** [comment] 2024-07-13 00:09
Thank you for sharing, @ThisIsIPat !
