### ISSUE TITLE
UUID Deserialization of 22 bytes strings is incorrect

### ISSUE THREAD

**Issue by ionutcapitanu** [FasterXML/jackson-databind#4658] opened 2024-08-08 15:00 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

UUID Deserialization of 22 bytes is assumed to be a base24 URL-safe encoded value, which allows for incorrect values as input

### Version Information

2.17.0

### Reproduction

 Example code : 
```java
    String json = "\"47ec-b2ab-3bc53a0c0f9e\"";
    ObjectMapper mapper = new ObjectMapper();
    UUID uuid = mapper.readValue(json, UUID.class); 
``` 

### Expected behavior

Should fail with a deserialization exception

**Comment by yawkat** [comment] 2024-08-09 08:30
This behavior seems correct to me. That's valid base64 url encoded data.

**Comment by cowtowncoder** [comment] 2024-08-11 23:04
I concur with @yawkat: `UUIDDeserializer` allows for 3 main valid input types:

1. For formats with true binary data: 16-byte binary value
2. Strings, 36 characters: canonical UUID representation
3. Strings, 22 or 24 characters: if valid Base64 representation, decode as 16 bytes, deserialize

Now... the interesting part is that hyphen (`-`) is only accepted for non-padded case (22 characters), which uses `Base64Variant.MODIFIED_FOR_URL`; it would fail for 24-character case (which uses default, padding-using standard Base64 encoding).

So: while it may seem odd, this is intended behavior. Closing.

**Closed by cowtowncoder** 2024-08-11 23:04 UTC
