### ISSUE TITLE
Unrecognized field "NAME" , not marked as ignorable (4 known properties: "name", "address", "departmentName", "departmentID"])  at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@6c4e13bb; line: 2, column: 9]

### ISSUE THREAD

**Issue by Deepak-D** [FasterXML/jackson-databind#2504] opened 2019-10-16 04:08 UTC
I have issue in deserialization of JSON property in my REST web service. I'm deserializing JSON properties using my POJO class as below

```java
@JsonPropertyOrder({ "NAME", "DepartmentID", "address", "departmentName"})
public class UserDetails implements Serializable {
private String NAME;
private Integer DepartmentID;
private String address;
private String departmentName;

public UserDetails() {
NAME= "";
DepartmentID = -1;
address= "";
departmentName= "";
}

@JsonProperty("NAME")
public String getNAME() {
	return NAME;
}

public void setNAME(String NAME) {
	this.NAME= NAME;
}

@JsonProperty("DepartmentID")
public Integer getDepartmentID() {
	return DepartmentID;
}

public void setDepartmentID(int DepartmentID) {
	this.DepartmentID = DepartmentID;
}

public String getAddress() {
	return address;
}

public void setAddress(String address) {
	this.address= address;
}

public String getDepartmentName() {
	return departmentName;
}

public void setScaleGroup(String scaleGroup) {
	this.scaleGroup = scaleGroup;
}
}
```

Here is my REST call look like

```
@POST
@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
@Consumes(MediaType.APPLICATION_JSON)
public Response addOrUserDetails(**UserDetails userDetails**, @Context final HttpServletRequest httpServletRequest, @Context final HttpServletResponse servletResponse) {
}
```

Below is the list of Jackson libraries I use in my project:

```
jackson-annotations-2.3.2.jar
jackson-core-2.3.2.jar
jackson-databind-2.3.2.jar
jackson-jaxrs-base-2.3.2.jar
jackson-jaxrs-json-provider-2.3.2.jar
jackson-module-jaxb-annotations-2.3.2.jar
```

Jersey Jackson version:
**jersey-media-json-jackson-2.17.jar**

I'm deploying my web service as a WAR package to the Jetty web server.

**Note: This problem is only when I use jersey library jersey-media-json-jackson-2.17.jar in parent classloader i.e., in jetty ext/lib/. If I include this library inside web service WEB-INF/lib/, the deserialization is working fine.**

From error log, I don't understand how the JSON property name has been case converted into ["name", "address", "departmentName", "departmentID"].

Appreciate any help! Thanks!

**Comment by cowtowncoder** [comment] 2019-10-16 17:07
I would need a test case (code to trigger the problem). It is of no use to see what JAX-RS framework does since it may configure `ObjectMapper` in specific way. What is needed is to show how Jackson is used, outside of other frameworks.

You should also upgrade to newer Jackson versions: 2.3.2 was released 5 years ago: it is possible that some issues have been resolved since then. Latest stable version is 2.10.0, but at least try the latest 2.9 patch, 2.9.10.

**Comment by Deepak-D** [comment] 2019-10-17 04:10
Thanks for getting back to me guys @aholake and @cowtowncoder 

@cowtowncoder, I will try using the stable version 2.10.0 and see if this helps.

**Comment by cowtowncoder** [comment] 2019-11-07 18:22
Closing for now, assuming it may have been resolved with upgrade. If not, may be reopened with full reproduction that does not rely on other frameworks/libraries (that is, with jackson-only dependencies).

**Closed by cowtowncoder** 2019-11-07 18:22 UTC
Labels: need-test-case
