### ISSUE TITLE
JsonMerge got unexpected result for List 

### ISSUE THREAD

**Issue by lubinson** [FasterXML/jackson-databind#2315] opened 2019-05-04 18:54 UTC
Hi Experts,

I got unexpected (but maybe as designed) result using JsonMerge for a List merge. 
For a short summary, I want to merge below Json1 with Json2:
Json1:
```
{"titles":["Mr","Mrs"]}
```
Json2:
```
{"titles":["mr","mrs"]}
```
I expect got Json2, but I got below Json3:
Json3:
```
{"titles":["Mr","Mrs","mr","mrs"]}
```
There has a description in [JSON Merge Patch](https://tools.ietf.org/html/rfc7396). 

> If the patch is
   anything other than an object, the result will always be to replace
   the entire target with the entire patch.

And there has a sample in section `3. Sample` of this spec.  
Based on this spec, I expected Json2. But I think maybe it will be better to make the behavior configurable, e.g. replace, add, merge with diff, etc. 

I also tried merging Json1 with a same List, then I got below which is also unexpected. 
```
{"titles":["Mr","Mrs","Mr","Mrs"]}
```
It looks the behavior of Merge List is just `add`.

Below is the code to reproduce, Pls copy to a java file and run. 
```
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonMerge;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;

public class JsonMergeTEst {
  public static void main(String[] args) throws IOException {


    ObjectMapper objectMapper = new ObjectMapper();

    List<String> list1 = new ArrayList<>();
    list1.add("Mr");
    list1.add("Mrs");
    
    List<String> list2 = new ArrayList<>();
    list2.add("mr");
    list2.add("mrs");
    
    
    Title title1 = new Title();
    title1.setTitles(list1);
    JsonNode title1Node = objectMapper.valueToTree(title1);

    Title title2 = new Title();
    title2.setTitles(list2);
    JsonNode title2Node = objectMapper.valueToTree(title2);

    ObjectReader objectReader = objectMapper.readerForUpdating(title1Node);
    JsonNode title3 = objectReader.readValue(title2Node);
    System.out.println(objectMapper.writeValueAsString(title3));

//    ObjectReader objectReader2 = objectMapper.readerForUpdating(title1);
//    Title title4 = objectReader2.readValue(title2Node);
//    System.out.println(objectMapper.writeValueAsString(title4));
  }

  public static class Title {
    @JsonMerge
    List<String> titles = null;

    public List<String> getTitles() {
      return titles;
    }

    public void setTitles(List<String> titles) {
      this.titles = titles;
    }
  }
}
```
In the code I also tried using class `Title` instead of `JsonNode` as input of `readerForUpdating`, but still get same result. 

Thanks very much.

**Comment by lubinson** [comment] 2019-05-10 14:16
can any one give an update on this issue?

**Comment by cowtowncoder** [comment] 2019-05-11 04:06
Jackson does not implement JSON Merge Patch, Merge functionality follows Jackson's definition in which `Collection` valued properties are combined by appending contents of second Collection into first one. If you want JSON Merge Patch style merging, you may need to implement it yourself, or find a tool that implements it.

I'll see if I can improve Javadocs for `@JsonMerge` to indicate that `Collection` merging occurs with `add` on base value.

**Comment by cowtowncoder** [comment] 2019-05-11 17:23
One more thing I forgot to mention: behavior where Collections/arrays are simply overwritten should actually work with merging if merging is disabled for Collection-/array-valued property, like:

    @JsonMerge(OptBoolean.FALSE)
    public List<String> values;

or equivalent configuration via "config overrides" (objectMapper.configOverrides(Collection.class).setMergeable(false);)

**Comment by tiguchi** [comment] 2019-11-20 23:56
> Jackson does not implement JSON Merge Patch, Merge functionality follows Jackson's definition in which `Collection` valued properties are combined by appending contents of second Collection into first one. If you want JSON Merge Patch style merging, you may need to implement it yourself, or find a tool that implements it.
> 
> I'll see if I can improve Javadocs for `@JsonMerge` to indicate that `Collection` merging occurs with `add` on base value.

I also need to merge data from a JSON input stream into an existing list property of a merge target object.

Is there any way to register a custom merge strategy with `ObjectReader` when calling `readerForUpdating`?

Or if I'd implement a custom `JsonDeserializer` for list collection types,

1. would Jackson acknowledge my deserializer and prefer it over the internal list deserialization mechanism?
2. would it be possible to retrieve the target object (the actual list I want to merge into) through `DeserializationContext`?

**Comment by cowtowncoder** [comment] 2019-11-22 20:24
Interesting... I _think_ functionality you are using is reasonable and should work, however, it may be bit fragile (i.e. could not work for some specific case of 3rd party deserializers).
One thing that could be helpful against regressions would be if you wanted to submit a unit test for `jackson-databind` that does simplified version of your real use case -- that would at least make it less likely databind itself would be changed in a way that breaks the logic (there are tests for keeping context info accurate but coverage is quite shallow).

One question however: did you try overriding

    public T deserialize(JsonParser p, DeserializationContext ctxt, T intoValue);

method? That is what merging use case should call, with default impl of

```
    {
        ctxt.handleBadMerge(this);
        return deserialize(p, ctxt);
    }
```

so overriding of this (or, method `handleBadMerge()` in `DeserializationContext` but that's more work, less robust) might work. Or is that called on wrong object, wrt what you need?

**Comment by tiguchi** [comment] 2019-11-22 21:08
> One question however: did you try overriding
> 
> ```
> public T deserialize(JsonParser p, DeserializationContext ctxt, T intoValue);
> ```
> 
> method? That is what merging use case should call, with default impl of
> 
> ```
>     {
>         ctxt.handleBadMerge(this);
>         return deserialize(p, ctxt);
>     }
> ```
> 
> so overriding of this (or, method `handleBadMerge()` in `DeserializationContext` but that's more work, less robust) might work. Or is that called on wrong object, wrt what you need?

I was absolutely unaware of the that method, since I always used `StdDeserializer` so far. Many thanks for pointing that out! I will give it a try and check if it receives the correct object to update. 

Ultimately I need to get access to a list property of an entity I want to update using a partial update. So the Jackson deserialization begins with 

```
objectMapper.readerForUpdating(entityWithListProperty)
```

The existing items in that list should be partially updated, without having to remove and re-create them entirely.

I already managed to finish my custom patch implementation and everything works fine. I covered it with a whole bunch of unit tests in my web app project to make sure that future updates don't break anything. So that's at least covered on my side.

I appreciate your offer that I can submit a simplified unit test to the `jackson-databind` project. I will look into it as soon as possible

**Comment by cowtowncoder** [comment] 2019-11-22 21:21
Ok yes. So method I pointed out is what should be called with value to update for merging, regardless of level, including root value.

But it would get called on `CollectionDeserializer`, so that may or may not work well.

Possibility to customize merging action was something I thought about when implementing `@JsonMerge`, but ultimately it seemed difficult to find good set of alternative behaviors. I would be open to allowing some form of custom handlers, if good API could be defined.
That would take a while, though, so would not help on short term (additions go into next minor/major versions).

**Comment by lubinson** [comment] 2020-05-17 11:43
@cowtowncoder 

Back to this after long time. 
Because we use JsonNode and all nested data types are changed to Json own data types. Of cause it also use Java data type, e.g. List. But at this case, Below configuration is not working.
```
objectMapper.configOverrides(Collection.class).setMergeable(false)
```
I am using Jackson 2.10.0. 

Thanks.

**Comment by cowtowncoder** [comment] 2020-05-17 16:34
@lubinson at this point I think what I would is just a bit more than what is included: actual unit test with assertions -- it is not enough to use "just run the code and see what output says" because this is often easy to misunderstand (exactly how is output wrong?).
Assertions in tests are better because they set exactly what submitter thinks is wrong and in this case I think it is only one or two more statements.

Would this be possible to add? I am happy to help, but want to make sure I fully understand the issue.

**Comment by lubinson** [comment] 2020-05-18 17:12
@cowtowncoder 
Thanks for your reply. So I thought the ArrayList in the `ArrayNode` shall also follow the configuration.  Hope it will work soon in 2.12. Keep following. Thanks.

**Comment by cowtowncoder** [comment] 2020-05-18 17:48
@lubinson use of `ArrayList` in `ArrayNode` is purely implementation detail, but logically it would seem reasonable that similar logic would be used.

But are you saying this is not the case? As I said, at this point I could use a concise example case with assertion(s) to show case where what I have said is expected behavior is not actual behavior. This is important as right now I do not have specific plan for changes, as I do not yet know the specific problem (discussion above covers many distinct things which makes it bit trickier to make sure we have shared understanding of the problem).

**Comment by cowtowncoder** [comment] 2020-10-27 04:19
At this point not quite sure what could be done here; closing. May be re-filed with a specific description of issue (possible referencing this issue for background if that helps).

**Closed by cowtowncoder** 2020-10-27 04:19 UTC
