### ISSUE TITLE
Possibly concurrency problem wrt `@JsonRootName` sometimes being missed

### ISSUE THREAD

**Issue by VinRoh** [FasterXML/jackson-databind#1512] opened 2017-01-31 16:30 UTC
#We have a serious problem with @JasonRootName annotation .This is happening on a highly critical Java project. The response of RestService is a POJO ServiceResponse.java with the @JasonRootName(value=serviceResponse). As expected most of the time the json response returned is correct as "serviceResponse" but data binding fails once in 50 deployments and sends the Json response as "ServiceResponse" which is the class name but with uppercase "S". The Jackson version used is 2.6.1 and the Java version is 1.7. Is there any issue with the JacksonAnnotationIntrospector.java and AnnotationClass.java under the com.fasterxml.jackson.databind.introspect package??

**Comment by VinRoh** [comment] 2017-02-01 01:53
Seems to be very similar to https://github.com/FasterXML/jackson-module-scala/issues/197

**Comment by VinRoh** [comment] 2017-02-02 17:14
Moved to a version 2.8.5 of fasterxml. Lets see if this fixes the data binding issue.

**Comment by cowtowncoder** [comment] 2017-02-02 21:50
I did check in a minor simplification of the way `AnnotatedClass` collects class annotations, so that they are eagerly calculated. This is in 2.8 branch, for upcoming 2.8.7 release.

What would be most useful at this point would be a reproduction: without one there is no good way to verify possible solutions (or to verify which platform(s), JVMs this occurs on).

Aside from `AnnotatedClass`, theoretically this could be related to use of `LRUMap` by `RootNameLookup`, but otherwise I'd have to question whether reflection within JDK could have something to do with it.

**Comment by VinRoh** [comment] 2017-02-05 08:53
Thanks for the details.
This problem happens every day on some 20 odd systems of the 1500 in network. But I need suggestion as to which classes should we observe in fasterxml/databind other than the ones which I mentioned earlier.
Is it just Annotation, JacksonAnnotationIntrospector ,LRU Map??

It seems LRU map should not be a problem as it is a Concurrent hash map .The annotation entry would be added only in the map if it is found or else the default class name gets added as per the findRootName() api in the RootNameLookup class. So, I feel whatever annotation name is added in the map for the first time is returned in the subsequent calls.

We run our applications on linux suse' platform.

**Comment by cowtowncoder** [comment] 2017-02-14 19:36
Ok; I did make one change to `2.8` so that `AnnotatedClass` will eagerly introspect class annotations.
This simplifies code slightly and could have an effect since these annotations are used for root name.
I am not 100% sure how the problem itself could come about but it sounds somewhat plausible in that incomplete information might be used before resolution.
Change will be in 2.8.7, although if you can build module locally you could try 2.8.7-SNAPSHOT (or via Sonatype snapshots, I think databind is automatically built).

Otherwise I do not really know what could be causing the issue unless there were some problems within JDK itself regarding annotation access.

**Comment by cowtowncoder** [comment] 2017-03-30 03:28
@VinRoh any chance you might have tested this with 2.8.7?

**Comment by VinRoh** [comment] 2017-06-30 19:10
Please close this. The Issue got resolved with 2.8.7 .
Thanks.

**Comment by cowtowncoder** [comment] 2017-06-30 22:57
Excellent, thank you for verifying this.

**Closed** 2017-06-30 22:57 UTC
