### ISSUE TITLE
TreeTraversingParser and UTF8StreamJsonParser create contexts differently

### ISSUE THREAD

**Issue by apetrelli** [FasterXML/jackson-databind#2049] opened 2018-05-24 10:29 UTC
UTF8StreamJsonParser creates a child context every time:
* it encounters a property
* if the property is collection-like a new context is born for every element in the collection.

TreeTraversingParser instead creates a child context every time a new object has been created.
The result is that, for collection-like properties, the current value of the current context is first set with the container object, then with the collection itself.

I attach a small test case with two tests in which I created a DeserializerModifier to try to append a parent to all children objects.
[jackson-bug-test.zip](https://github.com/FasterXML/jackson-databind/files/2034895/jackson-bug-test.zip)
I tried with versions 2.9.5 and 2.8.10.

**Comment by cowtowncoder** [comment] 2018-07-17 23:30
Possibly dup of #1803? (or just related)

**Comment by apetrelli** [comment] 2018-07-20 07:06
@cowtowncoder no, that issue refers to the passing of parent context externally, instead this issue is about the creation of subcontexts, that in UTF88StreamJsonParser happens more frequently than in TreeTraversingParser.

**Comment by cowtowncoder** [comment] 2019-10-26 00:47
Good news -- finally found time to go back to this, and filed separate #2525 to resolve slightly bigger issue (there is also `TokenBuffer` to consider).
Provided test now passes: fix will be in 2.11.0, eventually: I am hesitant to make a change in patch for 2.10 (although it is relatively early) just because there is non-trivial chance of some code somewhere relying on some aspects of old handling.

**Closed** 2019-10-26 01:03 UTC
Labels: 2.10

**Comment by cowtowncoder** [comment] 2025-11-17 00:36
Note: fails for 3.0.0 for some reason; reopening.

**Comment by cowtowncoder** [comment] 2025-11-17 00:43
As expected, test-only problem, not actual regression. Fixed in 3.x for 3.1.
