### ISSUE TITLE
`@JsonValue` discards collection value-type information on serialization (doesn't use static typing for collections)

### ISSUE THREAD

**Issue by henryptung** [FasterXML/jackson-databind#1806] opened 2017-10-24 20:55 UTC
When serializing using `@JsonValue`, serialization does not reflect polymorphic type information for collection types. For example:

```
class A {
    @JsonValue public List<B> getThings() {
        return Collections.singletonList(new B.Impl());
    }
}

class A2 {
    public List<B> getThings() {
        return Collections.singletonList(new B.Impl());
    }
}

@JsonTypeInfo(use = NAME, include = WRAPPER_OBJECT)
@JsonSubTypes(@Type(value = B.Impl.class, name = "impl"))
interface B {
    final class Impl implements B {
        public int value = 1;
    }
}
```

Serializing an instance of `A` yields `[{"value":1}]` instead of `[{"impl":{"value":1}}]`.

By comparison, serializing an instance of `A2` yields `{"things":[{"impl":{"value":1}}]}` as expected.

Observed in Jackson 2.8.6 and 2.9.2.

~~Looking into code a bit, seems to be related to how `JsonValueSerializer` constructs delegate serializers using the original `BeanProperty` of type `A`, not the `@JsonValue`-annotated property `A.things` of type `List<B>`. As such, the serializer provider is unable to locate the appropriate value-type serializer for the `CollectionSerializer`, and the type information is lost.~~

Wrong assumption - see comment below.

**Comment by henryptung** [comment] 2017-10-24 21:50
Update: Nevermind, it's related to [this comment](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/PropertyBuilder.java#L107) and how `JsonValueSerializer` doesn't behave similarly (it checks for static typing and final type, but doesn't check for collection type).

**Comment by cowtowncoder** [comment] 2017-11-01 20:59
Hmmh. Ok yes, this is a tricky case and although I have tackled with it (or similar variant) earlier, I can't recall all the intricasies. A fundamental problem is that `@JsonValue` includes sort of surrogate value, type of which is not assignment compatible with property. But... I am not sure if that should be limit in this particular case, as polymorphism is not needed directly for surrogate, but for types within.

So I hope to look into this and see if it could be improved: I agree that type information should be included here if possible.

**Comment by henryptung** [comment] 2017-11-10 19:03
@cowtowncoder If it helps, I created a hack-patch in my project which makes `JsonValueSerializer` treat a collection/reference type as "use static typing on", which seems to do the trick. Not sure how much that would break, but just food for thought.

**Comment by henryptung** [comment] 2017-12-02 00:40
@cowtowncoder My patch amounted to adding `t.hasContentType()` here (https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/std/JsonValueSerializer.java#L131). Does that kind of patch not suffice in this case?

**Comment by cowtowncoder** [comment] 2017-12-04 05:36
@henryptung You may be right, fix should work. Do you have a link/ref to patch, and esp. unit test(s) to show what is not working before but is after patch?

**Comment by tuxslayer** [comment] 2022-04-20 10:17
Hey guys, is there any progress on the issue? 

It basically makes tuning serialization of collections marked with `@JsonValue` impossible. 

I.e. for the field 
```
    @JsonValue
    @JsonSerialize(contentAs = Action_v2_0.class)
    private List<IAction> value;
```
The `@JsonSerialize` is just ignored due to this issue.
I debugged the code a bit and it looks like the issue is that on presence of JsonValue other annotations are ignored, (probably it has something to do with `POJOPropertiesCollector._addFields` but not sure), though I had to resources to fix that myself.

**Comment by tuxslayer** [comment] 2022-04-20 10:20
Oh.. spot `need-test-case` label. Please let me know if my description is not enough. I'll provide more comprehensive sample

**Comment by cowtowncoder** [comment] 2022-04-20 19:31
I don't think anyone has had time to look into this.

And yes, a unit test would be useful: it's not that I don't understand the issue but sometimes adding a test can slightly simplify processing.

Note on `@JsonSerialize(contentAs=)` is very useful: I can see why type refinement is useful and necessary; but it is definitely possible that information from two annotations may not be properly combined (things get bit hairy for various combinations).
But it should be possible to make that work, if anyone has time -- I am pretty much swamped with all the other issues, but always try to help with PRs at least.

**Comment by cowtowncoder** [comment] 2022-04-29 04:38
@tuxslayer I cannot reproduce the original issue at this point (with 2.13.2) -- will add a passing test and close this issue.
But if your case -- using `@JsonSerialize(contentAs=...)` fails, please file a new issue with reproduction?

**Comment by cowtowncoder** [comment] 2022-04-29 04:45
Cannot reproduce the original reported issue; closing this one: if there are differing issues (like one mentioned above), please file a new issue with reproduction. I wouldn't be surprised if there were further edge cases due to limitations of current implementation.

**Closed by cowtowncoder** 2022-04-29 04:45 UTC
Labels: need-test-case
