### ISSUE TITLE
propertyName and camelCase

### ISSUE THREAD

**Issue by hyundae** [FasterXML/jackson-databind#886] opened 2015-08-04 05:59 UTC
```java
import java.io.Serializable;

import lombok.Data;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

public class LombokJacksonTest {

	public static void main(String[] args) throws Exception {
		String json = "{\"fName\":\"fName\", \"firstName\":\"firstName\"}";
		ObjectMapper om = new ObjectMapper();
		
		Model1 model1 = om.readValue(json, new TypeReference<Model1>(){});
		System.out.println( om.writer().writeValueAsString(model1) );
		
		json = "{\"fname\":\"fname\", \"firstName\":\"firstName\"}";
		
		model1 = om.readValue(json, new TypeReference<Model1>(){});
		System.out.println( om.writer().writeValueAsString(model1) );
		
		
	}
}
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
class Model1 implements Serializable {
	private static final long serialVersionUID = 3230574438971430939L;
	
	private String fName;
    private String firstName;
}
```

Output:

```json
{"firstName":"firstName","fname":null}
{"firstName":"firstName","fname":"fname"}
```

**Comment by islanderman** [comment] 2015-08-04 08:37
I am pretty sure it's not a bug.

Following unit test passed in ``2.6.0``

```java
import static org.junit.Assert.assertEquals;

import java.io.IOException;
import java.io.Serializable;

import org.junit.Test;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class CamelCaseTest {

    @Test
    public void testCamel() throws JsonParseException, JsonMappingException,
            IOException {
        String json = "{\"fName\":\"fName\", \"firstName\":\"firstName\"}";
        ObjectMapper om = new ObjectMapper();

        Model model1 = om.readValue(json, new TypeReference<Model>() {
        });

        assertEquals("{\"fName\":\"fName\",\"firstName\":\"firstName\"}", om.writer().writeValueAsString(model1));

        json = "{\"fname\":\"fname\", \"firstName\":\"firstName\"}";

        model1 = om.readValue(json, new TypeReference<Model>() {
        });
        assertEquals("{\"fName\":null,\"firstName\":\"firstName\"}", om.writer().writeValueAsString(model1));
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    static class Model implements Serializable {
        private static final long serialVersionUID = 3230574438971430939L;

        private String fName;
        private String firstName;

        public Model() {
        }

        public String getfName() {
            return fName;
        }

        public void setfName(String fName) {
            this.fName = fName;
        }

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }
    }
}
```

**Comment by cowtowncoder** [comment] 2015-08-04 16:45
@hyundae It all depends on what kind of getters/setters Lombok generates for this case; and I think your use of `fName` is the problem here. If method is generated as `getFName`, for example, Jackson will (with default settings) infer property name `fname`. This part depends on Lombok's handling.

One thing that may be relevant here is the handling of multiple leading capital letters in getters/setters (like "getURL()", or "getFName()"). By default, Jackson will simply lower-case ALL leading upper-case letters, giving "url" and "fname".
But if you enable `MapperFeature.USE_STD_BEAN_NAMING` (added in Jackson 2.5), it will follow what Java Bean naming convention would do, which is only lower-case a single upper-case leading letter; if multiple found, do nothing.
That would result in properties "URL" and "FName".

But I would probably not use names like `fName`, if they can result in inconsistent handling.

**Comment by cowtowncoder** [comment] 2015-09-08 23:21
I don't think this is a bug, closing.

**Closed by cowtowncoder** 2015-09-08 23:21 UTC
