### ISSUE TITLE
Is JavaType.toCanonical() supposed to return canonical Java names?

### ISSUE THREAD

**Issue by dbarvitsky** [FasterXML/jackson-databind#4081] opened 2023-08-17 14:56 UTC
### Describe your Issue

The `JavaType.toCanonical()` contract says:

> Method that can be used to serialize type into form from which it can be fully deserialized from at a later point (using TypeFactory from mapper package). For simple types this is same as calling `Class.getName()`, but for structured types it may additionally contain type information about contents.
>
> Returns: String representation of the fully resolved type

The actual behavior is per contract (which never claims the return to be any standard type name), however the method name is a bit confusing. 

Per [JLS 6.7. Fully qualified names and canonical names](https://docs.oracle.com/javase/specs/jls/se20/html/jls-6.html#jls-6.7), the canonical names have specific syntax (`foo.bar.TypeX.TypeY`). If you construct a `JavaType` from a nested type:

```java
package foo.bar;
interface TypeX {
  interface TypeY {}
}
```

The `TypeFactory.defaultInstance().constructType(foo.bar.TypeX.TypeY.class).toCanonical()` yields `foo.bar.TypeX$TypeY` rather than canonical name `foo.bar.TypeX.TypeY`. However the `$` is the only difference. With respect to everything else, including type parameters, it does appear to be following the rules of canonical names, as well as producing valid Java type expressions. Which makes `.toCanonical()` very useful in various code and documentation generation applications that use Jackson type introspection.

Questions:
- Is this intended behavior? 
- Is it safe to rely on `$` to be used as nested type separator?
- Should `toCanonical()` return values be treated as informational string only, or is it safe for the caller to assume that it is a valid Java type expression (granted `$` -> `.` replacement of course).

Thank you!

**Comment by cowtowncoder** [comment] 2023-08-19 02:31
Short answer is that `JavaType.toCanonical()` was intended to only be used by `jackson-databind` core functionality and not user code. It is not intended to produce "JDK canonical" Strings; only something necessary to support Jackson's polymorphic deserialization.
Being `public` method it can of course be used by anything...

At this point I don't think I want to rename method for 2.x, although it could be changed for Jackson 3.0 if that is a big problem. I am not sure it is; I'd be open to improvements to Javadocs.
Similarly I think use of `$` instead of `.` for nested classes is something that cannot be safely changed.

**Comment by cowtowncoder** [comment] 2023-08-22 22:51
If anyone wants to do a PR for Javadoc improvements, that'd be great; closing this issue otherwise.

**Closed by cowtowncoder** 2023-08-22 22:51 UTC

**Comment by dbarvitsky** [comment] 2023-08-28 17:33
@cowtowncoder I will try to give it a shot. Thank you!
