### ISSUE TITLE
The `createContextual()` of a `ContextualSerializer` should be called every time before serializing a property.

### ISSUE THREAD

**Issue by Haixing-Hu** [FasterXML/jackson-databind#3683] opened 2022-11-27 09:13 UTC
**Describe the bug**

I wrote a customized serializer which should have different serialization behaviours according to the annotation of the property to be serialized. I use the `ContextualSerializer` to implement my request. 

But I found the framework does not call the `ContextualSerializer.createContextual()` before serializing a property. Instead, it calls the `createContextual()` after first time the serializer is found or created by the `SerializerProvider`, and cached the serializer instance for further use, which will cause some problems.

For example, let's suppose a customized  `ContextualSerializer`, say, `ser`, is used for two different properties `a` and `b` of an object. There is two cases:

- If the property `a` and `b` are primitive types or JDK build-in types. The framework will first construct a serializer for the object, which will find the serializer `ser`, for property `a` and `b`, and will call the `ser.createContextual()` on property `a` and `b` before performing the serialization. After that the framework will serialize the property value of `a` and `b` with the same serializer `ser`. In short, the calling order in this case is: `ser.createContextual(a), ser.createContextual(b), ser.serialize(a), ser.serialize(b)`.
- If the property `a` and `b` are customized type. The framework will firstly construct a serializer for the object, leaving the serializer for property `a` and `b` empty. Next the framework will serialize the property `a`, after finding the serializer `ser` of property `a` from the `SerializerProvider` and calling the `ser.createContextual()` on property `a`; and then serialize the property `b`, after finding the serializer `ser` of property `b` from the `SerializerProvider` and calling the `ser.createContextual()` on property `b`. In short, the calling order in this case is: `ser.createContextual(a), ser.serialize(a), ser.createContextual(b),  ser.serialize(b)`. This seems OK. But if we use the same `ObjectMapper` to serialize the same object again, the framework will not find and initialize the serializer of the properties again. Instead the framework will use the cached serializers. Therefore the second time the calling order is: `ser.serialize(a), ser.serialize(b)`, which means the `ser.createContextual()` will not be called on `a` and `b`. In short, the calling order in this case for the two successive serializations of the same object is: `[first time] ser.createContextual(a), ser.serialize(a), ser.createContextual(b),  ser.serialize(b), [second time] ser.serialize(a), ser.serialize(b)`. Note that the second time when calling `ser.serialize(a)`, the context of the serializer `ser` is still set to the context of property `b`.

**Version information**

- jackson-core: 2.14.0
- jackson-databind: 2.14.0

**To Reproduce**

The following code snippet shows the first case described above. 

```java
  @Retention(RUNTIME)
  @Target({FIELD})
  @Documented
  @interface Text {
    String value();
  }

  static class Foo {
    @Text("name")
    private String name = "unknown";
    @Text("code")
    private String code = "unknown";

    public String getName() {
      return name;
    }

    public void setName(final String name) {
      this.name = name;
    }

    public String getCode() {
      return code;
    }

    public void setCode(final String code) {
      this.code = code;
    }
  }

  static class CustomizedSerializer extends StdSerializer<String> implements
      ContextualSerializer {

    private String text = "unknown";

    public CustomizedSerializer() {
      super(String.class);
    }

    @Override
    public JsonSerializer<?> createContextual(final SerializerProvider prov,
        final BeanProperty property) throws JsonMappingException {
      final Text annotation = property.getAnnotation(Text.class);
      if (annotation != null) {
        this.text = annotation.value();
      } else {
        this.text = "unknown";
      }
      return this;
    }

    @Override
    public void serialize(final String value, final JsonGenerator gen,
        final SerializerProvider provider) throws IOException {
      gen.writeString(text);
    }
  }

  @Test
  public void testJacksonBug_1() throws JsonProcessingException {
    SimpleModule module = new SimpleModule();
    module.addSerializer(String.class, new CustomizedSerializer());
    final Foo obj = new Foo();

    final ObjectMapper jsonMapper = new ObjectMapper();
    jsonMapper.registerModule(module);
    final String s1 = jsonMapper.writeValueAsString(obj);
    System.out.println(s1);    // the output is: {"name":"code","code":"code"}
    assertEquals("{\"name\":\"name\",\"code\":\"code\"}", s1);
  }

```

The following code snippet shows the second case described above. 

```java
  @Retention(RUNTIME)
  @Target({FIELD})
  @Documented
  @interface Text {
    String value();
  }

  static class MyType {
    public String value = "";
  };

  static class Goo {
    @Text("name")
    private MyType name = new MyType();
    @Text("code")
    private MyType code = new MyType();

    public MyType getName() {
      return name;
    }

    public void setName(final MyType name) {
      this.name = name;
    }

    public MyType getCode() {
      return code;
    }

    public void setCode(final MyType code) {
      this.code = code;
    }
  }

  static class MyTypeSerializer extends StdSerializer<MyType> implements
      ContextualSerializer {

    private String text = "unknown";

    public MyTypeSerializer() {
      super(MyType.class);
    }

    @Override
    public JsonSerializer<?> createContextual(final SerializerProvider prov,
        final BeanProperty property) throws JsonMappingException {
      final Text annotation = property.getAnnotation(Text.class);
      if (annotation != null) {
        this.text = annotation.value();
      } else {
        this.text = "unknown";
      }
      return this;
    }

    @Override
    public void serialize(final MyType value, final JsonGenerator gen,
        final SerializerProvider provider) throws IOException {
      gen.writeString(text);
    }
  }

  @Test
  public void testJacksonBug_2() throws JsonProcessingException {
    SimpleModule module = new SimpleModule();
    module.addSerializer(MyType.class, new MyTypeSerializer());
    final Goo obj = new Goo();

    final ObjectMapper jsonMapper = new ObjectMapper();
    jsonMapper.registerModule(module);
    final String s1 = jsonMapper.writeValueAsString(obj);
    System.out.println(s1);   // the output is: {"name":"name","code":"code"}
    assertEquals("{\"name\":\"name\",\"code\":\"code\"}", s1);
    final String s2 = jsonMapper.writeValueAsString(obj);
    System.out.println(s2);   // the output is: {"name":"code","code":"code"}
    assertEquals(s1, s2);
  }
```

**Expected behavior**

In the first code snippet, the output of the `println()` should be 
```
{"name":"name","code":"code"}
```
but was 
```
{"name":"code","code":"code"}
```

In the first code snippet, the output of the `println()` should be 
```
{"name":"name","code":"code"}
{"name":"name","code":"code"}
```
but was 
```
{"name":"name","code":"code"}
{"name":"code","code":"code"}
```

**Additional context**

Another way to solve the problem is to have some way to register a dynamic created serializer, instead of registering a singleton serializer. But the framework always cached the serializers of the same type, and this feature cannot be controlled. Therefore even if an object has two properties of the same type which should be serialized by two different `ContextualSerializer` instances, the framework still uses the serializer of the first property to serialize the second property. 

If we use the `@JsonSerialize(using = MyTypeSerializer.class)` in the second code snippet, i.e., as the follwoing code snippet:
```java

  static class Too {
    @JsonSerialize(using = MyTypeSerializer.class)
    @Text("name")
    private MyType name = new MyType();
    @JsonSerialize(using = MyTypeSerializer.class)
    @Text("code")
    private MyType code = new MyType();

    public MyType getName() {
      return name;
    }

    public void setName(final MyType name) {
      this.name = name;
    }

    public MyType getCode() {
      return code;
    }

    public void setCode(final MyType code) {
      this.code = code;
    }
  }

  @Test
  public void testJacksonBug_3() throws JsonProcessingException {
    final Too obj = new Too();
    final ObjectMapper jsonMapper = new ObjectMapper();
    final String s1 = jsonMapper.writeValueAsString(obj);
    System.out.println(s1);
    assertEquals("{\"name\":\"name\",\"code\":\"code\"}", s1);
    final String s2 = jsonMapper.writeValueAsString(obj);
    System.out.println(s2);
    assertEquals(s1, s2);
  }
```

The output of the above code snippet is exactly as desired. 

Because the `@JsonSerialize` is processed by the `JacksonAnnotationIntrospector` class, and `BasicSerializerFactory.findSerializerFromAnnotation()` will be called and create two different instances of `MyTypeSerializer` for the property `name` and `code`. This is a possible solution to implement my request. But I thinks the behavours of the framework should be consistent for the second and third code snippet.

**Comment by yawkat** [comment] 2022-11-27 10:04
The issue is your `return this;`. `createContextual` is supposed to create a **new** serializer, with the added contextual information. That way, there will be independent serializers for each property, and you will not get the interference between properties that you describe.

**Comment by Haixing-Hu** [comment] 2022-11-27 10:17
> 

> The issue is your `return this;`. `createContextual` is supposed to create a **new** serializer, with the added contextual information. That way, there will be independent serializers for each property, and you will not get the interference between properties that you describe.

Yes, you are right. You saved my day! Thank you very much!

But I still think the design of the framework is problematic. Maybe we should have to way to intercept before and after serializing each property.

**Comment by yawkat** [comment] 2022-11-27 10:21
You can do that, with a custom BeanPropertyWriter, but it's generally not a good pattern, for performance reasons.

**Closed** 2022-11-27 10:39 UTC
Labels: to-evaluate
