### ISSUE TITLE
Exception thrown for incorrectly annotated record changed from `InvalidDefinitionException` to `MismatchedInputException`

### ISSUE THREAD

**Issue by soc** [FasterXML/jackson-databind#3988] opened 2023-06-16 15:20 UTC
**Describe the bug**

The exception thrown for an incorrectly annotated record has changed.

**Version information**
2.15.2

**To Reproduce**

Consider these two examples:

```
public record RecordWithSingleValueValue(@JsonValue String value) {}

public record RecordWithSingleValueCreatorDelegating(String value) {

  @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
  public RecordWithSingleValueCreatorDelegating {}

}

public class JacksonSerializationTest {

  private static final ObjectMapper mapper = new ObjectMapper();

  @Test
  public void recordWithSingleValueValue() throws JsonProcessingException {
    var instance = new RecordWithSingleValueValue("foo");
    var result = mapper.writeValueAsString(instance);
    assertEquals("\"foo\"", result);
    // missing setter
    assertThrows(InvalidDefinitionException.class,
        () -> mapper.readValue(result, RecordWithSingleValue.class));
  }

  @Test
  public void recordWithSingleValueCreatorDelegating() throws JsonProcessingException {
    var instance = new RecordWithSingleValueCreatorDelegating("foo");
    var result = mapper.writeValueAsString(instance);
    assertEquals("{\"value\":\"foo\"}", result);
    // missing setter
    assertThrows(InvalidDefinitionException.class,
        () -> mapper.readValue(result, RecordWithSingleValueCreatorDelegating.class));
  }
}
```

**Expected behavior**
In 2.14.2 `InvalidDefinitionException` was thrown as shown above, with 2.15.3 this changed to `MismatchedInputException`.
From my understanding `InvalidDefinitionException` was perhaps more "correct"?

**Additional context**
I tried to figure out whether this change was intentional or not, but couldn't find anything in the changelog or issues.
I just wanted to let you know of this change – apologies if this was intentional and I missed it.

(I also found some other behavioral changes in 2.15, but I assume they are intentional – things that weren't deserializing before are now deserializing.)

**Comment by yihtserns** [comment] 2023-06-16 15:32
Looking at the javadoc:
- `InvalidDefinitionException`: Something is wrong with the class to deserialize into.
- `MismatchedInputException`: The wrong input has been provided.

The scenario is providing JSON String to a class that expects JSON Object, and providing JSON Object to a class that expects a JSON String.  Isn't that "the wrong input has been provided"?

**Comment by yihtserns** [comment] 2023-06-16 15:33
>...things that weren't deserializing before are now deserializing.

What's the scenarios for those?

**Comment by soc** [comment] 2023-06-16 15:35
>  Isn't that "the wrong input has been provided"?

Good point! Perhaps my confusion comes from things changing for `record`, but not for `class`. :thinking:
(I basically have a small test suite that tests all possible combinations of Jackson annotations.)

**Comment by soc** [comment] 2023-06-16 15:37
> What's the scenarios for those?

```
public record RecordWithSingleValue(String value) {}

public record RecordWithSingleValueCreatorDelegating(String value) {

  @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
  public RecordWithSingleValueCreatorDelegating {}

}
```

now both round-trip, they failed with `InvalidDefinitionException` on 2.14.

**Comment by yihtserns** [comment] 2023-06-16 16:07
I think you need to check your scenario, because when I tried using `2.14.0`:

<table>
<thead>
<tr>
<th>recordWithSingleValueValue</th>
<th>recordWithSingleValueCreatorDelegating</th>
</tr>
</thead>
<tbody>
<tr>
<td>Failed with:
<blockquote>
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Problem with definition of [AnnotedClass com.github.yihtserns.records.jackson.RecordWithSingleValueValue]: Multiple 'as-value' properties defined ([field com.github.yihtserns.records.jackson.RecordWithSingleValueValue#value] vs [method com.github.yihtserns.records.jackson.RecordWithSingleValueValue#value()])
</blockquote>
at:
<pre>
@Test
public void recordWithSingleValueValue() throws JsonProcessingException {
    var instance = new RecordWithSingleValueValue("foo");
    var result = mapper.writeValueAsString(instance); <---- failed here
    ...
}
</pre>
</td>
<td>
<pre>
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, 
Expected :class com.fasterxml.jackson.databind.exc.InvalidDefinitionException
Actual   :class com.fasterxml.jackson.databind.exc.MismatchedInputException
</pre>
</td>
</tr>
</tbody>
</table>

**Comment by yihtserns** [comment] 2023-06-16 16:11
> ```
> public record RecordWithSingleValue(String value) {}
> 
> public record RecordWithSingleValueCreatorProperties(String value) {
>   @JsonCreator(mode = JsonCreator.Mode.PROPERTIES)
>   public RecordWithSingleValueCreatorProperties {}
> }
> ```
> now both round-trip, they failed with InvalidDefinitionException on 2.14.

Sorry I don't understand what that means, you'd have to explain more than that...  😞

**Comment by yihtserns** [comment] 2023-06-16 17:23
<table>
<thead>
<tr>
<th>Version ⬇️</th>
<th>recordWithSingleValueValue</th>
<th>recordWithSingleValueCreatorDelegating</th>
</tr>
</thead>
<tbody>
<tr>
<th>2.14.2</th>
<td>
<pre>
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, 
Expected :class com.fasterxml.jackson.databind.exc.InvalidDefinitionException
Actual   :class com.fasterxml.jackson.databind.exc.MismatchedInputException
</pre>
</td>
<td>
<pre>
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, 
Expected :class com.fasterxml.jackson.databind.exc.InvalidDefinitionException
Actual   :class com.fasterxml.jackson.databind.exc.MismatchedInputException
</pre>
</td>
</tr>
<tr></tr>
<tr>
<th>2.15.3-SNAPSHOT</th>
<td>
Successfully deserializes because of new feature #3654 (+#3724).
</td>
<td>
<pre>
org.opentest4j.AssertionFailedError: Unexpected exception type thrown, 
Expected :class com.fasterxml.jackson.databind.exc.InvalidDefinitionException
Actual   :class com.fasterxml.jackson.databind.exc.MismatchedInputException
</pre>
</td>
</tr>
</tbody>
</table>

**Comment by yihtserns** [comment] 2023-06-16 17:33
> I'm reverting the whole thing, just got another failure about
>> Invalid type definition for type ...Dto: Argument https://github.com/FasterXML/jackson-databind/pull/5 of constructor [constructor for ...Dto (6 args), annotations: [null] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator
>
> for a record that is not annotated with @JsonCreator, and also has no property name annotations for args https://github.com/FasterXML/jackson-databind/issues/1-https://github.com/FasterXML/jackson-databind/pull/4 or https://github.com/FasterXML/jackson-databind/pull/6 either.

Without direct access to your machine, it's basically impossible to know what you're talking about.  Maybe you can create a Github repository with all the (failing) test cases to describe the issue - that's the most effective way for us to be "in-sync" with each other.

**Comment by cowtowncoder** [comment] 2023-06-17 23:30
I would suggest actually addressing a small number -- possibly just one -- fail at a time and not bundling together all cases.

But aside from that, the general idea would be that:

1. Things that are wrong with definition -- regardless of input; that is, occurring during construction/initialization of deserializer -- should results in `InvalidDefinitionException`
2. Things that could work (value/deserializer annotations valid) but do not work for encountered input should result in exceptions like `MismatchedInputException`

Whether change in specific case is intentional, valid, or invalid depends on many things of course. Above is just the general guidance.
We try not to change exception types unless there was an incorrect one before; exceptions thrown are considered part of API definition. One exception to this (no pun intended) is that sometimes we may start using a more specific one (new subtype).

**Comment by soc** [comment] 2023-06-19 10:27
It appears as if Jackson behaves wildly different with and without a Java module-info file, even on 2.14.2.
I believe this should not be the case.

2.14.2 with module-info:
![jackson-2 14 2-with-module-info](https://github.com/FasterXML/jackson-databind/assets/42493/b254a44d-02b5-48ba-ba90-fa66da3c771b)


2.14.2 without module-info:
![jackson-2 14 2-without-module-info](https://github.com/FasterXML/jackson-databind/assets/42493/38bb8b13-61ca-42a9-a021-b2acce2ef80f)


2.15.2 with module-info:
![jackson-2 15 2-without-module-info](https://github.com/FasterXML/jackson-databind/assets/42493/d0e86164-ebbf-4de8-936b-8c3b261792da)
module-info:


2.15.2 without module-info:
![jackson-2 15 2-with-module-info](https://github.com/FasterXML/jackson-databind/assets/42493/575397e9-a1eb-4802-ad4f-e720b310cbce)

I'm not sure it makes sense to look at the behavioral changes between 2.14 and 2.15, if using the Java module system makes the results diverge that much.

Reproduction: https://github.com/soc/jackson-repro

**Comment by soc** [comment] 2023-06-19 10:42
I added the reproduction for

> Invalid type definition for type ...Dto: Argument https://github.com/FasterXML/jackson-databind/pull/5 of constructor [constructor for ...Dto (6 args), annotations: [null] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator

in a second commit in the same repo.

**Comment by yihtserns** [comment] 2023-06-19 12:59
@soc can you also commit a [Maven wrapper](https://maven.apache.org/wrapper/) into your repo, please?  Just want to ensure our environmental settings are close enough:

- Running `mvn test` ignores all the test methods, I had to specifically specify a newer `maven-surefire-plugin` - this is likely because my personal Maven installation uses an older `maven-surefire-plugin` by default.
- When I run `JacksonSerializationTest` directly in Intellij, the result WITH `module-info` is the same as your result for WITHOUT `module-info`:
![image](https://github.com/FasterXML/jackson-databind/assets/3615932/7cfcf8d2-9ead-4d33-a7bc-b2eae4bfec26)

**Comment by yihtserns** [comment] 2023-06-19 13:11
For these test cases in `JacksonSerializationTest`:
- `recordWithSingleValueCreatorProperties`
- `recordWithSingleValue`
- `recordWithSingleValueValue`
- `recordWithSingleValueCreatorDelegating`

...in 2.14.2 they failed with:
> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type \`<...snip>\`: Failed to call \`setAccess()\` on Field '<...snip>' (of class \`<...snip>\`) due to \`java.lang.reflect.InaccessibleObjectException\`, problem: Unable to make field private final java.lang.String <...snip> accessible: module repro does not "opens repro" to module com.fasterxml.jackson.databind

That was a bug that has been fixed by #3352.  Which is why:
- `recordWithSingleValueCreatorProperties`: can now deserialize the valid JSON
- `recordWithSingleValue`: can now deserialize the valid JSON
- `recordWithSingleValueValue`: can now fail with "mismatched input" error for the invalid JSON
- `recordWithSingleValueCreatorDelegating`: can now fail with "mismatched input" error for the invalid JSON

---
As for JacksonSerialization2Test failing with:
> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type \`repro2.RecordWithMultipleValuesAndOnePropertyAccessAnnotationDto\`: Argument \#&#8203;1 of constructor [constructor for \`repro2.RecordWithMultipleValuesAndOnePropertyAccessAnnotationDto\` (2 args), annotations: [null] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator

...that is caused by #3724 not covering the scenario where deserialization uses a Record with a constructor property with `access=READ_ONLY` .

**Comment by soc** [comment] 2023-06-19 13:53
Ok, thanks! Then I'll wait for 2.15.3 and report back!

**Comment by cowtowncoder** [comment] 2023-08-22 22:55
This is too convoluted an issue, discussion, to be of much value (IMO), so I'll close it. Relevant, remaining pieces may be re-filed (with possible ref to this one), with clear explanation of intended correct outcome, and not so much on what has changed -- some changes are fine (fixes), others not: but it's perfectly fine to suggest that specific change is wrong (bug/regression). There is no need to ask "why was this changed" if change seems wrong: but there is clear need to clearly indicate both type of exception and message being reported -- latter likely explains how change came about (new validation, regression).

**Closed by cowtowncoder** 2023-08-22 22:55 UTC
Labels: to-evaluate

**Comment by Mochis** [comment] 2023-09-15 17:28
I have some doubts, is the problem related to constructor con property with access=READ_ONLY resolved in 2.15.3 or 2.16?

> ...that is caused by https://github.com/FasterXML/jackson-databind/pull/3724 not covering the scenario where deserialization uses a Record with a constructor property with access=READ_ONLY .

**Comment by cowtowncoder** [comment] 2023-09-19 04:13
@Mochis Read my note above. If you have remaining problem case that is not covered by an open issue, please file a new, targeted issue for specific problem.

**Comment by Mochis** [comment] 2023-09-19 12:00
Thank you @cowtowncoder. Reported here https://github.com/FasterXML/jackson-databind/issues/4119

**Comment by soc** [comment] 2023-09-28 13:32
Short update: After I reported this issue, I adapted the test to the behavior on 2.15.2.

Now, with the same Jackson version (2.15.2), but updated Java version (to 21) I get similar failures for classes:

```
Failures: 
  JacksonSerializationTest.classWithSingleValueCreatorDelegating:31 Unexpected exception type thrown, expected: <com.fasterxml.jackson.databind.exc.InvalidDefinitionException> but was: <com.fasterxml.jackson.databind.exc.MismatchedInputException>
  JacksonSerializationTest.classWithSingleValueCreatorDelegatingProperty:41 Unexpected exception type thrown, expected: <com.fasterxml.jackson.databind.exc.InvalidDefinitionException> but was: <com.fasterxml.jackson.databind.exc.MismatchedInputException>
  JacksonSerializationTest.classWithSingleValueCreatorPropertiesProperty:61 Expected com.fasterxml.jackson.databind.exc.InvalidDefinitionException to be thrown, but nothing was thrown.
  JacksonSerializationTest.classWithSingleValueGetConstructor:71 Unexpected exception type thrown, expected: <com.fasterxml.jackson.databind.exc.InvalidDefinitionException> but was: <com.fasterxml.jackson.databind.exc.MismatchedInputException>
  JacksonSerializationTest.classWithSingleValueProperty:90 Unexpected exception type thrown, expected: <com.fasterxml.jackson.databind.exc.InvalidDefinitionException> but was: <com.fasterxml.jackson.databind.exc.MismatchedInputException>
```

**Comment by soc** [comment] 2023-11-27 15:59
Just checked with 2.16.0 and Java 21:

Example `JacksonSerializationTest.classWithSingleValueProperty`:

```
  @Test
  public void classWithSingleValueProperty() throws JsonProcessingException {
    var instance = new ClassWithSingleValueProperty("foo");
    var result = mapper.writeValueAsString(instance);
    assertEquals("{\"value\":\"foo\"}", result);
    // missing setter
    assertThrows(InvalidDefinitionException.class,
        () -> mapper.readValue(result, ClassWithSingleValueProperty.class));
  }
```

- Test green when running the test from the IDE.
- Error message when running `mvn` from the CLI:

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `ClassWithSingleValueProperty` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"value":"foo"}"; line: 1, column: 2]
```

If I adjust the example to

```
  @Test
  public void classWithSingleValueProperty() throws JsonProcessingException {
    var instance = new ClassWithSingleValueProperty("foo");
    var result = mapper.writeValueAsString(instance);
    assertEquals("{\"value\":\"foo\"}", result);
    // missing setter
    assertThrows(InvalidDefinitionException.class,
        () -> mapper.readValue("\"foo\"", ClassWithSingleValueProperty.class));
  }
```

- Test green when running the test from the IDE.
- Error message when running `mvn` from the CLI (this is expected):
```
Expected com.fasterxml.jackson.databind.exc.InvalidDefinitionException to be thrown, but nothing was thrown
```

**Comment by JooHyukKim** [comment] 2023-11-30 00:32
> Test green when running the test from the IDE.
> Error message when running mvn from the CLI:

What is version IDE is configured with? @soc 
Also, could you check mvn version? (stdout will have jdk version)

**Comment by cowtowncoder** [comment] 2023-11-30 01:24
This is closed issue, fwtw.
