### ISSUE TITLE
AutoValue Class needs @JsonProperty for all it's abstract methods

### ISSUE THREAD

**Issue by feinstein** [FasterXML/jackson-databind#2344] opened 2019-06-04 22:02 UTC
I am using Jackson version 2.9.8, because some of my libraries depend on it (`Jersey 2.27` and `aws-serverless-java-container-jersey 1.3.1`). I am using Jackson inside Jersey, running locally for testing under Tomcat 9, returning an AutoValue immutable object, constructed with a Builder, as the resutl of a REST GET method, encoded as JSON.

I originally defined my `User` class like this:

```Java

package com.example.autojackson;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.auto.value.AutoValue;

import java.util.UUID;

@AutoValue
@JsonSerialize(as = User.class)
@JsonDeserialize(builder = AutoValue_User.Builder.class)
public abstract class User {
    public abstract UUID id();
    @JsonProperty("first_name") 
    public abstract String firstName();
    @JsonProperty("last_name") 
    public abstract String lastName();
    public abstract String cellphone();
    public abstract String email();
    @JsonProperty("picture_url") 
    public abstract String pictureUrl();    
    @JsonProperty("user_status") 
    public abstract short userStatusCode();
    public abstract float rating();
    public abstract String gender();

    public static Builder builder() {
        return new AutoValue_User.Builder();
    }

    public abstract Builder toBuilder();

    @AutoValue.Builder
    @JsonPOJOBuilder(withPrefix = "set")
    public abstract static class Builder {
        public abstract Builder setId(UUID id);
        @JsonProperty("first_name") 
	public abstract Builder setFirstName(String firstName);
        @JsonProperty("last_name") 
	public abstract Builder setLastName(String lastName);
        public abstract Builder setCellphone(String cellphone);
        public abstract Builder setEmail(String email);
        @JsonProperty("picture_url") 
	public abstract Builder setPictureUrl(String pictureUrl);        
        @JsonProperty("user_status") 
	public abstract Builder setUserStatusCode(short userStatusCode);
        public abstract Builder setRating(float rating);
        public abstract Builder setGender(String gender);
        public abstract User build();
    }
}
```

As you can see, only the properties with names different from the abstract method names were annotated with `@JsonProperty`. According to all the docs I read, this should work, but the JSON returned to the client missed all the properties without the `@JsonProperty` annotation.

If in turn I change my `User` class to this one:

```Java
package com.example.autojackson;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.auto.value.AutoValue;

import java.util.UUID;

@AutoValue
@JsonSerialize(as = User.class)
@JsonDeserialize(builder = AutoValue_User.Builder.class)
public abstract class User {
    @JsonProperty("id") public abstract UUID id();
    @JsonProperty("first_name") public abstract String firstName();
    @JsonProperty("last_name") public abstract String lastName();
    @JsonProperty("cellphone") public abstract String cellphone();
    @JsonProperty("email") public abstract String email();
    @JsonProperty("picture_url") public abstract String pictureUrl();    
    @JsonProperty("user_status") public abstract short userStatusCode();
    @JsonProperty("rating") public abstract float rating();
    @JsonProperty("gender") public abstract String gender();

    public static Builder builder() {
        return new AutoValue_User.Builder();
    }

    public abstract Builder toBuilder();

    @AutoValue.Builder
    @JsonPOJOBuilder(withPrefix = "set")
    public abstract static class Builder {
        @JsonProperty("id") public abstract Builder setId(UUID id);
        @JsonProperty("first_name") public abstract Builder setFirstName(String firstName);
        @JsonProperty("last_name") public abstract Builder setLastName(String lastName);
        @JsonProperty("cellphone") public abstract Builder setCellphone(String cellphone);
        @JsonProperty("email") public abstract Builder setEmail(String email);
        @JsonProperty("picture_url") public abstract Builder setPictureUrl(String pictureUrl);        
        @JsonProperty("user_status") public abstract Builder setUserStatusCode(short userStatusCode);
        @JsonProperty("rating") public abstract Builder setRating(float rating);
        @JsonProperty("gender") public abstract Builder setGender(String gender);
        public abstract User build();
    }
}
```

The JSON returned by the REST endpoint correctly includes all the AutoValue implemented properties of this value class, but it's tedious and error prone to be setting all the `@JsonProperty` annotations.

If you can't reproduce this, for any reasons, please do let me know and I will upload a fully functioning Jersey example.

I could reproduce this by running:

```java
public void testJacksonAutoValue() {
    User user = User.builder()
            .setId(UUID.randomUUID())
            .setFirstName("John")
            .setLastName("Smith")
            .setCellphone("99999")
            .setEmail("jhon@smith.com")
            .setPictureUrl("http://www.test.com")
            .setUserStatusCode((short)  1)
            .setRating((float) 5.0)
            .setGender("m")
            .build();
    ObjectMapper mapper = new ObjectMapper();
    try {
        System.out.println(mapper.writeValueAsString(user));
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

**Comment by cowtowncoder** [comment] 2019-06-04 23:26
Thank you for reporting this.

**Comment by cowtowncoder** [comment] 2020-03-26 02:16
Actually should have initially asked for stand-alone reproduction: what is specifically needed is generated classes that AutoValue provides.

**Comment by feinstein** [comment] 2020-03-26 17:51
I am sorry, I didn't understand, is this a question?

**Comment by cowtowncoder** [comment] 2020-03-27 15:45
@feinstein Yes. Can you please include version that does not require use of AutoValue (for example, classes after AV has generated actual sources to use). I do not use tests that require external frameworks; problem needs to be reproducible with only Jackson components.
Usually it is possible to create a minimal test case, leaving just one or two properties.

**Comment by feinstein** [comment] 2020-03-27 15:52
Ok, I will try to make something by next week.

**Comment by cowtowncoder** [comment] 2020-03-27 15:54
@feinstein Much appreciated.

**Comment by feinstein** [comment] 2020-03-30 00:35
Using the examples above, I created 2 AutoValue classes, one named `UserWorking` and `UserNotWorking`. I can see the difference are the `@JsonProperty` not being auto created in the derived classes.

Here goes their `AutoValue` abstract classes definitions and auto-generated implementations:

## UserWorking
```java
package com.example.vo;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.auto.value.AutoValue;

import java.util.UUID;

@AutoValue
@JsonSerialize(as = UserWorking.class)
@JsonDeserialize(builder = AutoValue_UserWorking.Builder.class)
public abstract class UserWorking {
    @JsonProperty("id") public abstract UUID id();
    @JsonProperty("first_name") public abstract String firstName();
    @JsonProperty("last_name") public abstract String lastName();
    @JsonProperty("cellphone") public abstract String cellphone();
    @JsonProperty("email") public abstract String email();
    @JsonProperty("picture_url") public abstract String pictureUrl();
    @JsonProperty("user_status") public abstract short userStatusCode();
    @JsonProperty("rating") public abstract float rating();
    @JsonProperty("gender") public abstract String gender();

    public static Builder builder() {
        return new AutoValue_UserWorking.Builder();
    }

    public abstract Builder toBuilder();

    @AutoValue.Builder
    @JsonPOJOBuilder(withPrefix = "set")
    public abstract static class Builder {
        @JsonProperty("id") public abstract Builder setId(UUID id);
        @JsonProperty("first_name") public abstract Builder setFirstName(String firstName);
        @JsonProperty("last_name") public abstract Builder setLastName(String lastName);
        @JsonProperty("cellphone") public abstract Builder setCellphone(String cellphone);
        @JsonProperty("email") public abstract Builder setEmail(String email);
        @JsonProperty("picture_url") public abstract Builder setPictureUrl(String pictureUrl);
        @JsonProperty("user_status") public abstract Builder setUserStatusCode(short userStatusCode);
        @JsonProperty("rating") public abstract Builder setRating(float rating);
        @JsonProperty("gender") public abstract Builder setGender(String gender);
        public abstract UserWorking build();
    }
}
```

```java
package com.example.vo;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.UUID;
import javax.annotation.Generated;

@Generated("com.google.auto.value.processor.AutoValueProcessor")
final class AutoValue_UserWorking extends UserWorking {

  private final UUID id;

  private final String firstName;

  private final String lastName;

  private final String cellphone;

  private final String email;

  private final String pictureUrl;

  private final short userStatusCode;

  private final float rating;

  private final String gender;

  private AutoValue_UserWorking(
      UUID id,
      String firstName,
      String lastName,
      String cellphone,
      String email,
      String pictureUrl,
      short userStatusCode,
      float rating,
      String gender) {
    this.id = id;
    this.firstName = firstName;
    this.lastName = lastName;
    this.cellphone = cellphone;
    this.email = email;
    this.pictureUrl = pictureUrl;
    this.userStatusCode = userStatusCode;
    this.rating = rating;
    this.gender = gender;
  }

  @JsonProperty("id")
  @Override
  public UUID id() {
    return id;
  }

  @JsonProperty("first_name")
  @Override
  public String firstName() {
    return firstName;
  }

  @JsonProperty("last_name")
  @Override
  public String lastName() {
    return lastName;
  }

  @JsonProperty("cellphone")
  @Override
  public String cellphone() {
    return cellphone;
  }

  @JsonProperty("email")
  @Override
  public String email() {
    return email;
  }

  @JsonProperty("picture_url")
  @Override
  public String pictureUrl() {
    return pictureUrl;
  }

  @JsonProperty("user_status")
  @Override
  public short userStatusCode() {
    return userStatusCode;
  }

  @JsonProperty("rating")
  @Override
  public float rating() {
    return rating;
  }

  @JsonProperty("gender")
  @Override
  public String gender() {
    return gender;
  }

  @Override
  public String toString() {
    return "UserWorking{"
         + "id=" + id + ", "
         + "firstName=" + firstName + ", "
         + "lastName=" + lastName + ", "
         + "cellphone=" + cellphone + ", "
         + "email=" + email + ", "
         + "pictureUrl=" + pictureUrl + ", "
         + "userStatusCode=" + userStatusCode + ", "
         + "rating=" + rating + ", "
         + "gender=" + gender
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof UserWorking) {
      UserWorking that = (UserWorking) o;
      return this.id.equals(that.id())
          && this.firstName.equals(that.firstName())
          && this.lastName.equals(that.lastName())
          && this.cellphone.equals(that.cellphone())
          && this.email.equals(that.email())
          && this.pictureUrl.equals(that.pictureUrl())
          && this.userStatusCode == that.userStatusCode()
          && Float.floatToIntBits(this.rating) == Float.floatToIntBits(that.rating())
          && this.gender.equals(that.gender());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= id.hashCode();
    h$ *= 1000003;
    h$ ^= firstName.hashCode();
    h$ *= 1000003;
    h$ ^= lastName.hashCode();
    h$ *= 1000003;
    h$ ^= cellphone.hashCode();
    h$ *= 1000003;
    h$ ^= email.hashCode();
    h$ *= 1000003;
    h$ ^= pictureUrl.hashCode();
    h$ *= 1000003;
    h$ ^= userStatusCode;
    h$ *= 1000003;
    h$ ^= Float.floatToIntBits(rating);
    h$ *= 1000003;
    h$ ^= gender.hashCode();
    return h$;
  }

  @Override
  public UserWorking.Builder toBuilder() {
    return new Builder(this);
  }

  static final class Builder extends UserWorking.Builder {
    private UUID id;
    private String firstName;
    private String lastName;
    private String cellphone;
    private String email;
    private String pictureUrl;
    private Short userStatusCode;
    private Float rating;
    private String gender;
    Builder() {
    }
    private Builder(UserWorking source) {
      this.id = source.id();
      this.firstName = source.firstName();
      this.lastName = source.lastName();
      this.cellphone = source.cellphone();
      this.email = source.email();
      this.pictureUrl = source.pictureUrl();
      this.userStatusCode = source.userStatusCode();
      this.rating = source.rating();
      this.gender = source.gender();
    }
    @Override
    public UserWorking.Builder setId(UUID id) {
      if (id == null) {
        throw new NullPointerException("Null id");
      }
      this.id = id;
      return this;
    }
    @Override
    public UserWorking.Builder setFirstName(String firstName) {
      if (firstName == null) {
        throw new NullPointerException("Null firstName");
      }
      this.firstName = firstName;
      return this;
    }
    @Override
    public UserWorking.Builder setLastName(String lastName) {
      if (lastName == null) {
        throw new NullPointerException("Null lastName");
      }
      this.lastName = lastName;
      return this;
    }
    @Override
    public UserWorking.Builder setCellphone(String cellphone) {
      if (cellphone == null) {
        throw new NullPointerException("Null cellphone");
      }
      this.cellphone = cellphone;
      return this;
    }
    @Override
    public UserWorking.Builder setEmail(String email) {
      if (email == null) {
        throw new NullPointerException("Null email");
      }
      this.email = email;
      return this;
    }
    @Override
    public UserWorking.Builder setPictureUrl(String pictureUrl) {
      if (pictureUrl == null) {
        throw new NullPointerException("Null pictureUrl");
      }
      this.pictureUrl = pictureUrl;
      return this;
    }
    @Override
    public UserWorking.Builder setUserStatusCode(short userStatusCode) {
      this.userStatusCode = userStatusCode;
      return this;
    }
    @Override
    public UserWorking.Builder setRating(float rating) {
      this.rating = rating;
      return this;
    }
    @Override
    public UserWorking.Builder setGender(String gender) {
      if (gender == null) {
        throw new NullPointerException("Null gender");
      }
      this.gender = gender;
      return this;
    }
    @Override
    public UserWorking build() {
      String missing = "";
      if (this.id == null) {
        missing += " id";
      }
      if (this.firstName == null) {
        missing += " firstName";
      }
      if (this.lastName == null) {
        missing += " lastName";
      }
      if (this.cellphone == null) {
        missing += " cellphone";
      }
      if (this.email == null) {
        missing += " email";
      }
      if (this.pictureUrl == null) {
        missing += " pictureUrl";
      }
      if (this.userStatusCode == null) {
        missing += " userStatusCode";
      }
      if (this.rating == null) {
        missing += " rating";
      }
      if (this.gender == null) {
        missing += " gender";
      }
      if (!missing.isEmpty()) {
        throw new IllegalStateException("Missing required properties:" + missing);
      }
      return new AutoValue_UserWorking(
          this.id,
          this.firstName,
          this.lastName,
          this.cellphone,
          this.email,
          this.pictureUrl,
          this.userStatusCode,
          this.rating,
          this.gender);
    }
  }

}
```

## UserNotWorking

```java
package com.example.vo;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.auto.value.AutoValue;

import java.util.UUID;

@AutoValue
@JsonSerialize(as = UserNotWorking.class)
@JsonDeserialize(builder = AutoValue_UserNotWorking.Builder.class)
public abstract class UserNotWorking {
    public abstract UUID id();
    @JsonProperty("first_name")
    public abstract String firstName();
    @JsonProperty("last_name")
    public abstract String lastName();
    public abstract String cellphone();
    public abstract String email();
    @JsonProperty("picture_url")
    public abstract String pictureUrl();
    @JsonProperty("user_status")
    public abstract short userStatusCode();
    public abstract float rating();
    public abstract String gender();

    public static Builder builder() {
        return new AutoValue_UserNotWorking.Builder();
    }

    public abstract Builder toBuilder();

    @AutoValue.Builder
    @JsonPOJOBuilder(withPrefix = "set")
    public abstract static class Builder {
        public abstract Builder setId(UUID id);
        @JsonProperty("first_name")
        public abstract Builder setFirstName(String firstName);
        @JsonProperty("last_name")
        public abstract Builder setLastName(String lastName);
        public abstract Builder setCellphone(String cellphone);
        public abstract Builder setEmail(String email);
        @JsonProperty("picture_url")
        public abstract Builder setPictureUrl(String pictureUrl);
        @JsonProperty("user_status")
        public abstract Builder setUserStatusCode(short userStatusCode);
        public abstract Builder setRating(float rating);
        public abstract Builder setGender(String gender);
        public abstract UserNotWorking build();
    }
}
```

```java
package com.example.vo;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.UUID;
import javax.annotation.Generated;

@Generated("com.google.auto.value.processor.AutoValueProcessor")
final class AutoValue_UserNotWorking extends UserNotWorking {

  private final UUID id;

  private final String firstName;

  private final String lastName;

  private final String cellphone;

  private final String email;

  private final String pictureUrl;

  private final short userStatusCode;

  private final float rating;

  private final String gender;

  private AutoValue_UserNotWorking(
      UUID id,
      String firstName,
      String lastName,
      String cellphone,
      String email,
      String pictureUrl,
      short userStatusCode,
      float rating,
      String gender) {
    this.id = id;
    this.firstName = firstName;
    this.lastName = lastName;
    this.cellphone = cellphone;
    this.email = email;
    this.pictureUrl = pictureUrl;
    this.userStatusCode = userStatusCode;
    this.rating = rating;
    this.gender = gender;
  }

  @Override
  public UUID id() {
    return id;
  }

  @JsonProperty("first_name")
  @Override
  public String firstName() {
    return firstName;
  }

  @JsonProperty("last_name")
  @Override
  public String lastName() {
    return lastName;
  }

  @Override
  public String cellphone() {
    return cellphone;
  }

  @Override
  public String email() {
    return email;
  }

  @JsonProperty("picture_url")
  @Override
  public String pictureUrl() {
    return pictureUrl;
  }

  @JsonProperty("user_status")
  @Override
  public short userStatusCode() {
    return userStatusCode;
  }

  @Override
  public float rating() {
    return rating;
  }

  @Override
  public String gender() {
    return gender;
  }

  @Override
  public String toString() {
    return "UserNotWorking{"
         + "id=" + id + ", "
         + "firstName=" + firstName + ", "
         + "lastName=" + lastName + ", "
         + "cellphone=" + cellphone + ", "
         + "email=" + email + ", "
         + "pictureUrl=" + pictureUrl + ", "
         + "userStatusCode=" + userStatusCode + ", "
         + "rating=" + rating + ", "
         + "gender=" + gender
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof UserNotWorking) {
      UserNotWorking that = (UserNotWorking) o;
      return this.id.equals(that.id())
          && this.firstName.equals(that.firstName())
          && this.lastName.equals(that.lastName())
          && this.cellphone.equals(that.cellphone())
          && this.email.equals(that.email())
          && this.pictureUrl.equals(that.pictureUrl())
          && this.userStatusCode == that.userStatusCode()
          && Float.floatToIntBits(this.rating) == Float.floatToIntBits(that.rating())
          && this.gender.equals(that.gender());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h$ = 1;
    h$ *= 1000003;
    h$ ^= id.hashCode();
    h$ *= 1000003;
    h$ ^= firstName.hashCode();
    h$ *= 1000003;
    h$ ^= lastName.hashCode();
    h$ *= 1000003;
    h$ ^= cellphone.hashCode();
    h$ *= 1000003;
    h$ ^= email.hashCode();
    h$ *= 1000003;
    h$ ^= pictureUrl.hashCode();
    h$ *= 1000003;
    h$ ^= userStatusCode;
    h$ *= 1000003;
    h$ ^= Float.floatToIntBits(rating);
    h$ *= 1000003;
    h$ ^= gender.hashCode();
    return h$;
  }

  @Override
  public UserNotWorking.Builder toBuilder() {
    return new Builder(this);
  }

  static final class Builder extends UserNotWorking.Builder {
    private UUID id;
    private String firstName;
    private String lastName;
    private String cellphone;
    private String email;
    private String pictureUrl;
    private Short userStatusCode;
    private Float rating;
    private String gender;
    Builder() {
    }
    private Builder(UserNotWorking source) {
      this.id = source.id();
      this.firstName = source.firstName();
      this.lastName = source.lastName();
      this.cellphone = source.cellphone();
      this.email = source.email();
      this.pictureUrl = source.pictureUrl();
      this.userStatusCode = source.userStatusCode();
      this.rating = source.rating();
      this.gender = source.gender();
    }
    @Override
    public UserNotWorking.Builder setId(UUID id) {
      if (id == null) {
        throw new NullPointerException("Null id");
      }
      this.id = id;
      return this;
    }
    @Override
    public UserNotWorking.Builder setFirstName(String firstName) {
      if (firstName == null) {
        throw new NullPointerException("Null firstName");
      }
      this.firstName = firstName;
      return this;
    }
    @Override
    public UserNotWorking.Builder setLastName(String lastName) {
      if (lastName == null) {
        throw new NullPointerException("Null lastName");
      }
      this.lastName = lastName;
      return this;
    }
    @Override
    public UserNotWorking.Builder setCellphone(String cellphone) {
      if (cellphone == null) {
        throw new NullPointerException("Null cellphone");
      }
      this.cellphone = cellphone;
      return this;
    }
    @Override
    public UserNotWorking.Builder setEmail(String email) {
      if (email == null) {
        throw new NullPointerException("Null email");
      }
      this.email = email;
      return this;
    }
    @Override
    public UserNotWorking.Builder setPictureUrl(String pictureUrl) {
      if (pictureUrl == null) {
        throw new NullPointerException("Null pictureUrl");
      }
      this.pictureUrl = pictureUrl;
      return this;
    }
    @Override
    public UserNotWorking.Builder setUserStatusCode(short userStatusCode) {
      this.userStatusCode = userStatusCode;
      return this;
    }
    @Override
    public UserNotWorking.Builder setRating(float rating) {
      this.rating = rating;
      return this;
    }
    @Override
    public UserNotWorking.Builder setGender(String gender) {
      if (gender == null) {
        throw new NullPointerException("Null gender");
      }
      this.gender = gender;
      return this;
    }
    @Override
    public UserNotWorking build() {
      String missing = "";
      if (this.id == null) {
        missing += " id";
      }
      if (this.firstName == null) {
        missing += " firstName";
      }
      if (this.lastName == null) {
        missing += " lastName";
      }
      if (this.cellphone == null) {
        missing += " cellphone";
      }
      if (this.email == null) {
        missing += " email";
      }
      if (this.pictureUrl == null) {
        missing += " pictureUrl";
      }
      if (this.userStatusCode == null) {
        missing += " userStatusCode";
      }
      if (this.rating == null) {
        missing += " rating";
      }
      if (this.gender == null) {
        missing += " gender";
      }
      if (!missing.isEmpty()) {
        throw new IllegalStateException("Missing required properties:" + missing);
      }
      return new AutoValue_UserNotWorking(
          this.id,
          this.firstName,
          this.lastName,
          this.cellphone,
          this.email,
          this.pictureUrl,
          this.userStatusCode,
          this.rating,
          this.gender);
    }
  }

}
```

**Comment by cowtowncoder** [comment] 2020-03-30 23:53
Oh. I should have read through the description, class definitions, first. The problem is this:

```
    public abstract float rating();
```

Method like this is not Java Beans "getter" method: it is missing prefix `get`. As such, it will also require annotation. Same would be true for setters in case of deserialization.
Since the name of property is same as name of property, you can simplify it slightly:

```
    @JsonProperty // will then just use name of method
    public abstract float rating();
```
but a marker is needed.

Apologies for not realizing this earlier.

At this point I will close this as "works as designed": in theory one could think of a new configuration feature of being able to change "get" and/or "set" prefixes (including possible case of "", i.e. not requiring prefix), but if so, I think it'd make sense to file a separate issue with specific feature idea.

**Closed by cowtowncoder** 2020-03-30 23:53 UTC
Labels: 2.10, need-test-case

**Comment by feinstein** [comment] 2020-03-31 00:36
I see, well, thanks for your time, I filed another issue with a Feature Request.
