### ISSUE TITLE
subclass @JsonViews do not work

### ISSUE THREAD

**Issue by ispringer** [FasterXML/jackson-databind#1146] opened 2016-02-29 15:15 UTC
If my active view is set to FooView.class, a field with view SubFooView.class (where SubFooView is a subclass of FooView) will *not* be included in serialization. Conversely, a field with view SuperFooView.class (where SuperFooView is a superclass of FooView) *will* be included in serialization. This is the opposite of how it should work.

The root cause for this bug is that https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/ser/impl/FilteredBeanPropertyWriter.java, and other classes that implement view filtering, do this:

```
if (activeView == null || _view.isAssignableFrom(activeView))
```

when they should be doing this:

```
if (activeView == null || activeView.isAssignableFrom(_view))
```

Here's a test that demonstrates the bug:

```
package test;

import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import org.testng.annotations.Test;

import static com.google.common.truth.Truth.assertThat;

@Test
public class JacksonTest {

    public void subclassViewsOfActiveViewAreIncluded() {
        ObjectWriter animalViewWriter = new ObjectMapper().writer().withView(Animal.class);
        String json = animalViewWriter.writeValueAsString(new Pojo());
        Map jsonAsMap = new ObjectMapper().readValue(json, Map.class);
        assertThat(jsonAsMap.keySet()).containsExactly("horse", "frog", "unclassified");
    }

    public void superclassViewsOfActiveViewAreExcluded() {
        ObjectWriter mammalViewWriter = new ObjectMapper().writer().withView(Mammal.class);
        String json = mammalViewWriter.writeValueAsString(new Pojo());
        Map jsonAsMap = new ObjectMapper().readValue(json, Map.class);
        assertThat(jsonAsMap.keySet()).containsExactly("horse", "unclassified");
    }

    static class Animal {}

    static class Mammal extends Animal {}

    static class Plant {}

    static class Pojo {
        @JsonView(Mammal.class)
        public boolean horse;

        @JsonView(Animal.class)
        public boolean frog;

        @JsonView(Plant.class)
        public boolean artichoke;

        public boolean unclassified;
    }

}
```

**Comment by cowtowncoder** [comment] 2016-02-29 17:06
I will have to think this through, but my initial thinking is that the behavior is exactly as intended and your expectations are incorrect. The intent for view annotation on a property is to set up a requirement: field marked with, say, `Mammal` would only be included if `View` is a `Mammal` or one of its subtypes like `Horse`. Conversely, if `Horse` is required for a property, it is not enough to be of any `Mammal` or `Animal`: it MUST be a `Horse` (or subtype).

If you can point to documentation (javadoc, article) that suggests different behavior I would be interested in knowing that, as behavior should be well-established at this point.

**Comment by ispringer** [comment] 2016-02-29 17:22
Currently if I have a field annotated with view Mammal, and I do writer.withView(Animal), my Mammal field will not be included, even though Mammal is a subtype of Animal. Yet a field annotated with java.lang.Object would be included, because it's a super-type of Animal. To me that is completely unintuitive and goes against the standard meaning of inheritance and polymorphism. The intuitive expectation for how writer.withView(Animal) would behave is to include all fields that are Animals, including Mammals. Can you give me a use case of where the current reversed behavior would have a real-world application?

**Comment by cowtowncoder** [comment] 2016-02-29 17:34
@ispringer I will argue with reverse logic: I have not heard anyone else complain about order of logic before this, ever (always possible others disagree with it; but I haven't observed it).
It is quite simple really: there are, like you point out, two ways to go about it. I understand that the way your intuition works is different than mine, and that to you this is not the logical way to go about it. I hadn't even thought about the alternative way.

As to real-world usage: you can have different security levels for users; more refined types are used higher access levels. You could start with generally accessible properties (either no view limitation, or basic `User`); then have sub-type of, say, `Employee`, and from thereon specialists. Fields would reflect minimum level of access needed. That seems to be a common usage; security/authorization.

Now, with that, one potential idea is to allow a `MapperFeature` that would reverse logic the way you suggest. It would be a global setting, simple to change, and assuming you are right wrt change being small one, should be easy to implement.
It could be added in 2.8 (it's API addition so needs to go in minor release).

**Comment by ispringer** [comment] 2016-02-29 18:49
Thanks for the example. It was very helpful.

So the value of the @JsonView annotation essentially represents a role of the *viewer*, with inheritance being from that perspective, whereas I was thinking the value represented a facet of the annotated *property*. A real-world example of using views to represent facets of properties is:

EventResponseView - include when serializing event responses
EventResponseAndExportView extends EventResponseView - include when serializing event responses or exports 

Also see my comment on https://github.com/FasterXML/jackson-databind/issues/456 for another use case.

These use cases could also be solved by adding support for multiple values to @JsonView. For example, you could get rid of the inheritance:

EventResponseView - include when serializing event responses
ExportView - include when serializing exports 

Then a field could be annotated with @JsonView({ EventResponseView.class, ExportView.class }) to indicate it should be included in both event responses and exports.

So adding support for multiple values to @JsonView is one option, but it's not ideal, because the way @JsonView inheritance currently works doesn't make sense for this alternate view semantic.

Your idea of adding a mapping feature that flips the inheritance semantics of @JsonView is another option.

But I think it would make the most sense to define a completely new concept of a serialization scenario, where a field annotation would indicate the scenarios in which a  property should be included. Lack of the annotation would mean the field should be serialized in all scenarios, including the default/unspecified scenario. Then when reading or writing, a single scenario could optionally be specified. Something like this:

```
// include in event responses and exports
@JsonProperty(inclusionScenarios = { "eventResponse", "export" })
private String foo;

// include in exports
@JsonProperty(inclusionScenarios = { "export" })
private String foo;
```

When serializing event responses, one would use:

```
writer.withScenario("eventResponse")
```

And when serializing exports, one would use:

```
writer.withScenario("export")
```

Exclusions would also be very useful. For example:

```
// exclude in exports and event responses, but include in all other scenarios
@JsonProperty(exclusionScenarios = { "export", "eventResponse" })
private String foo;

// exclude from REST API responses, but include in all other scenarios
@JsonProperty(exclusionScenarios = { "restApi" })
private String password;
```

**Comment by cowtowncoder** [comment] 2016-03-09 23:25
There are many ways in which expressive power could be improved, but I think JSON View concept such as Jackson implements it is balancing things like performance (single active view means only one simple check), simplicity of usage/implementation with fundamental limitation of the approach (being based on statically defined classes).
So while I am always open to improvements, I suspect that there are better ways to handle more advanced filtering use cases. For example, JSON Filter approach Jackson has can support much more complex rules.

I'll close this issue for now; specific improvement suggestions (from this thread or outside) can be used to file a new more targeted issue, if that makes sense.

**Closed by cowtowncoder** 2016-03-09 23:25 UTC

**Comment by WoodsD37** [comment] 2025-03-21 00:30
if (activeView == null || _view.isAssignableFrom(activeView))

**Comment by WoodsD37** [comment] 2025-03-21 00:36
[Document (41).docx](https://github.com/user-attachments/files/19377548/Document.41.docx)

**Comment by JooHyukKim** [comment] 2025-03-21 01:22
> [Document (41).docx](https://github.com/user-attachments/files/19377548/Document.41.docx)

This is file. Do not post file
