### ISSUE TITLE
jackson convert exception when the string contain slash('\')

### ISSUE THREAD

**Issue by lijunyong** [FasterXML/jackson-databind#3987] opened 2023-06-15 02:52 UTC
```
<dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.11.4</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
     <version>2.11.4</version>
    </dependency>

static {
        jacksonMapper =  JsonMapper.builder().enable(JsonReadFeature.ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER,
                JsonReadFeature.ALLOW_UNESCAPED_CONTROL_CHARS).build();
        jacksonMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        //jacksonMapper.configure(JsonParser.Feature.ALLOW_UNQUOTED_CONTROL_CHARS, true);
        //jacksonMapper.configure(JsonParser.Feature.ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER, true);
 }
```
the json string
```
{
    "sign": "cc20694f0cf4a5db8f9d7c26c97f6a46",
    "appSecretId": "OzLhyKMn",
    "timestamp": "20230615161800",
    "nonce": "24",
    "data": "{\"mobile\":\"19512277459\",\"content\":\"您的验证码是：018998，验证码10分钟内有效，请勿泄露给他人，\\如非本人操作，请忽略此信息\", \"classify\":\"captcha\"}"
}
```
exception
```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('c' (code 99)): was expecting comma to separate Object entries
 at [Source: (String)"{"mobile":"19512277459","content":"您的验证码是：018998，验证码10分钟内有效，请勿泄露给他人，如非本人操作，请忽略此信息\", "classify":"captcha"}"; line: 1, column: 88]
```

**Comment by cowtowncoder** [comment] 2023-06-15 03:10
Ok, would need FULL reproduction: code doesn't show `mapper.readValue()` or similar. I am almost certain there must be something more here, too, since line/column numbers do NOT match input as shown here.

**Comment by cowtowncoder** [comment] 2023-08-22 22:55
Cannot reproduce, closing.

**Closed by cowtowncoder** 2023-08-22 22:55 UTC
Labels: need-test-case
