### ISSUE TITLE
Stream#toList() using DefaultTyping.NON_FINAL fails

### ISSUE THREAD

**Issue by pilak** [FasterXML/jackson-databind#4140] opened 2023-10-03 12:20 UTC
I'm reopening [jpbassinello](https://github.com/jpbassinello) issue https://github.com/FasterXML/jackson-databind/issues/3404 by creating a new one as it seems https://github.com/FasterXML/jackson-databind/commit/0016185419e35dc903d0098689cb00326500f054 does not fix it for `Stream#toList()`

Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'a' as a subtype of java.lang.Object: no such class found

Version information
jackson 2.15.0
jdk 19

To Reproduce
```java
public static void main(String[] args) throws JsonProcessingException {
    var objectMapper = new ObjectMapper()
        .activateDefaultTyping(LaissezFaireSubTypeValidator.instance, ObjectMapper.DefaultTyping.NON_FINAL);

    // works
    var list1 = Stream.of("a", "b", "c").collect(Collectors.toList());
    var json1 = objectMapper.writeValueAsString(list1);
    var deserealized1 = objectMapper.readValue(json1, Object.class);
    System.out.println(deserealized1);

    // fails
    var list2 = Stream.of("a", "b", "c").toList();
    var json2 = objectMapper.writeValueAsString(list2);
    var deserealized2 = objectMapper.readValue(json2, Object.class);
    System.out.println(deserealized2);
  }
```
Expected behavior
It is expected Jackson to deserialize the types correctly.

**Comment by pjfanning** [comment] 2023-10-03 14:29
I reproduced this issue. Something about using `.activateDefaultTyping(LaissezFaireSubTypeValidator.instance, ...` causes this. Using other types of 'default typing' seems to work - there are unit tests.

**Comment by pjfanning** [comment] 2023-10-03 14:30
Stream.toList is not the problem - we have unit tests for Stream.toList.

The issue is with using LaissezFaireSubTypeValidator.

**Comment by pjfanning** [comment] 2023-10-03 14:43
This works: https://github.com/pjfanning/jackson-databind/blob/12898dfc2b5e13e0121bba30fba3d3456f14c52a/src/test-jdk17/java/com/fasterxml/jackson/databind/jdk17/Java17CollectionsTest.java#L15

**Comment by pilak** [comment] 2023-10-03 15:02
> There is [2.15 documentation](https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/2.15.2/index.html) on `LaissezFaireSubTypeValidator` saying...
> 
> ```
>  Only used for backwards-compatibility reasons: users should usually NOT use such a permissive implementation but use allow-list/criteria - based implementation.
> ```
> 
> ... so as @pjfanning mentioned in [#3404 (comment)](https://github.com/FasterXML/jackson-databind/issues/3404#issuecomment-1740711839), something about `LaissezFaireSubTypeValidator` 🤔

I also tried with `objectMapper.getPolymorphicTypeValidator()`...

> This works: https://github.com/pjfanning/jackson-databind/blob/12898dfc2b5e13e0121bba30fba3d3456f14c52a/src/test-jdk17/java/com/fasterxml/jackson/databind/jdk17/Java17CollectionsTest.java#L15

yes but with EVERYTHING the javadoc says that it could be very verbose

**Comment by cowtowncoder** [comment] 2023-10-03 21:41
On `final` or non-final class: this is yet another reason for ideally never serializing Generic Types (like `List`s) as root values: determination of "base type" for polymorphism is typically wrong.

That is: although nominal type should be `List`, for all practical purposes, for root type we do not have access to that type -- and instead `value.getClass()` is used as the base type. Since that type is `final` (whereas `List` is not), `NON_FINAL` criteria won't match. But when reading back as `List`, it is noted that `List` is indeed "NON_FINAL".
So there is typically mismatch between base types on serialization vs deserialization.

In this case, one could force type on serialization, something like:

```java
// Use whatever type you will read as: either List or Object
byte[] json = mapper.writerWithType(List.class)
    .writeValueAsBytes(myList);
// and then read should work
```

although I am not 100% sure if `Object.class` works (`List.class` definitely should).

In addition, yes, SubtypeValidator has to allow polymorphic handling for the type in question.

**Comment by cowtowncoder** [comment] 2023-10-10 04:26
I will actually close this as "wont fix" because it really has to be worked around by user.

My main recommendation is NOT to use polymorphic handling for root values: that is problematic in most cases.

But if you insist, it will be necessary to use `mapper.writerWithType()` as shown.

**Closed** 2023-10-10 21:21 UTC
Labels: 2.16

**Comment by baiyz0825** [comment] 2024-09-25 05:16
> > There is [2.15 documentation](https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/2.15.2/index.html) on  saying...`LaissezFaireSubTypeValidator`
> > ```
> >  Only used for backwards-compatibility reasons: users should usually NOT use such a permissive implementation but use allow-list/criteria - based implementation.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ... so as @pjfanning mentioned in [#3404 (comment)](https://github.com/FasterXML/jackson-databind/issues/3404#issuecomment-1740711839), something about  🤔`LaissezFaireSubTypeValidator`
> 
> I also tried with ...`objectMapper.getPolymorphicTypeValidator()`
> 
> > This works: https://github.com/pjfanning/jackson-databind/blob/12898dfc2b5e13e0121bba30fba3d3456f14c52a/src/test-jdk17/java/com/fasterxml/jackson/databind/jdk17/Java17CollectionsTest.java#L15
> 
> yes but with EVERYTHING the javadoc says that it could be very verbose

i want to known why use EVERYTHING can success run Java17CollectionsTest but use the NON_FINAL isn't work?
