### ISSUE TITLE
Type info not serialized when using @JsonAnyGetter

### ISSUE THREAD

**Issue by Maxouwell** [FasterXML/jackson-databind#901] opened 2015-08-15 08:37 UTC
@JsonAnyGetter state that
>contents of the returned Map are serialized as if they were actual properties of the bean that contains method/field with this annotations

but when the object in the map are annoted with @JsonTypeInfo, the type info is not serialized, although it is on a classic getter.

```Java
public class Test {
	
	public static final ObjectMapper mapper = new ObjectMapper()
			.enable(SerializationFeature.INDENT_OUTPUT);
	
	public static void main(String[] args) throws Exception {
		Index i = new Index(1);
		
		Test1 t1 = new Test1(i, 2);
		Test2 t2 = new Test2(i, 3);
		
		System.out.println(mapper.writeValueAsString(t1));
		System.out.println(mapper.writeValueAsString(t2));
	}

}

@JsonTypeInfo(use=JsonTypeInfo.Id.MINIMAL_CLASS, include=JsonTypeInfo.As.PROPERTY)
public class Index {
	private int x;
	
	public Index(int x) {
		this.x = x;
	}
	
	public int getX() {
		return x;
	}
}

public class Test1 {
	private Index index;
	private int z;
	
	public Test1(Index index, int z) {
		this.index = index;
		this.z = z;
	}
	
	public Index getIndex() {
		return index;
	}
	
	public int getZ() {
		return z;
	}
}

public class Test2 {
	private Index index;
	private int w;
	
	public Test2(Index index, int w) {
		this.index = index;
		this.w = w;
	}
	
	public int getW() {
		return w;
	}
	
	@JsonAnyGetter
	public Map<String, Object> any() {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("index", index);
		return map;
	}
}
```

This output
```
{
  "index" : {
    "@c" : ".Index",
    "x" : 1
  },
  "z" : 2
}
{
  "w" : 3,
  "index" : {
    "x" : 1
  }
}
```
Am I doing something wrong or is this a bug ?

(Jackson 2.5.4)

**Comment by cowtowncoder** [comment] 2015-08-18 04:32
I am not sure this is actually a bug, because nominal type of values for "any" setter is `Object`; and `java.lang.Object` does not have `@JsonTypeInfo` on it.
If type declaration was, instead

    Map<String, Index>

then type information should indeed be included.

**Comment by cowtowncoder** [comment] 2015-12-19 03:18
Closing, assuming this is not a bug per se.

**Closed by cowtowncoder** 2015-12-19 03:18 UTC
