### ISSUE TITLE
Deserialize list of array failed with enableDefaultTyping

### ISSUE THREAD

**Issue by quaff** [FasterXML/jackson-databind#2095] opened 2018-07-23 03:26 UTC
I use the same ObjectMapper instance to serialize and deserialize `List<String[]>`, deserialization failed with all of DefaultTyping's, and same as `List<Integer[]>`, tested with the latest version 2.9.6.
```
ObjectMapper objectMapper = new ObjectMapper();
objectMapper = objectMapper.enableDefaultTyping(ObjectMapper.DefaultTyping.JAVA_LANG_OBJECT,
			JsonTypeInfo.As.PROPERTY);
List<String[]> list = new ArrayList<>();
list.add(new String[] { "test" });
String s = objectMapper.writeValueAsString(list); // [["[Ljava.lang.String;",["test"]]]
List<String[]> list2 = objectMapper.readValue(s, new TypeReference<List<String[]>>() {
});
System.out.println(Arrays.equals(list.get(0), list2.get(0)));
```
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (String)"[["[Ljava.lang.String;",["test"]]]"; line: 1, column: 25] (through reference chain: java.util.ArrayList[0]->java.lang.Object[][1])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1138)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1092)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:569)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:157)
	at com.fasterxml.jackson.databind.deser.std.StringArrayDeserializer.deserialize(StringArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
```

**Comment by cowtowncoder** [comment] 2018-07-26 00:02
I think the problem is Java Type Erasure with root values: you are serializing something only seen as `List<?>` (due type erasure), and type information is included for elements as they are nominally of type `Object (type information checks always use static type, not runtime type).
But when reading back you are instructing type to be `List<String>` , and thereby entries are not expected to have type information.

In general I would strongly recommend against using generic types like `List<X>` as root values; and instead use a POJO as wrapper. This avoid most if not all type erasure issues.

If you do want combination to work without changes, however, you will need to force type on serialization. Something like

    objectMapper.writerFor(new TypeReference<List<String>>() { })
        .writeValueAsString(list);

or create a non-generic List type:

    public class StringList extends ArrayList<String> { }

and use that instead of generic version. This will also work around  type erasure.

**Comment by quaff** [comment] 2018-07-26 01:41
Thanks for explain, It's great if jackson can keep compatibility with deserialization, I'm trying to replace jdk serialization with jackson, so I cannot write special code for certain condition. I'm not aware the json result is `[["[Ljava.lang.String;",["test"]]]` or `[["test"]]`, I wish it can be deserialized with `java.lang.reflect.Type`

```
public class Main {

	public static void main(String[] args) throws Exception {
		ObjectMapper objectMapper = new ObjectMapper();
		objectMapper = objectMapper.enableDefaultTyping(ObjectMapper.DefaultTyping.JAVA_LANG_OBJECT,
				JsonTypeInfo.As.PROPERTY);
		List<String[]> list = Collections.singletonList(new String[] { "test" });
		String json = objectMapper.writeValueAsString(list);
		System.out.println(json);
		Type type = Main.class.getMethod("testMethod", List.class).getGenericParameterTypes()[0]; // List<String[]>
		objectMapper.readValue(json, objectMapper.getTypeFactory().constructType(type));
	}

	public static void testMethod(List<String[]> list) {

	}

}

```

**Comment by cowtowncoder** [comment] 2018-07-26 21:53
@quaff Your problem is that type on write (serialization) is different from read (deserialization). You need to make these match somehow. One way would be to force nominal type of `java.lang.Object`. In this case you could also consider reading `List<Object>`, not `List<String>` -- then declared/nominal types would match.

Otherwise this will not work. It is a limitation due to Java type erasure and Jackson can not do much about it.

**Comment by quaff** [comment] 2018-07-27 01:12
Replace `List<String[]>` with `List<Object[]>` doesn't works.
```
objectMapper.readValue("[[\"[Ljava.lang.String;\",[\"test\"]]]", new TypeReference<List<Object[]>>() {});
```
```
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'test' as a subtype of [simple type, class java.lang.Object]: no such class found
 at [Source: (String)"[["[Ljava.lang.String;",["test"]]]"; line: 1, column: 32] (through reference chain: java.util.ArrayList[0]->java.lang.Object[][1])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1628)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1186)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:53)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:44)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:191)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:712)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
```

**Comment by cowtowncoder** [comment] 2018-07-27 05:57
@quaff Ok that is odd. Actually the odd part is the type id: `String` values should never have type as Strings are one of 4 "natural" types (along with Boolean, Long and Double). So it is serializer that should not add this type information... and if so, deserialization should work (exception indicates it is surprised to see an array).

So I think there is a problem in handling.

However: another way to work around this issue would be to wrap typed value in a wrapper like:

```java
public class Wrapper {
     // either use default typing, or add @JsonTypeInfo on property
     public Object value;
}
```

This should work better as it would force use of `java.lang.Object` as the base type.

**Comment by quaff** [comment] 2018-07-27 06:58
@cowtowncoder I agree it's serializer's problem, It shouldn't add type info here, then deserializer will works.

**Comment by quaff** [comment] 2018-07-27 07:05
It also works if I replace `List<String[]>` with `List<Object>` not `List<Object[]>`

**Comment by cowtowncoder** [comment] 2018-11-20 06:37
Actually the flaw here is call for deserialization: it must use same type information as serialization, to determine proper base type. Specifically, it should NOT try to pass type as `List<String[]>` since that is not type serializer has access to: due to Java Type Erasure, all it knows is type is `List<?>`.

So: either writeValue() call has to also pass more specific type information (via `mapper.writerFor(new TypeReference<....>`) or `readValue()` should be given less accurate one.

And note that the reason your change also works is that as per configuration, ONLY nominal type of `Object` will get type information added; `Object[]` is not `Object` (nor is `String[]`).
There are other `DefaultTyping` options (like `OBJECT_AND_NON_CONCRETE` and `NON_FINAL`) that could work better as well.

At any rate functionality works as I would expect so I will close the issue.

**Closed by cowtowncoder** 2018-11-20 06:37 UTC
Labels: 2.9, ACTIVE
