### ISSUE TITLE
`SNAKE_CASE` doesn't work when using Lombok's `@AllArgsConstructor`

### ISSUE THREAD

**Issue by izeye** [FasterXML/jackson-databind#1197] opened 2016-04-14 13:32 UTC
`SNAKE_CASE` doesn't work when using Lombok's `@AllArgsConstructor` in 1.7.3 but it (`CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES`) works regardless of using `@AllArgsConstructor` in 1.6.5.

This is a sample test to show the problem:

```
public class ObjectMapperLombokAllArgsConstructorTests {

	@Test
	public void test() throws JsonProcessingException {
		LombokAllArgsConstructorDomain lombokDomain = new LombokAllArgsConstructorDomain();
		lombokDomain.setSomeProperty("test");
		String lombokJson = new ObjectMapper()
				.setPropertyNamingStrategy(
						PropertyNamingStrategy.SNAKE_CASE)
				.writeValueAsString(lombokDomain);
		System.out.println(lombokJson);

		ManualAllArgsConstructorDomain manualDomain = new ManualAllArgsConstructorDomain();
		manualDomain.setSomeProperty("test");
		String manualJson = new ObjectMapper()
				.setPropertyNamingStrategy(
						PropertyNamingStrategy.SNAKE_CASE)
				.writeValueAsString(manualDomain);
		System.out.println(manualJson);
		
		String workaroundAppliedLombokJson = new ObjectMapper()
				.enable(MapperFeature.ALLOW_EXPLICIT_PROPERTY_RENAMING)
				.setPropertyNamingStrategy(
						PropertyNamingStrategy.SNAKE_CASE)
				.writeValueAsString(lombokDomain);
		System.out.println(workaroundAppliedLombokJson);
	}

	@Data
	@NoArgsConstructor
	@AllArgsConstructor
	static class LombokAllArgsConstructorDomain {

		private String someProperty;

	}

	@Data
	@NoArgsConstructor
	static class ManualAllArgsConstructorDomain {

		private String someProperty;

		public ManualAllArgsConstructorDomain(String someProperty) {
			this.someProperty = someProperty;
		}

	}
	
}
```

You can also find it in the following location to test immediately: https://github.com/izeye/samples-java-branches/blob/master/src/test/java/learningtest/com/fasterxml/jackson/databind/ObjectMapperLombokAllArgsConstructorTests.java

This was originally reported at: https://github.com/spring-projects/spring-boot/issues/5687

**Comment by cowtowncoder** [comment] 2016-04-14 15:48
Since Jackson does not support `@NoArgsConstructor`, it sounds like one of two things:

1. Handling added by Springs Boot implies that these are explicit names, and explicit names (like via `@JsonProperty`) are never modified by naming convention -- intent being that user decided to override names
2. This is related to problem wrt `@CostructorProperties` which is directly supported by Jackson 2.7, and is considered explicit -- whether it should or not is an open issue; as well as what to do about it.

If it's (1), this could be changed by SB I think, to expose names as "implicit" names, instead of "explicit" (via `AnnotationIntrospector`); this is how regular field/getter names are exposed, and they will get renamed.

**Comment by wilkinsona** [comment] 2016-04-14 18:20
`NoArgsConstructor` is from Lombok, not Spring Boot. The tests above illustrate the problem without Spring Boot being involved. It looks like Jackson's interpretation of the Lombok-generated bytecode has changed between 2.6.5 (where it works as expected) and 2.7.3 (where it does not).

**Comment by cowtowncoder** [comment] 2016-04-14 20:09
@wilkinsona Ok. Still, Jackson does not use `@NoArgsConstructor` or `@AllArgsConstructor`, so handling of that must be somewhere else. Bytecode handling has not changed as far as I now. I do not know how that annotation is expected to work, or what effect it is to have.

What has changed slightly is that `@ConstructorProperties` are directly determined, and they are taken to mean explicit annotation. So if generated classes have these declarations, that could be the difference.
Perhaps two Lombok annotations are used to generate `@ConstructorProperties` under the hood.

**Comment by izeye** [comment] 2016-04-15 06:03
@cowtowncoder Thanks for the feedback. As you said, Lombok's `@AllArgsConstructor` is using `@ConstructorProperties`: https://projectlombok.org/features/Constructor.html

I can suppress it by using `suppressConstructorProperties` but the parameter is not recommended to use:

> To suppress the generation of the @ConstructorProperties annotation, add a parameter to your annotation: @AllArgsConstructor(suppressConstructorProperties=true). However, as java 1.5, which has already been end-of-lifed, fades into obscurity, this parameter will eventually be removed. It has also been marked deprecated for this reason.

May I ask the background of using `@ConstructorProperties` when rendering JSON?

**Comment by cowtowncoder** [comment] 2016-04-15 15:39
@izeye `@CreatorProperties` is one way to define names for constructor arguments, similar to `@JsonCreator`, and has the benefit of not requiring extra module (Paranamer), and is part of JDK (as of Java 7). So users requested support.

Originally support was added via JDK7 module (as core Jackson only depended on Java 6):

https://github.com/FasterXML/jackson-datatype-jdk7

but since Jackson 2.7 raised baseline to Java7, it could be merged directly in, with its current behavior. Behavior is similar to combination of `@JsonCreator` with `@JsonProperty`.

Now: I can see why different behavior would make sense, if and when a framework like Lombok adds annotations, and intent is to further modify naming.

**Comment by cowtowncoder** [comment] 2016-04-15 15:43
@izeye One other thing -- aside from allowing configurability for behavior (not 100% sure what is the best way), one thing that could allow changing this would be sub-classing of `JacksonAnnotationIntrospector`, as it is responsible for detection of `@CreatorProperties`.

Actually what I could do as a stop-gap would be to add a `boolean` setting in `JacksonAnnotationIntrospector`, for 2.7.4. While as a general rule I do make API changes (including additions) in patch releases, since this may be widely occurring issue, I would be open to do adding such an option for frameworks to use. And for 2.8 we could figure out a cleaner solution.

**Comment by izeye** [comment] 2016-04-16 00:13
@cowtowncoder Thanks for the details. So to have the previous behavior (2.6.5) I have to set the flag explicitly in 2.7.4, right?

**Comment by cowtowncoder** [comment] 2016-04-18 05:08
@izeye yes, if such a flag was to be added; one does not yet exist. Behavior with 2.6 should have been identical if jdk7 module was used, but I assume this was not the case.

**Comment by izeye** [comment] 2016-04-18 06:05
@cowtowncoder Thanks for the answer.

@wilkinsona If the flag is added in 2.7.4, will Spring Boot use the flag to keep the previous behaviour (in 2.6.5) by default?

**Comment by wilkinsona** [comment] 2016-04-18 08:34
@izeye We'd have to think about it as there are to competing goals:

1. Align with Jackson's defaults
2. Preserve behavior between Spring Boot 1.3 and 1.4

Ideally, Jackson would not have made a breaking change between 2.6 and 2.7 and we'd then be able to satisfy both goals.

**Comment by izeye** [comment] 2016-04-18 09:27
@wilkinsona Okay, I'd better stay with 2.6.5 for the time being.

**Comment by cowtowncoder** [comment] 2016-04-19 00:20
@wilkinsona From my perspective, Jackson did not change behavior, but this was based on assumption that anyone who uses `@CreatorProperties` would be using jdk7 module.
Looks like this is not universally true.
Maybe better phrasing is that this was unintentional change: there was no intent to change observed or expected behavior.

It is also worth noting that the whole problem seems to be due to 2 distinct styles of usage:

1. Developers explicitly adding `@CreatorProperties` in POJOs, presumably to specify names (and implying equivalence of `@JsonCreator`, that is, to use marked constructor as Creator)
2. Framework (like Lombok) adding annotations as standard practice as metadata that may or may not be useful for various uses, but without explicit intent wrt Jackson usage.

**Comment by cowtowncoder** [comment] 2016-04-20 06:23
After thinking this through, and consider #1122, I changed my mind on this having to be config option.
I think change to implicit names is reasonable default and should not have significant risk of breakage.
If more configurability is needed we can add a `MapperFeature` for 2.8.

**Comment by cowtowncoder** [comment] 2016-04-20 06:24
One final note: I can't easily test this with Lombok, so I can not verify that this fixes specific problem (there are other tests to confirm changed behavior, like one for #1122, just not Lombok usage).
If anyone can double-check with 2.7.4-SNAPSHOT that'd be great.

**Closed by cowtowncoder** 2016-04-20 06:24 UTC

**Comment by izeye** [comment] 2016-04-20 07:52
@cowtowncoder I confirmed it works again with 2.7.4-SNAPSHOT: https://github.com/izeye/samples-java-branches/blob/master/src/test/java/learningtest/com/fasterxml/jackson/databind/lombok/ObjectMapperLombokAllArgsConstructorTests.java

Thanks 👍

**Comment by Shredder121** [comment] 2016-04-20 08:31
I also confirmed that it works, since I was one of the people who pushed for `@ConstructorProperties` support.
Sorry for the hassle :sweat_smile:
Keep up the good work.

**Comment by cowtowncoder** [comment] 2016-04-20 17:51
@Shredder121 thank you for verifying this -- very glad to hear this still works wrt original goals. My main concern would specifically be having 2 non-overlapping goals, and difficulty in making both work well enough.

@izeye thank you for verifying it.

**Comment by Shredder121** [comment] 2016-04-20 17:55
If you need any testing, feel free to ping me.
It was merely chance that I stumbled upon this.
