### ISSUE TITLE
Deserialization: fail-on-unknown-properties: false  is not working getting Unrecognized field "xxyyzz"

### ISSUE THREAD

**Issue by anand188** [FasterXML/jackson-databind#4655] opened 2024-08-05 13:01 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

  jackson:     deserialization:       fail-on-unknown-properties: false  is not working getting Unrecognized field "xxyyzz"

### Version Information

2.17.1

### Reproduction

```java
  @Bean
    public ObjectMapper objectMapper() {
        ObjectMapper mapper = new ObjectMapper();
        mapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        mapper.setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.NONE);
        mapper.setVisibility(PropertyAccessor.GETTER, JsonAutoDetect.Visibility.PUBLIC_ONLY);
        mapper.setVisibility(PropertyAccessor.IS_GETTER, JsonAutoDetect.Visibility.PUBLIC_ONLY);
        mapper.setVisibility(PropertyAccessor.SETTER, JsonAutoDetect.Visibility.PUBLIC_ONLY);
        mapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false);
        mapper.configure(SerializationFeature.FAIL_ON_UNWRAPPED_TYPE_IDENTIFIERS, false);
        mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        mapper.configure(SerializationFeature.WRITE_DATES_WITH_ZONE_ID, true);
        mapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX"));
        mapper.configure(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, false);
       
        return mapper;
}
``` 
  jackson:     deserialization:       fail-on-unknown-properties: false  is not working getting Unrecognized field "xxyyzz"

### Expected behavior

Should not get any exception , continue to work

**Comment by cowtowncoder** [comment] 2024-08-12 00:22
Full reproduction needed: specifically, what kind of input is used; what POJO (class) is used and so on.
Without that it is impossible to say what happens.

**Comment by anand188** [comment] 2024-08-13 16:04
@cowtowncoder For example pojo has name , data but no id and immutable properties when API is invoked with id and immutable 

Here always Deserialization Feature is not considered and executes else block expected to skip and continue 
![image](https://github.com/user-attachments/assets/d151f138-51ab-4a17-8c4f-8dafa8d5a19e)

**Comment by cowtowncoder** [comment] 2024-08-14 00:04
@anand188 Huh? I don't understand what you saying here.

And it definitely isn't what I asked:

   Full reproduction needed: ...

**Comment by anand188** [comment] 2024-08-21 10:35
@cowtowncoder  question is configuration set on mapper will always propagated in Deserialization Context , i dont think so ,i am working on huge project which cannot be shared . Do you have test which can show this working ?

**Comment by JooHyukKim** [comment] 2024-08-21 11:45
@anand188 The configuration in question has been working for a long time. 

U are not asked to provide ur project's source code. But U need to provide at least full reproduction(or preferrably) simplified input, output, version information and test showing that what u r saying is happening. Otherwise can't properly get help

**Comment by cowtowncoder** [comment] 2024-08-21 18:09
I don't understand at all what is being asked here. Leaving open for a bit for clarification, but will close unless there's pertinent new information.

**Comment by yihtserns** [comment] 2024-08-22 12:30
@anand188 I highly recommend that you get a senior developer in your team to go through this thread and help you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this issue.

**Comment by cowtowncoder** [comment] 2024-08-22 16:30
If this is due to Spring Boot configuration, issue belongs to SB trackers.
Without Jackson-only reproduction we cannot really help here.
(that is, no point in creating reproduction that relies on SB -- we won't be using that).

Will close.

**Comment by anand188** [comment] 2024-08-23 11:43
@cowtowncoder  just want to make sure "@jsonignoreproperties"  if this annotation is not  used does it override any the configuration set in Objectmapper ?

**Comment by cowtowncoder** [comment] 2024-08-23 14:09
@anand188 I don't understand the question.

**Comment by golimpio** [comment] 2024-11-19 10:50
I've seen this issue, but it was caused by a race condition involving a shared ObjectMapper used by multiple threads, with its configuration being changed by another thread.

**Comment by cowtowncoder** [comment] 2024-11-19 23:15
No reproduction, closing.

**Closed by cowtowncoder** 2024-11-19 23:15 UTC
Labels: need-test-case

**Comment by hohwille** [comment] 2025-11-11 08:53
This bug still exists and can be reproduced with a single-threaded processing.
Just chain 2 records into each other.
Workaround is to add `@JsonIgnoreProperties(ignoreUnknown = true)` to each `record`.
Actually according to Jackson documentation `disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)` should be sufficient and no extra annotation `@JsonIgnoreProperties(ignoreUnknown = true)` would be required.

**Comment by pjfanning** [comment] 2025-11-11 09:01
> This bug still exists and can be reproduced with a single-threaded processing. Just chain 2 records into each other. Workaround is to add `@JsonIgnoreProperties(ignoreUnknown = true)` to each `record`. Actually according to Jackson documentation `disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)` should be sufficient and no extra annotation `@JsonIgnoreProperties(ignoreUnknown = true)` would be required.

@hohwille can you raise a new issue with details about the jackson version that you are using. Also, a full POC would be appreciated.
Jackson support for Java records has its own code so stuff that works with POJOs may not necessarily work with records so maybe that is a point to raise in the new issue is if what you are seeing is specific to records.

**Comment by snow-zen** [comment] 2026-02-10 15:28
> > This bug still exists and can be reproduced with a single-threaded processing. Just chain 2 records into each other. Workaround is to add `@JsonIgnoreProperties(ignoreUnknown = true)` to each `record`. Actually according to Jackson documentation `disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)` should be sufficient and no extra annotation `@JsonIgnoreProperties(ignoreUnknown = true)` would be required.
> 
> [@hohwille](https://github.com/hohwille) can you raise a new issue with details about the jackson version that you are using. Also, a full POC would be appreciated. Jackson support for Java records has its own code so stuff that works with POJOs may not necessarily work with records so maybe that is a point to raise in the new issue is if what you are seeing is specific to records.

I'm experiencing a similar issue. My project depends on `spring-boot-starter-jackson:4.0.0`, which transitively pulls in both `com.fasterxml.jackson.core:jackson-databind:2.20.1` and `tools.jackson.core:jackson-databind:3.0.2`. When I use `com.fasterxml.jackson.databind.ObjectMapper` for deserialization, it throws an exception. However, deserialization works correctly when using `tools.jackson.databind.json.JsonMapper`.

Here is my data class:
```java
@Getter
@Setter
@EqualsAndHashCode
@JsonIgnoreProperties(ignoreUnknown = true)
public class ImageAssert {

    private List<Item> items = new ArrayList<>();

    public ImageAssert add(Item item) {
        items.add(item);
        return this;
    }

    public record Item(@JsonProperty("src") String src) {
    }
}
```
And here is a simple unit test that demonstrates the problem:
```java
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.test.ImageAssert;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.json.JsonMapper;

public class ObjectMapperTest {

    @Test
    void test1() throws JsonProcessingException {
        String jsonStr = "{\"items\": [{\"src\": \"https://test.com/1.jpg\", \"width\": 1800, \"height\": 2545}]}";
        ObjectMapper objectMapper = new ObjectMapper();
        ImageAssert imageAssert = objectMapper.readValue(jsonStr, ImageAssert.class);
        Assertions.assertNotNull(imageAssert);
    }

    @Test
    void test2() throws JsonProcessingException {
        String jsonStr = "{\"items\": [{\"src\": \"https://test.com/1.jpg\", \"width\": 1800, \"height\": 2545}]}";
        JsonMapper jsonMapper = new JsonMapper();
        ImageAssert imageAssert = jsonMapper.readValue(jsonStr, ImageAssert.class);
        Assertions.assertNotNull(imageAssert);
    }
}
```
When running test `test1`, the following exception is thrown:
```text
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "width" (class com.test.ImageAssert$Item), not marked as ignorable (one known property: "src"])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 59] (through reference chain: com.test.ImageAssert["items"]->java.util.ArrayList[0]->com.test.ImageAssert$Item["width"])

	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1208)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2380)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1823)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1801)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:271)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:466)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1499)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:340)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeNoNullChecks(CollectionDeserializer.java:501)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:358)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:302)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:169)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:5038)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3954)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3922)
	at com.test.ObjectMapperTest.test1(ObjectMapperTest.java:19)
```
Test `test2` passes without issues.

**Comment by cowtowncoder** [comment] 2026-02-10 22:10
@snow-zen This issue is closed. If you have on-going problem(s), please file a new issue with version info and reproduction.
(note on reproduction: these need to be stand-alone and specifically not rely on Lombok or other 3rd party deps -- may delombokify value classes).
