### ISSUE TITLE
ClassCastException when try to serialize a list of java Records

### ISSUE THREAD

**Issue by SimoneGiusso** [FasterXML/jackson-databind#4028] opened 2023-07-11 09:39 UTC
**Describe the bug**
An exception is thrown when trying to serialize an object containing a list of java records:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: java.lang.ClassCastException@2971bebd (through reference chain: java.util.ArrayList[10]->com.edgelab.me.ClassWrappingAListOfJavaRecords["listOfJavaRecords"]->java.util.ArrayList[0]->java.util.LinkedHashMap["doubleField"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:782)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContentsUsing(IndexedListSerializer.java:142)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:88)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.datatype.hibernate5.PersistentCollectionSerializer.serialize(PersistentCollectionSerializer.java:244)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:657)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeTypedContents(IndexedListSerializer.java:181)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:92)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1518)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1219)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1086)
```

**Version information**
2.13.3

**To Reproduce**
```java
public class ClassWrappingAListOfJavaRecords implements Serializable {

    @Id
    private Integer id;

    @Type(type = "jsonb")
    private MyObject surface;

    @Type(type = "jsonb")
    private List<Point> listOfJavaRecords;

}
```

```java
public record Dividend(LocalDateTime date, double doubleField) {

}
```

call `ObjectWriter#writeValueAsString`.

**Comment by yawkat** [comment] 2023-07-11 13:16
can you please give the full stack trace and full reproducer code

**Comment by cowtowncoder** [comment] 2023-07-11 21:06
Looks like this is related to Hibernate module as well, likely needs moving.

**Comment by cowtowncoder** [comment] 2023-11-04 04:14
Without reproduction not much we can do, closing.

**Closed by cowtowncoder** 2023-11-04 04:14 UTC
Labels: need-test-case
