### ISSUE TITLE
Adding multiple deserializers for the same target type ignores the ones previously added.

### ISSUE THREAD

**Issue by ecausarano** [FasterXML/jackson-databind#3089] opened 2021-03-26 13:37 UTC
I'm trying to configure an object mapper to work with AWS Dynamo AttributeValues. These `are` holder types to construct the Map<String, AttributeValue> DTO used in the AWS API.

By trial & error I reached the following configuration, but I have these problems

- It only works if I define one serdes pair of all the possible items the AttributeValue can take. Adding a second will cause IAEs as only the last one defined will be used, despite having the wrong IN type. 
- When deserialising back from the map, it just doesn't pick-up the correct deserializer to unpack the holder and just leaves the field null.

I'm probably not configuring the module correctly, can anyone explain and document the correct usage?

See the following:

```
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.deser.std.StdDelegatingDeserializer;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer;
import com.fasterxml.jackson.databind.type.MapLikeType;
import com.fasterxml.jackson.databind.util.StdConverter;
import lombok.*;

import java.util.HashMap;
import java.util.Map;

class Scratch {
    public static void main(String[] args) {

        SimpleModule module = new SimpleModule();
        module.addDeserializer(Holder.class, new StdDelegatingDeserializer<>(new StdConverter<String, Holder>() {
            @Override
            public Holder convert(String value) {
                return Holder.builder().aString(value).build();
            }
        })).addSerializer(Holder.class, new StdDelegatingSerializer(new StdConverter<Holder, String>() {
            @Override
            public String convert(Holder value) {
                return value.getAString();
            }
        })).addDeserializer(Holder.class, new StdDelegatingDeserializer<>(new StdConverter<Integer, Holder>() {
            @Override
            public Holder convert(Integer value) {
                return Holder.builder().anInteger(value).build();
            }
        })).addSerializer(Holder.class, new StdDelegatingSerializer(new StdConverter<Holder, Integer>() {
            @Override
            public Integer convert(Holder value) {
                return value.getAnInteger();
            }
        }));
        ObjectMapper objectMapper = new ObjectMapper().registerModule(module);

        try {
            Foo foo = Foo.builder().foo("foo").build();
            MapLikeType mapLikeType = objectMapper.getTypeFactory().constructMapLikeType(Map.class, String.class, Holder.class);
            Map<String, Holder> mappedFoo = objectMapper.convertValue(foo, mapLikeType);
            System.out.printf("Foo converted to Map: %s%n", mappedFoo.toString());
        } catch (RuntimeException e) {
            System.err.println("BOOM!");;
        }

        Map<String, Holder> barMap = new HashMap<>();
        barMap.put("bar", Holder.builder().anInteger(1).build());
        Bar bar = objectMapper.convertValue(barMap, Bar.class);
        System.out.printf("Map converted to Bar: %s%n", bar);

        Map<String, Holder> fooMap = new HashMap<>();
        fooMap.put("foo", Holder.builder().aString("foo").build());
        Foo foo = objectMapper.convertValue(fooMap, Foo.class);
        System.out.printf("Map converted to Foo: %s%n", foo);
    }
}

@Builder
@Data
@ToString
class Holder {
    private String aString;
    private Integer anInteger;
}

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
class Foo {
    private String foo;
}

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
class Bar {
    private Integer bar;
}
```

**Comment by cowtowncoder** [comment] 2021-03-26 16:25
Correct: you can only ever register one (de)serializer for given "raw" class. I am not sure how else that could work.

Perhaps you could explain what you are trying to achieve, in addition to what constructs you are trying to use?

**Comment by ecausarano** [comment] 2021-03-26 19:14
Hi @cowtowncoder I was expecting it to be possible to add several serializers with different IN1->OUT, IN2 -> OUT, ... INn -> OUT signatures, so the mapper could then pick the correct IN1->OUT combination depending on both the desired OUT type and the given INn type. How could the ObjectMapper convert a POJO to Map<String, String> otherwise? Indeed, in the end I just want to turn my POJO to a Map<String, AttributeValue> where the latter type is the holder used in AWS Dynamo.

**Comment by cowtowncoder** [comment] 2021-03-26 20:25
If you need to handle target type of `AttributeValue`, you will need to register (de)serializer for that type: `Map` handlers will request key/value (de)serializers separately and you shouldn't have to worry about that part.

So in essence registration of `Map` deserializer is always separate from registration of value (and key) deserializers.

But I don't think that is the problem here.

Now, `convertValue()`: it does not try to match serializers and deserializers as much as conceptually do:

1. Serialize given value as JSON (internally, in this case, it will only get built into a `TokenBuffer` as optimization)
2. Deserialize given token stream (from that `TokenBuffer`) into target type; similar to how regular JSON databinding works

So as long as your serializers can produce a token stream; and deserializers read from token stream into type, conversion should work.

But if using union-like `Holder` types, you will need to figure out how to do those, based on content you see: at Java type level there is no indication of declared content type. With generic signature you could change that, of course, and you can registered different handlers too... although not using `SimpleModule` because it only handles non-generic types (instead you'd create `Module`, which has to register `Serializers` and `Desererializers` providers which can use full generic type signatures). I am not sure that would make sense here, however.

**Comment by cowtowncoder** [comment] 2021-04-11 01:15
Closing this wrt original question: it is true, one can only register a single serializer or deserializer for given type: with `SimpleModule` for one type-erased type, or, in case of `Module` in general, for any type-erased or generic type (`JavaType`). This is by design.

**Closed by cowtowncoder** 2021-04-11 01:15 UTC

**Comment by ecausarano** [comment] 2021-04-11 09:58
Thanks @cowtowncoder might be useful to document this design and link it in https://github.com/FasterXML/jackson-databind#tutorial-fancier-stuff-conversions

**Comment by cowtowncoder** [comment] 2023-02-17 22:52
Yes, wrt registration of serializers/deserializers, later registrations will have precedence over earlier ones. I would be open to contributions (PRs) for suggested changes in documentation; class Javadocs, repo README's and so on.

**Comment by JooHyukKim** [comment] 2023-02-19 13:37
> Also one other note: do not use `constructMapLikeType()` if you are creating a true Map type -- use `constructMapType()`. Map-like types are only meant for supporting things that do not implement `Map` interface and as such cannot use standard Map handlers. This does not make sense when trying to actually handle Map values.

Can we add your explanation (quoted) to the JavaDoc of method, @cowtowncoder?
I tried writing JavaDoc to both constructMapLikeType methods like below and seems reasonable.
So, lemme know if you agree.

![image](https://user-images.githubusercontent.com/61615301/219951639-96221568-dd4b-4820-a02c-e30511ef7e04.png)

**Comment by cowtowncoder** [comment] 2023-02-19 23:56
Good idea @JooHyukKim , will do!

**Comment by JooHyukKim** [comment] 2023-02-19 23:58
@cowtowncoder If you are busy lemme know, I will make a PR. 
I already wrote the javadoc like above 😆

**Comment by cowtowncoder** [comment] 2023-02-19 23:59
@JooHyukKim That would be great!
