### ISSUE TITLE
Lack of path on MismatchedInputException

### ISSUE THREAD

**Issue by TheEin** [FasterXML/jackson-databind#2357] opened 2019-06-18 11:32 UTC
Upon deserializing a null value creator property we get a MismatchedInputException without having the property name specified (possibly only in a message).
Path should be populated in the property name is known.

**Comment by TheEin** [comment] 2019-06-18 12:45
Patch for PR

[Add_path_to_MismatchedInputException_where_possible.zip](https://github.com/FasterXML/jackson-databind/files/3301506/Add_path_to_MismatchedInputException_where_possible.zip)

**Comment by cowtowncoder** [comment] 2019-09-11 20:42
```
Index: src/main/java/com/fasterxml/jackson/databind/DeserializationContext.java

--- src/main/java/com/fasterxml/jackson/databind/DeserializationContext.java	(date 1560483158000)
+++ src/main/java/com/fasterxml/jackson/databind/DeserializationContext.java	(date 1560861621000)
@@ -1368,8 +1368,12 @@
             String msg, Object... msgArgs) throws JsonMappingException
     {
         msg = _format(msg, msgArgs);
-        JavaType type = (prop == null) ? null : prop.getType();
-        throw MismatchedInputException.from(getParser(), type, msg);
+        Optional<BeanProperty> propertyOptional = Optional.ofNullable(prop);
+        JavaType type = propertyOptional.map(BeanProperty::getType).orElse(null);
+        MismatchedInputException e = MismatchedInputException.from(getParser(), type, msg);
+        propertyOptional.map(BeanProperty::getMember).ifPresent(member ->
+                e.prependPath(member.getDeclaringClass(), prop.getName()));
+        throw e;
     }
 
     /**
@@ -1405,6 +1409,29 @@
         throw MismatchedInputException.from(getParser(), targetType, msg);
     }
 
+    /**
+     * Helper method used to indicate a problem with input in cases where more
+     * specific <code>reportXxx()</code> method was not available.
+     */
+    public <T> T reportPropertyInputMismatch(Class<?> targetType, String propertyName,
+            String msg, Object... msgArgs) throws JsonMappingException
+    {
+        msg = _format(msg, msgArgs);
+        MismatchedInputException e = MismatchedInputException.from(getParser(), targetType, msg);
+        Optional.ofNullable(propertyName).ifPresent(name -> e.prependPath(targetType, name));
+        throw e;
+    }
+
+    /**
+     * Helper method used to indicate a problem with input in cases where more
+     * specific <code>reportXxx()</code> method was not available.
+     */
+    public <T> T reportPropertyInputMismatch(JavaType targetType, String propertyName,
+            String msg, Object... msgArgs) throws JsonMappingException
+    {
+        return reportPropertyInputMismatch(targetType.getRawClass(), propertyName, msg, msgArgs);
+    }
+
     public <T> T reportTrailingTokens(Class<?> targetType,
             JsonParser p, JsonToken trailingToken) throws JsonMappingException
     {
Index: src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java	(date 1560483158000)
+++ src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java	(date 1560861621000)
@@ -2372,7 +2372,7 @@
         }
         String actualName = p.currentName();
         if (!expSimpleName.equals(actualName)) {
-            ctxt.reportInputMismatch(rootType,
+            ctxt.reportPropertyInputMismatch(rootType, actualName,
                     "Root name '%s' does not match expected ('%s') for type %s",
                     actualName, expSimpleName, rootType);
         }
Index: src/main/java/com/fasterxml/jackson/databind/ObjectReader.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/com/fasterxml/jackson/databind/ObjectReader.java	(date 1560483158000)
+++ src/main/java/com/fasterxml/jackson/databind/ObjectReader.java	(date 1560861621000)
@@ -1644,7 +1644,7 @@
         }
         String actualName = p.currentName();
         if (!expSimpleName.equals(actualName)) {
-            ctxt.reportInputMismatch(rootType,
+            ctxt.reportPropertyInputMismatch(rootType, actualName,
                     "Root name '%s' does not match expected ('%s') for type %s",
                     actualName, expSimpleName, rootType);
         }
Index: src/main/java/com/fasterxml/jackson/databind/deser/impl/ExternalTypeHandler.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/com/fasterxml/jackson/databind/deser/impl/ExternalTypeHandler.java	(date 1560483158000)
+++ src/main/java/com/fasterxml/jackson/databind/deser/impl/ExternalTypeHandler.java	(date 1560861621000)
@@ -225,7 +225,7 @@
                     }
                     // 26-Oct-2012, tatu: As per [databind#94], must allow use of 'defaultImpl'
                     if (!_properties[i].hasDefaultType()) {
-                        ctxt.reportInputMismatch(bean.getClass(),
+                        ctxt.reportPropertyInputMismatch(bean.getClass(), extProp.getName(),
                                 "Missing external type id property '%s'",
                                 _properties[i].getTypePropertyName());                                
                     } else  {
@@ -237,7 +237,7 @@
 
                 if(prop.isRequired() ||
                         ctxt.isEnabled(DeserializationFeature.FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY)) {
-                    ctxt.reportInputMismatch(bean.getClass(),
+                    ctxt.reportPropertyInputMismatch(bean.getClass(), prop.getName(),
                             "Missing property '%s' for external type id '%s'",
                             prop.getName(), _properties[i].getTypePropertyName());
                 }
@@ -270,7 +270,7 @@
                 // but not just one
                 // 26-Oct-2012, tatu: As per [databind#94], must allow use of 'defaultImpl'
                 if (!extProp.hasDefaultType()) {
-                    ctxt.reportInputMismatch(_beanType,
+                    ctxt.reportPropertyInputMismatch(_beanType, extProp.getProperty().getName(),
                             "Missing external type id property '%s'",
                             extProp.getTypePropertyName());
                 } else {
@@ -278,7 +278,7 @@
                 }
             } else if (_tokens[i] == null) {
                 SettableBeanProperty prop = extProp.getProperty();
-                ctxt.reportInputMismatch(_beanType,
+                ctxt.reportPropertyInputMismatch(_beanType, prop.getName(),
                         "Missing property '%s' for external type id '%s'",
                         prop.getName(), _properties[i].getTypePropertyName());
             }
Index: src/main/java/com/fasterxml/jackson/databind/deser/impl/PropertyValueBuffer.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/com/fasterxml/jackson/databind/deser/impl/PropertyValueBuffer.java	(date 1560483158000)
+++ src/main/java/com/fasterxml/jackson/databind/deser/impl/PropertyValueBuffer.java	(date 1560861621000)
@@ -167,7 +167,7 @@
             for (int ix = 0; ix < props.length; ++ix) {
                 if (_creatorParameters[ix] == null) {
                     SettableBeanProperty prop = props[ix];
-                    _context.reportInputMismatch(prop.getType(),
+                    _context.reportInputMismatch(prop,
                             "Null value for creator property '%s' (index %d); `DeserializationFeature.FAIL_ON_NULL_FOR_CREATOR_PARAMETERS` enabled",
                             prop.getName(), props[ix].getCreatorIndex());
                 }
Index: src/main/java/com/fasterxml/jackson/databind/deser/std/JsonNodeDeserializer.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/com/fasterxml/jackson/databind/deser/std/JsonNodeDeserializer.java	(date 1560483158000)
+++ src/main/java/com/fasterxml/jackson/databind/deser/std/JsonNodeDeserializer.java	(date 1560861621000)
@@ -219,7 +219,7 @@
     {
         // [databind#237]: Report an error if asked to do so:
         if (ctxt.isEnabled(DeserializationFeature.FAIL_ON_READING_DUP_TREE_KEY)) {
-            ctxt.reportInputMismatch(JsonNode.class,
+            ctxt.reportPropertyInputMismatch(JsonNode.class, fieldName,
                     "Duplicate field '%s' for ObjectNode: not allowed when FAIL_ON_READING_DUP_TREE_KEY enabled",
                     fieldName);
         }

```

**Comment by cowtowncoder** [comment] 2019-09-11 21:16
Hmmh. Would have been great to have a reproduction, to see problem being fixed... but I think this makes sense.

**Comment by cowtowncoder** [comment] 2019-09-11 21:20
Merged as suggested, with one exception: left out one for `JsonNodeDeserializer` since I think path could be incorrect due to recursive calls: a test case would be great, although maybe I can have a look to see what it looks like.

**Closed** 2019-09-11 21:21 UTC
Labels: 2.10

**Comment by cowtowncoder** [comment] 2019-09-11 21:32
Tested `JsonNodeDeserializer` case: to include path there, would need to include possible enclosing content too so can not just pass the name of object property that is duplicate. So leaving it out at this point makes sense I think.
