### ISSUE TITLE
Existing property polymorphic deserialization does not work on enums

### ISSUE THREAD

**Issue by devcsrj** [FasterXML/jackson-databind#1635] opened 2017-05-25 07:43 UTC
Seems like, enum-related deserialization annotations doesn't work on polymorphic types with builders. Using the following main:

```java
        ObjectMapper om = new ObjectMapper();
        String json = "{\"type\":\"ggwp\",\"name\":\"Hello\"}";
        Endpoint endpoint = om.readValue( json, Endpoint.class );
        System.out.println(endpoint);
```

This fails to deserialize due to the non-null requirement of `Endpoint#type()`.

```java
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of io.toro.integrate.labs.esb1271.AutoValue_EndpointImpl$Builder, problem: Missing required properties: type
 at [Source: {"type":"ggwp","name":"Hello"}; line: 1, column: 30]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:277)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1441)
	at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1055)
...
```

 I tried to set breakpoints to:

- `@JsonCreator Endpoint.Type#fromKey` - would've expected this to be used, so that proper fallback is taken care of
- `@JsonValue Endpoint.Type#getKey`
- `@JsonCreator EndpointImpl.Builder#create` - would've expected this to be used, so that the type be initialized

..and none of these methods are called. My goal was to deserialize all unknown endpoints into an `EndpointImpl`, with type = `Type.UNRECOGNIZED`. I even tried to implement custom `JsonSerializer` and `JsonDeserializer` for the enum, but both aren't called either. I'm using jackson 2.8.6, with google's auto value.

Edit: Actually, even if I specify an existing 'type' in the json, it's not deserialized properly too.

----

Here's the base class:

```java
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.EXISTING_PROPERTY,
        property = "type",
        defaultImpl = EndpointImpl.class )
@JsonSubTypes( value = {} ) // more subtypes
public abstract class Endpoint {

    @JsonProperty( "name" ) public abstract String name();
    @JsonProperty( "type" ) public abstract Type type();

    public abstract static class Builder<B extends Builder<B>> {
        @JsonProperty( "name" ) public abstract B name( String name );
        @JsonProperty( "type" ) public abstract B type( Type type );
        public abstract Endpoint build();
    }

    public static enum Type {

        UNRECOGNIZED( "unrecognized" );
        ...
        @JsonCreator
        public static Type fromKey( String key ) {
            for ( Type type : values() ) {
                if ( type.key.equals( key ) )
                    return type;
            }
            return UNRECOGNIZED;
        }

        @JsonValue
        public String getKey() {
            return key;
        }
    }
}
```

This is extended by:

```java
@AutoValue
@JsonDeserialize( builder = AutoValue_EndpointImpl.Builder.class )
public abstract class EndpointImpl extends Endpoint {

    public static Builder builder() {
        return new AutoValue_EndpointImpl.Builder()
                        .type( Type.UNRECOGNIZED );
    }

    @AutoValue.Builder
    public abstract static class Builder extends Endpoint.Builder<Builder> {

        @JsonCreator
        private static Builder create() {
            return EndpointImpl.builder();
        }

        public abstract EndpointImpl build();
    }

}

```

**Comment by devcsrj** [comment] 2017-05-26 07:48
Update: For now, I implemented this requirement by providing a `@JsonTypeResolver`. (`AsPropertyTypeDeserializer`).

But, any light to why the above setup doesn't work is much appreciated!

**Comment by cowtowncoder** [comment] 2017-06-06 04:28
@devcsrj Polymorphic types only work with builder if builder itself is constructed with type information, that is, is polymorphic.

**Comment by cowtowncoder** [comment] 2017-06-09 05:45
Looking at example bit more, I think most likely problem is that current handling of builders for value types does have issues with generic types: most likely parameterization is dropped at some point.
I think there is at least one other issue reported; and from what I remember, attempts to carry fully resolved types did not get far due to complexity of handling. Big part of the problem is that builder handling is sort of specialized add-on to basic POJO handling: low-level handlers are not aware of difference between builder type (on which properties are set), and resulting result type.
(add to this mix separate framework (auto-value) which generates its own types and things start to get even more complicated -- but that may be side-issue here).

Still: if it was possible to create a self-contained example that does not refer external types (in this case, autovalue library), perhaps I could help figure out the root cause and either possibly fix it, or (perhaps more likely) be able to more accurately describe the issue.

**Comment by devcsrj** [comment] 2017-06-09 12:11
Hi @cowtowncoder !

While doing the self-contained example, I managed [to fix](https://github.com/devcsrj/bug-reports/commit/a715aaee64cbfb02a1e7243a30140dec5ab58dde) the issue `@JsonCreator EndpointImpl.Builder#create` where it [wasn't called](https://github.com/devcsrj/bug-reports/blob/master/jackson-databind-1635/src/main/java/io/devcsrj/jackson/EndpointImpl.java#L16-L19) by Jackson. So now, the above example now works! 

While the fix is already good enough for my use case, I still don't get why `@Json|Creator|Value` on the enum is not called. The example now works, only because the 'type' property is set during builder instantiation (thus allowing jackson to later on infer the subtype). I don't know if this is still a relevant bug that you'd like to fix, so I'll leave the discretion of closing of ticket up to you.


--
PS: Here's a [self-contained example](https://github.com/devcsrj/bug-reports/tree/master/jackson-databind-1635), without auto value.

**Comment by cowtowncoder** [comment] 2017-06-11 22:10
@devcsrj Thank you! I will have a look and try to see what is going on.

**Comment by cowtowncoder** [comment] 2017-06-11 22:34
Ok: so, looks like the expectation is that even in cases where type id fails to match to known values, attempt was still made to set the external property value with id (with proper binding). That seems like one potential outcome, although it may be bit tricky to achieve as this is a special case that is considered sort of failure.

It is possible that type of property has no effect, and that simple `String` property would show similar behavior.

**Comment by cowtowncoder** [comment] 2017-06-11 22:37
Ah. One problem with code as shown: `@JsonTypeInfo` must specify property `visible`:

    visible=true

for type id to be exposed to regular `BeanDeserializer`, which can then map it to existing property.
Without this, type id is considered metadata, consumed directly by databind itself.
This is the default setting.

The reason why visibility is not directly determine from `EXISTING_PROPERTY` (which would seem like a reasonable inference) is that there are couple of different uses for existing-property option: one being it would only be accessed via getter (or field) for serialization; but not necessarily set during deserialization.

So, this needs to be added.
With this setting, both String and enum-valued type id property does get property set, in a more simplified test I'll add.

It does however look that this is not enough for your test case, so I will try digging deeper; it is possible that use of Creator properties could be the problem here, or that it is due to use as `defaultImpl`.

**Comment by cowtowncoder** [comment] 2017-06-11 22:41
And no, it does not like `defaultImpl` is the problem here. So perhaps it has to do with creator method.

**Comment by cowtowncoder** [comment] 2020-10-09 18:16
At this point, I am not sure quite how to reproduce the issue and handling may have changed significantly over past 3 years. Closing now, may be re-filed with a simplified reproduction.

**Closed by cowtowncoder** 2020-10-09 18:16 UTC
