### ISSUE TITLE
Problem serializing `JsonMappingException` due to addition of non-ignored `processor` property

### ISSUE THREAD

**Issue by jecaplan** [FasterXML/jackson-databind#1368] opened 2016-09-11 18:11 UTC
I notice that, e.g.,  JsonMappingException has several bidirectional links in internal fields like _processor.

Why not annotate those fields with @JsonIgnore?  You've already got the Java serialization "transient" on them.

One symptom of not eating your own dog food here is that AWS SWF Flow Framework is broken.  If it attempts to deserialize the result of an activity and that attempt fails with a JsonMappingException, the framework then attempts to serialize the resulting DataConverterException via Jackson...which fails with a different JsonMappingException (StackOverflowError) because of the embedded JsonMappingException.

I see no reason why a serde framework should not be able to serde itself.

**Comment by cowtowncoder** [comment] 2016-09-12 03:16
Since there is `transient` (and since field is marked as `protected`) it seems superfluous to also add `@JsonIgnore`: former alone should prevent usage. If this is not enough for some reason, I am not against adding annotations; and certainly exceptions produced should be Jackson-serializable.
In perfect world deserialization should also work, although that is bit trickier due to usually polymorphic nature of exception hierarchies.

If there is an actual problem (which sounds like there is), a reproducible test case would be helpful, especially to guard against future regressions. But also to make sure I understand the specific problem.

**Comment by jecaplan** [comment] 2016-09-12 05:31
public class TestJackson {
    	public static class NoSerdeConstructor {
    		private String strVal;
    		public String getVal() { return strVal; }
    		public NoSerdeConstructor( String strVal ) {
    			this.strVal = strVal;
    		}
    	}
    	@Test
    	public void test() throws IOException {
    		ObjectMapper mpr = new ObjectMapper();
    
    //		// fails: shouldn't this pass?
    //		assertFalse( mpr.canDeserialize( mpr.constructType( NoSerdeConstructor.class ) ) );

    		try {
    			mpr.readValue( "{ \"val\": \"foo\" }", NoSerdeConstructor.class );
    		} catch ( JsonMappingException excCannotConstructInstance ) {
    			// throws a different JsonMappingException: Infinite recursion
    			mpr.writeValueAsString( excCannotConstructInstance );
    		}
    	}
    }

**Comment by cowtowncoder** [comment] 2016-09-13 05:36
Thank you! I'll see if it occurs with 2.7 as well (most likely does); original description makes more sense with code now.

**Comment by cowtowncoder** [comment] 2016-09-13 05:45
Ah yes. You are right about need for `@JsonIgnore`: I forgot that `transient` keyword does not (by default) propagate to matching getter.

Quite odd that this wasn't reported earlier for 2.7, but better late than never.

**Comment by jecaplan** [comment] 2016-09-13 05:53
I have a pull request with regression test open if that's of any use to you.

**Comment by cowtowncoder** [comment] 2016-09-13 05:57
@jecaplan it is indeed.

**Closed** 2016-09-13 05:56 UTC
