### ISSUE TITLE
The method com.fasterxml.jackson.databind.introspect.AnnotatedClass._classAnnotations() contains a race condition

### ISSUE THREAD

**Issue by ThomasKrieger** [FasterXML/jackson-databind#1386] opened 2016-09-27 12:20 UTC
Here is my test class:

``` java
public void testRead()
    {
        try{

            ObjectMapper objectMapper = new ObjectMapper();


            Map<String,String> myMap = new HashMap<String, String>();
            objectMapper.readValue( new File("resource/map.json") , myMap.getClass());

        }
            catch(Exception e)
            {
                e.printStackTrace();
            }



    }
```

The method is run by multiple threads. Here is the stack trace found by [vmlens](http://vmlens.com), a tool to test multithreaded java.

com.fasterxml.jackson.databind.introspect.AnnotatedClass._classAnnotations
Thread-2
com/fasterxml/jackson/databind/introspect/AnnotatedClass._classAnnotations
com/fasterxml/jackson/databind/introspect/AnnotatedClass.getAnnotation
com/fasterxml/jackson/databind/AnnotationIntrospector._findAnnotation
com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.findDeserializer
com/fasterxml/jackson/databind/deser/DeserializerCache.findDeserializerFromAnnotation
com/fasterxml/jackson/databind/deser/DeserializerCache._createDeserializer
com/fasterxml/jackson/databind/deser/DeserializerCache._createAndCache2
com/fasterxml/jackson/databind/deser/DeserializerCache._createAndCacheValueDeserializer
com/fasterxml/jackson/databind/deser/DeserializerCache.findValueDeserializer
com/fasterxml/jackson/databind/DeserializationContext.findNonContextualValueDeserializer
com/fasterxml/jackson/databind/deser/std/UntypedObjectDeserializer._findCustomDeser
com/fasterxml/jackson/databind/deser/std/UntypedObjectDeserializer.resolve
com/fasterxml/jackson/databind/deser/DeserializerCache._createAndCache2
com/fasterxml/jackson/databind/deser/DeserializerCache._createAndCacheValueDeserializer
com/fasterxml/jackson/databind/deser/DeserializerCache.findValueDeserializer
com/fasterxml/jackson/databind/DeserializationContext.findContextualValueDeserializer
com/fasterxml/jackson/databind/deser/std/MapDeserializer.createContextual
com/fasterxml/jackson/databind/DeserializationContext.handleSecondaryContextualization
com/fasterxml/jackson/databind/DeserializationContext.findRootValueDeserializer
com/fasterxml/jackson/databind/ObjectMapper._findRootDeserializer
com/fasterxml/jackson/databind/ObjectMapper._readMapAndClose
com/fasterxml/jackson/databind/ObjectMapper.readValue
com/vmlens/testMultithreadedJson/jackson/JacksonLocalVariable.testRead

If you look at the source you see that the method uses the double based locking pattern, [which is broken](https://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html):

``` java
    private AnnotationMap _classAnnotations() {
        AnnotationMap anns = _classAnnotations;
        if (anns == null) {
            // 06-Dec-2015, tatu: yes, double-locking, typically not a good choice.
            //  But for typical usage pattern here (and with JVM 7 and above) is
            //  a reasonable choice to avoid non-common but existing race condition
            //  from root name lookup style usage
            // Also note that race condition stems from caching only used for loading
            // where just class annotations are needed
            synchronized (this) {
                anns = _classAnnotations;
                if (anns == null) {
                    anns = _resolveClassAnnotations();
                    _classAnnotations = anns;
                }
            }
        }
        return anns;
    }
```

I think the easiest way would be to make the complete method synchronized.

**Comment by cowtowncoder** [comment] 2016-09-27 20:49
How does the problem manifest itself? As per comments, the downside should be that there is a possibility of resolving type information more than once; but are you observing an exception here?
If so, would it be possible to add an example stack trace.

Also, which version did you test it with?

I am not against improving this, and I agree that handling is not clean, and it may well make sense to just synchronize the method. I just want to double-check I understand immediate problems observed.

**Comment by ThomasKrieger** [comment] 2016-09-30 13:36
I will try to generate an exception. This will take some time since the race condition does not always appear. 
I used version 2.8.3

**Comment by cowtowncoder** [comment] 2016-09-30 18:23
@ThomasKrieger Ok; as long as there is an exception it needs to be fixed. If you happen to have something like stack trace, that'd be enough for me, if actual reliable reproduction is difficult to get.
I am mostly asking since sometimes certain aspects (like performance) are hard to reliably gauge, so I want to know exact problem encountered beyond thread dump itself.

**Comment by cowtowncoder** [comment] 2017-03-30 03:46
Quick note: `2.8.7` includes one change to eagerly load class annotations for `AnnotatedClass`, which I think should resolve the potential issue here. Please re-open if problem does reoccur.

**Closed by cowtowncoder** 2017-03-30 03:46 UTC
