### ISSUE TITLE
Change to StdDeserializer class in 2.9.x

### ISSUE THREAD

**Issue by mehmetsalgar** [FasterXML/jackson-databind#1764] opened 2017-09-11 10:13 UTC
I was trying to use Spring Hateoas library with Spring 5.0.0.M2 which using jackson-databind 2.9.0.pr2 and it was not working after debugging a while, I saw a problem cause in 2.9.x version of the jackson-databind.

For ex, at 2.6.0  (and up until 2.8.x) version of the jackson-databind the class StdDeserializer contains following constructor.

` protected  [More ...] StdDeserializer(JavaType valueType) {
    _valueClass = (valueType == null) ? null : valueType.getRawClass();
   }`

in the 2.9.X version it became...

` protected StdDeserializer(JavaType valueType) {
     _valueClass = valueType.getRawClass();
  }`

as you see the check ' (valueType == null) ? null : valueType.getRawClass();' is disappeared, it exactly this point, Spring Hoteoas library now breaks its search for the standard deserializer for a bean.

Is there a specific reason why this check is removed if not is it possible re-insert it?

**Comment by cowtowncoder** [comment] 2017-09-11 18:56
@mehmetsalgar Thank you for reporting this -- it looks like oversight, and I am not sure why it happened.

**Comment by cowtowncoder** [comment] 2017-09-11 22:25
Hmmh. Actually. I take it back. I wish there was a comment there, but I suspect reason was/is is that since there is alternate constructor:

```java
    protected StdDeserializer(Class<?> vc) {
        _valueClass = vc;
    }
```

then one that takes `JavaType` should never get `null`.
Basically one should always indicate at least raw type deserializer handles (although granted other constructor should also have `null` check to enforce this).

I am not necessarily 100% against adding back the check due to backwards compatibility aspects -- 3.0 development is starting and this is probably better place to add stricter checks, all things considered -- but at this point I would recommend changing code to actually pass a non-null value like `Object.class` (or, ideally, if more specific type is known, that).

**Comment by mehmetsalgar** [comment] 2017-09-12 07:27
If it would my implementation I have no problem with it, if it would be code that is developed from me, but as I said it is a code from Spring Hateoas Project (http://projects.spring.io/spring-hateoas/) and I have no control over it.

If you make this change, it would take too much time for them to adapt this (possibly other libraries also), the error they were reporting was nothing to do with change and it took me lots of debugging time to figure out what is going wrong.

**Comment by cowtowncoder** [comment] 2017-09-12 20:39
@mehmetsalgar I think that is actually a problem in that library: could you at least report an issue for them? I am not planning to release new jackson 2.9.x patch any time soon, so fix from Jackson side will not be immediate either, if it is added.

**Comment by mehmetsalgar** [comment] 2017-09-13 05:50
Sure I can report there but lots of other libraries will have problems if they are implemented in the old check.....

At the moment, it is not an urgent problem for me, I dropped back from Spring Boot 2.0.0.M2 to 1.5.6 and my problem is solved. I just like to give here a pre-warning about what is about to come.

**Comment by cowtowncoder** [comment] 2017-09-15 17:40
@mehmetsalgar I appreciate your help here.

@sdeleuze WDYT? I can do changes for Jackson 2.9.2 as necessary, but would also like to see if things could be fixed on Spring side if you know who to contact? It should be very small change using existing API.

**Comment by sdeleuze** [comment] 2017-09-15 18:13
I will have a deeper look Monday first thing cc @gregturn @olivergierke.

**Comment by cowtowncoder** [comment] 2017-09-15 18:18
Thanks! No hurry from my side unless something turns up (since 2.9.1 just went out). But don't want to wait until trouble if such exists =)

**Comment by gregturn** [comment] 2017-09-15 18:24
@cowtowncoder, Spring HATEOAS is based on Jackson 2.8.5 for Spring 4, and 2.9.1 for Spring 5. When you mention Jackson 2.6, not sure what to say there.

If you have a bit of code we can use to capture this regression, we could pinpoint the exact bug and either patch Spring HATEOAS or provide better feedback to the Jackson team.

**Comment by cowtowncoder** [comment] 2017-09-15 18:34
@gregturn I don't think I have said Jackson 2.6 anywhere... ?

Change in question is in 2.9, removal of one `null` check. I may bring that back, but fundamentally I think calling code (sub-class of `StdDeserializer`) should probably be changed so that instead of calling 

    public StdDeserializer(JavaType t)

with `null`, it should call

    public StdDeserializer(Class<?> type)

with non-null value (if not known, `Object.class`) is fine. Passing `null` would probably not fail either and would be improvement as well.

So what I was hoping was to suggest a minor improvement since passing of `null` as `JavaType` is probably going to disappear from later versions.

Does this make more sense? Apologies for not giving enough context.

**Comment by gregturn** [comment] 2017-09-15 18:34
Digging deeper into Spring HATEOAS, it appears the only place such a constructor call is invoked, is inside HalResourcesDeserializer(JavaType type, JavaType contentType). This invokes super(type), which as you pointed out, no longer has the nullable option.

Well, in Spring HATEOAS, the only code invoking this constructor is:

```
this(TypeFactory.defaultInstance().constructCollectionLikeType(List.class, Object.class), null)
```
and
```
this(TypeFactory.defaultInstance().constructCollectionLikeType(List.class, vc), vc);
```
Both of these produce a `List` based type, and so shouldn't yield a `null`. Do you agree? Or do you have an example illustrating something else happening?

**Comment by cowtowncoder** [comment] 2017-09-15 18:36
@gregturn Oh. No, that call should never return `null`. If it did, that'd be a bug in Jackson.

Hmmh. Odd. I have not seen the bug myself unfortunately.

Perhaps it could have been different in one of milestone builds, and not existing any more?

**Comment by gregturn** [comment] 2017-09-15 18:39
Spring HATEOAS has multiple build profiles to ensure backward compatibility. Our baseline profile, built against Java 6 and Spring 4 is using Jackson 2.8.5. We have a second profile to run everything against Spring 5 snapshots + Jackson 2.9.1. Neither version has yielded a breaking test case. So if something is wrong, I'd very much like to capture a regression test case in our code, fix the problem, and then never have it sneak in again. I just don't know what @mehmetsalgar is doing that is causing issues.

**Comment by cowtowncoder** [comment] 2017-09-15 18:56
@gregturn Thank you for following through this. I agree, if @mehmetsalgar can repro this with a version that'd be great to find, add regression test for & fix.
For now I assume there isn't much else that can be done.

**Comment by olivergierke** [comment] 2017-09-16 15:43
I think what you run into was fixed with spring-projects/spring-hateoas#583. I guess we're gonna need an 0.24 release sooner than later then.

**Comment by cowtowncoder** [comment] 2017-09-26 23:11
Added null check for `2.9.2` just to minimize friction. Will change for 3.0.

**Closed by cowtowncoder** 2017-09-26 23:11 UTC

**Comment by gregturn** [comment] 2017-09-26 23:54
Tnx @cowtowncoder!
