### ISSUE TITLE
JsonParser cannot getText() for input stream on MismatchedInputException

### ISSUE THREAD

**Issue by joca-bt** [FasterXML/jackson-databind#2635] opened 2020-03-01 11:15 UTC
I've stumbled upon a situation in which I'm not able to get the textual representation of the current token.

I have the following class:

```
public class Test {
    public Boolean value;
    public Boolean getValue() { return value; }
    public void setValue(Boolean value) { this.value = value; }
}
```

And the following object mapper:

```
ObjectMapper objectMapper = new ObjectMapper();
objectMapper.disable(MapperFeature.ALLOW_COERCION_OF_SCALARS);
```

I'm trying to deserialize something that would result in a `MismatchedInputException`. I'm providing an integer to something that should be a boolean:

```
try {
    objectMapper.readValue("{ \"value\": 1 }", Test.class);
} catch (MismatchedInputException exception) {
    JsonParser parser = (JsonParser) exception.getProcessor();
    System.out.println(parser.currentToken());
    System.out.println(parser.getText());
} catch (Exception exception) {}
```

This results in:

```
VALUE_NUMBER_INT
1
```

as expected.

What's the use case for this you might ask? Whenever the clients of my service send me something incorrect I want to be able to give them detailed information about what went wrong. For example, "I was expecting a boolean but you gave me 1, which is an integer.".

Now, if I use an input stream instead of a string, I can no longer access the text and get a null instead:

```
objectMapper.readValue(new ByteArrayInputStream("{ \"value\": 1 }".getBytes()), Test.class);
```

```
VALUE_NUMBER_INT

```

On Jackson 2.10.2.

**Comment by cowtowncoder** [comment] 2020-03-08 00:50
Thank you for the report: while some of the information is best-effort and occasionally not possible to retain, this seems like something that should be available as expected.

**Comment by cowtowncoder** [comment] 2020-03-08 01:51
Interesting. At first I had trouble reproducing the problem, the way I tried to extend existing tests.
The problem is that if passing `JsonParser` to `readValue()`, problem does not exist.
But when using exact test provided, I can see the issue: problem being that underlying parser gets closed due to exception (so that we do not leak underlying `Reader` or `InputStream` when created by mapper or `JsonFactory` itself).
Interesting that this only affects one of parser factories.

I'll have to see if `TextBuffer` contents could still be retained: closing of the parser is necessary, but since current token value is retained, and it works for one of parsers, that should be doable.
But since there may be unintended retention, will likely fix for 2.11(.0) to minimize change of such regression in patch release.

**Comment by cowtowncoder** [comment] 2020-03-08 04:15
So, the actual fix is for:

https://github.com/FasterXML/jackson-core/issues/606

and takes care of this problem. Will go in 2.11.0.

**Closed by cowtowncoder** 2020-03-08 04:15 UTC

**Comment by joca-bt** [comment] 2020-06-15 11:03
It seems the fix was only made for integers. Can it be expanded to the remaining types? And they don't even need a stream instead of a string to result in the issue.

```
try {
    objectMapper.readValue("{ \"value\": 1.0 }", Test.class);
} catch (MismatchedInputException exception) {
    JsonParser parser = (JsonParser) exception.getProcessor();
    System.out.println(parser.currentToken());
    System.out.println(parser.getText());
} catch (Exception exception) {}

> VALUE_NUMBER_FLOAT
>
```

```
try {
    objectMapper.readValue(new ByteArrayInputStream("{ \"value\": 1.0 }".getBytes()), Test.class);
} catch (MismatchedInputException exception) {
    JsonParser parser = (JsonParser) exception.getProcessor();
    System.out.println(parser.currentToken());
    System.out.println(parser.getText());
} catch (Exception exception) {}

> VALUE_NUMBER_FLOAT
> 
```

**Comment by joca-bt** [comment] 2020-06-16 13:51
How can I re-open this ticket? @cowtowncoder

**Comment by cowtowncoder** [comment] 2020-06-16 17:21
@joca-bt Please file another one, easier to track -- you can refer to this issue as background (to avoid some explanation).

And yes, it is quite possible there are other cases where this won't work as it is unfortunately not something that can be solved in general fashion (to retain content, it must be accessed before input is auto-closed).
