### ISSUE TITLE
@JsonProperty on Enum not working as key in Map

### ISSUE THREAD

**Issue by voidmain** [FasterXML/jackson-databind#1535] opened 2017-02-23 16:25 UTC
I'm using Jackson-Databind 2.8.1 and it seems like Enums that are keys in a Map aren't respecting their `@JsonProperty` settings. 

Here's my Enum:

```java
public enum EventType {
  @JsonProperty(value = "user.delete")
  UserDelete,

  @JsonProperty(value = "user.create")
  UserCreate,

  @JsonProperty(value = "user.update")
  UserUpdate,

  @JsonProperty(value = "user.deactivate")
  UserDeactivate,

  @JsonProperty(value = "user.bulk.create")
  UserBulkCreate,

  @JsonProperty(value = "user.reactivate")
  UserReactivate,

  @JsonProperty(value = "user.action")
  UserAction
}
```

Here's my object:

```java
    public static class EventConfiguration implements Buildable<EventConfiguration> {
      public Map<EventType, EventConfigurationData> events = new HashMap<>();

      public static class EventConfigurationData {
        public boolean enabled;

        public TransactionType transactionType;

        public EventConfigurationData() {
        }

        public EventConfigurationData(boolean enabled, TransactionType transactionType) {
          this.enabled = enabled;
          this.transactionType = transactionType;
        }
      }
    }
```

Here's the **ACTUAL** and **INCORRECT** JSON:

```json
{
  "eventConfiguration": {
    "events": {
      "UserDelete": {
        "enabled": true,
        "transactionType": "None"
      },
      "UserCreate": {
        "enabled": true,
        "transactionType": "None"
      },
      "UserUpdate": {
        "enabled": true,
        "transactionType": "None"
      },
      "UserDeactivate": {
        "enabled": true,
        "transactionType": "None"
      },
      "UserBulkCreate": {
        "enabled": true,
        "transactionType": "None"
      },
      "UserReactivate": {
        "enabled": true,
        "transactionType": "None"
      }
    }
  }
}
```

This is the JSON that comes from this call:

```java
      try {
        body = objectMapper.writeValueAsBytes(request);
      } catch (IOException e) {
        throw new JSONException(e);
      }
```

This is the **EXPECTED** and **CORRECT** JSON that Jackson is **NOT** generating:

```json
{
  "eventConfiguration": {
    "events": {
      "user.delete": {
        "enabled": true,
        "transactionType": "None"
      },
      "user.create": {
        "enabled": true,
        "transactionType": "None"
      },
      "user.update": {
        "enabled": true,
        "transactionType": "None"
      },
      "user.deactivate": {
        "enabled": true,
        "transactionType": "None"
      },
      "user.bulk.create": {
        "enabled": true,
        "transactionType": "None"
      },
      "user.reactivate": {
        "enabled": true,
        "transactionType": "None"
      }
    }
  }
}
```

As you can see, when the JSON is generated by Jackson, it is not respecting the `@JsonProperty` enum values but is instead using the `EventType.name()` method. Additionally, if I feed the JSON that Jackson generates right back into Jackson, it fails. It should never fail as Jackson should always produce JSON that it can consume back (at least with my code here - I can definitely create code where this isn't true).

Then when I turn around and parse this JSON using this code it explodes:

```java
objectMapper.reader(EventConfiguration.class).readValue(request.getInputStream());
```

I get this stack trace:

```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize Map key of type com.inversoft.passport.domain.event.EventType from String "UserDelete": not a valid representation, problem: Can not deserialize Map key of type com.inversoft.passport.domain.event.EventType from String "UserDelete": not one of values excepted for Enum class: [user.delete, user.create, user.update, user.reactivate, user.bulk.create, user.deactivate, user.action]
 at [Source: org.primeframework.mock.servlet.MockServletInputStream@5a634b91; line: 1, column: 507]
 at [Source: org.primeframework.mock.servlet.MockServletInputStream@5a634b91; line: 1, column: 507] (through reference chain: com.inversoft.passport.domain.api.SystemConfigurationRequest["systemConfiguration"]->com.inversoft.passport.domain.SystemConfiguration["eventConfiguration"]->com.inversoft.passport.domain.EventConfiguration["events"])
```

Am I missing a configuration option or something that would make this work?

**Comment by voidmain** [comment] 2017-02-23 16:35
Quick update. This work-around works:

```java
public enum EventType {
  UserDelete("user.delete"),

  UserCreate("user.create"),

  UserUpdate("user.update"),

  UserDeactivate("user.deactivate"),

  UserBulkCreate("user.bulk.create"),

  UserReactivate("user.reactivate"),

  UserAction("user.action");

  private static Map<String, EventType> nameMap = new HashMap<>(EventType.values().length);

  private final String eventName;

  EventType(String eventName) {
    this.eventName = eventName;
  }

  @JsonCreator
  public static EventType forValue(String value) {
    return nameMap.get(value);
  }

  @JsonValue
  public String eventName() {
    return eventName;
  }

  static {
    for (EventType eventType : EventType.values()) {
      nameMap.put(eventType.eventName(), eventType);
    }
  }
}
```

**Comment by cowtowncoder** [comment] 2017-02-23 17:37
Quick question: have you tried a patch of 2.8 (latest is 2.8.7)? Does this occur with that as well?

**Comment by cowtowncoder** [comment] 2017-02-24 04:15
Um, I don't get it -- if you wanted to use values like `UserDelete`, why are you specifying `@JsonProperty` to rename those as `user.delete`, which does not match JSON you are sending?
This seems to be working exactly as expected unless your sample code and/or JSON are wrong.

**Comment by voidmain** [comment] 2017-02-24 15:38
Hi @cowtowncoder. I updated the original description to provide more detail. Let me know if you are still confused and I can add some more detailed code and description.

**Comment by cowtowncoder** [comment] 2017-02-24 16:50
@voidmain thank  you. Yes, that makes sense. I did indeed assume JSON you included was input you expected to feed, not serialization (may have misread description).

I hope to have time to look into this soon; it is quite possible that serialization side of `Enum` Map key handling is more simplistic than regular Enum value serialization.

One more thing that'd help is to use latest version -- that would be 2.8.7. There have been 38 fixes since that, 4 of which are related to enum handling, although none seem directly related here.
For now I assume problem still persists.

**Comment by cowtowncoder** [comment] 2017-02-24 21:52
Actually. I really wish this was repro'd with an up-to-date version. Because when I went back I was unable to reproduce this with 2.8 branch (~2.8.7). Then went to 2.8.1 where test fails. And with pinpointing looks like 2.8.2 contain something that did fix this issue (although none of 3 fixes listed for `jackson-databind` directly related).

So, I think this is now fixed in 2.8 and there is a simplified test for it (just a single `Enum` as `Map` key).

**Closed by cowtowncoder** 2017-02-24 21:52 UTC

**Comment by voidmain** [comment] 2017-02-24 21:54
Sorry about that. I was planning on reproducing it later today or this weekend on 2.8.7. Glad it is fixed though. I'll make sure to use the latest version in the future.

**Comment by cowtowncoder** [comment] 2017-02-24 22:30
@voidmain np. But also let me know just in case there are other issues -- I am always slightly uneasy about fixes that do not match intended changes (that is, none of bug fixes listed were aimed at this problem).

**Comment by fredgalvao** [comment] 2019-09-13 09:43
I'll create a new issue and paste the java version. As I said, this is not a kotlin issue, I was able to reproduce it on both sides. I just provided the kotlin test because it's easier to read.

**Comment by cowtowncoder** [comment] 2019-09-13 15:34
@fredgalvao Ok if this is true leaving it here makes sense, no need or point to transfer.
I will need a Java-only reproduction as `jackson-databind` can not depend on kotlin core (even from tests). I can do conversion when I have time, or if you or anyone else time that's fine too.
Code looks quite... elaborate so my main concern is just conversion.

**Comment by fredgalvao** [comment] 2019-09-13 15:35
@cowtowncoder done: https://github.com/FasterXML/jackson-databind/issues/2454.

**Comment by cowtowncoder** [comment] 2019-09-13 15:35
Cool thanks!
