### ISSUE TITLE
Polymorphic class with `@JsonUnwrapped` throwing "Unrecognized field" after upgrade to 2.18

### ISSUE THREAD

**Issue by martin-frydl** [FasterXML/jackson-databind#4792] opened 2024-11-11 12:34 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

I have following code:
```java
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonSubTypes.Type;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo.As;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.databind.ObjectMapper;

import static com.fasterxml.jackson.annotation.JsonProperty.Access.READ_ONLY;

class Test {
    @JsonTypeInfo(use = Id.NAME, include = As.PROPERTY, property = "name")
    @JsonSubTypes({
            @Type(value = SubA.class, name = "A"),
    })
    interface Parent {}

    static class SubA implements Parent {
        @JsonUnwrapped
        @JsonProperty(access = READ_ONLY)
        private Model model;

        @JsonCreator
        public SubA(@JsonProperty("model") Model model) {
            this.model = model;
        }
    }

    static class Model {
        @JsonProperty
        private double x;
    }

    public static class Wrapper {
        @JsonProperty
        private Parent model;
    }

    public static void main(String[] args) throws Exception {
        Wrapper w = objectMapper.readValue("{\"model\":{\"name\":\"A\",\"x\":10.0}}", Wrapper.class);
        System.out.println(((SubA)w.model).model.x);
    }
}
```
When run in 2.17.3, it works fine. However, in 2.18 it started to fail:
```
Unrecognized field "x" (class UnwrappedTest$SubA), not marked as ignorable (0 known properties: ])
```

### Version Information

2.18.0, 2.18.1

### Reproduction

<-- Any of the following
1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here
 -->
```java
// Your code here
``` 

### Additional context

Could be related to issue #1497 but is a bit different and worked before.

**Comment by JooHyukKim** [comment] 2024-11-11 13:31
Thank you for reporting @martin-frydl 🙏🏼

There is a chance this is regression caused by #4515.
As always, will submit failing test against 2.18.

**Comment by JooHyukKim** [comment] 2024-11-16 03:51
UPDATE : Did some hard digging into the difference made. So..

- In 2.17, Creator is registered via `BasicDeserializerFactory._constructDefaultValueInstantiator()` then `_handleSingleArgumentCreator()`. Later on the creator gets proper delegate deserializer to use.
- In 2.18, Creator is registered as property creator but is neither implicit or explicit and not used. Also has no delegate deser.

**Comment by cowtowncoder** [comment] 2024-11-16 04:01
I wonder if the issue are the annotation combination used: 

```
        @JsonUnwrapped
        @JsonProperty(access = READ_ONLY)
        private Model model;

        @JsonCreator
        public SubA(@JsonProperty("model") Model model) {
            this.model = model;
        }
```

I am suspicious of `READ_ONLY` in there; and placement of `@JsonUnwrapped`.
I am not 100% sure what the intent with `READ_ONLY` is. But moving `@JsonUnwrapped` to constructor parameter would seem to make sense ... in what none should be put on Field, I think.

**Comment by cowtowncoder** [comment] 2024-11-16 04:04
@JooHyukKim Single-arg constructor definitely should be considered properties-based (due to `@JsonProperty`), and explicit (for that plus `@JsonCreator`).
But it is definitely NOT delegating-one, so should not be added with `_addExplicitDelegatingCreators()`.

**Comment by JooHyukKim** [comment] 2024-11-16 04:07
Btw, changing `SubA` declaration like below works.

```java
    static class SubA implements Parent {
        private Model model;
        @JsonCreator
        public SubA(@JsonUnwrapped Model model) {
            this.model = model;
        }
    }
```

I think you are right about ...

> I am suspicious of READ_ONLY in there; and placement of @JsonUnwrapped.
> I am not 100% sure what the intent with READ_ONLY is. But moving @JsonUnwrapped to constructor parameter would seem to make sense ... in what none should be put on Field, I think.

... placement and `@JsonProperty` and all. 

We can also advise users to follow new usage if the usage is off or intended as long as we provide more documentation, then it would be fine.

**Comment by cowtowncoder** [comment] 2024-11-16 04:21
Ohhhhhhh. Now I get it -- because `@JsonUnwrapped` won't work until 2.19 (support is added via #1467), that's why DELEGATING is intended for deserialization.
But that can't work with `@JsonProperty` UNLESS `@JsonCreator(mode=Mode.DELEGATING)` specified. So that's one thing.

And then `@JsonUnwrapped` is indeed only meant for serialization.
So handling is asymmetric, if so.

So maybe what is attempted would work better with:

```
        @JsonUnwrapped
        private Model model;

        // Optionally can use @JsonCreator but not required
        public SubA() { }
```

if I finally understood intent correctly.

**Comment by JooHyukKim** [comment] 2024-11-16 05:03
So yeah @martin-frydl. What do u think?

**Comment by JooHyukKim** [comment] 2024-11-16 14:23
FYI @cowtowncoder , what I said above about working is in version **2.18**. Below declaration succeeds deserialization

```java
    static class SubA implements Parent {
        private Model model;
        @JsonCreator
        public SubA(@JsonUnwrapped Model model) {
            this.model = model;
        }
    }
```

**Comment by JooHyukKim** [comment] 2024-11-16 14:23
Anyway @martin-frydl  if you need "exactly same" declaration with `JsonProperty(READ_ONLY)` and all in 2.18, you need to modify `SubA` JsonCreator like below... just add `Mode.DELEGATING`.

```java
    static class SubA implements Parent {
        @JsonUnwrapped
        @JsonProperty(access = READ_ONLY)
        private Model model;

        @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
        public SubA(@JsonProperty("model") Model model) {
            this.model = model;
        }
    }
```

**Comment by cowtowncoder** [comment] 2024-11-17 04:07
@JooHyukKim Ah. I bet it works because property linking works when there's explicit `@JsonCreator`, and then creator annotation is available for Field -- and `@JsonUnwrapped` works for Fields in 2.18, no need for Constructor to be used.

At any rate, as long as we have a set of annotations (or maybe even alternatives), I don't see a bug to fix -- I think 2.17 handled it wrong (detection of mode for `@JsonCreator` should be `Mode.PROPERTIES` due to `@JsonProperty` annotation) and 2.18 fixed handling to expected. It is of course unfortunate that user was relying on this incorrect behavior (and understandably assumed it was intentional).
Still, at this point I think 2.18 handling is more along the lines of intended behavior.

**Comment by JooHyukKim** [comment] 2024-11-17 05:25
Ah I see, this issue ends up being `works-as-expected` then 
Plus reporter is MIA :)

**Comment by cowtowncoder** [comment] 2024-11-17 23:40
Closing as "work-as-intended" (will create label).

**Closed** 2024-11-17 23:41 UTC
Labels: will-not-fix, 2.18, works-as-intended
