### ISSUE TITLE
Jackson deserialising with static method argument

### ISSUE THREAD

**Issue by royjin** [FasterXML/jackson-databind#2790] opened 2020-07-09 11:08 UTC
I am reporting this issue when I migrate jackson from 2.9.0 to 2.11.0 along with spring boot upgrade.

I got following test cases passed when 2.9.0, but failed in 2.11.0

In the private static method, the argument is not deserialisable. Seems in 2.11.0, the private static method argument was scanned as property and tries to be deserialised? As long as I remove static it works but not occurred in 2.9.0

```
public class JacksonDeserTest {

    @Test
    public void test() throws Exception {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.readValue("{\"name\":\"test\"}", TestModel.class);
    }

    public static final class TestModel {

        private String name;

        public String getName() {
            return name;
        }

        public TestModel setName(String name) {
            this.name = name;
            return this;
        }

        private static String format(SomeNonDeserialisedClass action) {
            return action.call();
        }

    }
}
```

Please have a look.

Thank you

**Comment by cowtowncoder** [comment] 2020-07-18 20:18
@royjin I am not able to reproduce this issue: part of the problem is that I do not know what you mean by "non-deserializable" here? Also, you may want to try this with `2.11.1` to see if that makes a difference (I am testing against 2.11 branch, which also has some fixes beyond 2.11.1).

**Comment by royjin** [comment] 2020-07-26 06:48
@cowtowncoder thank you for reply. I think my point here is jackson tries to deserialise the "private static function argument", I also tried to 2.11.1, it did same thing but not happened on 2.8.11.

**Comment by cowtowncoder** [comment] 2020-07-26 22:36
@royjin My point is that I do not see anything wrong: test passes just fine. So you will need to point exactly what you think is going wrong,

**Comment by cowtowncoder** [comment] 2020-08-11 02:10
I unfortunately cannot reproduce the issue without a test case, closing. May be reopened with a reproduction.

**Closed by cowtowncoder** 2020-08-11 02:10 UTC
Labels: 2.11, need-test-case
