### ISSUE TITLE
Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil 

### ISSUE THREAD

**Issue by tomstachura** [FasterXML/jackson-databind#2820] opened 2020-08-15 14:23 UTC
I searched this and the issue was closed, but it's still happening.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil (file:/C:/Users/stachura/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.6.7.1/306775aeb5164835a1dcbdf3f945587045cfb3b5/jackson-databind-2.6.7.1.jar) to method java.lang.Throwable.setCause(java.lang.Throwable)
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.databind.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

context:

- kafka and kafka sdk 2.6.0 (scala 2.13 varient)
- Windows 10
- JDK 13
- all vanilla server configuration - no changes - just started zookeeper and kafka server
- string serializer on both the consumer and sender sides for both keys and values (just sending jsons using string)
- all messages are sent and received properly

Consumer setup

        final Properties properties = new Properties();
        properties.put( ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092" );
        properties.put( ConsumerConfig.GROUP_ID_CONFIG, "event-handlers" );
        properties.put( ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "false" );
        properties.put( ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest" );
        properties.put( ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName() );
        properties.put( ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName() );
        this.consumer = new KafkaConsumer<>( properties );

Sender setup

        final Properties properties = new Properties();
        properties.put( ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092" );
        properties.put( ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName() );
        properties.put( ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName() );
        this.producer = new KafkaProducer<>( properties );

**Comment by cowtowncoder** [comment] 2020-08-15 21:25
@tomstachura Unfortunatel there is quite literally no way for Jackson to prevent this in general -- there is no one thing, as it relates to access rights to types usually provided by JDK. Unfortunately message JDK gives is bit vague.

What can be done is to figure out specific value class(es) involved and either add handling or help user add annotations to prevent need for (de)serializer for value type.
This means that in every case we will need a full standalone reproduction to help: above code is unfortunately not enough to help. From exception alone I am guessing that warning is related to deserialization of an `Exception` but that's about it.

One thing I do notice, however, is that Jackson version 2.6(.7.1) is very old and has not received non-security-related fixes since 2016. 
If possible it would make sense to use a newer version like 2.10.5 or 2.11.2 -- it is possible that type(s) involved here have explicit handling now.

**Comment by cowtowncoder** [comment] 2020-09-25 16:53
Would need a reproduction (test case) to dig further, to see if this specific problem could be avoided (there is no general solution). Closing, may be reopened with a test case.

**Closed by cowtowncoder** 2020-09-25 16:53 UTC
Labels: JDK11, need-test-case
