### ISSUE TITLE
Non-cachable deserializers are still created in a single-threaded way

### ISSUE THREAD

**Issue by winitzki** [FasterXML/jackson-databind#1394] opened 2016-10-01 01:13 UTC
This is related to issues https://github.com/FasterXML/jackson-databind/issues/735 and https://github.com/FasterXML/jackson-databind/issues/604.

Deserializers are created and cached in `com.fasterxml.jackson.databind.deser.DeserializerCache#_createAndCacheValueDeserializer` within a `synchronized` block. The comment in that file explains that "Only one thread to construct deserializers at any given point in time; limitations necessary to ensure that only completely initialized ones are visible and used". In case the deserializer is not cachable, we do not need to lock the cache with the `synchronized` block; we can just create a new deserializer and return it. However, the code still creates a lock and calls `_createAndCache2`, which then checks whether the deserializer is cachable.

So, for a deserializer that is not cachable, the lock is created even though cache is not being updated, so no locking is needed.

The result of this is a multithreading lock contention for non-cachable deserializer. In scenarios where many threads are deserializing at once, this contention leads to severe degradation of performance.

This problem has been mitigated as of version 2.8.x by enabling more deserializers to be cached. However, if serializers are not cached (because they are custom serializers with complicated behavior), performance degradation due to unnecessary locking will still occur.

Perhaps it is possible to rearrange the logic in `DeserializerCache#_createAndCache2` and `DeserializerCache#_createAndCacheValueDeserializer` so that non-cachable deserializers are created without a global lock.

**Comment by cowtowncoder** [comment] 2016-10-02 03:20
Interesting. Yes, I agree that avoiding synchronization for non-cachable instances would make sense.

**Comment by cowtowncoder** [comment] 2016-10-05 05:41
Looking at the code, I am not overly optimistic about possibilities for rearranging. The problem is that cachability is only known at a rather late point (after locating/constructing said deserializer) and even without caching it is necessary to resolve recursive refefences (via `_incompleteDeserializers`).

**Comment by sandszhouSZ** [comment] 2020-07-03 00:16
@cowtowncoder  I faced the same Performance issues  with synchronized block when running many threads；

I think we should replace synchronized block with ThreadLocal;  
The perfomace doubled when I modify code locally.

**Comment by cowtowncoder** [comment] 2020-07-03 00:38
@sandszhouSZ most of the time the real problem is not this blocking, but rather question of why are deserializers not being cached: synchronization is only needed when creating deserializer for the first time. I am not sure how `ThreadLocal` would be applicable in this case either.

**Comment by sandszhouSZ** [comment] 2020-07-03 01:45
I have a case like this: the inputs are map nested map
![image](https://user-images.githubusercontent.com/41145333/86422824-c1fe0d00-bd10-11ea-8aa2-4dab2ba56d3f.png)

But because MapDeserializer.java will checking _valueTypeDeserializer == null, so every time the result will not be cached（though _valueTypeDeserializer may be the same）,
At the same time the creation is  high cost
![image](https://user-images.githubusercontent.com/41145333/86422902-0093c780-bd11-11ea-9e5f-3ac7060c1943.png)

so many thread blocking here
![image](https://user-images.githubusercontent.com/41145333/86423034-5bc5ba00-bd11-11ea-8282-291291f7f549.png)

i think maybe ThreadLocal will be a better choice just with Minimal memoery space overhead
final protected ThreadLocal<HashMap<JavaType, JsonDeserializer<Object>>> _incompleteDeserializers
 51             = ThreadLocal.withInitial(() -> new HashMap<JavaType, JsonDeserializer<Object>>(8));
 52     //final protected HashMap<JavaType, JsonDeserializer<Object>> _incompleteDeserializers
 53            // = new HashMap<JavaType, JsonDeserializer<Object>>(8);

**Comment by cowtowncoder** [comment] 2020-07-04 00:26
Depending on how your code is structured, use of `ObjectReader` would allow lookup of the main deserializer to be only done once and retained there, instead of attempting to find one from ObjectMapper global cache.

My concern with ThreadLocal approach really is that it seems to have a good chance of leading to unintentional memory retention (every thread will have `HashMap` on it -- granted, should be mostly empty), and could lead to bizarre problems with deserializer `resolve()` having its own local copy, yet some deserializers ending up in shared cache.
During heavy concurrent usage I would not trust this not to cause additional new failures that I would then be asked to troubleshoot.
This is why I am not particularly interested in considering this approach.

**Comment by cowtowncoder** [comment] 2024-12-12 02:19
Nothing actionable at this point, unfortunately: locking is required for resolving possible cyclic dependencies. Will close: may be re-filed with specific suggestions for change, reproduction to show performance problem or something else that is more specific than ask here.

**Closed by cowtowncoder** 2024-12-12 02:19 UTC
