### ISSUE TITLE
FileInpuStream created but not closed if an error occur.

### ISSUE THREAD

**Issue by willome** [FasterXML/jackson-databind#1743] opened 2017-08-21 10:02 UTC
This duplicate an issue opened on dataformats (https://github.com/FasterXML/jackson-dataformats-text/issues/29) but is sounds like this bug is not specific to CSV and should probably be fixed here.

- Jackson-dataformat-csv version 2.8.8

When using csvMapper.readValues(file), a new FileinputStream is created, but if an error occur during the parsing, this inputStream is never closed.

**Comment by cowtowncoder** [comment] 2017-09-07 02:26
I don't really know if or how this should be changed -- catching exceptions and automatically closing adds complexity and often leads to odd problems if `close()` can throw exceptions.

However... since `MappingIterator` is a `Closeable` (which extends `AutoCloseable`), would it not be possible to use it with Java 7 `try` block? Something like:

```java
try (MappingIterator<T> it = mapper.readValues(file)) {
    // iterate and handle
}
```

which would guarantee that iterator is closed, which will close underlying `FileInputStream`.

**Comment by cowtowncoder** [comment] 2018-07-17 23:21
As per my earlier comments, I don't think automatic closing on error is feasible for iterators -- caller needs to, instead, either create and manage streams OR ensure `close()` is called.

**Comment by JohnDuncanScott** [comment] 2019-09-20 11:04
Sorry if I've misunderstood something here, but closing the iterator doesn't seem to close the stream. I'm using 2.9.3.

I have this test:
```
    @Test
    void createFromInputStreamClosesStream() throws IOException {
        InputStream inputStreamSpy = Mockito.spy(IOUtils.toInputStream("a,b,c,0.0", StandardCharsets.UTF_8.name()));

        factory.create(inputStreamSpy);

        verify(inputStreamSpy).close();
    }
```
and this code:
```
private static final CsvMapper CSV_MAPPER = new CsvMapper();
...
create(InputStream inputStream) {
        try (MappingIterator<CsvLine> csvLines =
                CSV_MAPPER.readerWithSchemaFor(CsvLine.class).readValues(inputStream)) {

            val builder = DataSource.builder();

            while (csvLines.hasNext()) {
                CsvLine csvLine = csvLines.next();
                builder.addData(csvLine.getA(), new DataItem(csvLine.getB(), csvLine.getC(), csvLine.getD()));
            }

            return builder.build();
        } catch (IOException ex) {
            throw new IllegalArgumentException("Could not read from input stream", ex);
        } finally {
//            try {
//                inputStream.close();
//            } catch (IOException ex) {
//                throw new IllegalArgumentException("Could not close input stream", ex);
//            }
        }
}
```

If the close() block at the bottom is left commented out, the test fails (i.e. the try-with-resources block doesn't seem to close the underlying InputStream passed into the function even though the MappingIterator will have been closed). The error message indicates that the stream was indeed used, but close() was never called. If I explicitly call close() by uncommenting the finally block, then the test passes as expected.

Have I missed something obvious here? The behaviour seems a little confusing.

**Comment by willome** [comment] 2019-09-20 12:29
@JohnDuncanScott I agree with you: closing the iterator does not seem to close the Stream. It should be manually/forced closed.

**Comment by JohnDuncanScott** [comment] 2019-09-20 14:31
Is that then technically a bug with the iterator internals? Shouldn't the MappingIterator close the stream if it's been closed itself?

**Comment by cowtowncoder** [comment] 2019-09-20 17:37
`MappingIterator`s close() method should close underlying parser, I think. Whether that gets propagated to underlying stream depends on couple of things: when Jackson itself creates stream, yes, always; but if given `InputStream`, it depends on `JsonParser.Feature.AUTO_CLOSE_SOURCE`: if enabled, yes, if disabled no.

In this particular case, there is one more open question: is this specific to CSV format module or not. There are some special cases in that particular one, for supporting some lenience (error recovery). If it is, this would need to be moved to `jackson-dataformats-text`; otherwise leaving here is fine.
In addition, it is important to include version this occurs in (ideally verifiable with `2.10.0.pr3` or whatever is latest at the time).

**Comment by JohnDuncanScott** [comment] 2019-09-26 13:58
Sorry if it got lost in the comment, it states at the top of the test that "2.9.3" is being used in my particular case: https://github.com/FasterXML/jackson-dataformats-text/tree/master/csv (it's latest the business has approved).

**Comment by cowtowncoder** [comment] 2019-09-27 01:23
Ok. I missed the version part. Ideally I'd just like verification that it still also fails in 2.10 (or not), as that would save time: I will not attempt reproduction on 2.9 since at this point it is unlikely that fix (if one possible) would be backported in 2.9.

But CSV vs JSON still stands: if this can be reproduced with JSON content, issue should remain here: if not, then CSV.

**Comment by cowtowncoder** [comment] 2020-04-02 05:31
Would need a reproduction: closing, may be reopened with one.

**Closed by cowtowncoder** 2020-04-02 05:31 UTC
