### ISSUE TITLE
Polymorphic deserialization with `EXTERNAL_PROPERTY` fails if type property not marked as property

### ISSUE THREAD

**Issue by prtmD** [FasterXML/jackson-databind#1527] opened 2017-02-13 14:12 UTC
I have class as follows

```
class XYZ {
    private String type;

    private TypeSpecific typeSpecific;

    public TypeSpecific getTypeSpecific() {
        return typeSpecific;
    }

    @JsonTypeInfo(
		use = JsonTypeInfo.Id.NAME, 
		include = JsonTypeInfo.As.EXTERNAL_PROPERTY, 
		property = "type"			
		)
    @JsonSubTypes({		
		@JsonSubTypes.Type(value = ATypeSpecific.class, name = "a")
    })
    public void setTypeSpecific(TypeSpecific typeSpecific) {
        this.typeSpecific = typeSpecific;
    }
}
```
Class ATypeSpecific extends TypeSpecific.

I want to deserialize JSON
`{"type":"b"}`
where typeSpecific will be set as null in object. But I am getting following exception:
```
com.fasterxml.jackson.databind.JsonMappingException: Missing property 'typeSpecific' for external type id 'type'
```

How do I deserialize above mentioned JSON into the object? If @JsonTypeInfo requires 'typeSpecific' property during deserialization, then is there a way to add it into JSON before deserialization?

Dependency versions:
jackson-annotations: 2.7.0
jackson-core: 2.7.4
jackson-databind: 2.7.4

**Comment by cowtowncoder** [comment] 2017-02-13 20:32
First things first, try with the latest patch from the batch in question: in this case, 2.7.9.
Does the process still occur?

**Comment by prtmD** [comment] 2017-02-14 06:26
I tried with latest patch, that is 2.7.9 and also with latest version of jackson-databind 2.8.6. But it is not working still.

**Comment by oliversaggau** [comment] 2017-05-11 15:56
Any updates on this issue? I just tested with 2.8.8 and 2.9.0-pr3, but this still throws an exception. I found an old post on [Stackoverflow](http://stackoverflow.com/questions/28089484/deserialization-with-jsonsubtypes-for-no-value-missing-property-error) with the same issue.

**Comment by cowtowncoder** [comment] 2017-05-11 18:58
The problem here is this:

```java
    private String type;
```

as there is no indication that this field is supposed to infer a property: it is `private` and has no annotations. It needs to be marked as a property; just indicating there should be one from polymorphic type id annotation is not enough.

Whether this should work without annotation is an interesting question: I can see why it would be nice; the problem however is that the way properties are introspected there is likely not enough information available to add inclusion.

**Comment by oliversaggau** [comment] 2017-05-12 09:04
Ah ok, hadn't noticed the missing `@JsonProperty` in the OP's code. In my code I have the following code:
```
@JsonProperty("type")
private String type;
```
And I event tried adding `@JsonTypeId`, but both won't work.

**Comment by cowtowncoder** [comment] 2017-05-12 17:50
@oliversaggau Ok, then there seems to be some other problem.

**Comment by buremba** [comment] 2018-05-06 12:29
Any updates on this issue? If `TypeSpecific` marked as not required, there is no requirement for Jackson to try to parse the value of it.

**Comment by cowtowncoder** [comment] 2018-05-07 00:15
@buremba Well the problem is that there IS a type identifier in there, and from databinding perspective it seems like a problem -- what is that type id for? Nothing? Why would something or someone serialize type without data being typed?

So in a way I am not sure if that ought to be allowed.

**Comment by buremba** [comment] 2018-05-07 09:52
@cowtowncoder The type id may be useful by itself so don't assume that type id is there just for deserializing another value. For example, here is our use-case:
We have reports and each report has a type. Depending on that type, each report has options and we use different classes for different report types. We also have two different endpoints in our API server; list and get. The list reports the report names and types but not options because we just need to list the reports in a table. When the user clicks a report, we fetch the options from the server and return the data to the user.

**Comment by cowtowncoder** [comment] 2018-05-07 22:14
@buremba Ok. That makes some more sense. Although I am bit worried about potential for masking issues, I guess I can see this as valid usage esp as there is no way to indicate difference like with `PROPERTY` vs `EXISTING_PROPERTY` (former implying its pure metadata, latter that it is explicit data also used as metadata).

**Comment by cowtowncoder** [comment] 2018-05-08 03:44
Oh. I had forgotten that as per #1341 (and mentioned above), `DeserializationFeature.FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY` can be disabled to allow such value to be missed (unless declared `required`).
So, @buremba, you want to disable that.

**Closed by cowtowncoder** 2018-05-08 03:44 UTC
Labels: 2.9, ACTIVE

**Comment by buremba** [comment] 2018-05-11 19:17
@cowtowncoder Unfortunately that doesn't work. I enabled the config `DeserializationFeature.FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY` but still get the error `Missing property 'options' for external type id 'type'`. I use Kotlin, Jackson 2.8.9 and the exception is thrown from `ExternalTypeHandler` class and line `211`. Hope it helps and please reopen the issue. :)

**Comment by cowtowncoder** [comment] 2018-05-11 23:26
@buremba Ok. In that case I would need a reproduction of the problem (in plain Java) since test for #1341 passes as expected at this point.
