### ISSUE TITLE
Cannot deserialize large objects (> 10mb) causes MismatchedInputException

### ISSUE THREAD

**Issue by sarbajitdutta** [FasterXML/jackson-databind#2907] opened 2020-10-28 17:45 UTC
**Describe the bug**
Cannot deserialize large objects (> 10mb) causes MismatchedInputException. If the object size is less than 10mb there is no error it can deserialize and store it in dynamodb. I have tested with all other objects from small to medium size (< 10mb) and it works. As soon as the object size increases it causes the exception.
Error is  - 
```
2020-10-28 13:52:46.824  INFO 22651 --- [nio-5000-exec-1] c.a.http.JsonErrorResponseHandler        : Unable to unmarshall exception content
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException` out of NOT_AVAILABLE token
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468) ~[jackson-databind-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242) ~[jackson-databind-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1190) ~[jackson-databind-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:203) ~[jackson-databind-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166) ~[jackson-databind-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4495) ~[jackson-databind-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2728) ~[jackson-databind-2.11.2.jar:2.11.2]
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3181) ~[jackson-databind-2.11.2.jar:2.11.2]
        at com.amazonaws.transform.JsonErrorUnmarshaller.unmarshall(JsonErrorUnmarshaller.java:61) ~[aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.JsonErrorResponseHandler.doLegacyUnmarshall(JsonErrorResponseHandler.java:185) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.JsonErrorResponseHandler.unmarshallException(JsonErrorResponseHandler.java:147) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.JsonErrorResponseHandler.createException(JsonErrorResponseHandler.java:131) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:94) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:40) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:58) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:45) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:27) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1810) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1412) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1374) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) [aws-java-sdk-core-1.11.884.jar:na]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:5177) [aws-java-sdk-dynamodb-1.11.884.jar:na]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:5144) [aws-java-sdk-dynamodb-1.11.884.jar:na]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeUpdateItem(AmazonDynamoDBClient.java:4760) [aws-java-sdk-dynamodb-1.11.884.jar:na]
```

**Version information**
2.11.2
Using jackson-bom.

**To Reproduce**
If you have a way to reproduce this with:
I have attached the object which is causing problem.
The object data model is in maven. Use it.
```
<!-- https://mvnrepository.com/artifact/edu.cornell.weill.reciter/reciter-dynamodb-model -->
<dependency>
    <groupId>edu.cornell.weill.reciter</groupId>
    <artifactId>reciter-dynamodb-model</artifactId>
    <version>2.0.5</version>
</dependency>
```

Affected piece of code - 
```
@Override
	public void save(AnalysisOutput analysis) {
		try{
			analysisOutputRepository.save(analysis);// This is the line where it fails
		} catch(Exception addbe) {
			if(isS3Use && !isDynamoDbLocal) {
				log.info("Storing item in s3 since it item size exceeds more than 400kb");
				ddbs3.saveLargeItem(AmazonS3Config.BUCKET_NAME, analysis.getReCiterFeature(), AnalysisOutput.class.getSimpleName() + "/" + analysis.getUid());
				analysis.setReCiterFeature(null);
				analysis.setUsingS3(true);
				analysisOutputRepository.save(analysis);
			} else if(isDynamoDbLocal){
				log.info("You are running dynamodb in local mode. Add AWS access key and secret key to environment variable to enable S3 storage.");
			} else {
				log.info("Enable s3 use in application properties file to store larger objects. Set aws.s3.use to true and set aws.s3.dynamodb.bucketName");
			}
			
		}
	}
```

**Expected behavior**
The object should successfully deserialize irrespective of its size.
[chr9093.json.zip](https://github.com/FasterXML/jackson-databind/files/5453893/chr9093.json.zip)

**Comment by cowtowncoder** [comment] 2020-10-28 19:44
Jackson has no restrictions based on size, so please first figure out what is happening with the client library that uses Jackson.

**Comment by cowtowncoder** [comment] 2020-11-25 00:38
Seems unlikely that this is due to Jackson itself, closing; may be reopened with a reproduction.

**Closed by cowtowncoder** 2020-11-25 00:38 UTC
Labels: need-test-case
