### ISSUE TITLE
JSON deserialization with malformed JSON

### ISSUE THREAD

**Issue by sokie** [FasterXML/jackson-databind#1494] opened 2017-01-10 12:22 UTC
On a REST api i receive a Json that gets mapped to a Java Object:
```java
@RequestMapping(value = "/example", method = RequestMethod.POST)
    public @ResponseBody
    ReturnObject doReturn(@RequestBody ProblemObject requestBody)
```
The object is simple:
```java
public class ProblemObject implements Serializable {

    private String field1;
    private String field2;

   //This appears to create problems, removing this Jackson throws exception correctly!!
   public ProblemObject(String field2) {
       this.field2 = field2;
   }

   public ProblemObject(String field1, String field2) {
       this.field1 = field1;
       this.field2 = field2;
   }
}
```
The problem is Jackson tries to deserialize a malformed JSON, with not so good results:

```json
 "field1": "test",
 "field2": "test"
}
```
notice no opening brace. This causes the object to get mapped with field1 having a value of "field1" and field2 being null.
Doing any other changes throws correctly an exception ( removing comma, removing close brace, ecc ). The only problem is with the opening brace.
Jackson version **2.8.1**

Example project:
[jackson_json_mapping.zip](https://github.com/FasterXML/jackson-databind/files/698740/jackson_json_mapping.zip)
JSON to send:
```json
"field1": "test",
 "field2": "test2"
}
```

**Comment by cowtowncoder** [comment] 2017-01-11 19:05
Interesting. I agree, such JSON content should result in an exception.

**Comment by sokie** [comment] 2017-01-12 12:29
@cowtowncoder a small but IMPORTANT detail, if I remove all constructors from the POJO, Jackson behaves correctly. The 1 string constructor sets this off.

**Comment by cowtowncoder** [comment] 2017-01-13 21:12
Ah! So this is quite likely related to buffering; `TokenBuffer` does not (for example) require well-formedness of contents. It should not prevent exception, but probably does currently.

**Comment by beeva-juanmanuelperez** [comment] 2017-02-14 16:40
Hello. I have a similar issue... following sokie's example, if you try to deserialize a valid JSON with any arbitrary content after the closing brace, no exception is thrown and it is deserialized correctly. 

```
ObjectMapper mapper = new ObjectMapper();
        ProblemObject value = mapper.readValue("{\"field1\":\"test\", \"field2\":\"test2\"}Whatever you type after closing brace is ignored{}{{{}}}{{}{{}}{{}{}}}}}", ProblemObject.class);

```

**Comment by cowtowncoder** [comment] 2017-02-14 17:54
@beeva-juanmanuelperez That is different and by design: only enough content is read to tokenize a full value. There is another RFE to add support for consuming whole input, and in that case exception would be thrown. Until then if you do want to verify if there's trailing content you need to construct `JsonParser` separately, pass it to readValue(), and then manually advance parser and verify that `nextToken()` returns `null` -- if not (or throws parse exception), you can indicate error.

**Comment by beeva-juanmanuelperez** [comment] 2017-02-15 07:09
Thank you very much for your support, cowtowncoder. I will try that.

Kind regards.

**Comment by cowtowncoder** [comment] 2017-03-29 04:26
@sokie Ah. Ok... I can see the problem here: parser only sees a JSON String value first -- "field1" -- and since it tokenizes minimal piece, it does not get to problematic part of ':', at which point it is not legal. And as constructor: there is implicit auto-detection of single-String-arg constructors, so what happens is that since parser consider String to be the full JSON Value, and since there is a constructor, it gets called.

So... my first guess about `TokenBuffer` was irrelevant here. In fact what is needed is the RFE that requires the whole input to be bound into value: if so the parsing problem would be uncovered, even if not immediately.

I'll see if I can locate the other issue; or if it doesn't exist, create one.

**Comment by cowtowncoder** [comment] 2017-03-30 04:40
Created #1583 to cover improvement idea since I was unable to locate existing issue.

**Closed by cowtowncoder** 2017-03-30 04:40 UTC
