### ISSUE TITLE
EXTERNAL_PROPERTY never gets deserialized

### ISSUE THREAD

**Issue by benson-basis** [FasterXML/jackson-databind#1271] opened 2016-06-17 17:39 UTC
The branch named 'fiddle' in git@github.com:benson-basis/jackson-custom-mess-tc.git shows another wrinkle: an EXTERNAL_PROPERTY of class value with a @JsonValue annotation is deserialized to null.

https://github.com/FasterXML/jackson-databind/issues/1270

**Comment by cowtowncoder** [comment] 2016-06-17 20:12
I don't know if it is impossible to make `@JsonValue` work with polymorphic types, but it's certainly challenging and error prone. This because serialization would need to handle things apart: type information for "source" Java object, but content to serialize being of different actual type.
Combining this with external property I am not surprised it might not work.

**Comment by benson-basis** [comment] 2016-06-17 20:41
I'm pretty sure I can see the failure even without JsonValue.

The type id resolution is working fine ... the problem is that the value
from the ext property gets lost on the way to its eventual home.

**Comment by benson-basis** [comment] 2016-06-17 21:20
The branch databind-1271 now demonstrates this without any use of JsonValue. The property called out as the EXTERNAL_PROPERTY is null after deserialization, even though was read and supplied to the type id resolver.

**Comment by cowtowncoder** [comment] 2016-06-20 06:08
Ok yes, I can reproduce this. Addition of `visible=true` makes no difference, the only thing I tried so far.

**Comment by cowtowncoder** [comment] 2016-06-21 05:15
Digging into this, no clear solution, but looking at existing failing tests seems like this might be same as #999.

**Comment by cowtowncoder** [comment] 2016-06-22 06:00
Duplicate of #999, resolved by same fix, to be included in 2.8.0 (or 2.8.0.rc3 if one more rc was to be released).

**Closed by cowtowncoder** 2016-06-22 06:00 UTC
