### ISSUE TITLE
Attempting to set a custom date within a bean serializer no longer works on 2.6.x.

### ISSUE THREAD

**Issue by nosachamos** [FasterXML/jackson-databind#968] opened 2015-10-12 17:16 UTC
In one of my apps a custom bean serializer needs to change the date format used to serialize it's content during runtime. This is done like so:

```
public void serialize(ResponseWrapper responseWrapper, JsonGenerator jgen,
        SerializerProvider provider) throws IOException, JsonProcessingException {

    ObjectCodec codec = jgen.getCodec();
    ObjectMapper mapper;
    if (codec instanceof ObjectMapper) {
        mapper = (ObjectMapper)codec;         
    } else {
        // this should never happen
        throw new IllegalStateException("Object codec is not of expected type.");
    }

    DateFormat sdf = ...

    ObjectMapper configuredMapper = mapper.copy();
    configuredMapper.setDateFormat(sdf);

    jgen.setCodec(configuredMapper);

    jgen.writeStartObject();
    jgen.writeObjectField(fieldName, body);
    jgen.writeEndObject();

    ...
}
```

That body object is a Map with string keys which contains a Date value that needs to be serialized according to the given custom date format configured on the ObjectMapper we set as the codec.

It worked fine on 2.5.1 and 2.5.4, but after upgrading to 2.6.2 it no longer works. I debugged this, and the SerializerProvider has the correct config in it, which contains the correct date format. However, the DateSerializer used to serialize the value has a null _customFormat field which is never configured to use the date format in the SerializerProvider's config.

**Comment by cowtowncoder** [comment] 2015-10-12 17:56
Ok. I don't know what causes this (hope to look), but I would suggest changing the code a bit: the reason being that constructing a new `ObjectMapper` instance is very expensive.
But fortunately you shouldn't have to here, even if you'd like to use the approach you are using.

Instead of using mapper, I would suggest using an `ObjectWriter`, as creating and reconfiguring them has low overhead. You should be able to do something like:

```java
jgen.writeStartObject();
jgen.writeFieldName(fieldName);
ObjectWriter w = mapper.writer()
    .with(sdf) // and any other (re)configuration you want
    .writeValue(jgen, body);
jgen.writeEndObject();

```

and I think this should both work, and be significantly more efficient in doing that.

**Comment by nosachamos** [comment] 2015-10-13 03:33
@cowtowncoder awesome! Quick question on using the objectwriter: is there an aquivalent to the objectmapper's `setSerializationInclusion(...);` method?

I need to configure that during serialization as well, and was using that copied object mapper. But if there is a way to do that directly with an objectwriter than I'm golden!

**Comment by cowtowncoder** [comment] 2015-10-13 04:50
Unfortunately no; this setting can not be dynamically changed as it changes how actual serializers are constructed, serializers are cached, and not recreated during lifetime of `ObjectMapper` (or `ObjectReader`s and `ObjectWriter`s it creates).

If you need that, then you actually need a new `ObjectMapper` with all the associated costs.

**Comment by nosachamos** [comment] 2015-10-13 19:04
I actually found interesting that replacing new instantiations of ObjectMapper by configurations on the ObjectWriter gave me no performance gain at all. On a total of about 30.000 operations, the result time is exactly the same. Maybe I'm I/O bound, but still, I'd expect to see at least a tiny gain but saw none. Updating here just as a curiosity, performance is not an issue for me at this time.

**Comment by cowtowncoder** [comment] 2015-10-14 04:44
It should give significant performance boosts, as difference between reuse of `ObjectMapper` and creating new instance can cause difference of about 100x (I have benchmarked this); although this depends on size of JSON object being processed (more fixed overhead for small data).
So there would be something quite odd going on. The only case where difference might be less prominent would be if annotation-processing was disabled.

Anyway: if you do need to create a new instance, and performance is not a problem, then that's the way to go. Correctly functioning code is the first thing. :)

**Comment by cowtowncoder** [comment] 2015-11-06 04:12
Would still be interested in knowing if there is something wrong with respect to setting of date format; but closing now since I can not reproduce the issue.

**Closed by cowtowncoder** 2015-11-06 04:12 UTC
