### ISSUE TITLE
JsonCreator in Enums issues (allow JSON integer to be passed to `String` creator)

### ISSUE THREAD

**Issue by BigMichi1** [FasterXML/jackson-databind#2777] opened 2020-06-27 12:20 UTC
after #2725 was finally resolved and released with 2.11.1 I had another try to upgrade from 2.10.4, as far as I have seen and tested it map keys are now working quite well but the upgrade broke the "normal" JsonCreator behaviour from 2.10.4 in enums. 

It is quite hard to explain under which conditions it works and it doesn't but I was able to create one reproduced for the issue:

```java
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Stream;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class JacksonVersionEnumUTest {
    public enum Foo {
        BAR(1), BAR2(2);

        private final long id;

        Foo(final long id) {
            this.id = id;
        }

        @JsonValue
        public long getId() {
            return id;
        }

        @JsonCreator
        public static Foo getByString(final String id) {
            return Stream.of(values()).filter(p -> Objects.equals(id, p.name())).findFirst().orElseGet(() -> getByLong(Long.parseLong(id)));
        }

        // @JsonCreator
        public static Foo getByObject(final Object id) {
            return getByString(id.toString());
        }

        // @JsonCreator
        public static Foo getByLong(final Long id) {
            return Stream.of(values()).filter(p -> p.id == Long.parseLong(id.toString())).findFirst().orElse(null);
        }
    }

    static class FooBar {
        private Map<Foo, String> fooStringMap;

        public Map<Foo, String> getFooStringMap() {
            return fooStringMap;
        }

        public void setFooStringMap(final Map<Foo, String> fooStringMap) {
            this.fooStringMap = fooStringMap;
        }

        @Override
        public String toString() {
            return "FooBar{" +
                    "fooStringMap=" + fooStringMap +
                    '}';
        }
    }

    // These tests are failing currently
    // with 2.10.4 because of a non working map deserialization
    // with 2.11.1 map deserialization is working but multiple creators are still not supported
    // multiple JsonCreators inside an enum are not considered as only on creator will be used for all creations
    // (cached and also inspection stops when the first one is found) order of the methods is not deterministic
    public static void main(@Nonnull final String[] args) throws JsonProcessingException {
        final ObjectMapper mapper1 = new ObjectMapper();
        final Foo foo1 = mapper1.readValue("1", Foo.class);
        System.out.println(foo1);

        final ObjectMapper mapper2 = new ObjectMapper();
        final Foo foo2 = mapper2.readValue("\"2\"", Foo.class);
        System.out.println(foo2);

        final ObjectMapper mapper3 = new ObjectMapper();
        final Foo foo3 = mapper3.readValue("\"BAR2\"", Foo.class);
        System.out.println(foo3);

        final HashMap<Foo, String> fooStringMap = new HashMap<>();
        fooStringMap.put(Foo.BAR, "Hello");
        fooStringMap.put(Foo.BAR2, "Hello");
        final FooBar fooBar = new FooBar();
        fooBar.setFooStringMap(fooStringMap);
        final ObjectMapper mapper4 = new ObjectMapper();
        final String fooBarJson = mapper4.writeValueAsString(fooBar);
        final ObjectMapper mapper5 = new ObjectMapper();
        final FooBar fooBar1 = mapper5.readValue(fooBarJson, FooBar.class);
        System.out.println(fooBar1);
    }
```

it would be nice if the original behaviour from 2.10.4 can be restored somehow plus also getting the map keys working as it is now with 2.11.1

**Comment by cowtowncoder** [comment] 2020-06-27 21:18
First things first: multiple `@JsonCreator`s are not and have never been supported for Enums, same way as they are supported for POJOs. While there is no technical reason this could not be supported, it would require new functionality.
I do not think 2.10.4 supported that, although it seems that due to interesting interaction between `JsonParser` actions some coercions worked (specifically I think numbers were converted implicitly into `String`)s.

One thing that might allow things to work is to use "untyped" Creator, which is hinted by code above: nominal type of `java.lang.Object` could map all JSON values through their natural mappings (`Number`, `String`, `Boolean`, `Map`, `List`).
Or, possible more convenient alternate would be to use `JsonNode` as argument: this is tested in `EnumCreatorTest` (type `EnumWithDelegateModeJsonCreator`)

**Comment by BigMichi1** [comment] 2020-06-28 05:51
thats interesting that it worked by "accident".

So it means for 2.11.1 (assuming only one ``JsonCreator`` is allowed to be used):
- when ``Object`` is used as an argument type everthing works
- when ``JsonNode`` is used as an argument type everthing works
- when ``Long`` is used a ``String`` can not be used anymore while in 2.10.4 it was calling the ``String`` creator
- when ``String`` is used as an argument type the normal deserialization doesn't work anymore as it sends a number to the method

any chance to restore the behaviour from 2.10.4 when a ``Number`` is deserialized that it will call a ``String`` creator?

**Comment by cowtowncoder** [comment] 2020-06-29 18:14
Ah. Hmmh. This is interesting case; 2.12 will add CoercionConfigs system to allow configuring these aspects, which up to 2.11 are implicit (although with some patchwork of global Features to try to disable).
Most of my work so far has been to make String->Number/Boolean coercions explicit, but I haven't put much thought to Number->String, which for most purpose has been allowed (at least for `String` valued properties).

So I think such coercion should indeed work for Enums, especially given that only one Creator is processed.
With that, I think I agree that:

* In 2.11, `String` taking Creator for Enums SHOULD accept JSON Integer number values too
* In 2.12, this coercion would check CoercionConfigs, defaulting to "allow".

Does this make sense?

**Comment by cowtowncoder** [comment] 2020-06-29 18:20
Hmmh. Just one potential blocker: unfortunately Enums already have definition of how to use Integers: as serialization of index. So I am not so sure coercion makes sense after all. Rather it may be better to consider supporting at least 2 creators (if not full `ValueInstantiator` approach that would consider everything POJOs do).

**Comment by BigMichi1** [comment] 2020-06-30 05:52
> Ah. Hmmh. This is interesting case; 2.12 will add CoercionConfigs system to allow configuring these aspects, which up to 2.11 are implicit (although with some patchwork of global Features to try to disable).
> Most of my work so far has been to make String->Number/Boolean coercions explicit, but I haven't put much thought to Number->String, which for most purpose has been allowed (at least for `String` valued properties).
> 
> So I think such coercion should indeed work for Enums, especially given that only one Creator is processed.
> With that, I think I agree that:
> 
> * In 2.11, `String` taking Creator for Enums SHOULD accept JSON Integer number values too
> * In 2.12, this coercion would check CoercionConfigs, defaulting to "allow".
> 
> Does this make sense?

makes sense, I would say ``String`` is some kind of fallback for everything in that case as also the ``BasicDeserializerFactory`` for enum keys is checking for a creator with a ``String`` argument, so it means ``String`` is an expected type anyway

**Comment by cowtowncoder** [comment] 2020-10-27 04:11
After thinking about this a bit I don't think allowing JSON number to go via `String` creator is something I would want to explicitly support, as that seems bit too risky considering that there is more established mapping of integers to Enum index. It is unfortunate, in hindsight, that 2.11.x patch change the behavior here, but I think change would have made sense for 2.12, considering that support was incidental and not by design.

I would be open to other improvements, such as allowing multiple creators (specifically, one for `int`, other for `String`), but will close this particular issue.

**Closed by cowtowncoder** 2020-10-27 04:11 UTC
Labels: 2.11
