### ISSUE TITLE
no added  @JsonFilter("baseFilter") globally filter the fields I don't want

### ISSUE THREAD

**Issue by authub** [FasterXML/jackson-databind#3720] opened 2022-12-27 09:55 UTC
I did the following test, is it possible without adding  @JsonFilter("baseFilter") get the result I expected

```java

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationConfig;
import com.fasterxml.jackson.databind.ser.impl.SimpleBeanPropertyFilter;
import com.fasterxml.jackson.databind.ser.impl.SimpleFilterProvider;
import lombok.Data;
import lombok.SneakyThrows;
import org.junit.jupiter.api.Test;

import java.util.Date;
import java.util.UUID;


public class JacksonIgnoreFieldTest {
    private static String[] IGNORE_FIELD = {"delFlag", "createBy", "createTime"};
    private static SimpleBeanPropertyFilter MY_FILTER = SimpleBeanPropertyFilter.serializeAllExcept(IGNORE_FIELD);

    private static ObjectMapper objectMapper() {
        return new ObjectMapper();
    }

    @SneakyThrows
    @Test
    public void serializationConfigTest() {
        ObjectMapper mapper = objectMapper();
        SerializationConfig serializationConfig = mapper.getSerializationConfig().withFilters(new SimpleFilterProvider().setDefaultFilter(MY_FILTER));
        mapper.setConfig(serializationConfig);
        User user = new User();
        System.err.println(mapper.writeValueAsString(user));
        // expect: {"userId":"9f452b3a-5962-45a9-b16c-e5cb92c3baf1_userId","userName":"fa566a27-f855-4c21-9dda-2b48590f0944_userName"}
        // actual: {"userId":"9f452b3a-5962-45a9-b16c-e5cb92c3baf1_userId","userName":"fa566a27-f855-4c21-9dda-2b48590f0944_userName","delFlag":"0","createBy":"cf6cfb21-5f14-4b4a-8268-f453ce991fdb_createBy","createTime":1672133883455}
    }

    @SneakyThrows
    @Test
    public void writerFilterProviderDefaultFilter() {
        ObjectMapper mapper = objectMapper();
        mapper.writer(new SimpleFilterProvider().setDefaultFilter(MY_FILTER));
        User user = new User();
        System.err.println(mapper.writeValueAsString(user));
        // expect: {"userId":"9f452b3a-5962-45a9-b16c-e5cb92c3baf1_userId","userName":"fa566a27-f855-4c21-9dda-2b48590f0944_userName"}
        // actual: {"userId":"9f452b3a-5962-45a9-b16c-e5cb92c3baf1_userId","userName":"fa566a27-f855-4c21-9dda-2b48590f0944_userName","delFlag":"0","createBy":"cf6cfb21-5f14-4b4a-8268-f453ce991fdb_createBy","createTime":1672133883455}
    }

    @SneakyThrows
    @Test
    public void addFilterAddAnnotation() {
        ObjectMapper mapper = objectMapper();
        mapper.setFilterProvider(new SimpleFilterProvider().addFilter("baseFilter", MY_FILTER));
        Role role = new Role();
        System.err.println(mapper.writeValueAsString(role));
        // expect: {"roleId":"313cb8b2-0568-410c-b987-2e4f6e5e3cfb_roleId","roleName":"cb88e09f-2b49-4544-be7d-beea9187c2b0_roleName"}
        // actual: {"userId":"2000c23d-c9f0-42f5-b599-263a1b5e41ff_userId","userName":"c9a221f2-1b5a-4ebf-bba2-8119878c32a4_userName","delFlag":"0","createBy":"7d4fc42c-461a-42b1-ad3d-5f3a2dfb0215_createBy","createTime":1672134420799}
    }

    @SneakyThrows
    @Test
    public void addFilterNoAnnotation() {
        ObjectMapper mapper = objectMapper();
        mapper.setFilterProvider(new SimpleFilterProvider().addFilter("baseFilter", MY_FILTER));
        User user = new User();
        System.err.println(mapper.writeValueAsString(user));
        // expect: {"userId":"9f452b3a-5962-45a9-b16c-e5cb92c3baf1_userId","userName":"fa566a27-f855-4c21-9dda-2b48590f0944_userName"}
        // actual: {"userId":"2000c23d-c9f0-42f5-b599-263a1b5e41ff_userId","userName":"c9a221f2-1b5a-4ebf-bba2-8119878c32a4_userName","delFlag":"0","createBy":"7d4fc42c-461a-42b1-ad3d-5f3a2dfb0215_createBy","createTime":1672134420799}
    }

    @Data
    public static class User {

        private String userId;
        private String userName;
        private String delFlag;
        private String createBy;
        private Date createTime;

        public User() {
            userId = UUID.randomUUID() + "_userId";
            userName = UUID.randomUUID() + "_userName";
            delFlag = "0";
            createBy = UUID.randomUUID() + "_createBy";
            createTime = new Date();
        }
    }

    @Data
    @JsonFilter("baseFilter")
    public static class Role {
        private String roleId;
        private String roleName;
        private String delFlag;
        private String createBy;
        private Date createTime;

        public Role() {
            roleId = UUID.randomUUID() + "_roleId";
            roleName = UUID.randomUUID() + "_roleName";
            delFlag = "0";
            createBy = UUID.randomUUID() + "_createBy";
            createTime = new Date();
        }

    }

}

```

**Comment by cowtowncoder** [comment] 2023-01-07 02:06
First of all: I am not big fan of tests that have "print something, see that's wrong" instead of proper assertions to show BY CODE what seems to be the issue.
But in this case that's ok.

Second: Lombok cannot be used in test reproductions; it will do its own processing so what happens is opaque to Jackson. It is possible to find out class definitions after Lombok processing -- these can be included.

But given all of that; the way to specify "default filter" -- which should indeed work! -- is, from jackson-databind unit tests, as follows:

```
        FilterProvider provider = new SimpleFilterProvider().setDefaultFilter(SimpleBeanPropertyFilter.filterOutAllExcept("b"));

       // Then either:
       ObjectMapper mapper = new ObjectMapper();
       mapper.setFilterProvider(provider);
       String json = mapper.writeValueAsString(value);
       // OR:
       ObjectMapper mapper = new ObjectMapper();
       ObjectWriter w = mapper.writer(provider).writeValueAsString(value);
```

you should NOT try to do it via `SerializationConfig` (`serializationConfigTest` tries this); and if you use `ObjectWriter` you must use instance configured (`writerFilterProviderDefaultFilter` has a clear bug that it constructs `ObjectWriter` -- but drops it and tries to use `ObjectMapper` which has not been configured).

But one of above configuration ways should work. I'll close this issue assuming they do (there is a unit test to test it). But if not, please add a comment and re-open (if you can? If not, I'll reopen it based on comment) with reproduction of continuing failure.

**Comment by authub** [comment] 2023-01-09 02:08
> First of all: I am not big fan of tests that have "print something, see that's wrong" instead of proper assertions to show BY CODE what seems to be the issue. But in this case that's ok.
> 
> Second: Lombok cannot be used in test reproductions; it will do its own processing so what happens is opaque to Jackson. It is possible to find out class definitions after Lombok processing -- these can be included.
> 
> But given all of that; the way to specify "default filter" -- which should indeed work! -- is, from jackson-databind unit tests, as follows:
> 
> ```
>         FilterProvider provider = new SimpleFilterProvider().setDefaultFilter(SimpleBeanPropertyFilter.filterOutAllExcept("b"));
> 
>        // Then either:
>        ObjectMapper mapper = new ObjectMapper();
>        mapper.setFilterProvider(provider);
>        String json = mapper.writeValueAsString(value);
>        // OR:
>        ObjectMapper mapper = new ObjectMapper();
>        ObjectWriter w = mapper.writer(provider).writeValueAsString(value);
> ```
> 
> you should NOT try to do it via `SerializationConfig` (`serializationConfigTest` tries this); and if you use `ObjectWriter` you must use instance configured (`writerFilterProviderDefaultFilter` has a clear bug that it constructs `ObjectWriter` -- but drops it and tries to use `ObjectMapper` which has not been configured).
> 
> But one of above configuration ways should work. I'll close this issue assuming they do (there is a unit test to test it). But if not, please add a comment and re-open (if you can? If not, I'll reopen it based on comment) with reproduction of continuing failure.

```java

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ser.FilterProvider;
import com.fasterxml.jackson.databind.ser.impl.SimpleBeanPropertyFilter;
import com.fasterxml.jackson.databind.ser.impl.SimpleFilterProvider;
import lombok.SneakyThrows;
import org.junit.jupiter.api.Test;
import org.springframework.util.Assert;

import java.util.UUID;


public class JacksonIgnoreFieldTest {


    @SneakyThrows
    @Test
    public void defaultFilter() {
        String propertyArray = "delFlag";
        FilterProvider provider = new SimpleFilterProvider()
                .setDefaultFilter(SimpleBeanPropertyFilter.serializeAllExcept(propertyArray));
        User user = new User();
        ObjectMapper mapper = new ObjectMapper()
                .setFilterProvider(provider);
        String json = mapper.writeValueAsString(user);
        Assert.isTrue(!json.contains(propertyArray), String.format("There is a field that needs to be ignored: %s", propertyArray));
    }

    @SneakyThrows
    @Test
    public void writerFilter() {
        String propertyArray = "delFlag";
        FilterProvider provider = new SimpleFilterProvider()
                .setDefaultFilter(SimpleBeanPropertyFilter.serializeAllExcept(propertyArray));
        User user = new User();
        ObjectMapper mapper = new ObjectMapper();
        String json = mapper.writer(provider).writeValueAsString(user);
        Assert.isTrue(!json.contains(propertyArray), String.format("There is a field that needs to be ignored: %s", propertyArray));
    }

    public static class User {

        private String userId;
        private String userName;
        private String delFlag;

        public User() {
            userId = UUID.randomUUID() + "_userId";
            userName = UUID.randomUUID() + "_userName";
            delFlag = "0";
        }

        public String getUserId() {
            return userId;
        }

        public void setUserId(String userId) {
            this.userId = userId;
        }

        public String getUserName() {
            return userName;
        }

        public void setUserName(String userName) {
            this.userName = userName;
        }

        public String getDelFlag() {
            return delFlag;
        }

        public void setDelFlag(String delFlag) {
            this.delFlag = delFlag;
        }


    }


}

```
I tried the two methods you said, or will serialize the fields I want to ignore, the above code is a test case

**Comment by cowtowncoder** [comment] 2023-01-09 19:58
Thank you @authub.

**Comment by cowtowncoder** [comment] 2023-01-10 04:28
Ah. Ok, now I remember: there is a reason why this usage does not work, and it is by design.

The reason is that filter is only looked for if POJO has `@JsonFilter` annotation indicating id: default filter will be returned for otherwise unknown filters -- but is never accessed if no filter is indicated.

But it is possible to achieve what you want by adding handling as if given POJO did indicate filter id to use. This can be done by custom `AnnotationIntrospector`, like so:

```java
public class MyIntrospector extends JacksonAnnotationIntrospector {
    @Override
    public Object findFilterId(Annotated ann) {
       // You can verify it's class you want to have id associate
       if (ann instanceof AnnotatedClass) {
          AnnotatedClass ac = (AnnotatedClass) ann;
          if (ac.getAnnotated() == ClassToMatch.class) {
             return "filterId";
          }
       }
       return super.findFilterId(ann);
    }
}
```

combination then does allow associating any filter on any POJO.

Note, however, that use of "mix-in annotations" to attach `@JsonFilter` may be simpler way to approach the problem.

**Comment by cowtowncoder** [comment] 2023-01-10 04:28
Given that this actually works as intended (although I forgot it for a while), will close the issue.

**Closed by cowtowncoder** 2023-01-10 04:28 UTC
Labels: has-failing-test

**Comment by authub** [comment] 2023-01-11 06:31
> Given that this actually works as intended (although I forgot it for a while), will close the issue.

I think we can add a global serialization filter,So don't need to add any annotations in POJO,The reason why I raise this question is that I want to replace the currently used fastjson. Now there are more than 1000 POJO classes in the project，This means I need to add 1000 times `@JsonFilter("myJsonFilter")`.I think this global filter will be used by many people.

**Comment by cowtowncoder** [comment] 2023-01-11 18:55
@authub No, there is no way to force addition of a filter for POJOs that do not indicate they want a filter using API. But I explained how you can make that work with custom(ized) `AnnotationIntrospector`, without requiring lots of annotations.
Another possibility could be to simply add `@JsonFilter` annotation in base class or interface if the project has some shared base class/interface.

But if you want to request a new feature for adding filter for any POJO that is NOT annotated to have one, please create a new issue explaining what would be needed.
This should probably default filter id to use if no filter id annotation found.
Currently no such functionality exists.

**Comment by authub** [comment] 2023-02-28 04:45
> No, there is no way to force addition of a filter for POJOs that do not indicate they want a filter using API. But I explained how you can make that work with custom(ized) `AnnotationIntrospector`, without requiring lots of annotations. Another possibility could be to simply add `@JsonFilter` annotation in base class or interface if the project has some shared base class/interface.
> 
> But if you want to request a new feature for adding filter for any POJO that is NOT annotated to have one, please create a new issue explaining what would be needed. This should probably default filter id to use if no filter id annotation found. Currently no such functionality exists.

```java
  public static void main(String[] args) throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper();
        HashMap<String, String> map = new HashMap<>();
        map.put("framework", "Spring");
        map.put("json", "Jackson");
        map.put("database", "MySQL");
        SimpleFilterProvider SIMPLE_FILTER = new SimpleFilterProvider().setDefaultFilter(
                SimpleBeanPropertyFilter.serializeAllExcept("json")
        );
        String json = mapper.setFilterProvider(SIMPLE_FILTER).writeValueAsString(map);
        Assert.isTrue(!json.contains("json"), "json key exist");
    }
```
I have a problem today. If I want to filter out the key output from MAP,The above code doesn't work,I must create a MyHashMap and add @JsonFilter("jsonFilter") annotation. Is this a bug.

**Comment by cowtowncoder** [comment] 2023-02-28 18:59
No this is not a bug. There is no mechanism to force use of Filters for Java types that do not indicate they are to be filtered.

Please re-read my answer above for work-arounds.
