### ISSUE TITLE
Bug when using @JsonRawValue with valueToTree()

### ISSUE THREAD

**Issue by jbq** [FasterXML/jackson-databind#971] opened 2015-10-13 09:35 UTC
I'm using the @JsonRawValue annotation in the `MyContribution` bean below:

```
import KeepAsJsonDeserializer;
import com.fasterxml.jackson.annotation.JsonRawValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

public class MyContribution {
    private String _topics;
    @JsonRawValue
    public String getTopics() {
        return _topics;
    }
    
    @JsonDeserialize(using=KeepAsJsonDeserializer.class)
    public void setTopics(String topics) {
        _topics = topics;
    }
}
```

I'm using a custom deserializer:

```
import java.io.IOException;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.TreeNode;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;

/**
 * Keeps json value as json, does not try to deserialize it
 * @author roytruelove
 *
 */
public class KeepAsJsonDeserializer extends JsonDeserializer<String> {
    @Override
    public String deserialize(JsonParser jp, DeserializationContext ctxt)
            throws IOException, JsonProcessingException {

        TreeNode tree = jp.getCodec().readTree(jp);
        return tree.toString();
    }
}
```

Then in my unit test I load a serialized JSON into a new instance of `MyContribution`, and serialize back using `valueToTree`:

    @Test
    public void testSerialize() throws IOException {
        String json = "{\"topics\":[\"foo\",\"bar\"]}";
        MyContribution c = new ObjectMapper().readValue(json, MyContribution.class);
        assertEquals(json, new ObjectMapper().valueToTree(c).toString());
    }

I expect this test to be successful but instead it fails with the following error:

```
org.junit.ComparisonFailure: expected:<{"topics":[["foo","bar"]]}> but was:<{"topics":[(raw value '[RawValue of type java.lang.String]')]}>
```

If instead I use the `writeValueAsString()` method, the test is successful:

```
    @Test
    public void testSerializeGood() throws IOException {
        String json = "{\"topics\":[\"foo\",\"bar\"]}";
        MyContribution c = new ObjectMapper().readValue(json, MyContribution.class);
        assertEquals(json, new ObjectMapper().writeValueAsString(c));
    }
```

I consider this as a bug in the jackson-databind library.  Can you confirm?

**Comment by cowtowncoder** [comment] 2015-10-28 18:19
And just to make sure, this is with version 2.6?

Also, beyond problem itself, one think worth pointing out is that `node.toString()` is NOT a proper way to serialize JSON, and specifically is not guaranteed to produce valid JSON. It is strictly to be used for diagnostic purposes. Actually this may be the root cause here.

**Comment by cowtowncoder** [comment] 2015-10-28 21:17
I can not reproduce a bug here. The problem with code as tested is the use of `JsonNode.toString()`, which will not necessarily produce valid JSON, and is specifically not designed to try to do that.
Instead, `mapper.writeValueAsString(tree)` is always needed to produce valid JSON output.

There were some issues (now fixed) with handling of raw values, with `convertValue()`, however, so it may be that there are/were additional problems; but I can not reproduce anything else on 2.6.3.

One other thing that is probably useful is that `DeserializationContext` has method `readValue(JsonParser, Class<?>)`, which allows for more efficient deserialization (if going via `JsonParser`, a new context is needed). Just pass `JsonNode.class` as the second argument, and it will work the same way as `mapper.readTree()`.

**Closed by cowtowncoder** 2015-10-28 21:17 UTC

**Comment by jbq** [comment] 2015-10-30 10:51
Hi @cowtowncoder this is Jackson 2.6.2.  Using `writeValueAsString()` this works perfectly.  May I suggest to improve the documentation of `toString()` to point to this method?

The current documentation is pretty lame:

    /**
     *<p>
     * Note: marked as abstract to ensure all implementation
     * classes define it properly.
     */
    @Override
    public abstract String toString();

Thanks!

**Comment by cowtowncoder** [comment] 2015-10-31 21:07
Sure, good idea.
