### ISSUE TITLE
ObjectMapper readValue closes InputStream unexpectedly

### ISSUE THREAD

**Issue by joelb-git** [FasterXML/jackson-databind#697] opened 2015-02-05 20:18 UTC
ObjectMapper [readValue](http://fasterxml.github.io/jackson-databind/javadoc/2.1.0/com/fasterxml/jackson/databind/ObjectMapper.html#readValue(java.io.InputStream, java.lang.Class)) from InputStream closes the
stream unexpectedly.

My use case: I have two custom deserializers for different formats,
but I don't know which one to use without inspecting the file.  I know
jackson will throw an exception if the wrong deserializer is used.
I'd like to catch the exception, reset the stream, and try again with
the other deserializer.  But jackson is closing the stream so I can't
reset it.  For an api that takes an InputStream, I usually expect that
it's the caller's responsibility to close the stream.

```
@Test
public void testUnexpectedClose() throws Exception {
    BufferedInputStream in = new BufferedInputStream(
        new ByteArrayInputStream("{\"foo\": 123}".getBytes(Charsets.US_ASCII)));
    in.mark(0);
    ObjectMapper mapper = new ObjectMapper();
    try {
        String s = mapper.readValue(in, String.class);
        System.out.println(s);
    } catch (JsonMappingException e) {
        // com.fasterxml.jackson.databind.JsonMappingException:
        // Can not deserialize instance of java.lang.String out of START_OBJECT token
    }
    in.reset();  // oops: java.io.IOException: Stream closed
}
```

Workaround is to create a NoCloseBufferedInputStream which overrides
the close() method to do nothing.

**Comment by cowtowncoder** [comment] 2015-02-06 19:56
It is not a bug; closing is completely expected. This is by design; although different from how some other APIs (like Stax XML API) specify expected behavior.

But to stop automatic closing, disable `JsonParser.Feature.AUTO_CLOSE_SOURCE`.

**Closed by cowtowncoder** 2015-02-06 19:56 UTC

**Comment by drcrallen** [comment] 2015-08-08 04:17
I have a `class SerializedJson[A](inputDelegate: A) extends Serializable` wrapping object for spark which uses Jackson as the underlying SerDe. This one caught me off guard on the `readObject` part but properly setting `JsonParser.Feature.AUTO_CLOSE_SOURCE` causes things to act as expected as per @cowtowncoder 's comment

**Comment by rehevkor5** [comment] 2021-08-20 01:07
`JsonParser.Feature.AUTO_CLOSE_SOURCE` appears to be usable against things other than JSON, such as YAML, but the `JsonFactory#enable()`/`JsonFactory#disable()` method returns `JsonFactory` rather than the appropriate type (such as `YAMLFactory`), so it cannot be used fluently. You can either call it separately on your YAMLFactory, it does mutate the object, or you can call it on your resulting mapper such as `YAMLMapper`.

**Comment by cowtowncoder** [comment] 2021-08-20 20:16
@rehevkor5 Starting with Jackson 2.10, the recommended way for constructing `JsonFactory` (and format-specific variants) is to use Builder-style construction:

```
YAMLFactory f = YAMLFactory.builder()
    // configure, but use the new `StreamReadFeature.AUTO_CLOSE_SOURCE` instead of `JsonParser.Feature`
    .build();
```

which supports type-safe, fluent construction.

Also note that `ObjectReader` instances may be (re)configured with `StreamReadFeature`s (or, now-legacy, `JsonParser.Feature`s); something like

```
ObjectReader r = objectMapper().readerFor(SomeType.class)
    .without(StreamReadFeature.AUTO_CLOSE_SOURCE);
```
