### ISSUE TITLE
Problem with type specialization for Maps with `@JsonDeserialize(as=subtype)`

### ISSUE THREAD

**Issue by brentryan** [FasterXML/jackson-databind#1215] opened 2016-04-27 02:25 UTC
If I have json that looks like

```
{
  "something": [
        {
           "id": "a uuid",
           "property": "value"
         }
  ]
}
```

And I have a java pojo with an annotation like this:

```
    @JsonDeserialize(as = MyHashMap.class)
    private void setSomething(Map<UUID, Foo> incomingValue) {
```

Where MyHashMap.java has some custom logic using generics that allow us to map the array json above into a Map where "id" is the key and everything else serializes into the value.  We use generics on MyHashMap to enforce that every value implements a certain interface that respects the contract of returning an "id" property.  In this example Foo.java implements this interface MyCustomIdInterface.java.

When using 2.6.6 this worked fine, but if I switch to 2.7.x then it breaks with the error:

```Can not construct instance of MyCustomIdInterface, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information```

in 2.7.x, it looks like jackson resolves to using AbstractDeserializer based on MyCustomIdInterface but in 2.6.6 it resolves to using BeanDeserializer based on Foo.java.

Is this a bug or is there some default/feature flag that changed here?

**Comment by cowtowncoder** [comment] 2016-04-27 05:07
I think this is one of bugs fixed (#1186) for 2.7.4, so I think this will be resolved with 2.7.4.

If so, the problem was that generic type parameters were not being properly resolved when creating specialized subtype: `MyHashMap` would be taken as `MyHashMap<Object,Object>`, despite `Map` having type parameters.

The only thing to make sure is that you declare `MyHashMap` as generic, something like:

    public class MyHashMap<K,V> extends HashMap<K,V> { ... } 
    // or whatever base type it is

because otherwise type resolution can not properly propagate variable substitutions (earlier versions did not care; they forcible set parameters regardless -- but this is not possible any more).

I don't know if it's possible for you to check 2.7.4-SNAPSHOT to verify, but I am fairly confident this is the root cause.

**Comment by brentryan** [comment] 2016-04-27 12:23
Ya, I can easily check that out. I'll repost what I find. Thanks for the quick response.

**Comment by brentryan** [comment] 2016-04-27 13:54
So I built the 2.7 branch of jackson-core and jackson-databind locally and updated my test project to use 2.7.4-SNAPSHOT and it doesn't fix the problem.

I'll see if there's more investigation I can do and maybe create a unit test that fails within this project.  I'm not sure how possible that will be because it uses annotations in my project but I can give it a try.

**Comment by brentryan** [comment] 2016-04-27 14:37
Also, it appears like the issue is still present in master 2.8.0-SNAPSHOT as well.

**Comment by cowtowncoder** [comment] 2016-04-27 15:56
@brentryan thank you for checking this. Too bad problem is not fixed. I'll try to figure it out, probably tomorrow. Any help in diagnosing appreciated.

**Comment by cowtowncoder** [comment] 2016-04-27 22:09
Ok, re-reading the description in more detail I think a reproduction is needed. It is quite possible that what happens here is more complex than previously added cases of how to specialize type parameters -- before 2.7, handling was much simpler and more naive, which has its problems as well as benefits.

**Comment by brentryan** [comment] 2016-04-28 01:41
I'll setup a mini project with an example that reproduces the issue.  Probably easier since it combines a few jackson libraries that aren't part of just 1 so unit tests are harder.

**Comment by cowtowncoder** [comment] 2016-04-28 03:41
@brentryan sounds good, thank you in advance.

**Comment by brentryan** [comment] 2016-04-30 01:47
[JacksonTest.zip](https://github.com/FasterXML/jackson-databind/files/243419/JacksonTest.zip)

@cowtowncoder Here's an example project that shows it failing.  Change the version to 2.6.6 and you'll see it work, while 2.7.3 fails.

**Comment by cowtowncoder** [comment] 2016-04-30 19:30
@brentryan Thank you; I can reproduce this locally, and have a lead to follow.
It is somehow due to using wrong part of type information, possibly not due to refinement (which appears to work just fine), but rather due to some part of code looking at method/field signature and not refined type.

**Comment by brentryan** [comment] 2016-06-14 01:20
@cowtowncoder I haven't tried yet, but was this issue covered in 2.7.5 or 2.8 latest?

**Comment by cowtowncoder** [comment] 2016-06-28 04:50
@brentryan issue with constructor type mismatch is not yet resolved, as per test; failing test is included to allow reproduction.

**Comment by cowtowncoder** [comment] 2016-06-29 23:56
Looks like this is indeed due to "generic type resolution" problems, specific to 2.7 changes.
So problematic method is `TypeFactory.constructSpecializedType()`, and ideally it should do full resolution... unfortunately that is complicated and so far it has been mostly question of adding handling for more and more special cases. Still hoping that could work for this case too, we shall see.

**Closed** 2016-06-30 04:45 UTC
