### ISSUE TITLE
Type parameter not passed by `ObjectWriter` if serializer pre-fetch disabled

### ISSUE THREAD

**Issue by fcamblor** [FasterXML/jackson-databind#1451] opened 2016-11-13 22:08 UTC
Hi,

We're trying to upgrade from Jackson 2.3.3 to Jackson 2.6.1 on [RESTX OSS framework](https://github.com/restx/restx/pull/228)

By upgrading to 2.6.1, we noticed some changes in behaviour when serializing iterables of polymorphic types :
* Here is some [sample code demonstrating a simple REST endpoint with polymorphic types](https://github.com/restx/restx/blob/master/restx-samplest/src/main/java/samplest/core/PolymorphicResource.java#L20)
* Here is [the `ObjectMapper` config](https://github.com/restx/restx/blob/master/restx-core/src/main/java/restx/jackson/FrontObjectMapperFactory.java#L35) we're using on the project
* Using `Jackson 2.4.6`, `GET /polymorphic/list/B` was returning :
```
[ {
  "@class" : ".PolymorphicResource$A",
  "a" : "a1"
}, {
  "@class" : ".PolymorphicResource$B",
  "a" : "a2",
  "b" : "b"
} ]
```
  and after migration to `Jackson 2.5.0`, it returns :
```
[ {
  "a" : "a1"
}, {
  "a" : "a2",
  "b" : "b"
} ]
```

I isolated this change in behaviour on version `2.5.0`, but I don't see any mention of this change [in the 2.5 release note](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.5).
Did I miss anything ?

I just want to be able to understand precisely what have changed in order to provide an easy migration path to our users :-)

BTW, congrats for the hard work on Jackson, we're very happy to use it on a daily basis.

**Comment by cowtowncoder** [comment] 2016-11-14 02:13
I don't think just a change is intentional. But before further investigation couple of notes:

* Please check with a more recent version 2.5, `2.5.5`. There are literally dozens of fixes, and it's a bad idea to use an obsolete patch revision. It is possible this was a bug that was fixed.
* If present in 2.5.5, it's worth further upgrade check as the oldest still-maintained branch is 2.7; of which 2.7.9 is the latest version.

If behavior is still such that polymorphic type information is missing from what seems like something that should have it, the next step would be a reproduction. Ideally it would be stand-alone, i.e. not require use of framework.

**Comment by fcamblor** [comment] 2016-11-14 10:13
Hi,

I just setup a git project with unit test reproducing the issue, you can see it [here](https://github.com/fcamblor/jackson-1451-typeinfo-testing)

Test case :
```
public class TypeInfoSerializationTest {
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@class")
    @JsonSubTypes({
        @JsonSubTypes.Type(value = A.class, name = "A"),
        @JsonSubTypes.Type(value = B.class, name = "B")
    })
    public static class A {
        public String a;
    }
    public static class B extends A {
        public String b;
    }

    @Test
    public void should_polymorphic_iterables_return_typeinfo_class_in_instances() throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper()
                .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
                .disable(DeserializationFeature.EAGER_DESERIALIZER_FETCH)
                .disable(SerializationFeature.EAGER_SERIALIZER_FETCH);

        ParameterizedType valueType = newParameterizedType(Iterable.class, A.class);
        ObjectWriter writer = mapper.writerWithType(TypeFactory.defaultInstance().constructType(valueType));

        String result = writer.writeValueAsString(createPolymorphicList());

        assertThat(result, is(equalTo("[{\"@class\":\"A\",\"a\":\"a1\"},{\"@class\":\"B\",\"a\":\"a2\",\"b\":\"b\"}]")));
    }

    private static ParameterizedType newParameterizedType(final Class<?> rawType, final Type... arguments) {
        return new ParameterizedType() {
            public Type[] getActualTypeArguments() {
                return arguments;
            }
            public Type getRawType() {
                return rawType;
            }
            public Type getOwnerType() {
                return rawType.getEnclosingClass();
            }
        };
    }


    private static Iterable<A> createPolymorphicList(){
        List<A> l = new ArrayList<A>();
        A a = new A();
        a.a = "a1";
        l.add(a);

        B b = new B();
        b.b = "b";
        b.a = "a2";
        l.add(b);

        return l;

    }
}
```

You can test it by cloning the repo and running maven with different jackson versions :
```
mvn -Djackson.version=2.3.3 test
=> Success
mvn -Djackson.version=2.4.6 test
=> Success
mvn -Djackson.version=2.5.0 test
=> Failure
mvn -Djackson.version=2.5.5 test
=> Failure
mvn -Djackson.version=2.7.9 test
=> Failure
mvn -Djackson.version=2.8.5 test
=> Failure
```

(Note that I didn't found 2.7.9 in maven repo, only 2.7.8 on 2.7.x branch ... though I found a 2.8.5 which is not passing the test as well)

**Comment by fcamblor** [comment] 2016-11-14 10:26
Also, note that call to `newParameterizedType()` is to reproduce our exact same behaviour in the framework.

But using a `new TypeReference<Iterable<A>>(){}` produces the exact same behaviour.

**Comment by cowtowncoder** [comment] 2016-11-14 21:07
My bad on 2.7.9: actually 2.7.8 is the latest release version. 2.8.5 is being released, but not fully out yet.

**Comment by cowtowncoder** [comment] 2016-11-14 21:11
I'll have to check this out. I first thought this is due to type erasure, but since you are actually forcing type via `writerWithType()` things should work.

**Comment by fcamblor** [comment] 2016-11-14 21:13
Yup, and exact same code is working (="@class" generated) perfectly with 2.4.6 ;-)

**Comment by cowtowncoder** [comment] 2016-11-14 21:34
@fcamblor if you used `Collection` instead of `Iterable`, would it work? My first suspicion would be with handling of `Iterable`

**Comment by fcamblor** [comment] 2016-11-14 21:57
@cowtowncoder same result
```
    @Test
    public void should_polymorphic_iterables_return_typeinfo_class_in_instances() throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper()
                .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
                .disable(DeserializationFeature.EAGER_DESERIALIZER_FETCH)
                .disable(SerializationFeature.EAGER_SERIALIZER_FETCH);

        ObjectWriter writer = mapper.writerWithType(TypeFactory.defaultInstance().constructType(new TypeReference<Iterable<A>>(){}));

        String result = writer.writeValueAsString(createPolymorphicIterables());

        assertThat(result, is(equalTo("[{\"@class\":\".TypeInfoSerializationTest$A\",\"a\":\"a1\"},{\"@class\":\".TypeInfoSerializationTest$B\",\"a\":\"a2\",\"b\":\"b\"}]")));
    }

    @Test
    public void should_polymorphic_collection_return_typeinfo_class_in_instances() throws JsonProcessingException {
        ObjectMapper mapper = new ObjectMapper()
                .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
                .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
                .disable(DeserializationFeature.EAGER_DESERIALIZER_FETCH)
                .disable(SerializationFeature.EAGER_SERIALIZER_FETCH);

        ObjectWriter writer = mapper.writerWithType(TypeFactory.defaultInstance().constructType(new TypeReference<Collection<A>>(){}));

        String result = writer.writeValueAsString(createPolymorphicCollection());

        assertThat(result, is(equalTo("[{\"@class\":\".TypeInfoSerializationTest$A\",\"a\":\"a1\"},{\"@class\":\".TypeInfoSerializationTest$B\",\"a\":\"a2\",\"b\":\"b\"}]")));
    }
```

**Comment by cowtowncoder** [comment] 2016-11-17 23:11
@fcamblor Thank you! What seems to happen here is that somehow disabling of `SerializationFeature.EAGER_SERIALIZER_FETCH` breaks things: without that setting, tests pass.
This should help to narrow this down and fix this.

Thank you once again for reporting the issue.

**Comment by fcamblor** [comment] 2016-11-17 23:13
You're welcome :-)

**Comment by cowtowncoder** [comment] 2016-11-18 03:03
Looks like type parameter was not properly passed. This is fixed in `master`, `2.8` and `2.7` branches which are only open branches at this point; for releases 2.7.9, 2.8.6 and 2.9.0.

**Closed** 2016-11-18 03:23 UTC
Labels: 2.8

**Comment by fcamblor** [comment] 2016-11-18 09:32
@cowtowncoder Is there somewhere a dev guide/aggregator project allowing me to build 2.7.9-SNAPSHOT for [Jackson core modules](https://github.com/fasterxml/jackson#core-modules) or should I build them one by one separately to prepare migration to 2.7.9 on RestX ?

**Comment by cowtowncoder** [comment] 2016-11-18 22:42
@fcamblor there's no aggregator project unfortunately. But for this version `jackson-databind` upgrade is enough; other components (`jackson-core`, namely) do not have relevant fixes. There is `2.7` branch for all components.

**Comment by fcamblor** [comment] 2016-11-18 23:42
OK thank you :)
