### ISSUE TITLE
java.lang.NoSuchFieldError crash

### ISSUE THREAD

**Issue by MaYinjian** [FasterXML/jackson-databind#2084] opened 2018-07-09 03:17 UTC
Our project got lots of crash because of jackson's NoSuchFieldError .
it was running in  AI device   : Skyworth_Skyworth 9R53 G6     , no root
android system: 5.1.1
cpu:armeabi-v7a
memory:isLowMem: no 
               availMem: 574.1M 
               threshold: 150.9M 
               totalPrivateDirty: 0B 
               totalPss: 0B 
               totalSharedDirty: 0B
 **I check the whole project , use the same jacksonVersion in gradle  :**
```
    def jacksonVersion = '2.9.1'
    compile "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}"
    compile "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    compile "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
```

Here is the crash  :   

``` 
java.lang.NoSuchFieldError: No static field FALSE of type Ljava/lang/Boolean; in class Ljava/lang/Boolean; or its superclasses (declaration of 'java.lang.Boolean' appears in /system/framework/core-libart.jar)
	at com.fasterxml.jackson.databind.ser.PropertyBuilder.<clinit>(PropertyBuilder.java:18)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructPropertyBuilder(BeanSerializerFactory.java:514)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:565)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:368)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:279)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:231)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:165)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1385)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1336)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:510)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:713)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:308)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:993)
	at com.baidu.duer.dcs.util.util.ObjectMapperUtil.objectToJson(ObjectMapperUtil.java:68)
```

**Comment by cowtowncoder** [comment] 2018-07-10 00:04
@MaYinjian We would need a reproduction running on regular JVM ideally as a unit test. Stack trace does not help without knowing what json is being read, or to what kind of Java class.

**Comment by MaYinjian** [comment] 2018-07-10 02:09
@cowtowncoder  But this is an online problem and the corresponding data could not be found. This is not a problem that must be present. It should be independent of the data. It is the data sent by the server. If it is related to json data, the amount of this crash should be very large.

**Comment by cowtowncoder** [comment] 2018-07-10 17:35
@MaYinjian without reproduction I have no way of helping unfortunately, so I will have to close this issue if there is nothing to help me to help you.

Your assumption that the problem is independent of data may or may not be true; but it is triggered by attempt to process data. And that code is needed, along with some data that triggers problem.
Exception message does not make any sense and I have never seen anything similar. So a unit test is absolutely need.

**Closed** 2020-12-04 20:40 UTC
Labels: need-test-case
