### ISSUE TITLE
JSON with 17-character keys deserializes incorrectly (2.6.0, 2.6.1)

### ISSUE THREAD

**Issue by steven-landers** [FasterXML/jackson-databind#916] opened 2015-09-01 16:36 UTC
We encountered an issue where not all keys are deserializing appropriately when there are many keys that are 17 characters long.

Found in:
- 2.6.0
- 2.6.1

Not found in:
- 2.5.4

Notes
- The size of the key is important (17, in this case)
- The number of keys is important (>25)
- It seems like `ByteQuadsCanonicalizer` is returning the wrong key name on calls to `findName`

Test Case:

```java

import com.fasterxml.jackson.databind.ObjectMapper;
import junit.framework.TestCase;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Map;

public class TestObjectMapperCollision extends TestCase {

    public void testNoCollisionOccursWith50Keys(){
        String testJson = "{\n" +
                "    \"lengthmatters1001\": true,\n" +
                "    \"lengthmatters1002\": true,\n" +
                "    \"lengthmatters1003\": true,\n" +
                "    \"lengthmatters1004\": true,\n" +
                "    \"lengthmatters1005\": true,\n" +
                "    \"lengthmatters1006\": true,\n" +
                "    \"lengthmatters1007\": true,\n" +
                "    \"lengthmatters1008\": true,\n" +
                "    \"lengthmatters1009\": true,\n" +
                "    \"lengthmatters1010\": true,\n" +
                "    \"lengthmatters1011\": true,\n" +
                "    \"lengthmatters1012\": true,\n" +
                "    \"lengthmatters1013\": true,\n" +
                "    \"lengthmatters1014\": true,\n" +
                "    \"lengthmatters1015\": true,\n" +
                "    \"lengthmatters1016\": true,\n" +
                "    \"lengthmatters1017\": true,\n" +
                "    \"lengthmatters1018\": true,\n" +
                "    \"lengthmatters1019\": true,\n" +
                "    \"lengthmatters1020\": true,\n" +
                "    \"lengthmatters1021\": true,\n" +
                "    \"lengthmatters1022\": true,\n" +
                "    \"lengthmatters1023\": true,\n" +
                "    \"lengthmatters1024\": true,\n" +
                "    \"lengthmatters1025\": true,\n" +
                "    \"lengthmatters1026\": true,\n" +
                "    \"lengthmatters1027\": true,\n" +
                "    \"lengthmatters1028\": true,\n" +
                "    \"lengthmatters1029\": true,\n" +
                "    \"lengthmatters1030\": true,\n" +
                "    \"lengthmatters1031\": true,\n" +
                "    \"lengthmatters1032\": true,\n" +
                "    \"lengthmatters1033\": true,\n" +
                "    \"lengthmatters1034\": true,\n" +
                "    \"lengthmatters1035\": true,\n" +
                "    \"lengthmatters1036\": true,\n" +
                "    \"lengthmatters1037\": true,\n" +
                "    \"lengthmatters1038\": true,\n" +
                "    \"lengthmatters1039\": true,\n" +
                "    \"lengthmatters1040\": true,\n" +
                "    \"lengthmatters1041\": true,\n" +
                "    \"lengthmatters1042\": true,\n" +
                "    \"lengthmatters1043\": true,\n" +
                "    \"lengthmatters1044\": true,\n" +
                "    \"lengthmatters1045\": true,\n" +
                "    \"lengthmatters1046\": true,\n" +
                "    \"lengthmatters1047\": true,\n" +
                "    \"lengthmatters1048\": true,\n" +
                "    \"lengthmatters1049\": true,\n" +
                "    \"lengthmatters1050\": true\n" +
                "}";

        InputStream is = new ByteArrayInputStream(testJson.getBytes());
        ObjectMapper mapper = new ObjectMapper();
        Map readObject = null;
        try {
            readObject = mapper.readValue(is, Map.class);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        assertEquals(50, readObject.size());
    }
}
```
This returns a size from 36 to 39 on each test execution (not same every time)

**Comment by cowtowncoder** [comment] 2015-09-08 22:08
Thank you for providing the test case. I'll try to get this fixed ASAP.

**Comment by cowtowncoder** [comment] 2015-09-08 22:14
Since the underlying problem is almost certainly within streaming parser (`jackson-core`), I will move this issue under `jackson-core`. Or, perhaps just merge with what seems like a dup, https://github.com/FasterXML/jackson-core/issues/213

**Comment by cowtowncoder** [comment] 2015-09-08 22:43
Ok: I can reproduce the issue, with code similar to above. Since the two issues are the same I think, I will close this one, but only because the other is under `jackson-core`. Thank you again for the test case; I hope to fix this asap.

**Closed by cowtowncoder** 2015-09-08 22:43 UTC
