### ISSUE TITLE
Deserialization into List subtype with JsonCreator no longer works

### ISSUE THREAD

**Issue by adamjoeldavis** [FasterXML/jackson-databind#936] opened 2015-09-15 21:03 UTC
I recently upgraded from 2.4.5 to 2.5.3, and the following code stopped working:

```java
    public class DataList<D extends DataObject> implements List<D>
    {
        @JsonCreator
        private DataList(List<D> values)
        {
            initialize(values);
        }
    }
```

    ObjectMapper mapper = ...;

    //2.4 deserialization 
    mapper.readValue(stringVersion, mapper.getTypeFactory().constructParametricType(DataList.class, SubclassOfD.class));

    //2.5 deserialization
    mapper.readValue(stringVersion, mapper.getTypeFactory().constructParametrizedType(DataList.class, DataList.class, SubclassOfD.class));

If I change this class so that it does not implement List, everything works as expected.  I can also change it so that the JsonCreator takes a `List<Map<String, Object>>`, but then I have to do conversion to D within the constructor and I don't have access to that type information at that point.

I get the following error:

```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
 at [Source: "[{"deleted":false,"data":{}}]"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:835)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:831)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3564)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2618)
	Suppressed: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of data.DataObject, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
 at [Source: [{"deleted":false,"data":{}}]; line: 1, column: 2] (through reference chain: java.util.ArrayList[0])
		at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
		at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:857)
		at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:139)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
		at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
		at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3564)
		at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2618)
		... 3 more
```

**Comment by cowtowncoder** [comment] 2015-09-15 21:12
Does this also fail with 2.6? (latest version, just released, being 2.6.2)?

**Comment by adamjoeldavis** [comment] 2015-09-15 21:13
Yes, it does - same stack trace

**Comment by cowtowncoder** [comment] 2015-09-15 21:14
Thanks. Would expect that, but just wanted to be sure.

**Comment by cowtowncoder** [comment] 2015-09-15 21:16
One quick suggestion would be to use `List.class` as the second constructParametrizedType, not sure if it makes material difference.

**Comment by adamjoeldavis** [comment] 2015-09-15 21:16
Tried that as well, still get the same error :)

**Comment by cowtowncoder** [comment] 2015-09-15 21:20
Ah. Ok, I'll have to look more into this. About the only other thing is that logically type should be `CollectionType`, so method in `TypeFactory` to call would be `constructCollectionType(...)`.
But it should not make much difference either, for purposes of finding custom creator method.

Now, as to reproduction, would it be possible to get definitions for types involved, for a unit test?

**Comment by adamjoeldavis** [comment] 2015-09-16 14:33
I added a test project here: https://github.com/adamjoeldavis/jacksontest

I'm relatively new to github, so let me know if you have any issues accessing it.

**Comment by cowtowncoder** [comment] 2015-09-24 16:56
Ok. Interesting... so, basically, looks like type refinement somehow fails to "upgrade" content type from abstract `DataObject` into `Person`, it looks like. 
Yes, I think that is a bug. Thank you for reporting this.

**Comment by cowtowncoder** [comment] 2015-09-24 17:12
I can reproduce this with a bit simplified test, checked in under `failing` (for 2.6.x branch, hope to backport if I can fix it).

**Comment by cowtowncoder** [comment] 2015-09-30 04:47
For what it is worth, the usual work-around of sub-classing does work here; something like:

    class SubclassOfDDataList extends DataList<SubclassOfD> { }
    SubclassOfDDataList list = mapper.readValue(...);

which gets around whatever the actual problem is here.

The problem itself is tricky; I can see that type resolution for constructor fails to get type information from declared type, as just uses what `DataList` declares. But I am not sure what changed between 2.4 and 2.5 to cause this, or more generally why it occurs.

**Comment by cowtowncoder** [comment] 2015-09-30 05:13
Actually, realized that it's not necessarily that easy, due to existence of `@JsonCreator`.
Similarly use of `TypeReference` would not work since that creates a subclass without that constructor.

**Comment by cowtowncoder** [comment] 2015-09-30 05:20
Unfortunately I have not been able to resolve this issue.

I did, however, find one straight-forward work-around for your specific problem. This is not a robust work-around, but appears to work: if you rename the type variable as `E` (instead of `D`), it actually resolves as expected.
This is not something you should have to do, obviously, but it just so happens that type variable resolution will align correctly if this is done.

**Comment by adamjoeldavis** [comment] 2015-09-30 14:48
Switching it to E works in my production code!  Thanks for finding a viable solution.  I'd be interested to know why E is the only one that works - maybe because that is the type variable that java.util.Collection uses, and there is a check somewhere that uses Collection's chosen letter?

**Comment by cowtowncoder** [comment] 2015-09-30 18:49
Long story short, it is because of flawed (incomplete / misguided) way Jackson handles recursive binding of type parameters. Since down in JDK type hierarchy `E` is the name of type variable for `Collection`s, `JavaType` decideds to give that name to the type parameter of `Collection`s.
This is not the right way to go (`java-classmate` implements the full painstaking method of traversing the type hierarchy, matching names all the way, layer by layer), but it is what is being done.

And so in a way you are just using specific naming to make a broken algorithm happen to stumble upon right answer. :)

I have had hopes of retrofitting `java-classmate` handling into Jackson for a while now -- classmate grew out of original Jackson code, but I went and actually fixed the problems there. Unfortunately at this point all the dependencies that databind has, and also exposes as extension points, is a huge ball of code...

**Closed** 2015-10-21 05:23 UTC

**Comment by cowtowncoder** [comment] 2015-10-21 05:24
As the luck would have it, I have finally been able to rewrite type handling code, based on `java-classmate`s ideas. There are a few differences and subtleties, leading to somewhat challenging work-arounds, but so far 3 nasty type-handling bugs have been squashed.
