### ISSUE TITLE
Include.NON_DEFAULT doesn't work for property override on Date

### ISSUE THREAD

**Issue by uberstud87** [FasterXML/jackson-databind#1676] opened 2017-06-24 01:14 UTC
Hi @cowtowncoder,

I tried using `@JsonInclude(Include.NON_DEFAULT)` on a property `Date` but it doesn't work.
I'm using 2.8.9.

https://fasterxml.github.io/jackson-annotations/javadoc/2.8/com/fasterxml/jackson/annotation/JsonInclude.Include.html#NON_DEFAULT

> When NOT used for a POJO (that is, as a global default, or as property override), definition is such that:
> 
> - All values considered "empty" (as per NON_EMPTY) are excluded
> - Primitive/wrapper default values are excluded
> - Date/time values that have timestamp (`long` value of milliseconds since epoch, see Date) of `0L` are excluded

As mentioned in the documentation (since 2.7), if the `Date` is 0, it would be excluded.
However, in my code, it still serializes the `Date` as 0 instead of excluding it.

I have included my code below.

```
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Date;

public class NewClass {

    public static void main(String[] args) throws Exception {
        
        ObjectMapper objectMapper = new ObjectMapper();
        
        DTO dto1 = new DTO();
        System.out.println(objectMapper.writeValueAsString(dto1));
        // results : {"date":0}
        // expected: {}
        
    }

}

class DTO {

    @JsonInclude(Include.NON_DEFAULT)
    private Date date = new Date(0);

    public DTO() {
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

}
```

**Comment by cowtowncoder** [comment] 2017-07-13 04:49
Test seems to pass with 2.9.0.pr4 for me. I _think_ this may actually be duplicate of #1550.
If so, as per comments there, I think fix can't be backported due to concerns about compatibility.

**Comment by cowtowncoder** [comment] 2017-07-19 03:37
Assuming duplicate, closing.

**Closed by cowtowncoder** 2017-07-19 03:37 UTC
Labels: 2.9
