### ISSUE TITLE
Excluding empty objects (nodes) from a list

### ISSUE THREAD

**Issue by alimoco** [FasterXML/jackson-databind#2376] opened 2019-07-04 12:44 UTC
I have following java structure:
```
class Record {
    public String name;
    public String type;
    @JsonIgnore
    public String payload;
    /// setters and getyers
}

class Payload {
    @JsonInclude(value = JsonInclude.Include.NON_EMPTY)
    List<Record> records;
    
    // getters & setters
}

class MainClass {
    public void process(Payload payload) {
        ObjectMapper om = new ObjectMapper();
        om.setVisibility(PropertyAccessor.FIELD, Visibility.ANY);
        JsonNode node = om.valueToTree(payload);
        // ...
    }
}
```
My problem is that node `object` contains empty node, I assume it is due to a members of `records` list that contain only value annotated with `@JsonIgnore`.

I tried with using custom @JsonIgnore, but I can't filter list members.
Using jackson-databind v2.9.8

**Comment by cowtowncoder** [comment] 2019-07-19 18:20
Excellent question for mailing list:

https://groups.google.com/forum/#!forum/jackson-user

but not a bug to report at issue tracker, so closing here.

But the gist of it is that concept of "empty" is not determined at JSON output level, but at Java object level. And currently there is no "empty" definition for POJOs, but only for containers and Strings.
Instead you will probably need to add custom filter (type `Include.CUSTOM`, impl via `valueFilter`).
This was added in 2.9, `@JsonInclude` Javadocs have more info, and there should be a unit test showing usage.

**Closed by cowtowncoder** 2019-07-19 18:20 UTC
