### ISSUE TITLE
BeanDeserializerBuilder doesn't respect CAN_OVERRIDE_ACCESS_MODIFIERS

### ISSUE THREAD

**Issue by Randgalt** [FasterXML/jackson-databind#1677] opened 2017-06-24 20:47 UTC
Note: this occurs in 2.8.9

`BeanDeserializerBuilder#_fixAccess` calls `prop.fixAccess(_config)` on all fields which in turn calls `FieldProperty#fixAccess()` which in turn calls `ClassUtil#checkAndFixAccess`. For private fields, this ends up calling `setAccessible(true)` which breaks our Sandboxed Security policy.

**Comment by Randgalt** [comment] 2017-06-24 20:48
Note: it appears this was reported here and never addressed: #520

**Comment by cowtowncoder** [comment] 2017-06-26 17:01
@Randgalt thank you for filing the follow-up issue. I'll have a look, assume should be easy enough to see. Will also check if there are any tests that set up `SecurityManager` to test fix here.

**Comment by cowtowncoder** [comment] 2017-06-26 17:02
Yes, `src/test/java/com/fasterxml/jackson/databind/misc/AccessFixTest.java` seems to do something like this. That should help... assuming this does not only occur for certain combinations.

**Comment by cowtowncoder** [comment] 2017-06-26 17:12
Hmmh. This gets bit complicated actually... problem being that semantics of `CAN_OVERRIDE_ACCESS_MODIFIERS` are bit vague, or not used consistently. Here assumption is sort of reverse, in that `true` is taken mean `setAccessible()` may be called always, even if not strictly needed (since that disables checks even for public fields that otherwise add measurable overhead).

But I think it is possible that call itself (to try to set field accessible) may be done in cases where it wouldn't be needed, speculatively. If so, such call should be avoided.
Beyond this there is then the question of perhaps suppressing the call, depending on setting.

I think I would need a sample case here, just make sure I understand (at least one) problem case, instead of speculating.

If I need to change semantics to block the call, fix will probably need to go in 2.9.0, just because 2.8 branch is quite long-living and I think there is non-trivial possibility of regression with change.
And I think it is safer to do that in minor version.

**Comment by cowtowncoder** [comment] 2019-09-19 15:21
Will need a test case, and perhaps a suggestion for change (guessing... a new additional `MapperFeature` for something like "only do it if strictly necessary"?). Keeping in mind that it is possible to prevent discovery of `private` fields... although, come to think of that, part of some fields getting pulled in may or may not be sufficiently addressed (see `MapperFeature.INFER_PROPERTY_MUTATORS`).

Closing for now but may be reopened with above info.

**Closed by cowtowncoder** 2019-09-19 15:21 UTC
Labels: need-test-case
