### ISSUE TITLE
JsonGenerationException: expected field name while writing ObjectId reference

### ISSUE THREAD

**Issue by JeffQuandt** [FasterXML/jackson-databind#1298] opened 2016-07-14 19:01 UTC
Issue submission requested by Tatu from jackson-user list question: https://groups.google.com/forum/#!topic/jackson-user/GOj0uGn_nTg

I'm using Jackson 2.8.0 to serialize some JPA Entities over a REST API with Spring Data REST. I'm having a problem with serializing an Array of Entities that contain references to the same child object. All objects are using JsonIdentityInfo as below, where the key property is a Long @Id field.

`@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "key", scope = MyClass.class)`

I believe the expected JSON should look like the below. The relevant object is supportEmailAddress.

```
"companies" : [ {
  "key" : 1,
  "name" : "company1",
  "supportEmailAddress" : {
    "key" : 1,
    "emailAddress" : "email@support.com"
  }
  "owner" : {
    "key" : 1,
    "name" : "owner 1",
    "_links" : {
      "company" : {
        "href" : "http://localhost:8080/company/1"
      }
    }
  }
}, {
  "key" : 2,
  "name" : "company2",
  "supportEmailAddress" : {[1]}
  "owner" : {
    "key" : 2,
    "name" : "owner 2",
    "_links" : {
      "company" : {
        "href" : "http://localhost:8080/company/2"
      }
    }
  }
```

The first time the child object is referenced, it serializes correctly. The second time, it fails with the stack trace below.

```
Caused by: com.fasterxml.jackson.core.JsonGenerationException: Can not write a number, expecting field name
at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1676)
at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:925)
at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeNumber(UTF8JsonGenerator.java:787)
at com.fasterxml.jackson.databind.ser.std.NumberSerializers$LongSerializer.serialize(NumberSerializers.java:188)
at com.fasterxml.jackson.databind.ser.impl.WritableObjectId.writeAsId(WritableObjectId.java:35)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase._serializeWithObjectId(BeanSerializerBase.java:584)
at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanSerializer.serialize(UnwrappingBeanSerializer.java:114)
at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.serializeAsField(UnwrappingBeanPropertyWriter.java:127)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
at com.fasterxml.jackson.databind.SerializerProvider.defaultSerializeValue(SerializerProvider.java:985)
at org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer.serialize(PersistentEntityJackson2Module.java:193)
at org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer.serialize(PersistentEntityJackson2Module.java:140)
at com.fasterxml.jackson.databind.SerializerProvider.defaultSerializeValue(SerializerProvider.java:985)
at org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$NestedEntitySerializer.serialize(PersistentEntityJackson2Module.java:356)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)x
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase._serializeWithObjectId(BeanSerializerBase.java:600)
at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanSerializer.serialize(UnwrappingBeanSerializer.java:114)
at com.fasterxml.jackson.databind.ser.impl.UnwrappingBeanPropertyWriter.serializeAsField(UnwrappingBeanPropertyWriter.java:127)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
at com.fasterxml.jackson.databind.SerializerProvider.defaultSerializeValue(SerializerProvider.java:985)
at org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer.serialize(PersistentEntityJackson2Module.java:193)
at org.springframework.data.rest.webmvc.json.PersistentEntityJackson2Module$PersistentEntityResourceSerializer.serialize(PersistentEntityJackson2Module.java:140)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:616)
at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:519)
at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:31)
at org.springframework.hateoas.hal.Jackson2HalModule$HalResourcesSerializer.serialize(Jackson2HalModule.java:340)
at org.springframework.hateoas.hal.Jackson2HalModule$HalResourcesSerializer.serialize(Jackson2HalModule.java:302)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1428)
at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:930)
at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:269)
... 57 more
```

If I remove the JsonIdentityInfo, I get the results back correctly. However, there are no Object references, and the full child object is serialized every time it is referenced. I'm concerned that this "fix" is not effective, because I originally added the JsonIdentityInfo annotations to get around some recursive relationships (ORM bi-directional stuff). If I have to remove them every time I might refer to the same instance in a result set, what is the point of the JsonIdentityInfo annotation in the first place? 

I'm sure I'm just applying something incorrectly, but I'm not able to find documentation on what I may be missing. Do I need a custom serializer to make use of this feature?

Attaching minimal example project. Extract and execute gradlew bootRun. Navigate to `localhost:8080/company` to see the bug. Full Stack trace is not logged by default and would require debugging or custom exception handler to be applied. Error message is visible on console. Navigating to individual objects (e.g. /company/1) works correctly. 

To validate /company works without the duplicate child object, edit rest-api/src/main/resources/data.sql and either set SUPPORT_EMAIL_ADDRESS null or to 3 for company 1 or company 3 and restart the application.

Ex: 
`2016-07-14T13:50:49,734 WARN  [mvc.support.DefaultHandlerExceptionResolver] [http-nio-8080-exec-2] Failed to write HTTP message: org.springframework.http.converter.HttpMessageNotWritableException: Could not write content: Can not write a number, expecting field name; nested exception is com.fasterxml.jackson.core.JsonGenerationException: Can not write a number, expecting field name`

[databind-bug.zip](https://github.com/FasterXML/jackson-databind/files/364596/databind-bug.zip)

**Comment by JeffQuandt** [comment] 2016-07-14 19:07
Additional info:

This was originally identified with jackson-databind 2.7.4. I upgraded to 2.8.0 to see if it resolved the issue. 

The issue also manifests whether or not the child property (i.e. Company.supportEmailAddress) is annotated with `JsonIdentityReference`. The provided example includes the annotation.

**Comment by cowtowncoder** [comment] 2016-07-15 02:39
Looking at stack trace I see a reference to unwrapping... so maybe that's the key. Unwrapping is one feature I wish I had never added to Jackson, as it is nothing but trouble and performance overhead. Sigh.

**Comment by cowtowncoder** [comment] 2016-07-15 02:48
Thank you for providing reproduction. Unfortunately I don't think this allows me to reproduce the issue since the invocations go through Spring MVC, and I would need jackson-only reproduction.
From stack trace, suspicious part is in:

    PersistentEntityJackson2Module$PersistentEntityResourceSerializer.serialize(...)

which somehow manages to call

    UnwrappingBeanPropertyWriter

without `@JsonUnwrapped` anywhere. I am guessing maybe some Spring component invokes unwrapping, but if so, it leads to failure. But if it is due to call sequence it is controlled by Spring component, not Jackson.

**Comment by JeffQuandt** [comment] 2016-07-15 16:09
I've created an [issue](https://jira.spring.io/browse/DATAREST-853) with Spring Data REST for this.

**Comment by JeffQuandt** [comment] 2016-07-21 16:35
I have confirmed the Spring is including a JsonUnwrapped annotation over the _embedded payload. I'm not sure this has to do with Unwrapping. Regardless, isn't this still a Jackson bug, because the UnwrappingBeanPropertyWriter or NumberSerializer is not properly handling ObjectIds, which are a Jackson feature? 

When it tries to write the ObjectId in WritableObjectId.writeAsId, the JsonGenerator is a UTF8JsonGenerator, which returns false for canWriteObjectId. It then delegates to the default serializer, NumberSerializer. That fails as above. 

Should UTF8JsonGenerator support ObjectIds, or do I need to provide a different version (how?)? I don't see any class in Jackson that overrides the default JsonGenerator.canWriteObjectId other than JsonGeneratorDelegate. That just delegates the method to some custom class. Shouldn't the ObjectId be supported by at least one default Generator? If not, how is this feature intended to be used?

**Comment by cowtowncoder** [comment] 2016-07-21 17:53
@JeffQuandt what I'd need is a test case, reproduction of the issue.
What I can say is that Object Ids are very unlikely to work with `@JsonUnwrapped` values, and so that combination should be avoided. Same is true for unwrapping on polymorphic type handling -- in fact, unwrapping is a feature that will not play well with any other structural changes.
Unwrapping is one widely-used feature that I regret ever having added. It is very difficult to make work, adds processing overhead, and is very difficult to make work with other features.
But since it exists, challenge is in figuring out exact limitations.

As to `STATUS_EXPECT_NAME`; keep in mind this is only question of low-level validation, meaning that conceptually what is necessary is ensuring that JSON token sequence is valid. Generator has no knowledge of Object Ids, except for case of non-JSON formats that have alternative native representation (such as YAML). So the issue is not with generators but at `jackson-databind` level; it has to produce valid token sequence.

It is still possible there is something to improve upon, but to see whether this is limitation or bug, a reproduction is needed.

**Comment by JeffQuandt** [comment] 2016-07-21 21:22
I already provided a reproduction. My point was that the Unwrapping doesn't really matter to the exception. The code that is at issue is in the base classes and non-Unwrapped code as well. The rest of the Unwrapped object is serialized correctly. 

Run the example and step into the databind code as the ObjectId is built and serialized.  

If the Generator doesn't know about ObjectIds, how are they output? Should the object id include the field name ({ "key":1 } vs {1})? If so, why doesn't it get built by the PropertyGenerator? It seems like it may be a bug with PropertyGenerator that it is not outputting the field name for the property it has defined ("key").

**Comment by JeffQuandt** [comment] 2016-07-21 21:47
BeanSerializerBase has three _serializeWithObjectId methods. Two try to call writeAsId first, if that returns false they call writeAsField. One calls writeAsField only.

Here is writeAsId:

`    public boolean writeAsId(JsonGenerator gen, SerializerProvider provider, ObjectIdWriter w) throws IOException
    {
        if ((id != null) && (idWritten || w.alwaysAsId)) {
            // 03-Aug-2013, tatu: Prefer Native Object Ids if available
            if (gen.canWriteObjectId()) {  <-- All default implementations return false here
                gen.writeObjectRef(String.valueOf(id));
            } else {
                w.serializer.serialize(id, gen, provider);  
            }
            return true;
        }
        return false;
    }`

Here is writeAsField:

`    /**
     * Method called to output Object Id as specified.
     */
    public void writeAsField(JsonGenerator gen, SerializerProvider provider,
            ObjectIdWriter w) throws IOException
    {
        idWritten = true;

        // 03-Aug-2013, tatu: Prefer Native Object Ids if available
        if (gen.canWriteObjectId()) {
            // Need to assume String(ified) ids, for now... could add 'long' variant?
            gen.writeObjectId(String.valueOf(id));
            return;
        }
        
        SerializableString name = w.propertyName;
        if (name != null) {
            gen.writeFieldName(name);
            w.serializer.serialize(id, gen, provider);
        }
    }`

It seems like the failure in the JsonGenerator could be caught by writeAsId and return false instead. That would let it move on to trying writeAsField instead as the Generator seems to expect. That begs the question of why does it default to calling the writeAsObjectId if no default Generators support it? 

I apologize for being dense, but I just don't see how this ObjectId was supposed to work and I don't see how my use case is really an edge case. If using ObjectId requires a custom JsonGenerator/Serializer, why aren't those required by the annotation?

**Comment by cowtowncoder** [comment] 2016-07-21 22:29
First, regarding `writeAsObjectId()`: that is only for benefit of those generators that do have native format-specific object ids; YAML, as I mentioned, to give them a chance to use whatever facilities there are. Anything else will return `false` to signal that generic, non-native embedding is to be used.
So you should not have to implement anything yourself, unless you are writing a new generator for a new dataformat.

Second, your diagnosis on missing handling sounds reasonable.

As to reproduction, I meant a stand-alone reproduction that does not rely on a framework.
If there are external frameworks included, they can not be included as unit tests, and I really would like to have a regression test going forward.

**Comment by cowtowncoder** [comment] 2016-07-22 03:18
Also: `writeAsField` and `writeAsId` are not same thing, and two should be never be tried as alternatives.
Naming does not reflect different intent, but:

* `writeAsField` is called when Object is to be written in its entirety, and `id` is to be one of properties: this means that context must be OBJECT (that is, between '{' and '}' in case of JSON), and that (at least) two tokens must be written: field/property name, and value (VALUE_STRING or VALUE_NUMBER_INT usually)
* `writeAsId` is called when reference to an Object is to be written as "object reference": this will be value of a property or element of an array; only value is to be written. Regular serializer is used for Object Id value.

Further, in case of native Object Ids (YAML), two will use different underlying entity: `writeAsField` will write an "anchor" `writeAsId()` will write "alias".

**Comment by JeffQuandt** [comment] 2016-07-22 14:38
>Also: writeAsField and writeAsId are not same thing, and two should be never be tried as alternatives.

All of the _serializeObjectId implementations in BeanSerializerBase call writeAsId first, and, if that fails, then try writeAsField. 

When you say native ObjectIds, can you explain a bit further? Is this feature not intended for JSON over HTTP? If it is supported, how is an ObjectId supposed to look/work? 

Do you have a suggestion for making ObjectIds work that doesn't require a code fix?

As for reproduction, I'm not sure how to set the scenario up without the framework initializing Jackson. A list of two beans that both have a reference to the same third bean should be sufficient.

**Comment by cowtowncoder** [comment] 2016-07-22 17:31
Ok. Maybe I am getting confused with my own naming schemes. :)

So, native Object Ids. Native here means that dataformat itself has a construct for Object Ids, and JSON does not have any, nor do most other dataformats. So it is not meant for JSON, but mainly to allow producing YAML that uses anchors, tags and labels (that is, both native Object and Type Ids) as YAML is expected to be used. These constructs work different from the work-around used for JSON -- instead of being mixed in data (that is, additional inline data) they are metadata, something not exposed as payload.

I would like to fix the library, but at this point I will need a stand-alone reproduction. That should help finding the fix; or, in worst case, documenting limitation. I do not code outside library should have to (or even try to) work around issues; if Jackson can not handle Object Id inclusion I suspect it is very difficult if not impossible to implement it outside.

**Comment by JeffQuandt** [comment] 2016-07-22 19:24
I added a test case to /failing which reproduces the issue in master. I'm new to Github, so apologies if I messed up the PR somehow.

Please let me know if I can help further.

**Comment by JeffQuandt** [comment] 2016-07-22 21:29
I should also note that I did a bit more digging while creating the test case. This **is** an Unwrapping specific problem. The issue is in UnwrappingBeanPropertyWriter.serializeAsField. It specifically checks if it is using an Unwrapping serializer and does not call writeFieldName if so.

        // note: must verify we are using unwrapping serializer; if not, will write field name
        if (!ser.isUnwrappingSerializer()) {
            gen.writeFieldName(_name);
        }

I'm not sure what the side effects of removing this check would be, so I didn't include it in the pull request.

**Comment by JeffQuandt** [comment] 2016-07-28 21:09
I wanted to check if there were any updates on this issue.

**Comment by cowtowncoder** [comment] 2016-07-28 22:06
@JeffQuandt unfortunately haven't had time to work on this.

**Comment by cowtowncoder** [comment] 2016-07-29 18:23
As per notes on PR, looks like the issue is duplication of `id` field: field is written twice, even in "working" case. I think this is what actually causes the problem for reference; first `{"id":3` is written, and this breaks otherwise legit serialization of id number. If that part is not written, serialization works. 
And it does work if `@JsonUnwrapped` is not included for `child`.

So I think this should be fixable, but may take a while to dig into details. The failing test is now in place, at any rate, and should make fix and verification much easier; thank you for providing it!

**Comment by JeffQuandt** [comment] 2016-08-31 15:48
Just checking to see if there's been any progress on this issue. Thanks.

**Comment by cowtowncoder** [comment] 2016-08-31 22:02
@JeffQuandt No progress unfortunately.

**Comment by epotvin** [comment] 2016-10-28 19:15
Until this bug is fixed, do you guys have found any workaround?

**Comment by mangrish** [comment] 2017-03-20 15:31
This affects the Spring Data REST stack (including all related projects like Spring Data JPA and Spring Data Neo4j, which makes heavy use of graph like structures).

**Comment by kane0409** [comment] 2017-04-18 06:54
Hi, have you get the answer of the question? I have got the same problem as yours.

**Comment by kane0409** [comment] 2017-04-18 06:55
Hi, have you get the answer of the question? I have got the same problem as yours. @JeffQuandt

**Comment by kane0409** [comment] 2017-04-18 06:55
Hi, have you got the answer of the question? I have got the same problem as yours. @JeffQuandt

**Comment by apezel** [comment] 2017-05-10 08:42
I have the same problem. Any progress on this bug ?

**Comment by gledsonrabelo** [comment] 2017-06-19 19:56
+1

**Comment by mvharsha** [comment] 2017-10-03 08:30
I am getting below error while trying to serialize :  It looks like same issue as above , anybody has a resolution please let me know .

com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value

	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:1961)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writePPFieldName(UTF8JsonGenerator.java:372)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:183)
	at com.inubit.ibis.plugins.json.types.serializer.ObjectTypeSerializer.serialize(ObjectTypeSerializer.java:21)
	at com.inubit.ibis.plugins.json.types.serializer.ObjectTypeSerializer.serialize(ObjectTypeSerializer.java:16)
	at com.inubit.ibis.plugins.json.types.serializer.JAXBElementSerializer.serialize(JAXBElementSerializer.java:16)
	at com.inubit.ibis.plugins.json.types.serializer.JAXBElementSerializer.serialize(JAXBElementSerializer.java:13)
	at com.inubit.ibis.plugins.json.types.serializer.ArrayTypeSerializer.serialize(ArrayTypeSerializer.java:20)
	at com.inubit.ibis.plugins.json.types.serializer.ArrayTypeSerializer.serialize(ArrayTypeSerializer.java:13)
	at com.inubit.ibis.plugins.json.types.serializer.JAXBElementSerializer.serialize(JAXBElementSerializer.java:16)
	at com.inubit.ibis.plugins.json.types.serializer.JAXBElementSerializer.serialize(JAXBElementSerializer.java:13)
	at com.inubit.ibis.plugins.json.types.serializer.ObjectTypeSerializer.serialize(ObjectTypeSerializer.java:36)
	at com.inubit.ibis.plugins.json.types.serializer.ObjectTypeSerializer.serialize(ObjectTypeSerializer.java:16)
	at com.inubit.ibis.plugins.json.types.serializer.JAXBElementSerializer.serialize(JAXBElementSerializer.java:16)
	at com.inubit.ibis.plugins.json.types.serializer.JAXBElementSerializer.serialize(JAXBElementSerializer.java:13)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3164)

**Comment by JeffQuandt** [comment] 2018-03-28 16:10
The only workaround I found was to `JsonIgnore` reciprocal relationships whenever possible. It's not perfect in that you still may get into issues where the same object will be referenced more than once and an ObjectId would be created. 

The other option is to not use `JsonIdentityInfo`, which defeats the purpose of the optimization altogether but does avoid the issue.

**Comment by maresja1** [comment] 2019-05-07 18:59
I also ran into similar problem when using custom `UnwrappingBeanSerializer`, the serializer stopped working, when it was not used in the context of `@JsonUnwrapped` (with the same exception). 

Fix for the issue was to wrap the content of `serializeFields` in `gen.writeStartObject()` and `gen.writeEndObject()`, when `gen.getOutputContext().hasCurrentName()` returned `true`. Maybe I am using the `UnwrappingBeanSerializer` in a wrong way (please let me know, if that is the case), but maybe it will throw some light on the aforementioned problem.

**Comment by cowtowncoder** [comment] 2019-05-11 06:06
@maresja1 `UnwrappingBeanSerializer` is an internal class and should only really be used by databind itself, to implement `@JsonUnwrapped` handling. So using it directly is usually a bad idea, and may end up not working reliably across versions since its interface is not designed for external use and may be changed across minor versions (except obviously standard API parts from `JsonSerializer`).
 But if you end up using it then it probably makes sense to do what you describe.

**Comment by yushijinhun** [comment] 2019-12-08 13:23
https://github.com/FasterXML/jackson-databind/blob/f315f1b22f47c9cfff2af9629910cb7c38c05463/src/main/java/com/fasterxml/jackson/databind/ser/std/ReferenceTypeSerializer.java#L300

I think change the expression to
```java
_unwrapper != null && _valueSerializer.isUnwrappingSerializer()
```
may fix it. But `_valueSerializer` can be null here.

**Comment by cowtowncoder** [comment] 2020-04-02 05:13
Not sure what could be done here; closing.

**Closed by cowtowncoder** 2020-04-02 05:13 UTC

**Comment by cowtowncoder** [comment] 2026-03-12 01:00
I think we need to produce better error message as combination of `@JsonUnwrapped` and `@JsonIdentityInfo` is not supported (or supportable).

**Comment by cowtowncoder** [comment] 2026-03-12 03:05
Now catching incompatible usage, failing explicitly. Will be in 3.2.0.
