### ISSUE TITLE
Default constructor and no setters on data object break serialization

### ISSUE THREAD

**Issue by PeterWippermann** [FasterXML/jackson-databind#1337] opened 2016-08-15 22:51 UTC
I've set up [a small app](https://github.com/PeterWippermann/person-repository) with a REST-Service serving `Person` objects. Therefore I'm using `jackson-jaxrs-json-provider` on version `2.7.6`.

`Person` used to have [a 3-arg-constructor and getters](https://github.com/PeterWippermann/person-repository/blob/bb18b244e1e6b685e214daeb6adf4049dd130a2d/person-repo-client-api/src/main/java/de/pwipp/person/api/model/Person.java) only and serialisation was working as expected: [verbose JSON](https://github.com/FasterXML/jackson-databind/files/419117/verbose.without.default.constructor.txt)

Then I added a default constructor to be able to build a client. This broke serialisation: [empty JSON](https://github.com/FasterXML/jackson-databind/files/419119/empty.with.default.constructor.without.setters.txt)

I realised that the serialiser may misses the setters, so [I added them](https://github.com/PeterWippermann/person-repository/commit/728014b5cbe29d84db38b4ee4baaa6eb4dbf92fe). Funny thing, the JSON became leaner: 
[lean JSON](https://github.com/FasterXML/jackson-databind/files/419123/normal.with.default.constructor.and.setters.txt)

**I've got three questions:**
1. Why don't I get any warnings that the setters are missing?
2. Why do I need the setters at all?
3. Why is the JSON more verbose when there is no default constructor?

Please let me know, if you need more info :-)

**Comment by cowtowncoder** [comment] 2016-08-15 22:58
Would it be possible to distill information into a single example class, showing what you did, and what you expected to get.

As to warnings, if there is a JSON property that does not have any way to be set (via visible setter or field, or `@JsonCreator` annotated constructor with `@JsonProperty` annotated parameters), an exception will be thrown -- unless configuration has been changed to ignore such "unknown" properties. I think newer versions of Spring MVC have changed this default, which can easily hide problems.

I have no idea how existence (or not) of default constructor should have any effect on serialization; it should not. Serialization is based on visible getters/fields (either `public`, or explicitly annotated).

**Comment by PeterWippermann** [comment] 2016-08-16 07:31
@cowtowncoder Thanks for paying attention to my issue :-)

Is it really necessary to distill a single example class? How should this look like, do you have an example from another issue? Actually I hoped, that my publicly available app would be fine for debugging: https://github.com/PeterWippermann/person-repository . A `mvn install` in the root folder will generate a .war file in the web project. The REST service's address is: `localhost/.../resources/persons`

Why did you mention Spring MVC? AFAIK I have no dependency on it.
The warnings (I am missing) should be written to StdOut, right?
Any idea why the JSON becomes more verbose without the default constructor?

Thanks in advance.

**Comment by cowtowncoder** [comment] 2016-08-17 22:55
@PeterWippermann I mentioned SpringMVC just in case you might be using it, since I remember their being some controversy on their changing `ObjectMapper` defaults for the unknown-property handling. Good to know this is not relevant here.

My asking for a single class minimal example is because that is often the most efficient way for me to see, so that instead of setting up a project (if it's maven/eclipse importable, not big deal but still bit more time) I can often spot a problem just from issue tracker. Or at least have a look. Otherwise if I do not have 10 minutes to set up the project, I'll work on some other issue, and come back when I have bigger chunk of time for more involved debugging.

So: the existing repo works, it just may take bit longer for me to find time to dig into issue that way. Smaller the reproduction, faster things move. :)

**Comment by cowtowncoder** [comment] 2016-10-04 02:54
I had a look at the project, but I really do not have time to go through actual web service calls.
A reproducible locally run simple example, with expected outcome would be needed.
All it needs is set of classes to use (as small as possible), and then code to trigger unexpected behavior; constructing instance to serialize by code, or if need be, resource file.

I'll leave the issue open for a while until closing it.

**Comment by PeterWippermann** [comment] 2016-10-04 20:11
Sorry, I can't provide this. Please go ahead and close this issue...

**Closed** 2016-10-04 23:53 UTC
