### ISSUE TITLE
Combination of `@JsonUnwrapped` and `@JsonAnySetter` results in `BigDecimal` instead of `Double`

### ISSUE THREAD

**Issue by hjohn** [FasterXML/jackson-databind#3277] opened 2021-09-15 09:35 UTC
**Describe the bug**
When deserializing a float value to a structure nested in JsonUnwrapped and JsonAnySetter, the float value becomes a BigDecimal instead of Double (USE_BIG_DECIMAL_FOR_FLOATS is left to its default setting).

**Version information**
2.12.4

**To Reproduce**

    @Test
    public void test() throws JsonParseException, JsonMappingException, IOException {
        ObjectMapper mapper = new ObjectMapper();

        Holder holder = mapper.readValue("{\"value1\": -60.0, \"value2\": -60.0}", Holder.class);

        assertEquals(Double.class, holder.value1.getClass());
        assertEquals(Double.class, holder.holder2.data.get("value2").getClass());
    }

    public static class Holder {
        private Object value1;
        @JsonUnwrapped private Holder2 holder2;

        public Object getValue1() {
            return value1;
        }

        public void setValue1(Object value1) {
            this.value1 = value1;
        }
    }

    public static class Holder2 {
        private Map<String, Object> data = new HashMap<>();

        @JsonAnyGetter
        public Map<String, Object> getData() {
            return data;
        }

        @JsonAnySetter
        public void setAny(String key, Object value) {
            data.put(key, value);
        }
    }

**Expected behavior**
Would still expect a Double here.

**Comment by hjohn** [comment] 2021-09-15 10:05
Workaround:

    @JsonAnySetter
    void setAny(String key, Object value) {
        parameters.put(key, value instanceof BigDecimal bd ? bd.doubleValue() : value);
    }

**Comment by yawkat** [comment] 2021-09-16 06:38
Looks to be caused by the fix for #2644. For that fix, the TokenBuffer buffers the exact value because the necessary precision can't be determined beforehand (the target type might turn out to be `BigDecimal` later). When the value is then read into an `Object` field, like in your any setter case, it then simply uses the already buffered number value, meaning `BigDecimal`.

Not sure if changing back to double downstream is a good idea. After all, the main reason for `USE_BIG_DECIMAL_FOR_FLOATS` as `false` is to avoid the perf impact of `BigDecimal`, but in this case the `BigDecimal` is already present anyway.

**Comment by hjohn** [comment] 2021-09-16 11:57
True, however, code does sort of expect a double since USE_BIG_DECIMAL_FOR_FLOATS is set to false, so it was a bit surprising to see values, which used to be doubles, change to BigDecimal because of a structural change (using JsonUnwrapped/JsonAnySetter).

The work-around is fine for now, but I would think that when filling these values it should check the USE_BIG_DECIMAL_FOR_FLOATS setting and convert them back to doubles if it is set to false.

**Comment by cowtowncoder** [comment] 2021-09-16 22:52
Quick note: this (`double` <-> `BigDecimal` coercions) is a known issue, and I think there are existing filed issue(s) for it.

The problem is tricky to solve for a few reasons. Basically:

1. Some formats (binary ones) do have clear type which we can use, and should retain original type as "the" natural type. Others (JSON, XML, CSV, Properties) does not, and thereby it is all about what caller expects or asks for.
2. For latter type ("contextual natural/expected type"), we should defer commitment to as late as possible -- up to and including `TokenBuffer`
3. To support (2), we'd probably need to figure out a way for lazy/deferred decoding: so textual parser simply validates that representation is legit FP, but does not decode value (handling of `double` / `BigDecimal` is different)
4. Although `BigDecimal` is a superset, and theoretically we could always start with it (minus overflows etc?), it also has, I think, more overhead so always defaulting to it can be expensive
5. Support `USE_BIG_DECIMAL_FOR_FLOATS` == true is much easier; `false` is ... tricky.

So. Alas, it's a tricky problem altogether.

**Comment by seadbrane** [comment] 2022-03-23 19:04
We ran into this issue when upgrading to 2.12 and I see that it is also not fixed in 2.13.
It is also a bit interesting that just calling  p.getNumberType() changes the behavior and results in a double instead of defaulting to BigDecimal.  
Are there any plans for fix?  Maybe adding a new DeserializationFeature to preserve the existing behavior?

**Comment by seadbrane** [comment] 2023-12-13 16:05
Any update on this issue?

**Comment by pjfanning** [comment] 2023-12-13 16:09
@seadbrane do you want to try Jackson 2.16.0 yourself? There have been some changes in number handling. This issue was not addressed directly but it's possible the behaviour has changed due to the other number changes in Jackson.

**Comment by JooHyukKim** [comment] 2023-12-13 16:22
> There have been some changes in number handling. This issue was not addressed directly but it's possible the behaviour has changed due to the other number changes in Jackson.

@pjfanning was right on point. See #4259 reproduction passes now

**Comment by seadbrane** [comment] 2023-12-13 17:03
Yes, not able to repro anymore either.  Thanks for the update.

**Closed** 2023-12-13 21:42 UTC
