### ISSUE TITLE
Add caching of resolved generic types for `TypeFactory`

### ISSUE THREAD

**Issue by plokhotnyuk** [FasterXML/jackson-databind#1277] opened 2016-06-24 14:27 UTC
We started migration from 2.6.х to 2.7.х and got 40x slow down in parsing of JSON strings to list of strings values.

Following changes fix it: https://github.com/FasterXML/jackson-databind/pull/1276
@cowtowncoder please consider to review & merge it to 2.7 branch and above.

Fast feedback or release with this fix will be greatly appretiated.

Thanks,
Andriy

**Comment by sonenko** [comment] 2016-06-24 14:32
+1

**Comment by cowtowncoder** [comment] 2016-06-24 17:44
How and where did performance change? I would like to see a reproduction to make sure I understand. Use of generic types as root value is discouraged; and type resolution should rarely be a performance bottleneck, esp. so for generic types. So I would want to make sure that this isn't masking some other issue.
Would it be possible to add a link to use case, or sample code, or just simplified class definition + usage to show what is the problem case?

As to backporting, branch 2.6 is closed, so no new full releases are planned. So it is unlikely change would be ported.

With 2.7 I do have concerns about change that could fundamentally break things in various places -- caching can be great for performance, but may also introduce very subtle bugs, especially if bound type parameters accidentally clash (that is, earlier resolution with certain bindings get cached and used for slightly different bindings). But if fix was deemed safe enough, that would be doable.

2.8.0 is to be released within a week so that would, in general, be the most likely addition point.

**Comment by plokhotnyuk** [comment] 2016-06-25 06:43
Here is code which catch ineficient parsing for list of strings:

` 
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper
   
def performance[R](name: => String, series: Int, times: Long)(f: => R): R = {
  var result: R = null.asInstanceOf[R]
  for (s <- 1 to series) {
    var i = 0
    val t = System.nanoTime()
    while (i < times) {
      result = f
      i += 1
    }
    val d = System.nanoTime() - t
    println(f"$name elapsed: ${d / 1000000} ms, performance: ${times * 1000000000.0 / d}%2.2f op/s")
  }
  result
}

val json = (1 to 1000).map(_.toString).mkString("[\"", "\",\"", "\"]")
val mapper = new ObjectMapper with ScalaObjectMapper {
  registerModule(DefaultScalaModule)
}
val request = performance("parse list of strings", 5, 10000) {
  mapper.readValue[List[String]](json)
}
`

But you are right, that need to check if there are any other posibilities to fix the problem with Scala collections w/o affecting of other users (Java, Kotlin, etc.).

**Comment by cowtowncoder** [comment] 2016-06-27 21:10
Ok. So it's basically using `List<String>` as the type. And there must be some Scala magic in passing that; perhaps `ScalaObjectMapper` has overloaded method to get to `JavaType`.
I am just trying to figure out how to reproduce so I can measure effects of the change.

**Comment by cowtowncoder** [comment] 2016-06-28 01:37
@plokhotnyuk Quick question; you said "40x" slow down, but perhaps you mean "40%" (40 percent)? The reason I am asking is that with a simple java-only test, with a small single-element JSON Array I can get difference of maybe 2.5x, which while big difference isn't quite that drastic. But it is possible there might be something additional that Scala mapper does, to try to carry generic type, above and beyond what `TypeReference` (from Jackson) would do.

Another oddity is that although type resolution was indeed rewritten for 2.7, cost of generic type resolution should not have been negligible even before, so sudden addition seems odd.

How much does caching help, compared to not caching?

**Comment by cowtowncoder** [comment] 2016-06-28 03:19
For what it's worth, it does look like caching along suggested lines works and improves performance as expected. There's still cost to resolution as lookup can only be made with resolved parameter types, but difference to optimal is lower with modified caching, key.

**Comment by cowtowncoder** [comment] 2016-06-28 04:30
Ah. One more thought here: I think Scala module uses `TypeModifier`, and perhaps that has been implemented particularly inefficiently: it gets called once per resolution into `JavaType`.

.... and brief grepping shows that Scala module adds one modifier per type. Ugh. That is VERY inefficient as that would seem to create long linear call chains, without much actual benefit. It seems unlikely that users really benefit from composing modules serializer by serializer; but supporting this modularity adds all kinds of inefficiencies.

So I am guessing that 40x may actually occur with Scala, and caching in many ways works around Scala module issues more than specific cost of basic type resolution.

This doesn't mean that caching couldn't be added, but I think I better file an issue for Scala module (I don't maintain it) to address other issues.

**Comment by cowtowncoder** [comment] 2016-06-30 04:47
I added caching of generic types as suggested (with slightly different impl); while it may be masking another problem improvement may make sense nonetheless. Fixed in 2.7.6 and 2.8.0, to be released.

**Comment by cowtowncoder** [comment] 2016-06-30 18:05
Hmmh. My concerns about caching seem to be (alas!) valid: Travis shows failures:

https://travis-ci.org/FasterXML/jackson-databind/jobs/141404620

which I can not replicate locally. But symptoms suggest that caching of resolved generic type is probably introducing unwanted handlers (`JavaType` can have up to 4 handlers associated type).
Oddly enough 2.7 branch is NOT failing, but I assume it all has to do with order of running tests.

I suspect problem has mostly to do with per-property annotations (like `@JsonDeserialize(using)`, `@JsonSerialize(using)` for value handler, `@JsonTypeInfo` for type handler), but I am not quite sure how those could be attached during type resolution itself -- there are mutators, so a new instance needs to be created.
But by adding checks to verify cached instances have no handlers, I can reproduce 2-3 failures for a full test run, locally, so there is a problem to fix regardless.

There are a few ways to try to tackle this;

1. Remove caching from generic types (although in theory this could also affect non-generic types, as handlers are associated via properties, it's just that problems much more likely with container types)
2. Try to see if sharing of global `TypeFactory` might be partially to blame (i.e. create new instance per ObjectMapper, even if no `TypeModifier` registered). Most likely this would just mask problems as it seems plausible
3. Prevent caching of types with handlers.

Approach (3) seems most sensible in general, although I am tempted to do (1) for 2.7; patch releases should try to minimize the risks, and this seems like something that could cause gnarly very hard to debug problems.

So I will probably do that: undo fix for 2.7, rewrite it for 2.8.

**Closed** 2016-07-01 06:32 UTC

**Comment by cowtowncoder** [comment] 2016-07-02 03:35
Fixed for 2.8, no test failures. Increased max cache size to 200: prefer not to extend indefinitely because cache is global, and NOT tied to `ObjectMapper` instance (unlike almost every other entity).
However, sub-classing does allow passing differently configured `LRUMap`. Will also add `withCache()` for 2.8.
