### ISSUE TITLE
Default ordering for record with @JsonProperties fields mixed with fields without annotations

### ISSUE THREAD

**Issue by mumukiller** [FasterXML/jackson-databind#4712] opened 2024-09-24 10:21 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Expected order of fields in result of `writeValueAsString` method should have the same order as order fields which are declared in record, but in fact it's not true.

### Version Information

2.17.2

### Reproduction

Below there is a simple test
```java
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class WhereIsMyOrderTest {

  private final ObjectMapper mapper = new ObjectMapper();

  @Test
  public void test() throws JsonProcessingException {
    var dto = new TestDto("1", BigDecimal.ONE,"3", "4");
    var result = mapper.writeValueAsString(dto);

    assertEquals("{\"a\":\"1\",\"b\":\"1\",\"c\":\"3\",\"d\":\"4\"}", result);
  }

  public record TestDto(
          @JsonProperty("a") String a,
          BigDecimal b,
          @JsonProperty("c") String c,
          String d) {}
}
``` 

Expected :{"a":"1","b":"1","c":"3","d":"4"}
Actual   :{"b":1,"d":"4","a":"1","c":"3"}

So i expect that fields in the result will be int he same order as declared in record

Probably that my understanding of how it should work is wrong.

### Expected behavior

{"a":"1","b":"1","c":"3","d":"4"}

**Comment by yihtserns** [comment] 2024-09-24 10:37
> 2.15.4

Are you sure that's the correct version?  From my local testing:
- 2.14.2: `{"a":"1","c":"3","b":1,"d":"4"}`
- 2.15.0: `{"a":"1","c":"3","b":1,"d":"4"}`
- 2.15.4: `{"a":"1","c":"3","b":1,"d":"4"}`

**Comment by JooHyukKim** [comment] 2024-09-24 10:45
Great! Thank you for testing @yihtserns 👍🏼

2.18 version is in release candidate state now. Please wait and use 2.18 release @mumukiller 👌🏼👌🏼

**Comment by yihtserns** [comment] 2024-09-24 10:47
Is there already a test for the scenario above?  If not, should there be one?

**Comment by mumukiller** [comment] 2024-09-24 10:47
Sorry i found this issue due to spring boot update, there was some issues with gradle, the real current version is 2.17.2

**Comment by cowtowncoder** [comment] 2024-09-24 15:26
If this is fixed in 2.18.0, let's close?

**Comment by yihtserns** [comment] 2024-09-24 15:29
@cowtowncoder do you remember if you added a test with the scenario above, when you did #4515?

**Comment by cowtowncoder** [comment] 2024-09-24 15:31
Ok: I think #4617 ?

**Comment by cowtowncoder** [comment] 2024-09-24 15:33
Closing as duplicate of #4617.

**Closed by cowtowncoder** 2024-09-24 15:33 UTC
Labels: duplicate, 2.17
