### ISSUE TITLE
jackson-jaxrs-json-provider-2.12.2.pom is missing in Maven Central

### ISSUE THREAD

**Issue by jschneider** [FasterXML/jackson-databind#3071] opened 2021-03-04 10:22 UTC
Updating to latest 2.12.2 version.
Gradle shouts at me, that 

https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.12.2/jackson-jaxrs-json-provider-2.12.2.pom

is missing.

Am doing something wrong?

**Comment by cowtowncoder** [comment] 2021-03-04 18:30
No, although this is the wrong repository. Problem exists but its root cause unclear:

https://github.com/FasterXML/jackson-jaxrs-providers/issues/138

and solution unclear as well.

**Comment by cowtowncoder** [comment] 2021-03-09 18:25
Closing since there is the other ticket (plus issue belongs on JAX-RS repo anyway) to follow.

**Closed by cowtowncoder** 2021-03-09 18:25 UTC
Labels: to-evaluate
