### ISSUE TITLE
Classloader leak: DEFAULT_ANNOTATION_INTROSPECTOR holds annotation reference (JBoss)

### ISSUE THREAD

**Issue by ciis0** [FasterXML/jackson-databind#3771] opened 2023-02-05 11:43 UTC
**Describe the bug**

Similar to #3093, in JBoss `JacksonAnnotationIntrospector._annotationsInside`, referenced statically via `ObjectMapper.DEFAULT_ANNOTATION_INTROSPECTOR`, might contain references to annotations from Deployment Class-Loaders, which leads to leaking those when the deployment is stopped/undeployed.

**Version information**
Which Jackson version(s) was this for?

2.13.4.2, but from the code it looks like it's still true today.

https://github.com/FasterXML/jackson-databind/blob/de62c677b12c02967c9620a11c1c5208f701cfef/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L375
https://github.com/FasterXML/jackson-databind/blob/de62c677b12c02967c9620a11c1c5208f701cfef/src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java#L82
https://github.com/FasterXML/jackson-databind/blob/de62c677b12c02967c9620a11c1c5208f701cfef/src/main/java/com/fasterxml/jackson/databind/introspect/JacksonAnnotationIntrospector.java#L162

**To Reproduce**

https://github.com/ciis0/jackson-3771

**Expected behavior**
If reproduction itself needs further explanation, you may also add more details here.

**Additional context**

Reference to annotation class from deployment class-loader in `JacksonAnnotationIntrospector `instance: 

![image](https://user-images.githubusercontent.com/16290850/216833558-dbb80246-58b9-4ac2-a155-966f5aa5ba2d.png)

Static reference to that annotation introspector instance from `ObjectMapper`:

![image](https://user-images.githubusercontent.com/16290850/216833563-b36078af-7404-4ea1-a888-ea60944903b4.png)

**Comment by ciis0** [comment] 2023-02-05 15:39
I have uploaded a reproducer here: https://github.com/ciis0/jackson-3771

**Comment by pjfanning** [comment] 2023-02-05 15:52
I'd say this should be fixed by JBoss. That LRUMap can readily be garbage collected. @cowtowncoder might have his own opinion but to me, I would need to be convinced why this is not a JBoss issue.

**Comment by pjfanning** [comment] 2023-02-05 15:55
In theory, Jackson could use a WeakHashMap instead of LRUMap but JBoss may still fail to clean up other Jackson refs.

**Comment by ciis0** [comment] 2023-02-05 16:36
Ah, this is hidden away in #3093: the LRUMap is (indirectly) referenced via a static field in `ObjectMapper.DEFAULT_ANNOTATION_INTROSPECTOR` (`JacksonAnnotationIntrospector`), no stand-alone object. :)

I have updated the description.

**Comment by ciis0** [comment] 2023-02-05 17:03
i.e. the problem is not that the LURMap is not cleaned up, but that the LRUMap contains _keys_ from another class-loader and with this keeps alive the other classloader until jackson's classloader is cleaned up -- which does not happen at runtime, you have to restart JBoss for that.

**Comment by pjfanning** [comment] 2023-02-05 17:15
Maybe a clear method on the Annotation inspector could allow users to clear up that old data

**Comment by cowtowncoder** [comment] 2023-02-05 17:44
Ah. Ok now it all makes sense. Series of unfortunate events, unintended side effects. So it's due to 2 things:

1. Use of `Class<?>`es from wherever (annotation types) as keys AND
2. Static reference to default introspector instance

Although (2) might be initially easier, I think (1) might actually make more sense: without resolving that there would still be possibility of retention via non-static references. Use of arbitrary Class instances as keys tends to lead to hard to track down retention.

A simple way that I'll probably is to use `String` of class name as the key. There's theoretical concern of same class via different class loaders, but I'd think these should refer to same definition (at leas wrt existence of `@JacksonAnnotationsInside`).

Unfortunately fix needs to go in 2.15.0, I think, just due to risk involved (no API change needed).
But I think it's otherwise fairly straight-forward; will tackle this now.

**Comment by pjfanning** [comment] 2023-02-05 19:04
@cowtowncoder there is com.fasterxml.jackson.databind.type.ClassKey which seems to have been written for this purpose. But it might keep unwanted references too. It might be worth reviewing if ClassKey needs to be rewritten too - to drop the Class<?> refs and only keep the name.

**Comment by cowtowncoder** [comment] 2023-02-05 19:39
@pjfanning That's something to consider too I suppose, although its actually usage should be less problematic as lookup maps are bound to individual `ObjectMapper`s and there are no static singletons.

Having said that.... I am starting to think that maybe `AnnotationIntrospector` static instance really should go too. It being stateful makes that a bad idea.
So perhaps I'll do both (1) and (2).

**Comment by cowtowncoder** [comment] 2023-02-05 19:42
Ok, not so fast I guess. The problem is not just `ObjectMapper.DEFAULT_ANNOTATION_INTROSPECTOR` but rather that it is then used in similarly shared `BaseSettings`.

What I'll do is create separate issue for follow-up work to do that refactoring.

**Closed** 2023-02-05 20:09 UTC
Labels: to-evaluate

**Comment by cowtowncoder** [comment] 2023-02-05 20:16
Created #3772 for follow up work. Also starting to think this might be one of bad speculative optimizations, overall, given that without this `JacksonAnnotationIntrospector` is nicely stateless, reusable. And that there are no measurements to really show big benefits (theoretically I can think of kinds of set ups it might... but, theoretically).
