### ISSUE TITLE
Possibly non-deterministic tests: `MapEntryFormatTest#testDefaultShapeOverride`, `TestObjectIdWithEquals#testSimpleEquals`

### ISSUE THREAD

**Issue by priyanka-28** [FasterXML/jackson-databind#3693] opened 2022-12-09 22:03 UTC
**Describe the bug**
The tests com.fasterxml.jackson.databind.format.MapEntryFormatTest#testDefaultShapeOverride and com.fasterxml.jackson.databind.objectid.TestObjectIdWithEquals#testSimpleEquals passed using normal maven-test, but showed Non-deterministic behavior under NonDex(https://github.com/TestingResearchIllinois/NonDex) and thus failed. 

**Version information**
2.15

**To Reproduce**
https://github.com/TestingResearchIllinois/NonDex
Nondex is order-dependent flaky tests detection tool developed by a research group led professor Darko at UIUC
Navigate to the project repo, compile and run the following - 

mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex

1. Brief code sample/snippet: 

Some of the error messages are as follows-

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/52324780/206802517-8491b731-8432-4a60-8218-155e25519017.png">

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/52324780/206802304-d6a01604-72f8-4c4f-8347-a94dd65c0dac.png">

2. Textual explanation: 
After some probing, I found the output from the test is not deterministic as the order of the attributes changes

**Expected behavior**
The tests should pass with nondex and be deterministic.

**Additional context**

**Comment by cowtowncoder** [comment] 2022-12-09 23:58
Note: passing with `nondex` is not an acceptance criteria per se but yes, we should not rely on behavior that is not stable. Modified title to include suspected unstable test cases.

If anyone has time and interest seems like a simple enough thing to fix (if it turns out these are problematic).

The main challenge those is reproduction; use of `nondex` is not something we'll require.

**Comment by cowtowncoder** [comment] 2022-12-11 04:07
Fixed via #3694 -- thank you @priyanka-28

**Closed by cowtowncoder** 2022-12-11 04:07 UTC
Labels: good first issue, 2.15, pr-welcome
