### ISSUE TITLE
module-info class lost during 2.18 version

### ISSUE THREAD

**Issue by bwzhang2011** [FasterXML/jackson-databind#4727] opened 2024-10-01 14:45 UTC
### Describe the bug

module info lost during the release since jackson-databind 2.18.0 version while correct in early version released like 2.17.2.  notice that 2.17.2 is correct for databind core and annotation package.  I recommend new deployed version to be released which could help the upgration of jacskon

### Version Information

2.18.0

### Reproduction

Not given

### Expected behavior

no error while import module class support

### Additional context

None

**Comment by pjfanning** [comment] 2024-10-01 14:56
Can you give more details? The issue is in jackson-databind 2.18.0 jar and only that jar?

**Comment by AndreasWBartels** [comment] 2024-10-01 20:28
compile with maven 3.9.5 (and newer) with jdk21 works (openjdk and temurin)

eclipse does not seem to be able to handle the multi version jar which it can with 2.17.2.

tested with eclipse 2024-03 and 2024-09 

there is a similar [issue](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2495) on  eclipse.jdt.core for gson

**Comment by GedMarc** [comment] 2024-10-01 20:33
That is 100% an eclipse problem,

Also found animal sniffer doesn't like compiles into alternative versions, e.g. jdk11 compiling into versions/17 , throws a java error - 
Same issue, the location of /9 is correct as well, 
This is internal to eclipse.

**Comment by pjfanning** [comment] 2024-10-01 20:37
jackson-core is a Multi-Release jar - not jackson-databind

I agree with @GedMarc that this does not appear to be an issue in jackson-core/jackson-databind and that issue is in tooling that users are using. @bwzhang2011 provided very little detail on what their issue is.

**Comment by cowtowncoder** [comment] 2024-10-01 22:59
Not sure if this might be related to a jackson-core fixed issue https://github.com/FasterXML/jackson-core/issues/1340.

Either way description is too incomplete to be actionable; closing. May be re-opened or re-filed with more information; in particular showing how to reproduce the issue.

**Comment by AndreasWBartels** [comment] 2024-10-02 12:54
This is a moditect issue https://github.com/moditect/moditect/issues/254

Which unfortunately makes it a jackson issue, because you should either downgrade or upgrade as soon as the issue for moditect is fixed.

**Comment by pjfanning** [comment] 2024-10-02 13:04
https://github.com/moditect/moditect/commit/5d63f7bfce19dbf9d17fa122a758ac2e88f93e6f seems to be in every release since 1.2.0.Final so maybe the best course of action is to downgrade to moditect 1.1.0 in all Jackson repos - 2.18 branches.

https://mvnrepository.com/artifact/org.moditect/moditect/1.1.0

**Comment by pjfanning** [comment] 2024-10-02 13:21
@AndreasWBartels Thanks for the analysis. Moditect is a pretty widely used tool and the commit that you highlight appears to have been in 3 releases of Moditect in the last 6 months. The internet is not ablaze with people complaining about broken jars. My vote would be to use an old version of Moditect until a fix is made - but that there is no reason to rush out a Jackson release.

Users can stick to older Jackson releases if they think they might be affected by this.

**Comment by cowtowncoder** [comment] 2024-10-02 17:02
Uggggh. Moditect downgrade is tricky since if I recall it comes via parent poms. And verification of newer versions, once available, seems difficult.

But if we have to, we have to.

**Comment by GedMarc** [comment] 2024-10-02 17:14
I'll update the jdk11 compat test to 2.18, should be able to add a test case there,
Will check on moditect as well

**Comment by cowtowncoder** [comment] 2024-10-04 02:12
Ok. So, if I understand this correctly, the problem reported as https://github.com/moditect/moditect/issues/254 ONLY affects `jackson-core` and NOT `jackson-databind` or other Jackson components (or at least not many).

If so, I think the safest patch would be to override plugin version just for `jackson-core` and not via `oss-parent`.

Does this make sense? My concern with `oss-parent` change is mostly that there may be fixes in Moditect (plugin) 1.2 that we'd roll back if downgrading generally.
And also, to a degree, the fact that `oss-parent` is not well versioned to align with Jackson components so changes should be incremental.

But most importantly: is the issue -- as far as we understand it -- limited to `jackson-core` only?

**Comment by AndreasWBartels** [comment] 2024-10-04 07:07
The problem affects all modules that only add module-info.java, i.e. jackson-databind, jackson-databind-jsr310.

jackson-core adds classes for different versions, which indirectly solves the problem.

**Comment by cowtowncoder** [comment] 2024-10-04 17:52
@AndreasWBartels ahhhhh. Ok, so the reverse of what I thought. This is... unfortunate to say the least.

In that case, need to consider placement. `oss-parent` may make sense, then... although `jackson-parent` could work too (or for most components, `jackson-base`).

**Comment by pjfanning** [comment] 2024-10-04 18:18
The real fix here is to get Eclipse to fix JDT.

**Comment by cowtowncoder** [comment] 2024-10-05 00:35
I agree wrt @pjfanning 's comment. But in the meantime maybe https://github.com/FasterXML/oss-parent/pull/179 is worth considering.

**Comment by bwzhang2011** [comment] 2024-10-09 23:26
@cowtowncoder  why dou you agree the suggestion from @pjfanning,  solve the compatibility should be first choice other than adjure eclipse to be adjust to the change between different version of jackson release.  and of source it does appear in eclipse enviroment when your project relates to the module-info. so  how can I solve it without major modification or wait for next release of jackson ?

**Comment by pjfanning** [comment] 2024-10-09 23:46
@bwzhang2011 dozens of jars are published with moditect. Since moditect made its change, lots of them of uptaken the change. The Java command is happy with the jars we publish.

**Comment by cowtowncoder** [comment] 2024-10-09 23:48
@bwzhang2011 Note that the First != Best -- I think Eclipse fixing tooling would be the BEST fix (assuming I understand the issue correctly). It might not be the FIRST thing we do -- we may well need to use a work-around like downgrade.

**Comment by cowtowncoder** [comment] 2024-10-13 04:10
Ok: so, Moditect plugin version is downgraded to 1.1.0 for Jackson 2.18 branch, and I verified that resulting jar/bundle now has intermediate directory entries.
Fix was actually via:

https://github.com/FasterXML/jackson-parent/issues/15

but I'll mark this as fixed in release notes as well.

Changes will be seen in 2.18.1 release.

I hope there will be a new Moditect release at some point so we can upgrade to the latest, but for now I hope this does the trick.

**Closed by cowtowncoder** 2024-10-13 04:10 UTC
Labels: to-evaluate
