### ISSUE TITLE
ObjectWriter::writeValues() leads to NoSuchMethodError in 2.16.0

### ISSUE THREAD

**Issue by estomagordo** [FasterXML/jackson-databind#4207] opened 2023-11-16 18:10 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Code relying on CsvMapper().writerFor(<a class>) throws an exception at writeValues() in 2.16.0 but was fine in 2.15.3.

Below is the stacktrace.

> 'void com.fasterxml.jackson.core.base.GeneratorBase.<init>(int, com.fasterxml.jackson.core.ObjectCodec, com.fasterxml.jackson.core.io.IOContext)'
java.lang.NoSuchMethodError: 'void com.fasterxml.jackson.core.base.GeneratorBase.<init>(int, com.fasterxml.jackson.core.ObjectCodec, com.fasterxml.jackson.core.io.IOContext)'
	at com.fasterxml.jackson.dataformat.csv.CsvGenerator.<init>(CsvGenerator.java:258)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory._createGenerator(CsvFactory.java:442)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory.createGenerator(CsvFactory.java:346)
	at com.fasterxml.jackson.dataformat.csv.CsvFactory.createGenerator(CsvFactory.java:14)
	at com.fasterxml.jackson.databind.ObjectWriter.createGenerator(ObjectWriter.java:738)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValues(ObjectWriter.java:854)

pointing at the line saying `.writeValues(outputFileStream)`

### Version Information

2.16.0

### Reproduction

```kotlin

        data class SimpleDataObject(val a: String, val b: List<String>)

        val simpleObjects = listOf(SimpleDataObject("foo", listOf("bar")), SimpleDataObject("baz", listOf("qux")))

        val csvSchema = CsvSchema.builder()
            .addColumn("a")
            .addColumn("b")
            .setUseHeader(true)
            .build()

        val outputFileStream = ByteArrayOutputStream()
        CsvMapper().writerFor(SimpleDataObject::class.java)
            .with(csvSchema)
            .writeValues(outputFileStream)
            .writeAll(simpleObjects)
``` 

### Expected behavior

The code does not throw and Exception but rather writes to the OutputStream.

### Additional context

This is kotlin 1.9.20

**Comment by pjfanning** [comment] 2023-11-16 20:02
Are you sure that you have v2.16.0 of all Jackson jars? That is no jars that have a different version number.

**Comment by estomagordo** [comment] 2023-11-16 21:21
I mean, it's a big project with all sorts of transitive dependencies. And you're saying this is definitely part of the explanation?

**Comment by pjfanning** [comment] 2023-11-16 21:23
closing since OP is unwilling to check their own dependencies

**Closed by pjfanning** 2023-11-16 21:23 UTC
Labels: to-evaluate

**Comment by cowtowncoder** [comment] 2023-11-17 04:49
@estomagordo Yes, version mismatch is almost certainly the root cause. Most likely version of `jackson-core` is older than that of `jackson-dataformat-csv` (or possibly `jackson-databind`).
For example, maybe `jackson-core` version is 2.14.0, but `jackson-databind` 2.16.0: this would not be guaranteed to work (since databind depends on core, version of core must be same or higher (minor version)).

In practice you should try to keep minor versions of all Jackson components the same: using `jackson-bom` (https://mvnrepository.com/artifact/com.fasterxml.jackson/jackson-bom) to force consistent set of versions helps with this.
