### ISSUE TITLE
Problem deserializing 'setterless' property with Jackson 2.9.7

### ISSUE THREAD

**Issue by nhantr** [FasterXML/jackson-databind#3488] opened 2022-05-18 08:47 UTC
**Describe the bug**
I upgraded my project from jackson 2.2.0 to 2.9.7 and found this problem.
My project calls to another SOAP webservice and the object generate from WSDL don't have setter for List type.
I'm try to write the test case, in this, I used readValue() of ObjectMapper to parse the JSON string back to SOAP WS object

When I use jackson 2.2 it worked but after upgrading to 2.9.7, I got:
` Error occurred: Problem deserializing 'setterless' property ("my property"): no way to handle typed deser with setterless yet`

**Version information**
jackson 2.9.7

**To Reproduce**
For example, my SOAP WS have the object like this (generate from WSDL):

```
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getFiltersResponse", propOrder = {
    "_return"
})
public class GetFiltersResponse{
    @XmlElement(name = "return")
    protected List<Element> _return;

    public List<Element> getReturn() {
        if (_return == null) {
            _return = new ArrayList<Element>();
        }
        return this._return;
    }
}
```
and I have the txt file which stores the response of a sample request, create by ObjectMapper writeValue() like this:

```
[ "com.sample.GetFiltersResponse", {
  "return" : [ [ "com.sample.Element", {
    "id" : "0",
    "name" : "John"
  } ], [ "com.sample.Element", {
    "id" : "1",
    "name" : "Thomas"
  } ] ]
} ]
```
Then I read that text file and then convert it back to GetFiltersResponse object by this method:

```
GetFiltersResponse getFiltersResponse = parseToObject(fileName, GetFiltersResponse.class);

// HELPER
public static <T> T parseToObject(String strFilePath, Class<T> clazz)
{
    File file = new File(strFilePath);
    ObjectMapper mapper = new ObjectMapper();
    mapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL);
    T obj= null;
    try
    {
        obj= mapper.readValue(file, clazz);
    }
    catch (JsonParseException e)
    {
        log.warn(ERROR_OCCURRED + e.getMessage(), e);
    }
    catch (JsonMappingException e)
    {
        log.warn(ERROR_OCCURRED + e.getMessage(), e);
    }
    catch (IOException e)
    {
        log.warn(ERROR_OCCURRED + e.getMessage(), e);
    }
    return obj;
}
```

**Expected behavior**
getFiltersResponse != null 
AND getFiltersResponse.getReturn().size() == 2 
AND getFiltersResponse.getReturn().get(0).getName() == "John"
AND getFiltersResponse.getReturn().get(1).getName() == "Thomas"

**Actual behavior**
EXCEPTION: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Problem deserializing 'setterless' property ("return"): no way to handle typed deser with setterless yet
at [Source: (File); line: 2, column: 14] (through reference chain: com.sample.GetFiltersResponse["return"])

**Additional context**
These code works well when I use Jackson 2.2.0

**Comment by nhantr** [comment] 2022-05-18 09:27
the root cause maybe from this : com.fasterxml.jackson.databind.deser.impl.SetterlessProperty

```
@Override
    public final void deserializeAndSet(JsonParser p, DeserializationContext ctxt,
            Object instance) throws IOException
    {
        ....
        // For [databind#501] fix we need to implement this but:
        if (_valueTypeDeserializer != null) {
            ctxt.reportBadDefinition(getType(), String.format(
                    "Problem deserializing 'setterless' property (\"%s\"): no way to handle typed deser with setterless yet",
                    getName()));
//            return _valueDeserializer.deserializeWithType(p, ctxt, _valueTypeDeserializer);
        }
        .....
    }
```

**Comment by cowtowncoder** [comment] 2022-07-28 22:45
Original example is incomplete, not having definition of `Element` but it definitely looks like it is polymorphic type -- and as per exception message, "setterless" deserialization does not support them.

With a self-contained example it'd be possible to see how fundamental limitation this is; it may or may not be.
But without test case there isn't much I can do here.
Closing but may be reopened with standalone reproduction.

**Closed by cowtowncoder** 2022-07-28 22:45 UTC
