### ISSUE TITLE
Ability to use @JsonAnySetter in MixIn

### ISSUE THREAD

**Issue by StasKolodyuk** [FasterXML/jackson-databind#1766] opened 2017-09-15 10:38 UTC
Hi!

I'd like to propose a feature related to usage of `@JsonAnySetter` in MixIn.

Currently, the following won't work:
```
public class ThirdPartyBean {
    String name;
    Map<String, String> attributes = new HashMap<>();
    // getters and setters
}

public abstract class MixIn {
    @JsonProperty("name")
    abstract String getName();
    @JsonProperty("attributes")
    abstract Map<String, String> getAttributes();
    
    @JsonAnySetter
    public void setAttribute(String key, String value) {
        getAttributes().put(key, value);
    }

}
```
So, `@JsonAnySetter` won't actually be called, however I'd like to :)

Thanks in advance

**Comment by cowtowncoder** [comment] 2017-09-15 17:23
@StasKolodyuk I would need actual reproduction here: mix-in annotations work in generic fashion and there is nothing specific to `@JsonAnySetter`. So as long as there is matching `setAttribute` method in `ThirdPartyBean`, it will work. So, I would see how things are not working -- either due to a bug, or possibly usage that is not supported (that is, something you may expect to work but is not the way mix-in annotations are designed to work).

**Comment by diesieben07** [comment] 2017-09-18 11:35
As far as I can see you'd want `setAttribute` to be called on your `MixIn` class, however that cannot work (you can't have an instance of that class, since it's abstract, so you can not call methods on it) plus that is not how Mixin annotations work, they only overlay annotations on methods that already exist in the original class.

**Comment by cowtowncoder** [comment] 2017-09-18 22:52
Right, if assumption was that somehow CODE from mix-ins was added, this is not the case.
Only annotations are added to matching entities (getters, setters, fields, constructors); code is never used in any way.

**Comment by cowtowncoder** [comment] 2017-09-26 23:07
No reproduction, closing.

**Closed by cowtowncoder** 2017-09-26 23:07 UTC
