### ISSUE TITLE
An illegal reflective access

### ISSUE THREAD

**Issue by xbaker** [FasterXML/jackson-databind#2609] opened 2020-01-29 16:18 UTC
java version : **OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)**

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil (file:/home/tarik/.m2/repository/com/fasterxml/jackson/core/**jackson-databind/2.9.8/jackson-databind-2.9.8.jar**) to field sun.nio.ch.ChannelInputStream.ch
WARNING: Please consider reporting this to the maintainers of com.fasterxml.jackson.databind.util.ClassUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by cowtowncoder** [comment] 2020-01-29 17:18
Unfortunately this is not much to go about. Do you have anything else to help trigger the issue? Code to reproduce, stack trace? Without this, all I know is that yes, module system can complain about reflection access used to introspect accessors for value types when reading/writing json.

**Comment by xbaker** [comment] 2020-01-30 11:15
Sure,  Sure
**working with spring boot 2.1.2,**
**java version : jdk 11.0.5**

config
`spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    visibility:
      FIELD: any`

I need to upload a file to a remote server using restemplate

`
private HttpEntity<MultiValueMap<String, Object>> multiPartHeader(MultipartFile image) throws IOException {
        HttpHeaders headers = this.header();
        headers.add("Content-Type", "multipart/form-data");
        MultiValueMap<String, Object> body = new LinkedMultiValueMap<>();
        body.add("media[file]", image.getInputStream());
        return new HttpEntity<>(body, headers);
    }
`

then i got two errors :

1. The reflective access warning

2.   Infinite recursion (StackOverflowError) (through reference chain: java.io.FileDescriptor["parent"]
`Infinite recursion (StackOverflowError) (through reference chain: java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io.FileInputStream["fd"]->java.io.FileDescriptor["parent"]->java.io`

**Comment by cowtowncoder** [comment] 2020-01-30 17:22
This:

    body.add("media[file]", image.getInputStream())

will not work: a value or property of type `InputStream` can not be serialized as it is a transient object.

If you would like to serialize contents of such input source, you will need to read them, and add as `byte[]` or `ByteBuffer`.

**Comment by pjfanning** [comment] 2020-02-25 21:39
this looks very similar to https://github.com/FasterXML/jackson-databind/issues/2626

**Comment by cowtowncoder** [comment] 2020-02-25 22:19
Yes, sort of: basically most JDK types should not be introspected as POJOs and this warning tends to show that either:

1. Type in question should not be serialized, or
2. There is a JDK type not yet explicitly supported by Jackson (POJO approach rarely works, even if excluding access problems)

**Comment by cowtowncoder** [comment] 2020-03-13 16:35
Since as per @pjfanning this is I think same as #2626, will close this as dup just because that one has bit more specific info (usually would keep older).

**Closed by cowtowncoder** 2020-03-13 16:35 UTC
Labels: JDK11

**Comment by pjfanning** [comment] 2020-03-13 17:10
It's almost like the 3rd party code is using jackson to serialize a class instance where the class has a member that is an InputStream. Maybe, I don't understand the use case - but serializing such a class should be set up to ignore the input stream because this will consume the stream. It seems to me that custom code should be written when you need to produce json based on reading an inputs stream.

**Comment by cowtowncoder** [comment] 2020-03-13 18:03
Right, I think many of these cases are for types that should not be serialized.
Question there is whether there are some common enough cases (esp. for JDK types) where maybe Jackson could add explicit failing deserializer to let dev know that type is typically not to be handled  or not. Could include info on how to ignore; I am not necessarily comfortable with automatically just hiding types as that tends to hide real root causes (often these dependencies are something that sneak in, expose other issues).
