### ISSUE TITLE
Version 2.13.0 is missing module-info.class files in artifacts

### ISSUE THREAD

**Issue by metacodez** [FasterXML/jackson-databind#3319] opened 2021-11-06 15:41 UTC
Dear developers, 

the release `2.13.0` seems to be missing the `module-info.class` file in the artifacts deployed to `maven-central` repository. I switched back to `2.12.5` in order to prevent using different automatic (unstable) module names . As of my findings, at least the artifacts `jackson-core-2.13.0` as well as `jackson-databind-2.13.0`are affected.

Best regards,
Siegfried

**Comment by cowtowncoder** [comment] 2021-11-06 18:58
@metacodez How did you reach this conclusion? I can see the module-info at:

    META-INF/versions/11/module-info.class

for jackson-databind, and should be similarly located for other artifacts.

**Comment by GedMarc** [comment] 2021-11-06 19:44
I can't confirm this - I am definitely building JLink artifacts with 2.13.0 -

Do you perhaps have an a sniffer like animal-sniffer during your build expecting to find it under the root or /versions/9 ?

If possible please create an empty test build project under your conditions that reproduces what you are seeing

**Comment by metacodez** [comment] 2021-11-07 10:17
Thanks for the reply, I understand - though seems to be the tool-chains configured for Java 9 + Java 10 are now failing with version `2.13.0` as `2.13.0` goes for Modular multi-release JAR files specifying Java 11 (which was not the case with versions `2.12.x`). Is there any reason why to support `module-info.class` for Java >= `11` and not as of `9` (I was happy with the `module-info.class` in the root as of `2.12.5`) ?

**Comment by GedMarc** [comment] 2021-11-08 23:10
We cannot put the module-info in the root, as we need to support class scanners on older platforms (like wildfly 10 as the major culprit here)

As the class structure changed -  if a classpath scanner, say javassist <13, picks it up, it produces hell and many unwanted effects - in some cases even boot death - 

The sniffer errors for class files supporting for JDK 9 (ver 5x) being placed in versions higher than 9, is actually an issue in the sniffer and not the library - the class files are valid for any version from

I'm pretty sure your issue is directly to your build, or a modification of the file - What's needed is 
* Multi-Release=true in the MANIEFST.MF file
* The module-info file placed in a version folder located in META-INF equal or higher to the compile version of the class

I think double check any changes you've made, and your build path, or please supply a replicator

**Comment by cowtowncoder** [comment] 2021-11-09 01:04
@metacodez I really wish user community were able to help me and other maintainers verifying compatibility -- we do release one or two release candidates, and have 1-2 months time to tease out problems. Alas, this issue was not reported by a single user as far as I know. This both means we could not make changes prior to 2.13.0 final release, and now I have hard time knowing whether this is, or is not, a big deal.
I am not trying to blame you or anyone in particular, just lamenting the fact that there does not seem to be a way to really test new minor releases, esp. regarding artifact metadata. :-(

As to changes: there are a few reports suggesting that use of version `9` would solve some issues: but @GedMarc is more knowledgeable of downsides there than I am. And I do remember that putting `module-info.class` at main level (a la 2.12) causes/caused its own set of hurdles for other, pre-java-9 (tool) users.

So. If we can figure out a balanced improvement, great. But I am not going to make speculative changes without bigger discussion and validation.
To that end, bringing this up on "jackson-dev" (https://groups.google.com/g/jackson-dev) would make sense.

**Comment by sohrabsaran** [comment] 2021-11-28 18:21
I'm probably facing the same issue. In IntelliJ with jdk 17, 2.13.0 goes on saying 'Module com.fasterxml.jackson.core cannot be found in the module graph' but 2.12.5 works fine.

**Comment by metacodez** [comment] 2021-11-29 19:43
I was lucky that I was able to switch to JDK 11 without any issues on other projects, so I am not affected any more although I think for JDK 9 and 10 the issue is still there. Sorry @cowtowncoder, as I maintain the artefacts on [REFCODES.ORG](https://bitbucket.org/refcodes) I just come across such issues when I rise versions on those modules (which are quite a few).

**Comment by GedMarc** [comment] 2021-12-02 04:25
please post a reproducer - I'm unable to replicate any issues here , @sohrabsaran especially with JDK17, that needs to replicated....

**Comment by cowtowncoder** [comment] 2021-12-03 02:25
As per @GedMarc's earlier comment (which I agree with) I am not very concerned about JDK 9 and 10 -- these should not be used by anyone anywhere for reasons mentioned -- but I am worried about tooling that may fail due to assumptions.
So if there are cases of failures on JDK 11 (f.ex) due to metadata, I'd like to find improvements.

But put this another way: is there an actual downside of changing location to be  `META-INF/versions/9/`, @GedMarc ?
I mean, yeah, it's sort of unfortunate but at the same time rather easy to do, esp. for core modules.
And I could do that for 2.13.1 before releasing it in near future.

**Comment by shamsasari** [comment] 2022-01-02 21:41
I've encountered the same issue when trying to update to 2.13.1. It seems the issue is related to Kotlin, at least for me. I've created a simple project reproducing the issue: https://github.com/shamsasari/jackson-kotlin-java-modules-issue.

**Comment by cowtowncoder** [comment] 2022-01-03 01:15
@shamsasari It would probably be worth filing a separate issue for `jackson-module-kotlin`, with a reference to this issue. Kotlin module maintainers have more knowledge of Kotlin runtime and could chime in here as well, but they are not necessarily following on issues for databind.

**Comment by shamsasari** [comment] 2022-01-03 17:59
@cowtowncoder even though the issue isn't specific to `jackson-module-kotlin` and affects `jackson-databind`?

**Comment by cowtowncoder** [comment] 2022-01-03 18:11
@shamsasari Even then because it sounds like there may be some different aspect to the issue, specific to Kotlin dependency or tooling. We can always close issues if they turn out to be fully redundant.

**Comment by unverbraucht** [comment] 2022-02-14 09:43
I'm facing the same issue, and it's a known issue with Kotlin. They do not look for java version specific module-info. I've opened an issue on their bug tracker months ago, and apparently a fix is in the works: https://youtrack.jetbrains.com/issue/KT-48027

**Comment by lbiazotto** [comment] 2022-03-10 14:32
I'm facing the same issue with JDK 1.8 (Zulu 8). I couldn't update to 2.13.*

**Comment by cowtowncoder** [comment] 2022-07-28 22:57
Ok, so this was fixed as #3380 ("`module-info.java` is in `META-INF/versions/11` instead of `META-INF/versions/9`") as of Jackson 2.13.2, so closing this issue.

If there are further problems, please file a new issue with details and a reference to this issue.

**Closed by cowtowncoder** 2022-07-28 22:57 UTC
