### ISSUE TITLE
Missed type info when serializing to Object Id

### ISSUE THREAD

**Issue by fangzhen** [FasterXML/jackson-databind#486] opened 2014-06-12 08:13 UTC
Hi,
I have encountered a problem when serializing and then deserializing shared reference with object Id feature. The following code makes this clear:

	public class TemTest {
		@Test
		public void testTypeReference() throws JsonGenerationException, JsonMappingException, IOException{
			List<Object> objs = new ArrayList<>();
			A v1 = new A();
			v1.val = 10;
			A v2 = v1;
			int v3 = 1;
			objs.add(v1);
			objs.add(v2);
			objs.add(v3);
			ByteArrayOutputStream out = new ByteArrayOutputStream();
	
			ObjectMapper mapper = new ObjectMapper();
			mapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL);
			mapper.writeValue(out, objs);
			System.out.println(out);
			//OUTPUT1: ["java.util.ArrayList",[["org.apache.ode.bpel.obj.serde.TemTest$A",{"@id":1}],1,1]]
			
			List dobjs = mapper.readValue(out.toByteArray(), List.class);
			System.out.println(dobjs);
			//OUTPUT2: [org.apache.ode.bpel.obj.serde.TemTest$A@5e0cbb9, 1, 1]

			String jsonstr = "[\"java.util.ArrayList\",[[\"org.apache.ode.bpel.obj.serde.TemTest$A\",{\"@id\":2, \"val\":10}],"
					+ "[\"org.apache.ode.bpel.obj.serde.TemTest$A\",2],2]]";
			List dobjs2 = mapper.readValue(jsonstr.getBytes(), List.class);
			System.out.println(dobjs2);
			//OUTPUT3: [org.apache.ode.bpel.obj.serde.TemTest$A@71f80d51, org.apache.ode.bpel.obj.serde.TemTest$A@71f80d51, 2]
		}
		@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")
		static class A{
			int val;
			public int getVal(){
				return val;
			}
			public void setVal(int val){
				this.val = val;
			}
		}
	}
The OUTPUT1:

	["java.util.ArrayList",[
		["org.apache.ode.bpel.obj.serde.TemTest$A",{"@id":1}],
		1,
		1]
	]

And as you could see, the object id ref of v2 and integer v3 are serialized to the same thing, so the deserializer couldn't tell which one is object id or integer, When deserialized, the last two object of the list are all integer 1, as OUTPUT2 shows:

	[org.apache.ode.bpel.obj.serde.TemTest$A@5e0cbb9, 1, 1]

And then I tested that when type information are added to json string, the deserializer works just fine. As OUTPUT3 shows:

	[org.apache.ode.bpel.obj.serde.TemTest$A@71f80d51, org.apache.ode.bpel.obj.serde.TemTest$A@71f80d51, 2]

The first two objects are deserialized to same instance of class TemTest$A.

I'm wondering if this is a bug that it didn't serialize type information. It's the latest 2.4.0 release. 

Later, I checked 2.4.0 source, and I think the com.fasterxml.jackson.databind.ser.std.BeanSerializerBase is responsible for this matter. I had a rough modification to this method to add type info when serialize. 

	protected final void _serializeWithObjectId(Object bean,
            JsonGenerator jgen, SerializerProvider provider,
            TypeSerializer typeSer)
You can check it here https://github.com/fangzhen/jackson-databind/commit/27dcf64a222663b70f8cc052155a392d143dd549 if it helps. 
Thanks.

**Comment by cowtowncoder** [comment] 2016-07-14 04:22
One other thing to note: having base type instead of `Object` is an absolute requirement for Object Id handling; this will not be changing. So if the problem is due to missing information, this will not be fixed.
However, there is also possibility that this could have been due to some other problem; because of this, I would need a reproduction for 2.8.0. For now, I'll close this, may be reopened with a reproducible unit test.

**Closed by cowtowncoder** 2016-07-14 04:22 UTC
