### ISSUE TITLE
Single-argument constructor not auto-discovered if there are any explicit `@JsonCreator` annotations

### ISSUE THREAD

**Issue by sukumarnxn** [FasterXML/jackson-databind#2305] opened 2019-04-17 10:57 UTC
Found this issue while bumping from 2.4.3 to 2.9.8
here is a small reproduction

**Object:**

```java
package com.export;

import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.google.common.collect.ImmutableList;

import java.util.ArrayList;
import java.util.List;

public final class ExportRequest {

    private final String heading;

    @JacksonXmlElementWrapper(useWrapping = false)
    private final List<Format> fields = new ArrayList<>();

    @JsonCreator
    public ExportRequest(@JsonProperty("fields") List<Format> fields,
                         @JsonProperty("heading") String heading) {

        if (fields == null || fields.isEmpty()) {
            throw new IllegalArgumentException("fields should not be empty");
        }

        if (heading == null) {
            heading = "";
        }

        this.fields.addAll(fields);

        this.heading = heading;
    }

    public List<Format> getFields() {
        return ImmutableList.copyOf(fields);
    }

    public String getHeading() {
        return heading;
    }

    public static class Format {
        private static final String DEFAULT_FORMAT = "0.00;(0.00)";

        private static final String DEFAULT_CURRENCY_FORMAT = "$0.00;($0.00)";

        private final Object value;

        private final String pattern;

        private final String currency;

        @JacksonXmlProperty(isAttribute = true)
        private int maxChars;

        @JacksonXmlProperty(isAttribute = true)
        private Double proportion;

        public Format(int value) {
            this(value, DEFAULT_FORMAT, null);
        }

        public Format(long value) {
            this(value, DEFAULT_FORMAT, null);
        }

        public Format(double value) {
            this(value, DEFAULT_FORMAT, null);
        }

        public Format(String value) { this(value, DEFAULT_FORMAT, null); }

        public Format(Boolean value) { this(value == null ? "" : String.valueOf(value), DEFAULT_FORMAT, null); }

        @JsonCreator
        public Format(@JsonProperty("value") Object value,
                      @JsonProperty("pattern") String pattern,
                      @JsonProperty("currency") String currency) {
            this.value = (value == null ? "" : value);
            this.currency = currency;
            this.pattern = pattern;
        }

        public String getValue() {
            return value == null ? null : value.toString();
        }

        @JsonIgnore
        public String getPattern() {
            return pattern;
        }

        @JsonIgnore
        public String getCurrency() {
            return currency;
        }

        public int getMaxChars() {
            return maxChars;
        }

        public void setMaxChars(int maxChars) {
            this.maxChars = maxChars;
        }

        public Double getProportion() {
            return proportion;
        }

        public void setProportion(Double proportion) {
            this.proportion = proportion;
        }

    }

}
```

**Test class:**

```java
package com.export;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.util.LinkedHashMap;

public class JacksonMainExport {

    public static void main(String[] args) throws IOException {


        String json = "{\"heading\": \"TEST\",\"fields\":[\"field1\",\"field2\"] }";

        LinkedHashMap<String,Object> result =
                new ObjectMapper().readValue(json, LinkedHashMap.class);

        ObjectMapper objectMapper = new ObjectMapper();
        ExportRequest exportReqt = objectMapper.convertValue(result, ExportRequest.class);

        System.out.println(exportReqt.getFields());
    }
}
```

**Sample JSON:**

```
String json = "{\"heading\": \"TEST\",\"fields\":[\"field1\",\"field2\"] }";`
```

**working fine till jackson-databind-2.8.7** 

**Getting following exception :**

**

```
> Exception in thread "main" java.lang.IllegalArgumentException: Cannot construct instance of `com.bnym.nexen.jackson.export.ExportRequest$Format` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('field1')
>  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.bnym.nexen.jackson.export.ExportRequest["fields"]->java.util.ArrayList[0])

**
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3750)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3668)
	at com.bnym.nexen.jackson.export.JacksonMainExport.main(JacksonMainExport.java:22)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.bnym.nexen.jackson.export.ExportRequest$Format` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('field1')
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.bnym.nexen.jackson.export.ExportRequest["fields"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1373)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3745)
```

**Comment by cowtowncoder** [comment] 2019-04-18 04:41
Thank you for reporting this. From quick glance I think it should still work with 2.9.

There may be a workaround: you can explicitly annotate "delegating" `String` constructor:

```
        @JsonCreator(mode = JsonCreator.MODE.DELEGATING)
        public Format(String value) { this(value, DEFAULT_FORMAT, null); }
```

which should make it visible even if it was not auto-detected any more for some reason.

**Comment by sukumarnxn** [comment] 2019-04-22 11:35
DELEGATING mode - did the magic... :)

**Comment by cowtowncoder** [comment] 2019-05-10 04:20
Ok. I finally had time to look into this and unfortunately I think it is now working as designed.
Long story short, auto-detection of single-arg constructor works without annotation EXCEPT if there are any `@JsonCreator` annotations, in which case all need to be annotated.
Whether this should be the logic is open to debate in theory, but there is the hairy question of how much explicit metadata should be required. As of 2.9, at least, I don't think I can change this in patch version. For 2.10 I'd have to think about this carefully.

As to change itself: this is probably due to major JsonCreator discovery implementation rewrite (for maybe... 2.7?), which solved many problems. But compatibility is only really verified for things for which there are unit tests, and mixed-use like here was not covered. So I don't think change was intentional per se.

I will leave this open for now.

**Comment by cowtowncoder** [comment] 2021-07-15 04:04
Ok I don't think this can really be changed; closing.

**Closed by cowtowncoder** 2021-07-15 04:04 UTC
Labels: 2.13, has-failing-test
