### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getParameterCount()I in class Ljava/lang/reflect/Method; or its super classes (declaration of 'java.lang.reflect.Method' appears in /system/framework/core-libart.jar)

### ISSUE THREAD

**Issue by Oussemahlel** [FasterXML/jackson-databind#3495] opened 2022-05-25 12:03 UTC
The app crash when using Nexus 5X Android 6.0.1

 com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector._isIncludableMemberMethod SourceFile:3
    com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector._addMemberMethods SourceFile:3
    com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector.collect SourceFile:2
    com.fasterxml.jackson.databind.introspect.AnnotatedMethodCollector.collectMethods SourceFile:2
    com.fasterxml.jackson.databind.introspect.AnnotatedClass._methods SourceFile:4
    com.fasterxml.jackson.databind.introspect.AnnotatedClass.memberMethods SourceFile:1
    com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addMethods SourceFile:1
    com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll SourceFile:3
    com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor SourceFile:2
    com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor SourceFile:2
    com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations SourceFile:4
    com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2 SourceFile:9
    com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer SourceFile:9
    com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer SourceFile:1
    com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer SourceFile:2
    com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer SourceFile:4
    com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer SourceFile:3
    com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue SourceFile:4
    com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose SourceFile:4
    com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString SourceFile:2
    kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith SourceFile:4
    kotlinx.coroutines.DispatchedTask.run SourceFile:18
    kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely SourceFile:1
    kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask SourceFile:4
    kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker SourceFile:4
    kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run SourceFile:1

**Comment by cowtowncoder** [comment] 2022-05-25 15:59
Duplicate of #3412 -- fixed in `2.13.3`.

**Closed by cowtowncoder** 2022-05-25 15:59 UTC
Labels: android
