### ISSUE TITLE
Upgrade to 2.11.3 (form 2.11.2) causes Configured `PolymorphicTypeValidator` (of type `com.fasterxml.jackson.databind.jsontype.BasicPolymorphicTypeValidator`) denied resolution

### ISSUE THREAD

**Issue by rdehuyss** [FasterXML/jackson-databind#2876] opened 2020-10-10 18:47 UTC
**Describe the bug**
After upgrading to 2.11.3 from 2.11.2, I receive the following exception:
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'org.jobrunr.jobs.context.JobDashboardLogger$JobDashboardLogLines' as a subtype of `java.lang.Object`: Configured `PolymorphicTypeValidator` (of type `com.fasterxml.jackson.databind.jsontype.BasicPolymorphicTypeValidator`) denied resolution
 at [Source: (String)"{"version":0,"jobSignature":"System.out.println(String)","jobName":"an enqueued job","jobDetails":{"className":"java.lang.System","staticFieldName":"out","methodName":"println","jobParameters":[{"className":"java.lang.String","object":"a test"}]},"id":"4a322d0d-a90b-4835-b583-62dd7977a45e","jobHistory":[{"@class":"org.jobrunr.jobs.states.EnqueuedState","state":"ENQUEUED","createdAt":"2020-10-10T18:30:37.525349Z"},{"@class":"org.jobrunr.jobs.states.ProcessingState","state":"PROCESSING","createdAt"[truncated 769 chars]; line: 1, column: 723] (through reference chain: org.jobrunr.jobs.Job["metadata"]->java.util.concurrent.ConcurrentHashMap["jobRunrDashboardLog-2"])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:1784)
	at com.fasterxml.jackson.databind.DatabindContext._throwSubtypeClassNotAllowed(DatabindContext.java:287)
	at com.fasterxml.jackson.databind.DatabindContext.resolveAndValidateSubType(DatabindContext.java:244)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:72)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:66)
``` 

**Version information**
Which Jackson version(s) was this for?
2.11.3 (2.11.2 worked).

**To Reproduce**
If you have a way to reproduce this with:

1. Clone repository https://github.com/jobrunr/jobrunr
2. Run tests in `core/src/test/java/org/jobrunr/utils/mapper` -> all tests green
3. In `platform/build.gradle` update the jackson dependency from `2.11.2` to `2.11.3`.
4. Comment lines to throw exception about incompatible Jackson version in `org.jobrunr.utils.mapper.jackson.JacksonJsonMapper` (lines 30-32)
5. Run tests in `core/src/test/java/org/jobrunr/utils/mapper` -> Jackson related tests are red

**Json that fails during deserialization**
```json
{
  "version": 0,
  "jobSignature": "System.out.println(String)",
  "jobName": "an enqueued job",
  "jobDetails": {
    "className": "java.lang.System",
    "staticFieldName": "out",
    "methodName": "println",
    "jobParameters": [
      {
        "className": "java.lang.String",
        "object": "a test"
      }
    ]
  },
  "id": "6d9e0857-fd22-4b12-9fe2-19549d53b5bf",
  "jobHistory": [
    {
      "@class": "org.jobrunr.jobs.states.EnqueuedState",
      "state": "ENQUEUED",
      "createdAt": "2020-10-10T18:56:16.346030Z"
    },
    {
      "@class": "org.jobrunr.jobs.states.ProcessingState",
      "state": "PROCESSING",
      "createdAt": "2020-10-10T18:56:16.346997Z",
      "serverId": "62c282de-b852-40f5-9cc9-a8c44e27dc23",
      "updatedAt": "2020-10-10T18:56:16.346997Z"
    }
  ],
  "metadata": {
    "@class": "java.util.concurrent.ConcurrentHashMap",
    "jobRunrDashboardLog-2": {
      "@class": "org.jobrunr.jobs.context.JobDashboardLogger$JobDashboardLogLines",
      "logLines": [
        {
          "level": "INFO",
          "logInstant": "2020-10-10T18:56:16.352182Z",
          "logMessage": "this is an info message"
        },
        {
          "level": "WARN",
          "logInstant": "2020-10-10T18:56:16.352199Z",
          "logMessage": "this is a warning message"
        },
        {
          "level": "ERROR",
          "logInstant": "2020-10-10T18:56:16.352205Z",
          "logMessage": "this is an error message"
        }
      ]
    },
    "jobRunrDashboardProgressBar-2": {
      "@class": "org.jobrunr.jobs.context.JobDashboardProgressBar$JobDashboardProgress",
      "totalAmount": 80,
      "currentValue": 10,
      "progress": 12
    }
  }
}
```

**Comment by cowtowncoder** [comment] 2020-10-10 19:51
Thank you for reporting the issue; I hope to look into it soon.

**Comment by cowtowncoder** [comment] 2020-10-14 00:15
Ok: at this point I don't have time to start digging through bigger tests, commenting out things and so on -- but if someone could help here trim tests down into core failure(s), more minimal/isolated case, I'd happily merge a PR.
Marking as "test-needed" to indicate above.

**Comment by kupci** [comment] 2020-10-14 04:22
@rdehuyss Seems to be having trouble with `JobDashboardLogger$JobDashboardLogLines`, so test-case could be trimmed down to that type.

_Could not resolve type id 'org.jobrunr.jobs.context.JobDashboardLogger$JobDashboardLogLines' as a subtype of `java.lang.Object`: Configured `PolymorphicTypeValidator` (of type `com.fasterxml.jackson.databind.jsontype.BasicPolymorphicTypeValidator`) denied resolution_

...
_(through reference chain: org.jobrunr.jobs.Job["metadata"]->java.util.concurrent.ConcurrentHashMap["jobRunrDashboardLog-2"])_

Looking at the [diff](https://github.com/FasterXML/jackson-databind/compare/jackson-databind-2.11.2...jackson-databind-2.11.3) between the versions might be helpful too, to help narrow down, one possibility (based on error message) would be the change from using this method, for #2840, maybe?

https://github.com/FasterXML/jackson-databind/blob/1ea245288c9150511524114672c42852504077f2/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L1722

**Comment by rdehuyss** [comment] 2020-10-14 11:34
The analysis of @kupci is correct - it is related to #2840.

Instead of using the PolymorphicTypeValidator below, I'm now using the `LaissezFaireSubTypeValidator.instance` (an excellent name by the way :smile: ).

```java
 ...
 .activateDefaultTypingAsProperty(BasicPolymorphicTypeValidator.builder()
                                .allowIfBaseType(JobState.class)
                                .allowIfBaseType(Map.class)
                                .allowIfBaseType(JobContext.Metadata.class)
                                .build(),
```

But I don't understand why this would fail as the `JobDashboardLogger$JobDashboardLogLines` implements `JobContext.Metadata`. Any idea why my PolymorphicTypeValidator is not correct?

**Comment by rdehuyss** [comment] 2020-10-14 15:15
I went through the code - that was the one used before. All my tests say everything is ok, so all should be well. 

Still don't understand why my own `BasicPolymorphicTypeValidator` isn't working though.

**Comment by cowtowncoder** [comment] 2020-10-15 03:50
`LaissezFaireSubTypeValidator` is added to allow backwards-compatibility, and as name implies "anything goes": no validation is performed. It typically should only be used when input is fully trusted.

But that should not cause failure like shown above... weird.
I would be very interested in seeing a stripped down version, if possible, to figure out what is going on.

**Comment by cowtowncoder** [comment] 2020-10-15 03:56
@rdehuyss  Ahh. So it's not super-permissive "validator", but configured standard one. I agree that this seems like validation ought to succeed, so would love to see a reproduction -- mostly interested in seeing how mapper is configured, as well as how polymorphic handling is used.
One thing that may be confusing is that there are 2 `PolymorphicTypeValidator`s configured with mapper: one for "Default Typing" (which is what I think you are setting), and another one for case of `@JsonTypeInfo` with class name.

**Comment by cowtowncoder** [comment] 2020-10-21 02:37
@rdehuyss not sure if you still have the issue, you may just need to add:

```
    .polymorphicTypeValidator(myPTV)
```

in there if (but only if) you are using `@JsonTypeInfo` explicitly. This because `activateDefaultTypingAsProperty()` only specifies PTV to use for Default Typing.

**Comment by cowtowncoder** [comment] 2020-10-27 03:59
I suspect the issue may have been due to validator not being registered; closing unless new information is uncovered.

**Closed by cowtowncoder** 2020-10-27 03:59 UTC
Labels: 2.11, need-test-case
