### ISSUE TITLE
`@Jsonsetter with Nulls.SKIP` collides with `DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL` when parsing enum

### ISSUE THREAD

**Issue by ndori** [FasterXML/jackson-databind#2015] opened 2018-04-30 06:16 UTC
Hi, I've noticed a behavior I think should be different with
@jsonsetter(value = "foo", nulls = Nulls.SKIP)
private String foo;
and with .configure(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL, true)

in that case, I would expect that if there is an unknown enum the setter will skip the null set, as I told him I don't want you to set null.

but what is probably happening is that it sees a value which is not null so it tries to set it, then when it can't set it, it becomes null.

I realize that it will be probably hard to fix, but on the other hand, the whole point of the nulls attribute is to do something else with nulls...

test case:

```
    public enum NUMS{
        ONE, TWO
    }

    public static class Pojo {
        @JsonSetter(value = "number", nulls = Nulls.SKIP)
        NUMS number = NUMS.TWO;
    }
    public void foo() {
        ObjectMapper parser = new ObjectMapper();
        parser.configure(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL, true);

        String json = "{\"number\":\"THREE\"}";

        try {
            Pojo p = parser.readValue(json, Pojo.class);
            //p.number == null , should be TWO
        } catch (IOException e) { }
    }
```

**Comment by cowtowncoder** [comment] 2018-05-05 19:42
I think this had the same root cause as #2023; test now passes in `2.9` so fix will be in `2.9.6`

**Closed** 2018-05-05 19:43 UTC
