### ISSUE TITLE
Memory leak at  jackson.databind

### ISSUE THREAD

**Issue by guylevin** [FasterXML/jackson-databind#1390] opened 2016-09-28 12:40 UTC
Hello,
I saw some post written a few years ago about a memory leak at jackson.databind
I haven't found a solution for it
This is a sample of a program that uses jackson to serialize objects like this.

`objectMapper = new ObjectMapper()
			.enableDefaultTyping()
			.enable(SerializationFeature.WRITE_ENUMS_USING_TO_STRING)
			.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL)
			.disable(SerializationFeature.FAIL_ON_EMPTY_BEANS);
`

`String json = objectMapper.writeValueAsString(msg);`

This results are after a few minutes:

![image](https://cloud.githubusercontent.com/assets/4077233/18913531/f968d420-8590-11e6-81c0-8db066dc2da4.png)

**Comment by cowtowncoder** [comment] 2016-09-28 19:35
I'm sorry but "some post years ago" isn't much context to go about. Why do you think there is memory leak here? `ObjectMapper` does indeed hold on to a few things, but that does not in itself constitute a leak (or "Unintended Memory Retention"). Any number of objects included may be linked to from serializers, deserializers, various handlers they invoke.

**Comment by cowtowncoder** [comment] 2016-10-11 05:09
No reproduction, closing; may be reopened with explanation of how leakage suspected (not just based on number of retained objects but on either increase over time [without expansion in number of handled types] or some other aspect that seems to be out of ordinary).

**Closed by cowtowncoder** 2016-10-11 05:09 UTC
