### ISSUE TITLE
[feature improvement] Jackson should allow real inheritance without property based polymorphism

### ISSUE THREAD

**Issue by jhcao23** [FasterXML/jackson-databind#1608] opened 2017-04-18 00:02 UTC
Jackson only allow inheritance with polymorphism style such as property based definition `@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = As.PROPERTY, property="type")`.
However, it is necessary to consider the situation that the subclass doesn't have this property.
`abstract class A {String common;}`
`class B extends A {String nameB;}`
`class C extends A {String type, extra;}`
if the give json string is `String content = "{ name_b: bbb }";`, we want Jackson to be able to automatically cast it to B even the given result type is A:
`A a = objectMapper.readValue(content, A.class);`
i.e.: `a instanceof B` should return true and yes, A should be a B. 
I believe this robust feature which requires tree-like traversal and reflection checking is what we need in a lot of real scenarios, especially when the expecting response json is an array of A which could be any subclass of A like B and C etc.

**Comment by cowtowncoder** [comment] 2017-04-18 04:32
I think this is duplicate of #43.

**Comment by cowtowncoder** [comment] 2017-04-27 03:10
Assuming this is a duplicate; if more information needed may modify #43 with it.

**Closed by cowtowncoder** 2017-04-27 03:10 UTC
