### ISSUE TITLE
`@JsonSerialize(contentAs=superType)` behavior disallowed in 2.7

### ISSUE THREAD

**Issue by markwoon** [FasterXML/jackson-databind#1178] opened 2016-03-31 20:43 UTC
After updating to 2.7, I'm getting:

Failed to widen value type of [collection type; class java.util.SortedSet, contains [simple type, class org.pharmgkb.model.AccessionIdentifier]] with concrete-type annotation (value org.pharmgkb.model.BaseAccessionIdentifier), from 'getGenes': Class org.pharmgkb.model.BaseAccessionIdentifier not a super-type of [simple type, class org.pharmgkb.model.AccessionIdentifier]

The signature of the method in question is:

```
@JsonSerialize(contentAs = BaseAccessionIdentifier.class)
@JsonDeserialize(contentAs = BaseAccessionIdentifier.class)
public Set<AccessionIdentifier> getGenes() {
}
```

How am I suppose to annotate this to get it to work again?

**Comment by cowtowncoder** [comment] 2016-03-31 23:36
Sounds like earlier versions did not verify that types are compatible. Assuming `BaseAccessionIdentifier` is a subtype of `AccessionIdentifier`, `@JsonSerialize` here would be problematic as it can really be guaranteed to match type; but I also don't think that should be necessary should it? Serialization annotations are only typically used to limit type to a supertype, and not to try to use specialized type. In that way `@JsonSerialize` and `@JsonDeserialize` behave in opposing ways; former to force more general type, latter for more specific.

**Comment by markwoon** [comment] 2016-04-01 00:49
Our inheritance tree looks something like this:

* AccessionIdentifier (interface)
  * BaseAccessionIdentifier
    * ClassA
    * ClassB

I'm trying to limit what gets serialized here to only the properties defined in BaseAccessionIdentifier.

Do I need to define a custom serializer in this case?

**Comment by cowtowncoder** [comment] 2016-04-01 01:58
@markwoon Hmmh. I can see that although such definition is not necessarily safe for all usage (since you could have alternative `AccessionIdentifier` implementations), it may be for some usage; and could just dynamically fail if so, instead of statically.

So perhaps this is a flaw after all.

**Comment by markwoon** [comment] 2016-04-01 02:00
@cowtowncoder Does that mean that this is something that might change a future release?

And what would you recommend in the mean time?

**Comment by cowtowncoder** [comment] 2016-04-01 02:24
@markwoon Right, I think I will try to fix this for 2.7.4.

In the meantime... good question. I am not sure if there is an easier way than custom serializer.
While forcing use of `AccessionIdentifier` would be easy (either by specifying that as content type, or marking typing as `Static`), getting this to use intermediate type is more difficult.

**Comment by cowtowncoder** [comment] 2016-04-04 04:34
I was able to fix this, will be included in 2.7.4.

**Closed** 2016-04-04 04:34 UTC

**Comment by markwoon** [comment] 2016-05-13 19:16
@cowtowncoder Confirming this works for collections, but not for single objects.

This is failing:

```
@JsonSerialize(as = BaseAccessionIdentifier.class)
@JsonDeserialize(as = BaseAccessionIdentifier.class)
public AccessionIdentifier getReference() {
}
```

**Comment by cowtowncoder** [comment] 2016-05-13 19:19
@markwoon could you file a new issue with that? Along with either reproduction, or at least type definitions needed. Stack trace would be helpful as well.
