### ISSUE TITLE
jacson 2.14 does not work on Android API < 26

### ISSUE THREAD

**Issue by Bixilon** [FasterXML/jackson-databind#3702] opened 2022-12-18 19:08 UTC
Hi, 
I am using jackson on android 7, the problem is that the commit (https://github.com/FasterXML/jackson-databind/commit/326bb8673515f37aefe7a82b31ddc9f9d7c82142) breaks some things, because the Method `Method::getParameterCount` does not exist.

It happens in e.g. https://github.com/FasterXML/jackson-databind/blob/2.15/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotatedMethodCollector.java#L187

This is a followup of pretty much exactly https://github.com/FasterXML/jackson-module-kotlin/issues/176

Please revert the commit or abstract it and handle it with `try {} catch(NoSuchMethodException) { }`

Thanks!

**Comment by pjfanning** [comment] 2022-12-18 19:18
Have you tried https://github.com/FasterXML/jackson-jr instead?

**Comment by Bixilon** [comment] 2022-12-18 19:28
No, why should I? I don't have the needs of them.

**Comment by yawkat** [comment] 2022-12-18 19:32
duplicate of #3658, jackson 2.14 only works on API >=26

**Comment by cowtowncoder** [comment] 2022-12-19 21:29
@Bixilon This change was unintentional wrt Android compatibility -- and as a result we added a compatibility checker and documented current baseline. CI will verify that we will abide by it, too:

https://github.com/FasterXML/jackson-databind/

However, as to 2.14 minimum Android level that became 26 and I have no intention of reverting those changes.

**Closed by cowtowncoder** 2022-12-19 21:29 UTC
Labels: to-evaluate

**Comment by Bixilon** [comment] 2022-12-19 21:58
> However, as to 2.14 minimum Android level that became 26 and I have no intention of reverting those changes.

If I PR this and use a static method that checks (one time) if the method is available and if so, uses it, otherwise fallsback, would you accept it?

**Comment by cowtowncoder** [comment] 2022-12-19 22:26
@Bixilon I appreciate your help, but no: at this point I do not want a workaround for use of this method. While the way it came about was unfortunate (during 2.13.x development), decision was made to just use the new method with 2.14.

To use Jackson on earlier Android SDK versions, it will be necessary to stay on Jackson 2.13 (latest 2.13.5 should have no issues).

For background, see: #3412, #3658 and #3661.

**Comment by Bixilon** [comment] 2022-12-19 22:49
I read through it, but still don't see the exact reason why < 26 should be deprecated, I still got one device with Android 7. But you could argue that workarounds are bad and those API versions only share less then 3% of total market share (see https://gs.statcounter.com/os-version-market-share/android)


Still thanks!

Moritz

**Comment by cowtowncoder** [comment] 2022-12-19 22:53
@Bixilon yes, sorry about that. Reasoning really is that eventually we will want to move on and not use various workarounds, exactly as you were speculating.

The main fail here was that upgrade was unintentional, unplanned. But given that there are now multiple released patch versions it seems simplest to go with a new stable baseline and rely on AnimalSniffer-based verification to make sure in future we upgrade when we want/plan to, not accidentally.
