### ISSUE TITLE
@JsonAnySetter not working with Jackson 2.9

### ISSUE THREAD

**Issue by beihaifeiwu** [FasterXML/jackson-databind#1689] opened 2017-07-05 06:41 UTC
I have run into this problem when I upgrade to Spring Boot 2.0.0.M2 which use the 2.9 version of Jackson, here is my test case: 

```java
    @Test
    public void testAnyGetterSetter() {
        Employee employee = new Employee();
        employee.setName("Jack");
        employee.setAge(22);
        employee.setOther("address", "ShangHai");
        String jsonString = JSON.toJsonString(employee);
        assertThat(jsonString).isNotBlank().contains("\"address\" : \"ShangHai\"");
        assertThat(JSON.parseObject(jsonString, Employee.class))
                .isNotNull()
                .isEqualToComparingFieldByFieldRecursively(employee);
    }

    @Data
    public static class Employee {
        private String name;
        private int age;
        private Map<String, Object> other = Maps.newHashMap();

        @JsonAnyGetter
        public Map<String, Object> getOther() {
            return other;
        }

        @JsonAnySetter
        public void setOther(String name, Object value) {
            other.put(name, value);
        }
    }
```
When I run this test, I got the fallow error:

```bash

java.lang.AssertionError: 
Expecting:
  <JacksonWebEnvironmentTest.Employee(name=Jack, age=22, other={})>
to be equal to:
  <JacksonWebEnvironmentTest.Employee(name=Jack, age=22, other={address=ShangHai})>
when recursively comparing field by field, but found the following difference(s):

Path to difference: <other>
- expected: <{"address"="ShangHai"}>
- actual  : <{}>
```

Is this a bug or something I did wrong ?

**Comment by beihaifeiwu** [comment] 2017-07-05 07:17
I think there the code below may have some bug:

com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair
```java
    @Override
    public Boolean hasAnySetter(Annotated a) {
        Boolean b = _primary.hasAnySetter(a);
        if (b == null) {                                          // here, should not just check null, also include false check
            b = _secondary.hasAnySetter(a);
        }
        return b;
    }
```

**Comment by cowtowncoder** [comment] 2017-07-10 05:34
Quick question: which pre-release version is this with? 2.9.0.pr4, or earlier?
I think there was something that was fixed recently... but can not locate issue number now.

As to root cause: check for only `null` is intentional, to allow masking of any setter annotation (via mix-ins, or by custom introspector) -- if `Boolean.FALSE` was ignored, this would not be possible. 

But I think the fix was actually for something like `AnnotationIntrospector` returning `Boolean.FALSE` as default unless sub-class overrode it: this is wrong, and `null` is the proper default value.

**Comment by beihaifeiwu** [comment] 2017-07-10 05:45
@cowtowncoder yes, it's with 2.9.0.pr4.  the problem is that **com.fasterxml.jackson.databind.AnnotationIntrospector** has the follow method :
```java
    public Boolean hasAnySetter(Annotated a) {
        return false;
    }
```
it just return false instead of null, So when use with AnnotationIntrospectorPair, the primary introspector may not overwrite this method and behave like the upper scene.

**Comment by cowtowncoder** [comment] 2017-07-10 05:53
Ah, yes. So, fix for #1672:

https://github.com/FasterXML/jackson-databind/commit/a2a45b371e19bfc97fa490fa378ee3124498de6a

but it went right after pr4, so you would not see the fix quite yet.
But will be in 2.9.0 release (no more pre-releases planned).

**Closed by cowtowncoder** 2017-07-10 05:53 UTC
Labels: 2.9, ACTIVE

**Comment by beihaifeiwu** [comment] 2017-07-10 06:10
@cowtowncoder Can I ask when the 2.9.0 will be released ?

**Comment by cowtowncoder** [comment] 2017-07-10 14:57
@beihaifeiwu As with all OSS, "when it's ready". I am hoping to do it before end of July 2017, which would be in 3 weeks.
