### ISSUE TITLE
Type info for unbounded generic types lost during serialization (regression from 2.4.2)

### ISSUE THREAD

**Issue by knorp** [FasterXML/jackson-databind#983] opened 2015-10-27 09:37 UTC
It seems that generics, when used unbounded (i.e. as <?>) are no longer correctly resolved to their actual types even when it would be possible.

This hierarchy:

`class MyClassToSerialize extends MySuperclassToSerialize<MyListEntry>`
`class MySuperclassToSerialize<T extends MyListEntrySuperclass<?>>`

`class MyListEntry extends MyListEntrySuperclass<MyInterfaceImpl>`
`class MyListEntrySuperclass<T extends MyInterface>`

with this annotation on MyInterface:
`@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property= "_t")`

will not correctly add a type information property "_t" to the resulting json.

* Reproducer test can be found here: http://pastebin.com/cjDDE0Ek or upon request as zip, seems i cannot attach .java files here. Works as expected with 2.4.2, breaks with 2.5.2 and 2.6.2.

* Screenshots of the type resolution during debugging in 2.4.2 and 2.6.2(TypeFactory._fromType()):
![jackson242](https://cloud.githubusercontent.com/assets/7696355/10754192/6281dbb4-7c96-11e5-9f4b-ad6ac7e8176c.PNG)

![jackson262](https://cloud.githubusercontent.com/assets/7696355/10754191/6280fcc6-7c96-11e5-833b-42cb479f513e.PNG)

**Workaround**
A solution to work around this (at least working for this example) is to change the definition of MySuperclassToSerialize to use a bounded wildcard. This will work:
`class MySuperclassToSerialize<T extends MyListEntrySuperclass<? extends MyInterface>>`

**Comment by cowtowncoder** [comment] 2015-10-27 18:43
First of all, thank you for the test case; I will see if I can get that to work to show the problem.

There are some known issues with resolution of type variables and wild cards of generic types.
It is possible that fix to one of these problems caused regression. Unfortunately type resolution as implemented up to 2.6 has some fundamental problems which mean that there are classes of cases that can not be solved without major rewrite.

Because of this, there has been long-standing hope to rewrite type resolution using more correct scheme used by `java-classmate` project. And this is what is being done for Jackson 2.7.
Existing `master` contains early version of the new system, and it has resolved 2 formerly failing (and unfixable) test cases. So it may make sense to see if your problem would be resolve by 2.7.

**Comment by cowtowncoder** [comment] 2015-10-27 18:45
Looking at the test case, it involves resolution of member types, so it may be bit longer before 2.7 resolves that part of the problem actually. But it also means that this could be a very useful verification case as well.

**Comment by cowtowncoder** [comment] 2015-11-04 16:42
FWIW, `master` now has fully rewritten type handling, including properly resolving members (fields, methods, constructors). So there's a chance this might work on 2.7; haven't had time to look into reproduction yet (checked in last changes last night).

**Comment by cowtowncoder** [comment] 2015-11-06 06:32
Test now passes on 2.7.

**Closed by cowtowncoder** 2015-11-06 06:32 UTC

**Comment by knorp** [comment] 2015-11-06 08:36
Thanks for the fast fix!
