### ISSUE TITLE
Odd behavior while de-serializing serialized `List.of` objects with Default Typing

### ISSUE THREAD

**Issue by sezinkarli** [FasterXML/jackson-databind#3892] opened 2023-04-21 16:05 UTC
I'm not sure if this counts as a bug so I wanted to create it as something else. I'm seeing an odd behavior while deserializing a serialized result of List.of and Set.of. 

```
@ExtendWith(MockitoExtension.class)
public class JacksonTest {

    @Test
    void mismatchedInputExceptionTest() throws IOException {
        final ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.activateDefaultTyping(objectMapper.getPolymorphicTypeValidator(), DefaultTyping.NON_FINAL, As.PROPERTY);
        final byte[] bytes = objectMapper.writeValueAsBytes(Set.of(new Foo("a", "b"), new Foo("c", "d")));
        final Object o = objectMapper.readValue(bytes, Object.class);
    }
}

class Foo {
    private String bar1, bar2;
    public Foo() {
    }

    public Foo(final String bar1, final String bar2) {
        this.bar1 = bar1;
        this.bar2 = bar2;
    }

    public String getBar1() {
        return bar1;
    }

    public void setBar1(final String bar1) {
        this.bar1 = bar1;
    }

    public String getBar2() {
        return bar2;
    }

    public void setBar2(final String bar2) {
        this.bar2 = bar2;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Foo foo = (Foo) o;
        return Objects.equals(bar1, foo.bar1) && Objects.equals(bar2, foo.bar2);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bar1, bar2);
    }

}
```

This is what I get:

> com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (START_OBJECT), expected VALUE_STRING: need JSON String, Number of Boolean that contains type id (for subtype of java.lang.Object)
>  at [Source: (byte[])"[{"@class":"com.service.Foo","bar1":"a","bar2":"b"},{"@class":"com.service.Foo","bar1":"c","bar2":"d"}]"; line: 1, column: 2]
> 

Changing default typing to EVERYTHING fixes the problem. I cant change objectMapper.readValue(bytes, Object.class); line because this in spring cache code (Jackson2JsonRedisSerializer or somewhere relatedI)

**Comment by cowtowncoder** [comment] 2023-04-22 20:02
I think this is due Java Type Erasure: when serializing, root value is missing its full generic type information.
Since type information is needed to know expected value type of `Set` elements it will be likely to have mismatching type expectation compared to deserialization.

To resolve this -- it is something Jackson cannot "fix" -- you have couple of options:

1. Not to serialize generic root-level values: use a simple wrapper POJO  (non-generic) with single generic field; this retains full type info. This is what I usually recommend
2. Use `Set` (etc) subtype to convert from generic `Set<X>` to `class SetX extends Set<X>` (not available if using convenience methods). This also retains type information
3. Use `ObjectWriter` created from `ObjectMapper`; something like:

   ObjectWriter w = mapper.writerFor(new TypeReference<Set<MyType>>() { });
   byte[] bytes = w.writeValueAsBytes(set);

Alternatively it is possible another `DefaultTyping` choice -- like, `OBJECT_AND_NON_CONCRETE` -- would work better.

But given this is via Redis cache I would strongly recommend using approach (1) -- that requires no configuration changes and should work reliably.

**Comment by sezinkarli** [comment] 2023-04-23 08:50
Hi, thanks a lot for your answer.

Do you know why it does work for

```
final HashSet<Foo> fooSet = new HashSet<>();
        fooSet.add(new Foo("a", "b"));
        fooSet.add(new Foo("c", "d"));
```

but not

`Set.of(new Foo("a", "b"), new Foo("c", "d"))` ?

I'd expect the same exception due to type erasure. Do you know why?

Also I can confirm that having a wrapper class for the collections work.

I was not able to fix my issue with any other DefaultTyping though. The only working one is still EVERYTHING.
What I got from OBJECT_AND_NON_CONCRETE was:

> com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (START_OBJECT), expected VALUE_STRING: need JSON String, Number of Boolean that contains type id (for subtype of java.lang.Object)
>  at [Source: (byte[])"[{"@class":"com.service.Foo","bar1":"a","bar2":"b"},{"@class":"com.service.Foo","bar1":"c","bar2":"d"}]"; line: 1, column: 2]

**Comment by cowtowncoder** [comment] 2023-04-23 18:17
@sezinkarli I suspect that the problem with `Set.of()` and related might be that there is specialized handling to support handling of some JDK provided "special" types like Immutable set/lists/maps. Perhaps edge case handling does something to prevent it from working. I agree that this is quite odd.

How about I leave this open, just in case I or someone else has time to look deeper? 

One thing that would be helpful would be creating minimal unit test, providing PR (putting test under `.../failing` package) (I know there is reproduction above, but could probably cut it to even smaller).

Thank you for reporting this issue, and I hope workarounds work for you in the meantime, if the issue cannot be resolved (and like I said, wrapper approach is the most robust way to avoid various problems).

**Comment by yihtserns** [comment] 2023-04-24 15:24
When using `HashSet`:
```json
[
    "java.util.HashSet",
    [
        {
            "@class":"some.package.Foo",
            "bar1":"a",
            "bar2":"b"
        },
        {
            "@class":"some.package.Foo",
            "bar1":"c",
            "bar2":"d"
        }
    ]
]
```

When using `Set.of`:
```json
[
    {
        "@class":"some.package.Foo",
        "bar1":"c",
        "bar2":"d"
    },
    {
        "@class":"some.package.Foo",
        "bar1":"a",
        "bar2":"b"
    }
]
```

The latter doesn't have the type info for the Set because `Set.of` returns an instance of [ImmutableCollections.Set12](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/jdk-11+28/src/java.base/share/classes/java/util/ImmutableCollections.java#L486) which has been declared `final` (vs `objectMapper.activateDefaultTyping(..., DefaultTyping.NON_FINAL, ...)`)

**Comment by sezinkarli** [comment] 2023-04-24 16:09
This seems in line with the config then? Thanks @yihtserns

**Comment by cowtowncoder** [comment] 2023-04-24 18:24
Yes, I think it unfortunately is. Use of forced (base) type would probably resolve that (option 3) fwtw.

**Comment by VictorZZZZ** [comment] 2023-08-08 13:30
This happens, when you try to serialize Umodifiable List.

**Comment by cowtowncoder** [comment] 2023-08-20 00:55
I don't think there is much that can be done here, aside from work-arounds, closing.

**Closed by cowtowncoder** 2023-08-20 00:55 UTC
Labels: to-evaluate
