### ISSUE TITLE
@JsonPropertyOrder annotation for JSON formatting

### ISSUE THREAD

**Issue by Jerry-X07** [FasterXML/jackson-databind#4387] opened 2024-02-15 07:36 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

I have a Java class named OrderCount which is annotated with @JsonPropertyOrder from the package com.fasterxml.jackson.annotation.JsonPropertyOrder. The goal is to format the JSON output in a specific order. The desired order is: entityId, entityName, totalTests, products, and childEntities at the end. However, despite attempting to reorder the properties, I'm encountering difficulties placing childEntities at the end of the JSON output.

```
@Data
@SuperBuilder(toBuilder = true)
@NoArgsConstructor
@JsonPropertyOrder({"entityId", "entityName", "totalTests", "products", "childEntities"})
public class OrderCount {
    private String entityId;
    private String entityName;
    private Integer totalTests;

    @Builder.Default
    private Map<String, Integer> products = new HashMap<>();

    private List<OrderCount> childEntities;

    @JsonAnyGetter
    public Map<String, Integer> getProducts() {
        return products;
    }

    @JsonAnySetter
    public void setAdditionalProductProperty(String name, Integer value) {
        products.put(name, value);
    }
}
```

Specifically, when I try to change the order of `entityId`, `entityName`, and `totalTests`, then it's working. However, when I try to change the order of products or childEntities, it's not working as expected

### Expected behavior

`{
    "entityId": "1",
    "entityName": "entity1",
    "totalTests": 6,
    "productName_1":2,
    "productName_2":2,
          .
          .
    "productName_n":2,
    "childEntities": [
        {
            "entityId": "2",
            "entityName": "entity2",
            "totalTests": 3,
            "productName_1":1,
        "productName_2":1,
          .
          .
        "productName_n":1,
            "childEntities": []
        },
        {
            "entityId": "3",
            "entityName": "entity3",
            "totalTests": 3,
            "productName_1":1,
        "productName_2":1,
          .
          .
        "productName_n":1,
            "childEntities": []
        }
    ]
}`

But Instead of above JSON Format getting This JSON format :
`{
    "entityId": "1",
    "entityName": "entity1",
    "totalTests": 6,
    "childEntities": [
        {
            "entityId": "2",
            "entityName": "entity2",
            "totalTests": 3,
            "childEntities": [],
            "productName_1":1,
            "productName_2":1,
                  .
                  .
            "productName_n":1
        },
        {
            "entityId": "3",
            "entityName": "entity3",
            "totalTests": 3,
            "childEntities": [],
            "productName_1":1,
            "productName_2":1,
                  .
                  .
            "productName_n":1
        }
    ],
    "productName_1":2,
    "productName_2":2,
          .
          .
    "productName_n":2
}`

**Comment by JooHyukKim** [comment] 2024-02-15 14:41
Maybe @JsonAnyGetter, @JsonAnySetter may be properties/getters/setters with those annotations are not respected....? 🤔

**Comment by yihtserns** [comment] 2024-02-15 20:20
Can you share how decompile `.class` looks like?

I'm suspecting either `@ConstructorProperties` or `MapperFeature.SORT_CREATOR_PROPERTIES_FIRST` is the cause.

**Comment by cowtowncoder** [comment] 2024-02-16 02:12
`@JsonPropertyOrder` does not affect serialization of "any" properties output by `@JsonAnyGetter`; they are always serialized after actual POJO properties.

There is #518 requesting "any properties" to be sorted (at least wrt alphabetic sorting), but I don't think anyone is working on that. The issue is that output of any-properties is quite separate from output of regular properties so there is no easy fix.

But I guess the idea of using logical name of "any getter" accessor (here, `products`) for determining ordering of any-properties contained makes sense from user perspective.

**Comment by cowtowncoder** [comment] 2024-02-16 04:28
I filed #4388 to specifically request that `@JsonPropertyOrder` would have effect on grouped "any" and "unwrapped" properties.

**Comment by cowtowncoder** [comment] 2024-02-16 18:15
I assume #4388 is a replacement for this, so closing.

**Closed by cowtowncoder** 2024-02-16 18:15 UTC
Labels: to-evaluate

**Comment by cowtowncoder** [comment] 2024-02-19 03:06
@Jerry-X07 which version were you testing this against?
