### ISSUE TITLE
field detection regression between Jackson 2.8 and 2.9

### ISSUE THREAD

**Issue by hgschmie** [FasterXML/jackson-databind#1972] opened 2018-03-15 18:08 UTC
Using this test code: https://github.com/airlift/airlift/blob/master/json/src/test/java/io/airlift/json/TestJsonModule.java#L101-L110

which explicitly tests that in an object mapper that has all autodetection disabled: https://github.com/airlift/airlift/blob/master/json/src/main/java/io/airlift/json/ObjectMapperProvider.java#L107-L130

This test passes with Jackson 2.8. With Jackson 2.9, it reports

[ERROR] testFieldDetection(io.airlift.json.TestJsonModule)  Time elapsed: 0.007 s  <<< FAILURE!
java.lang.AssertionError: Sets differ: expected [make, model, year, purchased, nameList] but got [make, model, year, purchased, notes, nameList]
	at io.airlift.json.TestJsonModule.testFieldDetection(TestJsonModule.java:109)

So the field, that is supposed to not-detected by Jackson is detected by 2.9 (but not by 2.8). I tested with 2.8.1 (passes), 2.8.11 (passes), 2.9.0 (fails) and 2.9.4 (fails). 

Looking through the release notes I did not find anything that would explain this behavior (or how to turn it off), so I consider that an actual regression.

**Comment by cowtowncoder** [comment] 2018-03-15 18:15
Ok sounds legit. `2.9.5` does have one bug fix, #1947, and I wonder if that might be related or same.

**Comment by cowtowncoder** [comment] 2018-03-15 20:46
Looking at code, I am wondering if I am missing something, regarding base visibility settings.
If the intent is to disable introspection of fields, default settings need to be changed, as `public` fields are detected by default. So I was expecting to see something do that, but test seems to use quite basic `ObjectMapper`. Since a DI framework is being used it is quite possible I am just missing that wiring which could explain the difference.

As to changes: no planned changes were made to change the logic between 2.8 and 2.9.

**Comment by hgschmie** [comment] 2018-03-20 18:52
Will test as soon as 2.9.5 comes out. Are snapshots available from somewhere? (oss?)

**Comment by cowtowncoder** [comment] 2018-03-20 20:54
@hgschmie Sonatype snapshots should have auto-built 2.9.5-SNAPSHOT. Although there have been some issues with dependencies (`jackson-base` and/or `jackson-parent` did not get travis-built from commits), so may require some local building.

**Comment by hgschmie** [comment] 2018-03-21 05:35
I can confirm that 2.9.5-SNAPSHOT for core and databind (these are the deps that I have replaced) fix the problem.  So this seems to be the problem described in #1947 .

**Comment by mbasmanova** [comment] 2018-03-21 11:18
I ran into this issue as well. When will 2.9.5 release become available?

**Comment by cowtowncoder** [comment] 2018-03-21 18:29
Planning to release 2.9.5 before end of the month. It would be good if this issue could be verified, but unfortunately test here as is won't work as regression test.
I can try cloning `airlift` at home, change dependency, and see if I can repro.

**Comment by hgschmie** [comment] 2018-03-21 21:55
Already wrote above that the fix in #1947 fixes the problem for me. So
![shipit-animated](https://user-images.githubusercontent.com/39495/37739604-e41b5c7a-2d17-11e8-8113-3fb6a9db08d3.gif)

**Comment by cowtowncoder** [comment] 2018-03-21 22:51
@hgschmie ah sorry. Somehow missed your update, didn't see it. Thanks!

**Comment by cowtowncoder** [comment] 2018-04-04 18:10
Fixed by 2.9.5.

**Closed by cowtowncoder** 2018-04-04 18:10 UTC
Labels: 2.9, ACTIVE
