### ISSUE TITLE
StackOverflowError with contentConverter that returns array type

### ISSUE THREAD

**Issue by fschopp** [FasterXML/jackson-databind#357] opened 2013-12-02 21:56 UTC
Jackson version: 2.3.0

The following code snippet

``` java
static class A { }

static class B {
    @JsonSerialize(contentConverter = AToStringConverter.class)
    public List<A> list = Arrays.asList(new A());
}

static class AToStringConverter extends StdConverter<A, List<String>> {
    @Override
    public List<String> convert(A value) {
        return Arrays.asList("Hello world.");
    }
}

@Test
void testBSerialization() throws Exception {
    new ObjectMapper().writeValueAsString(new B());
}
```

produces the following endless recursion:

```
[...]
at com.fasterxml.jackson.databind.ser.std.StdSerializer.findConvertingContentSerializer(StdSerializer.java:252)
at com.fasterxml.jackson.databind.ser.impl.StringCollectionSerializer.createContextual(StringCollectionSerializer.java:91)
at com.fasterxml.jackson.databind.SerializerProvider.handleSecondaryContextualization(SerializerProvider.java:835)
at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:503)
at com.fasterxml.jackson.databind.ser.std.StdSerializer.findConvertingContentSerializer(StdSerializer.java:252)
at com.fasterxml.jackson.databind.ser.impl.StringCollectionSerializer.createContextual(StringCollectionSerializer.java:91)
at com.fasterxml.jackson.databind.SerializerProvider.handleSecondaryContextualization(SerializerProvider.java:835)
at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:503)
[...]
```

It seems that the @JsonSerialize annotation is applied both before and after the conversion.

**Comment by cowtowncoder** [comment] 2016-04-14 23:22
Alas: it looks like my fix did not fully work; it just happened to add a different flaw that did fix converter problem, but caused other issues. Essentially removal of lock failed, and so lock lasted until end of current processing (`writeValue()`). I am not fixing the problem with mechanism locking uses, and once lock lifecycle works as intended, the original problem reappears.

So it's back to square one, with 2.7.4. :-(

**Comment by nazymko** [comment] 2016-04-26 10:25
Hello, 
Is this bug fixed in 2.7 ?

**Comment by cowtowncoder** [comment] 2016-04-27 05:09
@nazymko No, unfortunately there is no known working fix. Earlier attempt did hide the problem, but in a way that broke any nested resolution (or one that follows in document order, even if not nested).

**Comment by TuomasKiviaho** [comment] 2017-03-30 11:08
```
Caused by: java.lang.StackOverflowError
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:601)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.createContextual(StdDelegatingSerializer.java:121)
	at com.fasterxml.jackson.databind.SerializerProvider.handleSecondaryContextualization(SerializerProvider.java:1001)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.createContextual(StdDelegatingSerializer.java:125)
	at com.fasterxml.jackson.databind.SerializerProvider.handleSecondaryContextualization(SerializerProvider.java:1001)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.createContextual(StdDelegatingSerializer.java:125)
```
I think that `StdDelegatingSerializer` was forgotten from https://github.com/FasterXML/jackson-databind/commit/9434f515e559ccb744064cfc82da3c41c64248ef

```
    @Override
    public JsonSerializer<?> createContextual(SerializerProvider provider, BeanProperty property)
        throws JsonMappingException
    {
        JsonSerializer<?> delSer = _delegateSerializer;
        JavaType delegateType = _delegateType;

        if (delSer == null) {
            // Otherwise, need to locate serializer to delegate to. For that we need type information...
            if (delegateType == null) {
                delegateType = _converter.getOutputType(provider.getTypeFactory());
            }
            // 02-Apr-2015, tatu: For "dynamic case", where type is only specified as
            //    java.lang.Object (or missing generic), [databind#731]
            if (!delegateType.isJavaLangObject()) {
                delSer = provider.findValueSerializer(delegateType);
            }
        }
        if (delSer instanceof ContextualSerializer) {
            delSer = provider.handleSecondaryContextualization(delSer, property);
        }
        if (delSer == _delegateSerializer && delegateType == _delegateType) {
            return this;
        }
        return withDelegate(_converter, delegateType, delSer);
    }
```
The `handleSecondaryContextualization` kicks in every time in this method and the commit referenced above tries to avoid just kind of situation. I got this with my introspector tweak #1584 in but I think that this could potentially pop up without it.

**Comment by cowtowncoder** [comment] 2017-03-30 19:17
@TuomasKiviaho is that with the original code here, or something else? Test case I had was slightly simplified but it passes. I don't doubt there's a remaining problem, just want to reproduce it -- the whole contextualization is tricky to get right, esp. for content (de)serializers.

**Comment by cowtowncoder** [comment] 2017-03-30 19:33
Original test as-is seems to pass, and test does use `StdDelegatingSerializer`, for what it is worth.

**Comment by TuomasKiviaho** [comment] 2017-03-31 11:50
> I don't doubt there's a remaining problem, just want to reproduce it

This should be reproducible by having `StdDelegatingSerializer` internal state `_delegateSerializer` as null and then calling the `createContextual` method shown above. This state can be achieved with the currently available constructors. 

`delSer = provider.findValueSerializer(delegateType);` seems to return in my case the same `StdDelegatingSerializer`instance that I'm already in thus looping ` delSer = provider.handleSecondaryContextualization(delSer, property);` forever.

**Comment by cowtowncoder** [comment] 2017-03-31 18:08
What I mean is a unit test, both as demonstration and to guard against regression, using actual API or declarations to get there.

**Comment by cowtowncoder** [comment] 2017-05-04 21:39
At this point, can not reproduce, so closing. I am not arguing that this does not occur, simply that I have no way of triggering this with actual usage and as such do not trust that tests that manipulate internal state would faithfully reproduce problem users might encountered (or, more importantly, verify that fix is appropriate).

A new issue should be filed with reproduction if this is encountered (with ref back to this as background) in wild.

**Closed by cowtowncoder** 2017-05-04 21:39 UTC
Labels: 2.9
