### ISSUE TITLE
field name changed when deserializing bean

### ISSUE THREAD

**Issue by huanm** [FasterXML/jackson-databind#3538] opened 2022-07-07 09:46 UTC
**Describe the bug**
RequestBody annotation bean with double upper word,filed will change.
for example,bean with field name `qAExportFieldList`,when deserializing bean ,bean properity name find `qaexportFieldList` insdead of `qAExportFieldList`.

ex:
`BeanDeserializer.class: SettableBeanProperty prop = _beanProperties.find(propName)`
_beanProperties exists qaexportFieldList insdead of qAExportFieldList

**Version information**
Which Jackson version(s) was this for?
2.13.1
**To Reproduce**
If you have a way to reproduce this with:

1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here

**Expected behavior**
If reproduction itself needs further explanation, you may also add more details here.

**Additional context**

**Comment by huanm** [comment] 2022-07-08 03:46
> This is not enough to show a problem: a unit test would be needed -- and it must not depend on external frameworks or libraries.
> 
> From description it appears that this might be related to Bean Name handling where capitalization matters, so reproduction is very important.

```
@Test
	public void testBo() throws IOException {
		//{"projectId":"projectId0001","qAExportFieldList":["{\"id\":\"Assignee\",\"name\":\"Assignee\"}"]}
		WorkitemQAQueryBO bo = new WorkitemQAQueryBO();
		bo.setQAExportFieldList(Collections.singletonList("{\"id\":\"Assignee\",\"name\":\"Assignee\"}"));
		bo.setProjectId("projectId0001");
		HttpHeaders headers = new HttpHeaders();
		headers.setContentType(MediaType.APPLICATION_JSON);
		HttpEntity entity = new HttpEntity(bo,headers);
		String response = restTemplate.postForObject("http://localhost:9105/quality/test/testBo", entity, String.class);
		//returns:{"projectId":"projectId0001","qaexportFieldList":["{\"id\":\"Assignee\",\"name\":\"Assignee\"}"]}
		System.out.println(response);
	}
```

* controller
```
@Controller
@RequestMapping("/test")
public class TestController {
    @PostMapping("/testBo")
    @ResponseBody
    public WorkitemQAQueryBO exportQA(@RequestBody WorkitemQAQueryBO queryBO){
        return queryBO;
    }
}
```

* WorkitemQAQueryBO
```
@Data
public class WorkitemQAQueryBO implements Serializable {
    private final static Long serialVersionUID = 1L;
    private String projectId;
    private List<String> qAExportFieldList;

}
```

**Comment by huanm** [comment] 2022-07-08 06:49
> 
run with
```
ObjectMapper objectMapper = new ObjectMapper();
        JavaType javaType = objectMapper.constructType(new TypeReference<WorkitemQAQueryBO>() {
        });
        String jsonStr ="{\"projectId\":\"projectId0001\",\"qAExportFieldList\":[\"{\\\"id\\\":\\\"Assignee\\\",\\\"name\\\":\\\"Assignee\\\"}\"]}";
        WorkitemQAQueryBO bo = objectMapper.readValue(new ByteArrayInputStream(jsonStr.getBytes(StandardCharsets.UTF_8)), javaType);
```

throws exception:
```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "qAExportFieldList" (class WorkitemQAQueryBO), not marked as ignorable (2 known properties: "projectId", "qaexportFieldList"])
 at [Source: (ByteArrayInputStream); line: 1, column: 51] (through reference chain: com.desv.es.bean.WorkitemQAQueryBO["qAExportFieldList"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3682)
```

**Comment by yawkat** [comment] 2022-07-08 09:18
your test case still requires lombok. please make a test case *without* other dependencies. i suspect lombok is generating a different getter name, but it's hard to tell with your test case.

the code you show in legacyManglePropertyName is not supposed to be hit because the property name begins with a lowercase character (there's a check further up). you can try `USE_STD_BEAN_NAMING` if you want, but i doubt it's going to work

**Comment by cowtowncoder** [comment] 2022-07-08 20:47
@huanm Like @yawkat what we need is a reproduction, not a claim on where something is allegedly wrong.

Based on past experiences it is very likely the case of Lombok creating getters/setters that will produce property names (by Jackson Bean name handling) that are different from your expectations. This in itself is not often a bug from Jackson perspective but rather difference in processing by frameworks.

Solution is usually adding a `@JsonProperty` annotation (or in rare cases, 2) to indicate how Field and accessors are related to each other (or just override logical property name for accessors).

But it is easier to explain this with actual POJO definition.

**Comment by cowtowncoder** [comment] 2022-07-28 22:27
No full reproduction, closing. But I am 95% certain that in this case user needs to use an annotation to connect somewhat non-standard (wrt Bean naming) field name and getter/setter, to get Jackson to use and recognize specific JSON property name.

**Closed** 2022-07-28 22:26 UTC
Labels: need-test-case
