### ISSUE TITLE
@JacksonInject fails when trying to inject and instance of ObjectMapper with a PROPERTIES based JsonCreator contructor

### ISSUE THREAD

**Issue by chapmbk** [FasterXML/jackson-databind#1119] opened 2016-02-05 19:57 UTC
This following example works as expected

```java
public class JacksonForUpdate {

    public static class Bean {
        private String name;
        private Map<String, Object> properties;

        public void setName(String name) {
            this.name = name;
        }

        @JsonCreator
        public Bean(JsonNode node, @JacksonInject ObjectMapper mapper) throws IOException {
            this.properties = mapper.convertValue(node, Map.class);
            mapper.readerForUpdating(this).readValue(node);
        }

        @Override
        public String toString() {
            return "Bean{" +
                "name='" + name + '\'' +
                ", properties=" + properties +
                '}';
        }
    }

    public static void main(String[] args) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        // make the mapper to be available for the bean
        mapper.setInjectableValues(new InjectableValues.Std().addValue(ObjectMapper.class, mapper));
        final ObjectNode objectNode = mapper.createObjectNode();
        objectNode.put("name", "value");
        System.out.println(
            mapper.treeToValue(
                objectNode, Bean.class));
    }
}
```

The next example fails with an exception:  Conflicting setter definitions for property "config": 

com.fasterxml.jackson.databind.ObjectMapper#setConfig(1 params) vs com.fasterxml.jackson.databind.ObjectMapper#setConfig(1 params)

```java
public class JacksonForUpdate {

    public static class Bean {
        private String name;

        @JsonCreator
        public Bean(@JsonProperty("name") String name, @JacksonInject ObjectMapper mapper) throws IOException {
            this.name = name;
        }

        @Override
        public String toString() {
            return "Bean{" +
                "name='" + name + '\'' +
                '}';
        }
    }

    public static void main(String[] args) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        // make the mapper to be available for the bean
        mapper.setInjectableValues(new InjectableValues.Std().addValue(ObjectMapper.class, mapper));
        final ObjectNode objectNode = mapper.createObjectNode();
        objectNode.put("name", "value");
        System.out.println(
            mapper.treeToValue(
                objectNode, Bean.class));
    }
}
```

**Comment by cowtowncoder** [comment] 2016-02-10 01:02
Hmmh. Interesting. Thank you for reporting this.

**Comment by cowtowncoder** [comment] 2016-05-25 05:30
I suspect this is same as/related to #962: that is, injectable value being introspected.
So sort of secondary fail.

**Comment by cowtowncoder** [comment] 2016-05-25 05:34
Ok, yes; I think this is duplicate of #962: I will close this one just based on order of reporting, problem itself is valid.

**Closed by cowtowncoder** 2016-05-25 05:34 UTC
