### ISSUE TITLE
PrettyPrinter Indenter: Ability to insert eol before object and array entries

### ISSUE THREAD

**Issue by cowwoc** [FasterXML/jackson-databind#724] opened 2015-03-10 02:53 UTC
I'd like to be able to configure an indenter to insert a newline before object and array braces/brackets. Instead of:

```
{
  foo: {
    bar: true
  }
}
```

I want:

```
{
  foo:
  {
    bar: true
  }
}
```

**Comment by cowtowncoder** [comment] 2015-03-10 16:42
Is this not currently possible with a custom `PrettyPrinter`? Patches for default pretty printer are accepted also of course.

**Comment by cowwoc** [comment] 2015-03-11 04:42
@cowtowncoder This implementation works for me:

```
public class MyPrettyPrinter implements PrettyPrinter
{
	private final String lf = System.getProperty("line.separator");
	private int indentation = 0;
	private boolean isNewline = false;

	@Override
	public void writeRootValueSeparator(JsonGenerator jg) throws IOException, JsonGenerationException
	{
		jg.writeRaw(' ');
	}

	@Override
	public void writeStartObject(JsonGenerator jg) throws IOException, JsonGenerationException
	{
		if (!isNewline)
			newline(jg);
		jg.writeRaw('{');
		++indentation;
		isNewline = false;
	}

	@Override
	public void writeEndObject(JsonGenerator jg, int nrOfEntries) throws IOException, JsonGenerationException
	{
		--indentation;
		jg.writeRaw(lf);
		newline(jg);
		jg.writeRaw('}');
		isNewline = false;
	}

	@Override
	public void writeObjectEntrySeparator(JsonGenerator jg) throws IOException, JsonGenerationException
	{
		jg.writeRaw("," + lf);
		newline(jg);
	}

	@Override
	public void writeObjectFieldValueSeparator(JsonGenerator jg) throws IOException, JsonGenerationException
	{
		jg.writeRaw(": ");
		isNewline = false;
	}

	@Override
	public void writeStartArray(JsonGenerator jg) throws IOException, JsonGenerationException
	{
		jg.writeRaw(lf);
		newline(jg);
		jg.writeRaw("[");
		++indentation;
		isNewline = false;
	}

	@Override
	public void writeEndArray(JsonGenerator jg, int nrOfValues) throws IOException, JsonGenerationException
	{
		--indentation;
		jg.writeRaw(lf);
		newline(jg);
		jg.writeRaw(']');
		isNewline = false;
	}

	@Override
	public void writeArrayValueSeparator(JsonGenerator jg) throws IOException, JsonGenerationException
	{
		jg.writeRaw(", ");
		isNewline = false;
	}

	@Override
	public void beforeArrayValues(JsonGenerator jg) throws IOException, JsonGenerationException
	{
		jg.writeRaw(lf);
		newline(jg);
	}

	@Override
	public void beforeObjectEntries(JsonGenerator jg) throws IOException, JsonGenerationException
	{
		jg.writeRaw(lf);
		newline(jg);
	}

	/**
	 * Writes a newline and indentation.
	 * <p>
	 * @param jg the JsonGenerator to write to
	 * @throws IOException if an I/O error occurs
	 */
	private void newline(JsonGenerator jg) throws IOException
	{
		for (int i = 0; i < indentation; ++i)
			jg.writeRaw("  ");
		isNewline = true;
	}
}
```

This isn't a patch, but it's a step in that direction.

**Comment by cowwoc** [comment] 2015-03-11 05:26
On a related note, I would love to know why `writeRootValueSeparator()` is never invoked because (as you can see from the code) I am forced to reset the value of `isNewline` in `writeEndObject()`. Ideally I would like to reset its value to `true` at the beginning or end of each serialization.

**Comment by cowtowncoder** [comment] 2015-03-12 18:29
Perhaps there is a bug in propagation of that call? I know default root value separator code works in general, but I don't remember trying it out through pretty printer, so it could be accidentally unwired.

**Comment by cowtowncoder** [comment] 2015-03-25 05:15
@cowwoc `writeRootValueSeparator()` is called as per tests in `jackson-core`: I added some more testing to double-check. If you have a reproduction of the problem that might explain it.
And just to make sure it's not just terminology question: root value separator is applied "outside" of top values, not at first level of JSON Object.

**Comment by cowtowncoder** [comment] 2015-05-02 03:19
I can not reproduce the issue with root value separator. Perhaps code is closing generator, creating new one, between serialization calls or something?

Issue may be reopened with a reproducible test case.

**Comment by cowwoc** [comment] 2015-09-20 10:12
@cowtowncoder Please reopen this issue. Here is the testcase you requested:

```
public class Main {

    public static class MyPrettyPrinter implements PrettyPrinter {

        private final String lf = System.getProperty("line.separator");
        private int indentation = 0;
        private boolean isNewline = true;
        public int rootValueSeparators = 0;

        @Override
        public void writeRootValueSeparator(JsonGenerator jg) throws IOException, JsonGenerationException {
            ++rootValueSeparators;
        }

        @Override
        public void writeStartObject(JsonGenerator jg) throws IOException, JsonGenerationException {
            if (!isNewline) {
                newline(jg);
            }
            jg.writeRaw('{');
            ++indentation;
            isNewline = false;
        }

        @Override
        public void writeEndObject(JsonGenerator jg, int nrOfEntries) throws IOException, JsonGenerationException {
            --indentation;
            newline(jg);
            jg.writeRaw('}');
            isNewline = indentation == 0;
        }

        @Override
        public void writeObjectEntrySeparator(JsonGenerator jg) throws IOException, JsonGenerationException {
            jg.writeRaw(",");
            newline(jg);
        }

        @Override
        public void writeObjectFieldValueSeparator(JsonGenerator jg) throws IOException, JsonGenerationException {
            jg.writeRaw(": ");
            isNewline = false;
        }

        @Override
        public void writeStartArray(JsonGenerator jg) throws IOException, JsonGenerationException {
            newline(jg);
            jg.writeRaw("[");
            ++indentation;
            isNewline = false;
        }

        @Override
        public void writeEndArray(JsonGenerator jg, int nrOfValues) throws IOException, JsonGenerationException {
            --indentation;
            newline(jg);
            jg.writeRaw(']');
            isNewline = false;
        }

        @Override
        public void writeArrayValueSeparator(JsonGenerator jg) throws IOException, JsonGenerationException {
            jg.writeRaw(", ");
            isNewline = false;
        }

        @Override
        public void beforeArrayValues(JsonGenerator jg) throws IOException, JsonGenerationException {
            newline(jg);
        }

        @Override
        public void beforeObjectEntries(JsonGenerator jg) throws IOException, JsonGenerationException {
            newline(jg);
        }

        /**
         * Writes a newline and indentation.
         * <p>
         * @param jg the JsonGenerator to write to
         * @throws IOException if an I/O error occurs
         */
        private void newline(JsonGenerator jg) throws IOException {
            jg.writeRaw(lf);
            for (int i = 0; i < indentation; ++i) {
                jg.writeRaw("  ");
            }
            isNewline = true;
        }
    }

    private static final MyPrettyPrinter prettyPrinter = new MyPrettyPrinter();
    private static final ObjectWriter writer = new ObjectMapper().writer(prettyPrinter);

    public static void main(String[] args) {
        String value = "value";
        String[] array = {value};
        String result;
        try {
            result = writer.writeValueAsString(array);
            result = writer.writeValueAsString(array);
            result = writer.writeValueAsString(array);
        } catch (JsonProcessingException e) {
            throw new AssertionError(e);
        }
        System.out.println("value: " + result);
        assert (prettyPrinter.rootValueSeparators == 3) : "rootValueSeparators = " + prettyPrinter.rootValueSeparators;
    }
}
```

**Comment by cowwoc** [comment] 2015-09-20 10:32
I think the problem is that `ObjectWriter.writeValueAsString()` creates a separate nested writer per invocations, so `rootValueSeparator` is never triggered. To clarify: I need a way to get notified at the beginning or end of each `writeValueAsString()` invocation. I don't see a way to do that with the current API.

**Comment by cowtowncoder** [comment] 2015-09-21 18:59
No, this will not work and is not intended to work. Indenter is valid within context of an open `JsonGenerator`, and one will be constructed for each `writeValueAsString`.
`ObjectWriter`s are stateless, immutable, and there is no way (or intent) to share state of indenter.

To produce root value separators, a single `JsonGenerator` must be used, as that tracks output state, to know where and when to add root value separator.

**Closed by cowtowncoder** 2015-09-21 18:59 UTC
