### ISSUE TITLE
Update from version 2.9.1 to 2.9.2 breaks Apache Log4j 

### ISSUE THREAD

**Issue by garydgregory** [FasterXML/jackson-databind#1795] opened 2017-10-16 19:02 UTC
Updating from version Jackson 2.9.1 to 2.9.2 breaks Apache Log4j.

Log4j does register mixins through **Log4jJsonObjectMapper**, **Log4jJsonModule** and **SetupContextJsonInitializer**.

Clone https://github.com/apache/logging-log4j2.git and update the Jackson reference in the root pom.xml from 2.9.1 to 2.9.2.

Run: 

`mvn clean test -pl log4j-core
`
All errors:

```
[ERROR] Errors:
[ERROR]   LevelMixInJsonTest>LevelMixInTest.testContainer:94 ╗ MismatchedInput Cannot co...
[ERROR]   LevelMixInJsonTest>LevelMixInTest.testNameOnly:103 ╗ MismatchedInput Cannot co...
[ERROR]   LevelMixInYamlTest>LevelMixInTest.testContainer:94 ╗ MismatchedInput Cannot co...
[ERROR]   LevelMixInYamlTest>LevelMixInTest.testNameOnly:103 ╗ MismatchedInput Cannot co...
[ERROR]   JsonLayoutTest.testExcludeStacktrace:392->testAllFeatures:147 ╗ MismatchedInput
[ERROR]   JsonLayoutTest.testLayoutLoggerName:345 ╗ MismatchedInput Cannot construct ins...
[ERROR]   JsonLayoutTest.testLocationOffCompactOffMdcOff:372->testAllFeatures:147 ╗ MismatchedInput
[ERROR]   JsonLayoutTest.testLocationOnCompactOnEventEolOnMdcOn:382->testAllFeatures:147 ╗ MismatchedInput
[ERROR]   JsonLayoutTest.testLocationOnCompactOnEventEolOnMdcOnMdcAsList:387->testAllFeatures:147 ╗ MismatchedInput
[ERROR]   JsonLayoutTest.testLocationOnCompactOnMdcOn:377->testAllFeatures:147 ╗ MismatchedInput
[ERROR]   XmlLayoutTest.testExcludeStacktrace:338->testAllFeatures:146 ╗ MismatchedInput
[ERROR]   XmlLayoutTest.testLocationOffCompactOffMdcOff:328->testAllFeatures:146 ╗ MismatchedInput
[ERROR]   XmlLayoutTest.testLocationOnCompactOnMdcOn:333->testAllFeatures:146 ╗ MismatchedInput
[ERROR]   YamlLayoutTest.testExcludeStacktrace:333->testAllFeatures:132 ╗ MismatchedInput
[ERROR]   YamlLayoutTest.testLayoutLoggerName:299 ╗ MismatchedInput Cannot construct ins...
[ERROR]   YamlLayoutTest.testLocationOffCompactOffMdcOff:323->testAllFeatures:132 ╗ MismatchedInput
[ERROR]   YamlLayoutTest.testLocationOnCompactOffEventEolOffMdcOn:328->testAllFeatures:132 ╗ MismatchedInput
[ERROR]   JsonLogEventParserTest.testByteArray:118 ╗ Parse com.fasterxml.jackson.databin...
[ERROR]   JsonLogEventParserTest.testByteArrayOffsetLength:125 ╗ Parse com.fasterxml.jac...
[ERROR]   JsonLogEventParserTest.testString:82 ╗ Parse com.fasterxml.jackson.databind.ex...
[ERROR]   XmlLogEventParserTest.testByteArray:113 ╗ Parse com.fasterxml.jackson.databind...
[ERROR]   XmlLogEventParserTest.testByteArrayOffsetLength:120 ╗ Parse com.fasterxml.jack...
[ERROR]   XmlLogEventParserTest.testString:82 ╗ Parse com.fasterxml.jackson.databind.exc...
[ERROR]   YamlLogEventParserTest.testByteArray:107 ╗ Parse com.fasterxml.jackson.databin...
[ERROR]   YamlLogEventParserTest.testByteArrayOffsetLength:114 ╗ Parse com.fasterxml.jac...
[ERROR]   YamlLogEventParserTest.testString:76 ╗ Parse com.fasterxml.jackson.databind.ex...
[INFO]
[ERROR] Tests run: 2280, Failures: 9, Errors: 26, Skipped: 26

```

Example error in detail:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.apache.logging.log4j.Level` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('DEBUG')
 at [Source: (String)""DEBUG""; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1342)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1031)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:370)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:170)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1216)
	at org.apache.logging.log4j.core.jackson.LevelMixInTest.testNameOnly(LevelMixInTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)	
```

**Comment by cowtowncoder** [comment] 2017-10-24 18:05
First of all thank you for reporting the problem.

Unfortunately this is not very useful from Jackson side -- I would need a reproduction of one or more problems. Or even cut'n pasting of an example from tests.

**Comment by garydgregory** [comment] 2017-10-25 02:57
How can that be? We have a failing unit test: LevelMixInJsonTest.

**Comment by cowtowncoder** [comment] 2017-10-25 15:50
@garydgregory I may be wrong without looking at tests, but what is needed is a stand-alone test without external dependencies. It is possible tests could be such already, if so, that's useful.
I hope to have a look at this in near future.

**Comment by cowtowncoder** [comment] 2017-11-01 21:10
Ok since #1809 has bit more detail, I'll close this one, either one would do.

But what seems to happen is that `2.9.2` actually fixes behavior of existing annotation which I think is wrong (`@JsonCreator` specifying properties-based behavior instead of delegating -- applied via mix-in). So I think change is needed on log4j side; change should be backwards compatible (i.e. older Jackson versions should work with changed version as well as 2.9.2).

**Closed by cowtowncoder** 2017-11-01 21:10 UTC
Labels: 2.9, ACTIVE
