### ISSUE TITLE
Unclear error message for invalid JsonTypeInfo type

### ISSUE THREAD

**Issue by becky-sequence** [FasterXML/jackson-databind#4373] opened 2024-02-08 08:51 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/FasterXML/jackson-databind/issues) and found nothing similar.

### Describe the bug

Change in behaviour (at least since 2.15.3) - the error message received when deseriliasing from JSON where a `JsonTypeInfo` value is required. If an an invalid value is provided (e.g. `'FAKE'`) we used to get a message `Could not resolve type: 'FAKE'`, but now we get `Cannot invoke "Object.toString()" because the return value of "com.fasterxml.jackson.core.io.ContentReference.getRawContent()" is null`.

The new error message is very unclear and is not a good response for customers calling our APIs with invalid requests. Is it possible to revert to the previous behaviour?

### Version Information

Was working for 2.15.3
Definitely not working for 2.16.1

### Reproduction

<-- Any of the following
1. Brief code sample/snippet: include here in preformatted/code section
2. Longer example stored somewhere else (diff repo, snippet), add a link
3. Textual explanation: include here
 -->
```java
// Your code here
```

**Comment by JooHyukKim** [comment] 2024-02-08 09:00
Sounds like regression that can be fixed. Will see later today if I can propose a fix.

Target version is TBD tho

**Comment by cowtowncoder** [comment] 2024-02-08 15:28
Yes, sound like minor regression to fix. A unit test would be great, although description probably allows one to create one.

**Comment by JooHyukKim** [comment] 2024-02-09 02:09
@becky-sequence Needs test case

**Comment by JooHyukKim** [comment] 2024-02-09 02:20
Right, we need test case here. I just tested and the results are providing unknown type id seems to be handled properly.

Could you provide a reproduction @becky-sequence ?

**Comment by becky-sequence** [comment] 2024-02-09 10:52
I did a bit more digging into our code and I see the error message I provided is actually due to the way we're handling this exception. It's because we try to access `idException.location.contentReference().rawContent.toString()` on the `InvalidTypeIdException` that is thrown and this is what's leading to this error. It's because `idException.location.contentReference().rawContent` is `null`. I think this is incorrect though?

**Comment by JooHyukKim** [comment] 2024-02-09 10:55
>  I think this is incorrect though?

Probably, NPE most of the time is not what Jackson wants to throw.
But to be for sure and make it possible to fix the issue, we need reproduction.

**Comment by becky-sequence** [comment] 2024-02-09 11:58
Sure. I think you'll get the error with any invalid type ID.

`package com.example

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonTypeInfo
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.exc.InvalidTypeIdException
import org.hamcrest.CoreMatchers.containsString
import org.hamcrest.MatcherAssert.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import kotlin.test.assertNotNull


internal class ExampleTest {

    enum class Type {
        A,B
    }


    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
    sealed class Example(
        @JsonProperty("type")
        val type: Type,
    )


    @Test
    fun `fails to deserialise with unknown type`() {
        val json = """{
            "type": "FAKE"
        }
        """

        val error = assertThrows<InvalidTypeIdException> { ObjectMapper().readValue(json, Example::class.java) }
        assertThat(
            error.message,
            containsString(
                "Could not resolve type id 'FAKE' as a subtype of `com.example.ExampleTest\$Example`"
            )
        )
        assertNotNull(error.location.contentReference().rawContent) // fails
    }
}
`

**Comment by cowtowncoder** [comment] 2024-02-10 00:18
Although `contentReference()` should not return `null`, rawContent is something for which no guarantees can be given, so `null` is possible.

So caller must be prepared to deal with `null`s -- given "rawContent" has no String typing (it's `java.lang.Object`); it can f.ex use

```
String.valueOf(error.location.contentReference().rawContent)
```

However. It is actually kind of wrong to try to blindly create `String` out of `rawContent` in general: it can be a `byte[]` with non-0 offset, just as an example.

`ContentReference` does, however, have other methods to use: I think `buildSourceDescription()` might be the best thing in your case.

**Comment by cowtowncoder** [comment] 2024-02-10 00:20
I don't think there is currently anything to fix: `rawContent` is allowed to be `null` as per my note above; and it should not be directly converter to `String` in general.

Closing: for other related improvement ideas, please file a new issue.

**Closed by cowtowncoder** 2024-02-10 00:20 UTC
Labels: need-test-case
