### ISSUE TITLE
Constructor autodetection does not take naming strategy into account

### ISSUE THREAD

**Issue by joca-bt** [FasterXML/jackson-databind#3846] opened 2023-03-27 16:38 UTC
Constructor autodetection (https://cowtowncoder.medium.com/jackson-2-12-most-wanted-3-5-246624e2d3d0/) does not appear to be working when used together with naming strategies which don't match the field names. See the examples below for more details.

```
public class Test {
    private final String fieldName;

    public Test(String fieldName) {
        this.fieldName = fieldName;
    }
}

ObjectMapper objectMapper = JsonMapper.builder()
    .addModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES))
    .constructorDetector(ConstructorDetector.USE_PROPERTIES_BASED)
    .propertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
    .build();
// Ok. Field name in JSON matches the one of the Java class so Jackson is able to find it, however, I've defined my strategy as snake case, so I was expecting fieldName to be invalid.
objectMapper.readValue("{ \"fieldName\": \"value\" }", Test.class);
// Fails. Field name doesn't match and the property naming strategy isn't being taken into consideration.
objectMapper.readValue("{ \"field_name\": \"value\" }", Test.class);
```

```
public class Test {
    private final String fieldName;

    public Test(@JsonProperty("field_name") String fieldName) {
        this.fieldName = fieldName;
    }
}

ObjectMapper objectMapper = JsonMapper.builder()
    .addModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES))
    .constructorDetector(ConstructorDetector.USE_PROPERTIES_BASED)
    .propertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
    .build();
// Ok. However we are helping Jackson by using @JsonProperty, which defeats the purpose of annotationless deserialization.
objectMapper.readValue("{ \"field_name\": \"value\" }", Test.class);
```

```
public class Test {
    private String fieldName;

    public Test(String fieldName) {
        this.fieldName = fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
}

ObjectMapper objectMapper = JsonMapper.builder()
    .addModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES))
    .constructorDetector(ConstructorDetector.USE_PROPERTIES_BASED)
    .propertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
    .build();
// Ok. Jackson is able to find the field without needing any annotation, but we need to define a setter. This is a no-go for records.
objectMapper.readValue("{ \"field_name\": \"value\" }", Test.class);
```

**Comment by cowtowncoder** [comment] 2023-03-28 03:01
Yes, @JooHyukKim is right; this is due to issue discussed under #3719 and just one symptom.

**Comment by yihtserns** [comment] 2023-04-07 14:49
Just a side note - about:
```
ObjectMapper objectMapper = JsonMapper.builder()
    .addModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES))
    .constructorDetector(ConstructorDetector.USE_PROPERTIES_BASED)
    .propertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
    .build();
// Ok. Jackson is able to find the field without needing any annotation, but we need to define a setter.
// *****This is a no-go for records.****** <---------------------
objectMapper.readValue("{ \"field_name\": \"value\" }", Test.class);
```

...`PropertyNamingStrategy` actually never worked with Records (#2992), but that has been fixed in `2.15.0` (tested with `2.15.0-rc2`), so now it can work without any special configuration, e.g.:
```
record Test(String fieldName) {
}

ObjectMapper objectMapper = JsonMapper.builder()
        .propertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
        .build();

// Prints Something[fieldName=value]
System.out.println(objectMapper.readValue("{ \"field_name\": \"value\" }", Test.class));
```

**Comment by yihtserns** [comment] 2023-05-07 11:49
Asking out of curiousity: if the field is `private` & it doesn't have a getter method, what is the class actually used?

**Comment by joca-bt** [comment] 2023-05-07 12:13
The point is that it doesn't have a setter. Getter is irrelevant here.

**Comment by yihtserns** [comment] 2023-05-07 12:20
It works if there's a getter, though.  Why is a setter relevant?

**Comment by yihtserns** [comment] 2023-05-07 12:30
I mean as pointed out [here](https://github.com/FasterXML/jackson-databind/issues/3846#issuecomment-1486025926), when a getter exists, naming strategy is used e.g.:

```
public class Test {
    private final String fieldName;

    public Test(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getFieldName() { // with getter
        return this.fieldName;
    }
}

ObjectMapper objectMapper = JsonMapper.builder()
    .addModule(new ParameterNamesModule(JsonCreator.Mode.PROPERTIES))
    .constructorDetector(ConstructorDetector.USE_PROPERTIES_BASED)
    .propertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
    .build();

objectMapper.readValue("{ \"field_name\": \"value\" }", Test.class); // This works
objectMapper.readValue("{ \"fieldName\": \"value\" }", Test.class); // This also works, but that's a (different) bug

```

**Comment by joca-bt** [comment] 2023-05-07 13:48
> Why is a setter relevant?

If there is a setter Jackson may use that instead of the constructor.

**Comment by yihtserns** [comment] 2023-05-07 16:00
For naming strategy to work for a "property", one of these are currently needed:
1. Visible field (e.g. `public` field, or `private` field + `setVisibility(PropertyAccessor.FIELD, ANY)`).
2. Getter.
3. Setter.
4. Constructor parameter annotated with named `@JsonProperty`.
5. Constructor parameter with implicit name (e.g. with `ParameterNamesModule`), for a `@JsonCreator` annotated constructor.
6. Constructor parameter for Record's canonical constructor.

So one of the things you can do to make naming strategy to work with:
```
public class Test {
    private final String fieldName;

    public Test(String fieldName) {
        this.fieldName = fieldName;
    }
}
```
...is to add a getter:
```
public class Test {
    private final String fieldName;

    public Test(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getFieldName() {
        return this.fieldName;
    }
}
```
...which is pretty normal because how else can that private field be used?

I'm just curious about what are you doing with your JSON model class in your project/codebase, for it to have a private field without getter, resulting in you facing this issue?

**Comment by joca-bt** [comment] 2023-05-07 16:42
This example is about #5.

> Constructor parameter with implicit name (e.g. with ParameterNamesModule), for a @JsonCreator annotated constructor.

Except @JsonCreator should not be needed contrary to what you wrote. You can read more about it here https://cowtowncoder.medium.com/jackson-2-12-most-wanted-3-5-246624e2d3d0.

> for it to have a private field without getter, resulting in you facing this issue?

I am not. It was not relevant for the example.

**Comment by yihtserns** [comment] 2023-05-07 16:54
> > Constructor parameter with implicit name (e.g. with ParameterNamesModule), for a @JsonCreator annotated constructor.
>
> Except @JsonCreator should not be needed contrary to what you wrote. You can read more about it here https://cowtowncoder.medium.com/jackson-2-12-most-wanted-3-5-246624e2d3d0.

I specifically said "**one of these** is currently needed"...  Meaning, even if you don't have number 5, as long as you have either 1, 2, 3, 4, or 6, naming strategy will work.

> I am not. It was not relevant for the example but I can see it being valid. Not all instance fields need/should have getters 🙃.

OK so you're not reporting for a _practical problem_ (i.e. "I'm facing this issue now!"), but rather an edge-case you found while testing Jackson.  I just wanted to know if I'm missing anything I should be careful of as a Jackson user, thanks!

**Comment by cowtowncoder** [comment] 2023-05-07 17:20
As per my earlier notes, I think it is very likely this is related to the problem of "implicit" Creators being discovered too late to be properly linked to accessors (getters/setters): explicit (annotation indicated) Creators are discovered first, their arguments get matched properly with getters/setters; implicit ones are discovered at a later phase.
It is sometimes possible to force proper linking by additional annotations (obviously `@JsonCreator`, but also `@JsonProperty` on Creator parameters).

This is something that I think requires a rewrite of property discovery (see #3719), and if and when this happens can be resolved. But I do not think smaller incremental fixes are possible.

**Comment by cowtowncoder** [comment] 2024-05-20 01:18
Work on #4515 may make this fixable for 2.18.

What would be great would be a reproduction (unit test), to help test eventual fix.

**Comment by cowtowncoder** [comment] 2024-05-30 04:00
Now that #4515 is fixed, I think this issue is likely covered as well.
Since no unit test added, I consider this as solved; may be reopened/re-filed with a reproduction (test) if there are further issues.

**Closed by cowtowncoder** 2024-05-30 04:00 UTC
Labels: property-discovery

**Comment by joca-bt** [comment] 2026-06-30 10:20
This specific example seems to be working correctly in Jackson 3, that is, the naming strategy is taken into account.
