### ISSUE TITLE
Cache for known serializers for classes seems broken

### ISSUE THREAD

**Issue by henrikolsson** [FasterXML/jackson-databind#1049] opened 2015-12-15 18:39 UTC
This[1] line tries to look up a serializer for the supplied class in the cache and if it doesn't find anything it will call \_createAndCacheUntypedSerializer to create and add it to the cache[2].

However that method will convert the Class to a JavaType before adding it to the cache, meaning it will never be in the cache for future lookups (by class at least).

1. https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/SerializerProvider.java#L1136
2. https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/SerializerProvider.java#L1178

**Comment by cowtowncoder** [comment] 2015-12-15 23:02
That sounds wrong, the intent is that caching should be accessible with either types, since there is non-trivial cost for resolving `JavaType` from `Class` (especially for certain kinds of types).

**Comment by henrikolsson** [comment] 2015-12-21 15:01
It can be observed by calling canSerialize(Class) on ObjectMapper multiple times with the same class and stepping through the code, to me it looks it will never get a cache hit. I actually noticed it when profiling a web  application returning json objects, the synchronization inside _serializerCache started to become a bottleneck. But if the caching worked it would also exist in_knownSerializers right?

**Comment by cowtowncoder** [comment] 2015-12-21 18:26
@henrikolsson I haven't had a chance to look deeper into it, but with quick glance it looked like you were right. If `canSerialize()` reproduces this that'd be great as it can be more easily wrapped in a unit test.
The main reason I hadn't caught this is probably since performance test I use tend to use `ObjectWriter`, which caches actual serializer, and further references via properties use `JavaType`, I think; so I didn't see this in profiler. Plus I don't usually do (heavy) multi-threaded tests which also mask "casual" calls.

I hope to resolve this by 2.7.0-rc3 (or, if that is skipped, 2.7.0 final).

**Comment by henrikolsson** [comment] 2015-12-21 18:55
Yes, I was considering submitting a unit test (And maybe a fix too), but I wasn't sure what the best way to test it would be. You'd need to be able to check if the cache is hit or not when calling canSerialize. 

And also not sure what the proper fix would be. Create a JavaType in _findExplicitUntypedSerializer before looking up in the cache or add the Class to the cache in _createAndCacheUntypedSerializer?

**Comment by cowtowncoder** [comment] 2015-12-21 23:17
I'll have to see abut the fix, I forget the exact details, but for performance reasons key ought to be `Class`, as construction of `JavaType` can be expensive. But it is a good question as to whether there should also be a secondary lookup for using newly constructed `JavaType`... then again, that entry should be added via `Class` as well.

**Closed** 2015-12-22 02:51 UTC

**Comment by cowtowncoder** [comment] 2015-12-22 02:52
@henrikolsson I see, it is not easy to test, and I am not big fan of adding test-only methods.

But on plus side, I think I was able to figure out what and where to fix. Tests still pass, although that's not necessarily much of a guarantee of nothing breaking in this particular case.

I will do some manual testing to see if I can verify things work as expected now.

**Comment by cowtowncoder** [comment] 2015-12-22 03:49
Odd. I can not actually reproduce the issue, even without the change, at least when doing actual serialization. I did notice that the original issue was mostly (only?) via `hasSerializer()` pathway, not sure if that matters.

**Comment by henrikolsson** [comment] 2015-12-22 19:20
Cool, thanks. Indeed it looked to me like it was only canSerialize that triggered it, not actual serialization. In this case I think it was because spring would call canSerialize first before serializing.
